### ISSUE TITLE
Standaard leesbaarder en beetje compacter te maken

### ISSUE THREAD

**Issue by ArjanLoeffen** [Geonovum/MIM-Werkomgeving#1]
Verzoek om de standaard leesbaarder en beetje compacter te maken. De lijst van tagged values kan bondiger en daarmee veel overzichtelijker. In de vorm van tabel bijvoorbeeld.
Om z'n minst als bijlage toevoegen.

**Comment by PalmJanssen** [comment]
zie ook #26

**Comment by lennartvanbergen-kadaster** [comment]
zoals in https://docs.geostandaarden.nl/mim/def-st-mim-20201023/#modelelementen-en-metagegevens-als-diagram 
of bedoel je wat anders?

**Comment by PalmJanssen** [comment]
Niet aan gewerkt voor de 1.1.1 versie. Blijft staan voor latere versie

**Comment by ArjanLoeffen** [comment]
Misschien meer in de richting van https://armatiek.nl/MIMPrimer/Fietsenwinkel.html#bijlage-metagegevens hetgeen begrijpelijk is voor een gewone sterveling van vlees en bloed.
