### ISSUE TITLE
Voorgedefinieerde datatypes t.b.v. selecteren of handmatig intypen (UML/XMI) 

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#10]
Richting: 
- goede naam intypen mag. Imvertor accepteert dit. 
- UML package die in et laden is als XMI of zo 

Geonovum levert dit UML package met types zoals Surface, Point, wellicht ook Integer, CharacterString, en wellicht ook GAB types.

**Comment by GeraldGrootRoessink** [comment]
Is dit een issue met betrekking tot de tool die wordt gebruikt om te modelleren. Zo ja, dan hoort het wat mij betreft hier niet thuis.

**Comment by PalmJanssen** [comment]
Dit is een ondersteunende MIM producten. In feite een package met MIM datatypen. We kunnen ook een zogenaamd MIM EA template maken, daar kan je dan ook al de MIM toolbox in laden.
