### ISSUE TITLE
Hoe hergebruiken van kenmerken of definities 

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#102]
In RDF/OWL kun je attribuuttypen en relatietypen hergebruiken voor meerdere objecttypen. Het MIM metamodel maakt het in beginsel mogelijk om dit te ondersteunen, maar expliciet wordt dit niet. Wens is om dit aan te kunnen geven, zodat in RDF/OWL algemene attribuuttypen als bv rdfs:label of “naam” hergebruikt kunnen worden 

In UML is het hergebruik van bepaalde typen model elementen wel mogelijk, zoals bij een gegevensgroeptype of een datatype, maar van andere zoals een attribuutsoort of een relatiesoort of een element van een datatype niet. 

Hoe kan je bij attribuutsoorten en relatiesoorten en elementen van datatypes dan toch aangeven dat er exact hetzelfde wordt bedoeld? Op een manier die voor zowel UML als RDF/OWL geschikt is. 

Antwoord kerngroep: oplossingsrichting moet geschikt zijn voor zowel UML als LD, zoek de richting in wat het betekenis als de definitie en/of naam hetzelfde is. 

- Als de definitie van twee of meer modelelementen EXACT hetzelfde is, dan wordt hiermee bedoeld dat het dezelfde definitie is. Bijvoorbeeld: "Het bedrag in euro's" van een 'overboeking' en een 'koopsom'. 
 
- Als de naam en de definitie van twee of meer kenmerken EXACT hetzelfde is, dan wordt hiermee bedoeld dat het hetzelfde kenmerk is. Bijvoorbeeld: verblijfsobject.oppervlakte : "De oppervlakte in m2" en perceel.oppervlakte. 

Dit geldt binnen hetzelfde informatiemodel. 

Verder is het uiteraard toegestaan om de definitie te publiceren en hiernaar te verwijzen via bv. een URI die opgenomen is in de definitie van een modelelement. Al zitten hier wat kanttekeningen bij, want als je de definitie niet zelf in beheer hebt, of een eigen leven leidt buiten het informatiemodel om, dan krijg je mogelijk ongewenste effecten in je IM als de definitie aangepast wordt of van internet af wordt gehaald. 

Dit opnemen in hoofdstuk: Afspraken en regels. Want het gaat niet over het metamodel zelf, maar hoe je dit invult en/of moet interpreteren. 

Zie ook #103

**Comment by lennartvanbergen-kadaster** [comment]
Voorstel: 

**Afspraken en regels** 

_Dezelfde naam en/of definitie gebruiken voor meerdere modelelementen_

Er kan sprake zijn van 1 naam en/of definitie die voor meerdere modelelementen gelijk moeten zijn, omdat er inherent hetzelfde bedoeld wordt. Generalisatie is gedefinieerd voor Datatypen en Objecttypen en Datatypen en gegevensgroeptypen kunnen op meerdere plekken gebruikt worden.

chter, voor bijvoorbeeld voor een relatiesoort of een attribuutsoort kan het ook nodig zijn om dezelfde naam en/of definitie te specificeren. Dit is mogelijk, maar het is dan niet geheel duidelijk of er hetzelfde bedoeld wordt, of dat de (exacte) overeenkomt in een informatiemodel (zoals bv. in een UML informatiemodel) een toevalligheid is. Daarom gelden de volgende afspraken: 

* Als de **definitie** van twee of meer modelelementen EXACT hetzelfde is, dan wordt hiermee bedoeld dat het dezelfde definitie is. Bijvoorbeeld: attribuutsoort overboeking met _definitie_ "Het bedrag in euro's" en attribuutsoort koopsom met _definitie_ "Het bedrag in euro's".

* Als de **naam** _en_ de **definitie** van twee of meer modelelementen EXACT hetzelfde is, dan wordt hiermee bedoeld dat het hetzelfde kenmerk is. Bijvoorbeeld bij objecttype Huis met attribuutsoort oppervlakte: : "De oppervlakte in hele vierkante meters" en objecttype Appartement met attribuutsoort oppervlakte : "De oppervlakte in hele vierkante meters".

Als niet hetzelfde bedoeld wordt, dan moet de definitie iets anders zijn. Bijvoorbeeld: "Het bedrag van een koopsom, in euro's". 

--

Merk op: het kan zijn dat er informatiemodellen zijn die deze afspraak niet volgen en wel kenmerken kennen met dezelfde naam en/of definitie. Deze informatiemodellen zullen dus iets aan hun definities moeten doen. Een ander voorstel is ook mogelijk, zoals metadata om aan te geven dat het om hetzelfde gaat.

**Comment by ThiesMesdag** [comment]
Je bedoelt dus eigenlijk te zeggen dat je niet bij het zelfde begrip een verschillende definitie mag hanteren. Dus bedrag met definitie in euros en bedrag met definitie in valuta gekozen uit waardelijst. mogen niet dezelfde naam hebben. 
Dat wordt dan bedragInEuro  en bedragValuta of zo.
