### ISSUE TITLE
Alias en naam, of naam en alias? Wat staat er in?

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#107]
Het MIM is niet exact over wat in een mim:naam en wat in een mim:alias mag of moet staan. Er worden verschillende conventies voorgesteld. Hierdoor is niet helemaal duidelijk wat je waar zou moeten neerzetten. Voorstel is om een aspect toe te voegen zodat de naamgevingsconventie expliciet in het model wordt gemodelleerd. 

Reactie: 
MIM kent 1 alternatief. ALS alternatief 1 is gekozen, dan staat in de naam in natuurlijke taal en in de alias (optioneel) de machine-leesbare naam, ALS alternatief 2 is gekozen dan staat in de naam de machine-leesbare naam en in de alias de naam in natuurlijke taal. 

Dit kan wat helderder worden opgenomen bij alias.

**Comment by lennartvanbergen-kadaster** [comment]
Voor LD is alternatief 1 gangbaar, en voor conventie van UL naar LD en andersom, is het nodig om te weten om welke het gaat. 

Oplossingsrichting: neem als metadata op welk alternatief er gekozen is. Dit is metadata bij het < < informatie model > > 

Voorstel: 
Metadata aspect: "Alternatief"
Definitie: aanduiding van een in MIM gedefinieerd alternatief, en welke keuze hierbij is gemaakt. 
Waardenbereik metadata: "Relatiesoort leidend" of "Relatierol leidend".
Verplicht. 

Voorbeeld: 
Alternatief 
Relatiesoort leidend

**Comment by ThiesMesdag** [comment]
Hoi Lennart,
Past je oplossing wel bij de vraag? het lijkt erop of je iets anders mbt relaties oplost ipv de alias van de vraag. Ik vindt metadata aspect "alternatief" niet een heel sterke naam. Iets als "Relatiegebruik" lijkt mij beter.

**Comment by lennartvanbergen-kadaster** [comment]
Verwerkt in algemeen. Moet nog verwerkt worden in UML en LD hoofdstuk, en in profiel.

**Comment by lennartvanbergen-kadaster** [comment]
Verwerkt in UML. Nog te doen: verwerken in LD hoofdstuk.

**Comment by lennartvanbergen-kadaster** [comment]
Als klaar met LD, doorzetten naar Paul tbv profiel en diagrammen.

**Comment by architolk** [comment]
Het voorstel van Lennart slaat niet op het issue (zie ook het punt van Thies). Wel denk ik dat het issue feitelijk is opgelost. Want er staat in de regels over naamgevingsconventies en modellen, dat bij een conceptueel model altijd wordt gekozen voor regel 1 (naamgeving met spaties) en voor een logisch model altijd voor regel 2 (naamgeving zonder spaties). Feitelijk is een Linked Data model altijd een conceptueel model (denk ik??), dus dan gaat het wel goed. De aanpassing die dan aan de Linked Data kant gedaan moet worden is enige uitleg dat we het altijd hebben over een conceptueel model, en dat een MIM logisch model al te veel implementatiedetails kent om nog in Linked Data te vertalen (wat bovendien zou leiden tot fouten in de transformatie?)

**Comment by lennartvanbergen-kadaster** [comment]
(bedoeld was inderdaad om de vraag achter de vraag op te lossen)

Ja, dat over conceptueel en logisch staat er. Maar niks houd het tegen om het anders te doen. Het kan dus in theorie nodig zijn om expliciet aan te geven welke naamgevingsconventie is gevolgd. Al zie je dat snel genoeg. De standaard ondersteund het nu in ieder geval om het op de bedoelde manier mogelijk te maken (en als het toch anders ingevuld wordt, om dit aan te geven, ook al is deze optie hier niet voor bedoeld en ook niet voor in het leveren geroepen).

**Comment by architolk** [comment]
Ja, dit punt begon bij alias, maar blijkt een achterliggend punt bloot te leggen, namelijk dat in een logisch informatiemodel keuzes zijn gemaakt die betrekking hebben op de opslagvorm, en daarmee feitelijk al of je de Linked Data kant op bent gegaan of juist de UML/XSD/XML/Relationele Database kant. Dit mag wat beter beschreven worden m.i., ik heb hier nu al een aanzet voor gedaan als onderdeel van het geven van een Linked Data intro, dus laten we daar even de reacties op afwachten. Ook kunnen we dan w.m.b. bepalen of het belangrijk is om expliciet een metadata-element op te nemen die gaat over deze naamgevingsconventie.
