### ISSUE TITLE
Ondersteunen aspect min/max voor getallen 

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#109]
Zie ook #72 : voorstel vanuit DUO om ook het aspect min/max te ondersteunen zoals ook beschikbaar in SHACL.

**Comment by lennartvanbergen-kadaster** [comment]
Iets meer info?

**Comment by architolk** [comment]
Zie #72. Het gaat er in dit geval om dat aan de constraints de mogelijkheid wordt toegevoegd om een minimum of maximum waarde te kunnen neerzetten, bijvoorbeeld: waarde moet liggen tussen 0 en 5.

**Comment by architolk** [comment]
Voorstel: opnemen zoals voorgesteld.

**Comment by lennartvanbergen-kadaster** [comment]
Ja, is eerder besproken als wens. Zodra iemand concreet een informatiemodel wilt maken waarin dit nodig is, gingen we deze toevoegen. 

Als je een praktijk voorbeeld noemt dan nemen we die ook op, dan kunnen mensen naar jouw informatiemodel gaan kijken hoe dat daar gedaan is.

**Comment by lennartvanbergen-kadaster** [comment]
Nagevraagd. Voor de BAG en voor de BRK hebben wij geen voorbeelden en dus ook niet zo zeer een voorstel hoe dit te specificeren. Wellicht dat de BRO of een model van TNO vaker met dit bijltje heeft gehakt? 

Zo nee, dan zou ik zeggen, geef een concreet voorbeeld en doe een voorstel voor de uitwerking. 

Er is even over nagedacht. Wat meespeelt: 

De kern van een informatiemodel is om de betekenis en de structuur van de informatie te specificeren. Een definitie van een gegevens, of het een String is, of de structuur van de String moet voldoen aan een patroon. 

Een minimum waarde zit in een grijs gebied. Dat geeft eigenlijk meer een bereik aan aan waaraan de data moet voldoen. Dat is niet zozeer betekenis of structuur, maar een waardebereik. Daarom een grijs gebied. 

Een bedrijfsregel: verzoeken mogen tot 18u worden aangeleverd, of de geometrie van dit object moet liggen binnen Nederland, of binnen een andere geometrie ... of de geometrie moet voldoen aan srs 28992 etc ... zijn ook zaken die niet bij de kern van een informatiemodel horen, en die we in feite ook niet modelleren. We bieden hiervoor de "catch all extra": een constrain language, OCL.  

Een minimum waarde is ook vrij complex, want voor een String moet dit anders gespecificeerd worden dan voor een Integer of een Decimal of een Date, of voor een zelf gedefinieerd datatype. waarbij de waarde zelf ook weer soms dus een String, Integer, Decimal of Date is. 

Ik ben hier dan ook vrij terughoudend in. Het lijkt veel werk om iets te specificeren wat vrij diep in de implementatie zit (en waar al een andere mogelijkheid voor is: constraint). 

De intentie van het informatiemodel is in ieder geval niet de volledige mogelijkheden van alle technische formaten te ondersteunen (XSD, SHACL, JSON schema enz). 

Ben benieuwd hoe andere hier tegen aankijken.

**Comment by lennartvanbergen-kadaster** [comment]
@architolk 

Voorstel voor MIM 1.1. - nog niet opnemen, opnemen zodra het nodig is en goed uitgewerkt is. Oftewel, MIM 1.11 of zo.

**Comment by lennartvanbergen-kadaster** [comment]
Hierbij zit ook de trade off: moet alles wat je in XSD kan ook in UML gemodelleerd worden? Er is al OCL. Er is al reguliere expressie/patroon. Is het dan nog nodig om min/max te doen?

**Comment by JanCampschroer** [comment]
Ik zou dit onderbrengen bij 'Kardinaliteit'. Daar heb je nu de mogelijke waarden: 1, 1..*, 0..1 en 0..*.
Daar kun je de mogelijke waarden n..m aan toevoegen, waarbij n kleiner (of gelijk) is dan m.  Dit komt dan overeen met de sh:minCount "n" ; sh:maxCount "m". 

Dus in 2.8.2.12 de tekst onder toelichting aanvullen met: 
"n..m: een object heeft dit kenmerk minimaal m keer, en het kenmerk kan maximaal m keer voorkomen. "

Een goed voorbeeld ontbreekt nog.

Op MIM-2 niveau zou ik dit interpreteren als een uitspraak over de werkelijkheid. Voor een (natuurlijk) Persoon heeft geboorteDatum kardinaliteit 1. (iedere persoon heeft precies één geboortedatum).
Op MIM 3  niveau zou ik dit interpreteren als een uitspraak over de geregistreerd: 1 betekent dan dat voor iedere geregistreerde persoon óók de geboortedatum is geregistreerd. Op dat niveau kan ook 0..1 worden aangegeven. Dan hoeft de registratie op die eigenschap niet volledig te zijn.

**Comment by PalmJanssen** [comment]
Ik zou nog de OCL voorbeelden uitwerken.
OCL werkt in de regel met Boolean expressies. Voor condities op Integer en Real typen gelden volgende standaard operaties.
attribuutwaarde: =, <>, <, >, <=, >=.

Voor een maxWaardeExclusief van een attribuut is dit een standaard OCL expressie:

Context: 'naamObjecttype''
self.'naamAttribuut' < 'maxWaarde'

Voor maxWaardeInclusief:
self.'naamAttribuut' <= 'maxWaarde'

Voor een range:
minWaarde <= self.'naamAttribuut' <= maxWaarde

Het sterke punt is dat je (bijna) elke expressie kan maken. Het zwakke dat je het in de OCL syntax moet doen.

OCL kent geen Date of DateTime en heeft dus ook geen operatoren daarop.

**Comment by pmaria** [comment]
@PalmJanssen deze lijkt per ongeluk (?) gesloten te zijn?

**Comment by PalmJanssen** [comment]
ja was per ongeluk gesloten

**Comment by lennartvanbergen-kadaster** [comment]
Duiding: organisaties die hiermee te maken hebben kunnen zelf ook metagegevens toevoegen dus blokkerend is het niet. 
Duiding: er is een duidelijke wens om dit wel te kunnen. 

Laatste keer hebben we deze bediscussieerd en ongeveer het volgende besproken: .

0. Niks doen, immers, OCL kan dit al en met patroon/formeel patroon (reguliere expressies) kom je ook een eind.  
    Voordeel; geen alternatieven voor het modelleren van minimum en maximum. We willen in MIM heel graag geen alternatieve modelleringen van hetzelfde. 
    
1. Een nieuw metagegeven met een notatiewijze. Geïnspireerd op een wiskundige notatie. 
    Voordeel: techniek onafhankelijk, de specificatie van min en max staat in 1 metagegeven. 
    Nadeel (maar oplosbaar binnen MIM): alternatieve modellering van iets wat als kan met OCL. We moeten bij OCL dan zeggen, met OCL specificeer je geen min en max (terwijl dit wel met OCL kan). 
    Nadeel: de notatiewijze moet je parsen bij het vertalen naar hoe XSD en SHACL enz ermee omgaan. [2-10> of [2..10> gaat dan naar minInclusive 2 en maxExclusive 10 enz. 

2. Aparte metagegevens voor minimaal en maximaal 
   Voordeel: mapped goed op XSD en SHACL voor minInclusive en maxInclusive enz 
   Voordeel: iedereen heeft een goed begrip hierbij 
   Nadeel (maar oplosbaar binnen MIM): alternatieve modellering van iets wat als kan met OCL. We moeten bij OCL dan zeggen, met OCL specificeer je geen lengte (terwijl dit wel met OCL kan). 
   Nadeel: wel erg geïnspireerd op techniek, jammer dat er geen ISO standaard voor is te vinden......
   
TODO: voorstel indienen.

**Comment by pmaria** [comment]
Nog te doen:

- [ ] toelichtingen bij beschrijving metagegevens
- [ ] bepalen en beschrijven icm welke datatypes dit gebruikt kan worden
- [ ] tekstuele beschrijving LD transformatie 
- [ ] validatie LD transformatie

--- 

## Voorstel

**Toevoeging aan [2.8.2 Specificatie metagegevens modelelementen](https://docs.geostandaarden.nl/mim/mim/#specificatie-metagegevens-modelelementen)**

#### Metagegeven **Minimumwaarde inclusief**

> **_Definitie: Minimumwaarde inclusief_**
>
> Minimumwaarde inclusief (`<=`) is de ondergrens van het waardebereik voor een primitief datatype inclusief die waarde zelf. De minimumwaarde moet van hetzelfde primitieve datatype zijn als het datatype van het modelelement waar het voor geldt.

_Toelichting_

TODO

_Toepassing_

Gebruik op attribuutsoorten en data elementen met een primitief datatype.

Een modelelement mag maar één voorkomen van metagegeven **Minimumwaarde inclusief** of **Minimumwaarde exclusief** hebben.

#### Metagegeven **Minimumwaarde exclusief**

> **_Definitie: Minimumwaarde exclusief_**
>
> Minimumwaarde exclusief (`<`) is de ondergrens van het waardebereik voor een primitief datatype exclusief die waarde zelf. De minimumwaarde moet van hetzelfde primitieve datatype zijn als het datatype van het modelelement waar het voor geldt.

_Toelichting_

TODO

_Toepassing_

Gebruik op attribuutsoorten en data elementen met een primitief datatype.

Een modelelement mag maar één voorkomen van metagegeven **Minimumwaarde inclusief** of **Minimumwaarde exclusief** hebben.

#### Metagegeven **Maximumwaarde inclusief**

> **_Definitie: Maximumwaarde inclusief_**
>
> Maximumwaarde inclusief (`>=`) is de bovengrens van het waardebereik voor een primitief datatype inclusief die waarde zelf. De maximumwaarde moet van hetzelfde primitieve datatype zijn als het datatype van het modelelement waar het voor geldt.

_Toelichting_

TODO

_Toepassing_

Gebruik op attribuutsoorten en data elementen met een primitief datatype.

Een modelelement mag maar één voorkomen van metagegeven **Maximumwaarde inclusief** of **Maximumwaarde exclusief** hebben.

#### Metagegeven **Maximumwaarde exclusief**

> **_Definitie: Maximumwaarde exclusief_**
>
> Maximumwaarde exclusief (`>`) is de bovengrens van het waardebereik voor een primitief datatype exclusief die waarde zelf. De maximumwaarde moet van hetzelfde primitieve datatype zijn als het datatype van het modelelement waar het voor geldt.

_Toelichting_

TODO

_Toepassing_

Gebruik op attribuutsoorten en data elementen met een primitief datatype.

Een modelelement mag maar één voorkomen van metagegeven **Maximumwaarde inclusief** of **Maximumwaarde exclusief** hebben.

---

**Toevoeging aan [3.2.1 Modellering metagegevens voor objecten en attributen in UML](https://docs.geostandaarden.nl/mim/mim/#modellering-metagegevens-voor-objecten-en-attributen-in-uml)**

**Bij Specificatie voor «Attribuutsoort»**

| Aspect                  | Kardinaliteit | Toelichting                                                                                                                                        | In UML 2.5 | in EA          |
|-------------------------|---------------|----------------------------------------------------------------------------------------------------------------------------------------------------|------------|----------------|
| Minimumwaarde inclusief | 0..1          | Algemeen metagegeven. Een attribuutsoort mag maar één voorkomen van metagegeven **Minimumwaarde inclusief** of **Minimumwaarde exclusief** hebben. |            | _Tagged value_ |
| Minimumwaarde exclusief | 0..1          | Algemeen metagegeven. Een attribuutsoort mag maar één voorkomen van metagegeven **Minimumwaarde inclusief** of **Minimumwaarde exclusief** hebben. |            | _Tagged value_ |
| Maximumwaarde inclusief | 0..1          | Algemeen metagegeven. Een attribuutsoort mag maar één voorkomen van metagegeven **Maximumwaarde inclusief** of **Maximumwaarde exclusief** hebben. |            | _Tagged value_ |
| Maximumwaarde exclusief | 0..1          | Algemeen metagegeven. Een attribuutsoort mag maar één voorkomen van metagegeven **Maximumwaarde inclusief** of **Maximumwaarde exclusief** hebben. |            | _Tagged value_ |


3.2.4 Specificatie metagegevens voor datatypen

**Toevoeging aan [3.2.4 Specificatie metagegevens voor datatypen](https://docs.geostandaarden.nl/mim/mim/#specificatie-metagegevens-voor-datatypen)**

**Bij Specificatie voor «Attribuutsoort»**

| Aspect                  | Kardinaliteit | Toelichting                                                                                                                                        | In UML 2.5 | in EA          |
|-------------------------|---------------|----------------------------------------------------------------------------------------------------------------------------------------------------|------------|----------------|
| Minimumwaarde inclusief | 0..1          | Algemeen metagegeven. Een data element mag maar één voorkomen van metagegeven **Minimumwaarde inclusief** of **Minimumwaarde exclusief** hebben. |            | _Tagged value_ |
| Minimumwaarde exclusief | 0..1          | Algemeen metagegeven. Een data element mag maar één voorkomen van metagegeven **Minimumwaarde inclusief** of **Minimumwaarde exclusief** hebben. |            | _Tagged value_ |
| Maximumwaarde inclusief | 0..1          | Algemeen metagegeven. Een data element mag maar één voorkomen van metagegeven **Maximumwaarde inclusief** of **Maximumwaarde exclusief** hebben. |            | _Tagged value_ |
| Maximumwaarde exclusief | 0..1          | Algemeen metagegeven. Een data element mag maar één voorkomen van metagegeven **Maximumwaarde inclusief** of **Maximumwaarde exclusief** hebben. |            | _Tagged value_ |

---

**Toevoeging aan [6.4.2 Gebruikte functies](https://docs.geostandaarden.nl/mim/mim/#gebruikte-functies)**

| Functie | Specificatie |
----------|--------------|
| t:cast  | Transformeert het datatype van een waarde naar het gegeven datatype. Deze functie verwacht twee parameters: `t:cast(?waarde, ?datatype)`. De `?waarde` parameter is de waarde waarvoor een datatype gezet moet worden. `?dataype` is het datatype wat `?waarde` moet krijgen. Op basis van `?datatype` bepaalt deze functie het juiste datatype om te zetten. |

--- 

**Toevoeging aan [6.4.9 Properties](https://docs.geostandaarden.nl/mim/mim/#properties)**

#### transformatie: Minimumwaarde inclusief

```sparql
CONSTRUCT {
  ?propertyshape sh:minInclusive ?minInclusive.
}
WHERE {
  ?modelelement mim:minimumwaardeInclusief ?minimumwaardeInclusief .
  ?modelelement mim:type ?datatype .
  ?propertyshape mim:equivalent ?modelelement .
  ?datatype a mim:PrimitiefDatatype .
  bind(t:cast(?minimumwaardeInclusief, ?datatype) as ?minInclusive)
}
```

#### transformatie: Minimumwaarde exclusief

```sparql
CONSTRUCT {
  ?propertyshape sh:minExclusive ?minExclusive.
}
WHERE {
  ?modelelement mim:minimumwaardeExclusief ?minimumwaardeExclusief .
  ?modelelement mim:type ?datatype .
  ?propertyshape mim:equivalent ?modelelement .
  ?datatype a mim:PrimitiefDatatype .
  bind(t:cast(?minimumwaardeExclusief, ?datatype) as ?minExclusive)
}
```

#### transformatie: Maximumwaarde inclusief

```sparql
CONSTRUCT {
  ?propertyshape sh:maxInclusive ?maxInclusive.
}
WHERE {
  ?modelelement mim:maximumwaardeInclusief ?maximumwaardeInclusief .
  ?modelelement mim:type ?datatype .
  ?propertyshape mim:equivalent ?modelelement .
  ?datatype a mim:PrimitiefDatatype .
  bind(t:cast(?maximumwaardeInclusief, ?datatype) as ?maxInclusive)
}
```

#### transformatie: Maximumwaarde exclusief

```sparql
CONSTRUCT {
  ?propertyshape sh:maxExclusive ?maxExclusive.
}
WHERE {
  ?modelelement mim:maximumwaardeExclusief ?maximumwaardeExclusief .
  ?modelelement mim:type ?datatype .
  ?propertyshape mim:equivalent ?modelelement .
  ?datatype a mim:PrimitiefDatatype .
  bind(t:cast(?maximumwaardeExclusief, ?datatype) as ?maxExclusive)
}
```

**Comment by lennartvanbergen-kadaster** [comment]
Graag matchen op deze: 

https://docs.geostandaarden.nl/mim/def-st-mim-20201023/#primitive-datatypes

Bij twijfel (vanwege laatste behandeldag voor bevriezen release inhoud) een type nog even weglaten, kan later worden toegevoegd. Bv. GM types en Boolean nog even niet.

**Comment by lennartvanbergen-kadaster** [comment]
Definitie: 
bevat _attribuutsoort en data element_ 
en bevat getypeerd met een _primitief datatype_

**Comment by pmaria** [comment]
@architolk zou jij voor https://github.com/Geonovum/MIM-Werkomgeving/issues/109#issuecomment-998590274 kunnen beoordelen of de beschreven transformatie zo duidelijk is?

**Comment by architolk** [comment]
@pmaria : transformatie helemaal duidelijk, en lijkt me ook helemaal goed zo. Prima om deze door te voeren.

**Comment by PalmJanssen** [comment]
@pmaria @architolk @dkrijtenburg-GNM @lennartvanbergen-kadaster 

Deze zit nog niet in done kolom en wordt niet meegenomen voor v 1.1.1.
Blijft staan voor 1.1.2

**Comment by pmaria** [comment]
Met de review van @architolk kan hij denk ik nu naar done. Prima om met 1.1.2 mee te nemen wat mij betreft.

**Comment by pmaria** [comment]
@pmaria maakt een PR

**Comment by ArjanLoeffen** [comment]
Twee vragen:

1. Waarom worden mix/max grenzen niet toegestaan op primitieve datatypen? Bijv. Leeftijd >= 0. 
1. Waarom worden gezet min/max grenzen gespecificeerd op referentie elementen? En als dat verklaarbaar is, waarom dan niet op codelijst?

Dit in het kader van https://github.com/Imvertor/Imvertor-Maven/issues/448

**Comment by PalmJanssen** [comment]
MIM 1.2 stelt het zoals het nu gesteld wordt. Dat zou ik aanhouden. Daarnaast blijft het een valide issue.
