### ISSUE TITLE
Metamodel ook in het Engels 

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#11]
Duiding: er zijn ook gebruikers die Engels willen lezen. Tevens aansluiting bij NEN en ISO.
Richting: een annex/bijlage, normatief. MIM niveau c/l.  Geonovum. 
Voor: BRO

**Comment by dkrijtenburg-GNM** [comment]
is hetzelfde als 17, wordt daarom gesloten
