### ISSUE TITLE
MIM metClass Generalisatie

### ISSUE THREAD

**Issue by LucHeres** [Geonovum/MIM-Werkomgeving#110]
In het kernmodel (paragraaf 2.1.1) wordt de MIM metaklasse  "Generalisatie" gebruikt om subtyperelaties te definiëren tussen Objecttypen onderling (bijv. Paard is subtype van Zoogdier).
Deze relaties kunnen echter prima direct tussen Objecttypes onderling worden gedefinieerd. Zo gebeurt het ook in RDF-modellen. Met behulp van rdfs:subClassOf kan men subtype relaties tussen objecttypes (Classes in RDF-terminologie) definiëren.
Met andere woorden: de metaklasse "Generalisatie" is in feite overbodig en staat integratie met RDF-modellen in de weg.
Voorstel is dus om subtyperelaties direct tussen Objecttypen te laten lopen.

**Comment by PalmJanssen** [comment]
Interessant. In het UML 2.5 metamodel komen beide voor, maar inderdaad op de class is het een directe recursieve relatie. Een argument om het als metaklasse op te nemen is dat we er eigen stereotype voor kunnen creeeren en aparte tagged values aan kunnen hangen. De vraag is of dit nodig is voor een generalisatie.

![image](https://user-images.githubusercontent.com/9932784/68493647-241f7480-024d-11ea-9064-62c57055006b.png)

**Comment by LucHeres** [comment]
Objectificatie (reïficatie in UML-termen) van relaties kan handig zijn Daarmee kun je allerlei (meta)informatie aan een relatie toevoegen. 
Toch is het niet aan te bevelen om ge-objectificeerde relaties standaard in een informatiemodel op te nemen,
Objectificatie (en de weerstand daartegen) was nl. afgelopen jaar hét centrale discussiepunt rond de COINS-standaard. In COINS 2.0 zijn nl. een groot aantal ge-objectificeerde relaties opgenomen met het doel om daar meta-informatie aan te kunnen koppelen.
Met name vanuit de Linked Data-hoek was daar geweldige weerstand tegen. Ontwikkelaars van LD-software beweren dat voor 90% van de toepassingen deze ge-objectificeerde relaties niet nodig zijn. Bovendien beïnvloeden deze objectificaties de performance van hun software op zeer nadelige wijze  en wordt standaardisatie nodeloos lastig en gecompliceerd gemaakt.
Vandaar dat in de NTA 8035 (ontstaan uit de discussie rond COINS) alle ge-objectificeerde constructies weggelaten zijn. 
Deze bezwaren komen met name uit de LD-hoek. Omdat het MIM zich nu ook op LD richt en pretendeert ook een meta-informatiemodel voor LD-modellen te zijn, is het belangrijk om de bezwaren van LD-software-ontwikkelaars serieus te nemen.

**Comment by architolk** [comment]
Mijn voorkeur zou ook hebben om generalisatie direct te beschrijven. Ik zie zo snel de use case niet om afzonderlijke eigenschappen te beschrijven van de generalisatie, en onnodige complexiteit introduceren.

**Comment by ThiesMesdag** [comment]
In onze modellen (Kadaster) hebben we geen metadata aan de generalisatie, wel hebben we een `<<Static liskov>>` stereotype ten behoeve van (naar ik meen) de serialisatie naar xsd's waarin dubbele overerving een probleem is.

**Comment by lennartvanbergen-kadaster** [comment]
Een generalisatie is wat anders dan een relatiesoort. Daarom zijn ze als afzonderlijke model elementen benoemd. Net zoals een ontologische relatie wat anders is dan een eigenschap relatie. 

Andersom bekeken: een relatie/link tussen twee objecttypen moet je duiden. Het kan een relatiesoort zijn, het kan een generalisatie zijn. Dat zijn twee verschillende dingen. Daar hebben we dus een apart modelelement voor nodig, anders is het onderscheidt niet te maken. 

Misschien gaat de vraag niet over het metamodel, maar over een informatiemodel, hoe het er daar uitziet. In een informatiemodel zelf is een Generalisatie rechtstreeks tussen twee objecttypen. Dit lijkt te voldoen ook aan wat je aangeeft. 

Het lijkt dus precies goed. Oftewel, mogelijk mis ik iets ... ?

**Comment by lennartvanbergen-kadaster** [comment]
Zoals Thies aangeeft is in UML ook de ene generalisatie de andere niet. Er zijn verschillende typen generalisaties. Maar de vraag gaat niet over of een Generalisatie eigenschappen heeft, of andere metadata nodig heeft. Daarom heb ik dit maar niet genoemd.

**Comment by ThiesMesdag** [comment]
Is een generalisatie misschien een soort of een specialisatie van het type releatiesoort? Logisch gezien vindt ik een generalisatie wel iets anders dan een "gewone" relatie.  In RDF wordt dat onderscheid niet gemaakt doormiddel van een ander type relatie, daar bepaalt de naam van de relatie ook het type van de relatie. 
Is dit dan niet op te lossen door MIM generalisatie altijd naar rdfs:subClassOf te vertalen in RDF.

**Comment by lennartvanbergen-kadaster** [comment]
> Deze bezwaren komen met name uit de LD-hoek. Omdat het MIM zich nu ook op LD richt en pretendeert ook een meta-informatiemodel voor LD-modellen te zijn, is het belangrijk om de bezwaren van LD-software-ontwikkelaars serieus te nemen.

We nemen dit uiteraard serieus.

**Comment by architolk** [comment]
In de huidige LD vertaling wordt een generalisatie inderdaad omzet naar rdfs:subClassOf. Daarbij geldt wel dat de aanvullende eigenschappen van een generalisatie niet kwijt kunnen. De vraag is of deze eigenschappen vaak aanwezig zullen zijn (ze zijn nu allen optioneel in het model), maar ALS ze nodig zijn, is de huidige uitwerking om een afzonderlijke rdf:Statement op te nemen.

**Comment by lennartvanbergen-kadaster** [comment]
@architolk ik meen dat we hier een oplossing voor hadden aan de LD kant? Zou deze daarom op verwerkt kunnen? Of ...

**Comment by PalmJanssen** [comment]
Conclusie voor mbt eigenschappen van de metaklasse Generalisatie:
- Naam, Alias, en Begrip zijn niet nodig. Worden verwijderd.
- Datum opname is wel van belang. Wordt toegevoegd.
