### ISSUE TITLE
Verschil tussen Externe Koppeling en Relatiesoort

### ISSUE THREAD

**Issue by LucHeres** [Geonovum/MIM-Werkomgeving#112]
Externe Koppeling en Relatiesoort lijken sterk op elkaar. Beide entiteiten onderhouden relaties met Objecttype die, op een klein verschil in naamgeving na, hetzelfde zijn. 
Uit de begeleidende tekst maak ik op dat Externe Koppeling bedoeld is om compositierelaties weer te geven en Realtiesoort voor de andere associaties. Compositiereaties worden in UML gevisualiseerd door een zwart wybertje. 
Hoewel zinvol, is dit een onderscheid dat in andere modelleertalen niet wordt gemaakt, althans niet in deze vorm. In andere talen wordt dit i..ha. weergegeven in de naamgeving van de relatie + een constraint. Het is dus te overwegen om Externe Koppeling uit het algemene MIM weg te laten en toe te voegen in een UML-specifieke extensie. 
Omdat Compositierelaties een speciaal soort relaties zijn, verdient het in ieder geval aanbeveling om Externe Koppeling als subtype van Relatiesoort te modelleren.

**Comment by lennartvanbergen-kadaster** [comment]
Het verschil is semantisch. De externe koppeling maakt een koppeling naar een objecttype van een ander domein. De gewone relatiesoort is binnen het eigen domein. Er gelden verder andere metadata aspecten voor. Im UML druk je beide hetzelfde uit, maar om het verschil in betekenis te behouden, is in UML daar het stereotype <<externe koppeling>> voor bedoeld. 

Beide zijn dus geen subtypes van elkaar. Het zijn anders bedoelde, zelfstandige modelelementen. Deze druk je wel uit met een UML-association maar deze overeenkomt wilt niet zeggen dat het subtypes van elkaar zijn. Dat is te veel geredeneerd vanuit UML.

**Comment by lennartvanbergen-kadaster** [comment]
Vraag is beantwoord.
