### ISSUE TITLE
Toelichting op gebruik linked data voor UML vs RDFS/OWL

### ISSUE THREAD

**Issue by rstap** [Geonovum/MIM-Werkomgeving#114]
In het document wordt de aangegeven dat het MIM een (of 'de') basis vormt voor linked data. Linked data kan zich in verschillende hoedanigheden voordoen, denk hierbij als voorbeeld aan de 5 verschillende types die in het 5-sterren model van Tim Bernes Lee wordt genoemd. Het document presenteert linked data als een formaat waarin een op MIM gebaseerd model kan worden uitgedrukt in linked data (primair in triples).

**Voorstel**: Vanwege deze suggestie en de sterke verbondenheid met het UML (OO) gedachtegoed, zou ik er voor willen pleiten om in dit hoofdstuk een aparte sectie/sub-hoofdstuk te wijden aan het paradigma verschil tussen het UML-object en de in de RDFS/OWL linked data gebruikte rdf class. In deze sectie zou duidelijk naar voren moeten komen dat beide paradigma's op dit moment in verschillende toepassingen succesvol worden toegepast, maar dat de onderlinge overlap niet triviaal is en modellen niet uitsluitend op syntax niveau kunnen worden gemapped.

In dit deel zou denk ik ook aandacht kunnen worden besteed aan de W3C semantische modellen zoals die nu o.a. in het KDP/PDOK platform worden toegepast en hoe die relateren aan het betreffende MIM model. Hoewel niet met zoveel woorden in dit document is terug te vinden, heb ik regelmatig begrepen dat met het MM de mogelijkheid zou ontstaan om één bron te creëren van waaruit zowel semantische- als informatie modellen kunnen worden afgeleid. Mocht dit eventueel toch niet het geval is, is het goed om dit expliciet aan te geven.

**Comment by architolk** [comment]
Dit verdient inderdaad meer aandacht. Het MIM is zelf het primaire metamodel, vanuit daar zijn twee representaties mogelijk: naar UML en naar RDF/OWL. Dit mag scherper geformuleerd zijn. Het lijkt daarin sterk op SBVR, waarin 1 model (SBVR) meerdere representaties kent (CogNIAM, RuleSpeak, ORM)

**Comment by rstap** [comment]
Het MIM zoals ik het nu leer kennen via het document heb ik twijfel of het een primair metamodel is (wordt hier in MDA termen een M3 model mee bedoeld?). Ik lees en hoor dat het een profiel is op UML, het geeft geen nadere specificaties over wat een class, attribute en/of associatie is zoals dat in de M3 modellen als e/cMof en ODM wel gedaan wordt. Een OO-objecttype (ook wel een class genoemde) en een RDFS/OWL class zijn verschillende meta-concepten. Een object met eigenschappen en gedrag is iets anders dan een verzameling (klasse) van dingen.
De genoemde representaties in SBVR zijn gebaseerd op hetzelfde gedachtegoed en dan is het prima mogelijk om de representatie van modellen aan te passen.

**Comment by lennartvanbergen-kadaster** [comment]
Reactie op 1 specifiek punt uit de vraag. De beantwoording van de vraag zelf komt later. 

Er staat: "ik hoor dat het een profiel op UML _is_". 

MIM _is_ geen profiel op UML. 

MIM _is_ een specificatie om informatiemodellen mee te maken, die aangeeft welke bouwblokken je hiervoor kan gebruiken, zoals gebruikelijk is bij een metamodel. Dat kan in UML-, het kan met linked data specificatie technieken. 

Wat betreft UML: In de uitwerking is MIM uitgewerkt in o.a. UML. 

Zo komt **objecttype** bijvoorbeeld niet voor in UML, maar wel in MIM en in basisregistraties. 

In dit perspectief is de uitwerking van MIM in een modelleertaal zoals UML inderdaad (bewust) een profiel op UML, want MIM gebruikt hierbij _niet alles_ van UML, maar _alleen_ specifieke componenten van UML. 

Omdat UML zelf niet specifiek genoeg is, een gegevensgroep modelleren we als een UML-Class en een **objecttype** modelleren we als een UML-Class is er aanvullende duiding nodig bij een UML-Class. We doen dat met UML-stereotypes. De UML-Class krijgt als UML-stereotype <<objecttype>>. Daarmee weten we dat het een objecttype is, en kan er model-gedreven mee verder gewerkt worden. 

Zo is een objecttype een concept, een thing, en is een gegevens groep een kenmerk van het concept. Hopelijk brengt dit verheldering ten aanzien waar het woord "profiel" terecht gebruikt kan worden en waar niet.

**Comment by rstap** [comment]
Een korte toelichting:
MIM is geen profiel, alleen maakt het gebruik voor het specificeren van MIM constructies die verdacht veel op lijken op- en uitgelegd worden op een wijze die met UM-profile kennis te plaatsen is, het stereotypering mechanisme.

Verder is wordt gesteld (en ook door Marco bevestigd) dat het geen M3 MDA metamodel is, maar dat MIM constructies geen verwijzing hebben naar een meta-artifact van een OO-class of RDF-class. Afhankelijk van de transformatie wordt de MIM model artifact geinterpreteerd. Dat maakt het lastig een MIM model eenduidig te begrijpen.

**Comment by architolk** [comment]
Roel, je hypothese dat een MIM objecttype een variant van een UML class is, klopt niet. Een MIM objecttype is uitgedrukt als een UML class met een stereotype "objecttype". Daarmee IS het geen UML class, maar UITGEDRUKT ALS UML class. Met andere woorden: met het uitdrukken van een MIM objecttype als een UML class met stereotype "objecttype" wordt uitdrukking gegeven dat het diagramelement UML class de betekenis krijgt van een MIM Objecttype, ongeacht wat een UML class betekent. Vandaar dat een transformatie van een dergelijk stereotype naar het RDF equivalent mim:Objecttype zo goed mogelijk is. En dat de transformatie naar een owl:Class vervolgens dus niet gezien moet worden als een "is gelijk aan", maar juist als: "is een goed transformatie naar".

**Comment by architolk** [comment]
Voor een uitleg over de verschillen tussen UML en LD wordt overigens in het NEN 3610 stuk wel aardig wat gezegd, zie: https://geonovum.github.io/NEN3610-Linkeddata/#basisprincipes.
Ook wordt hier aangegeven wat een vertaling van UML naar RDF anders maakt dan een vertaling van een MIM model naar RDF: https://geonovum.github.io/NEN3610-Linkeddata/#roundtrip

**Comment by rstap** [comment]
...Als iets wordt uitgedrukt als een UML-class met een bepaald stereotype, maar het is het vervolgens niet.... en, even verder wordt gesteld dat een "...UML class de betekenis krijgt van een MIM Objecttype, ongeacht wat een UML class betekent...", dan ben ik wat verbaasd. Na mijn idee heeft een UML-class een gedefinieerde betekenis, nl die van een object met eigenschappen en gedrag (zoals in M3-MOF/ODM is vastgelegd). Ik begrijp niet goed meer wat hier bedoeld wordt, en kan ik het niet meer op de OMG MDA architectuur afbeelden. 

Maar wellicht dat ik e.e.a. niet goed begrijp en dat we met MIM modellen straks toch prima in staat zijn informatie- en semantische modellen af te leiden, ik laat mij dan graag verrassen......

**Comment by architolk** [comment]
Voorstel: zie het voorstel bij #115
