### ISSUE TITLE
OMG-MDA layered model comment

### ISSUE THREAD

**Issue by rstap** [Geonovum/MIM-Werkomgeving#115]
Hoofdstuk 1.7 geeft een uitleg van het 4-lagen OMG-MDA model waarvan ik twijfels heb of die juist en volledig zijn. Het BAG als voorbeeld, zijn de MDA lagen als volgt in te delen: 

- M0 is inderdaad een data representatie (model) van een UoD (bv. de gebouwen en adressen van de gemeente Apeldoorn zoals in de BAG is vastgelegd),

- M1 bevat b.v. het BAG-model waarin de structuur is gedefinieerd hoe de verschillende BAG-objecten in M0 zich tot elkaar verhouden, vastleggen van de relaties en hiërarchie is hier onderdeel van. Dit M1 model is uitgedrukt in UML. Ook ontologieen als SKOS, SHACL, FOAF, Schema.org, etc kunnen als M1 model worden beschouwd.

- M2 bevat het model van UML, de modelleer taal waarin o.a. classes (objecttype)-, attributes-, methods-, associaties-, generalisaties- en containment artifacts zijn gespecificeerd om een M1 model in uit te kunnen drukken. In de semantische W3C omgeving zijn OWL/RDFS voorbeelden van standaarden die in M2 kunnen worden gepositioneerd, en gebruikt worden om in M1 genoemde ontologieen te kunnen specificeren.

- M3 bevat het meta-model van een M2 model, voor UML is dit een MOF en/of c/eMOF.  OMG-ODM (=? eCore) is een relatief recent metamodel van OMG waarin een mogelijkheid zou moeten zijn om een relatie te maken tussen de UML gebruikte MOF concepten en de in RDF geïntroduceerde class-concept. Hier ontbreekt mij de concrete kennis of dit echt het geval is. 

In dit MIM document blijft M3 buiten beschouwing, terwijl daar naar het oordeel van OMG (en ik denk dat ze gelijk hebben) de brug gelegd zou moeten/kunnen worden tussen het UML en RDFS/OWL (class) domein.

**Voorstel**: aanpassen/uitbreiden van de tekst over de door OMG gespecificeerde MDA beschrijving en de MDA layers. Ook zou de rol van M3 daarin kunnen worden toegelicht, ook als die voor MIM niet relevant is het goed om aan te geven waarom dit het geval is.

**Comment by architolk** [comment]
De manier waarop we tot op heden de link leggen, is juist net een iets andere: we beschouwen het MiM als een model dat los staat van het MOF, maar een semantische betekenis heeft, conform het document. Vanuit hier kun je naar UML, waarin je de lagen M0 tot M3 lagen gebruikt. En je kunt naar OWL, waar je ook lagen M0 tot M3 gebruikt, maar M3 is dan een ander model. Deze aanpak stelt het MIM zelf centraal, ipv 1 meta-metamodel. Het is in die zin dus niet zozeer een constructie-aanpak, maar een referentie-aanpak (je refereert naar een term die een betekenis heeft). Zowel UML als OWL hebben eigen formalismen die moeilijk in elkaar uit te drukken zijn. In praktische zin gaat het wat eenvoudiger door het MIM als model er tussen te zetten, feitelijk als "brug" tussen de twee modellen, waarbij het MIM zelf eerder een "zacht" formalisme kent dan een hard. Enige hard eis is dat een bepaalde MIM metaklasse een eenduidige transformatie beide kanten op heeft.

**Comment by architolk** [comment]
Voorstel: feitelijk maken we een profiel, zoals de OMG deze ook heeft gemaakt voor ODM (zie: https://www.omg.org/spec/ODM/1.1/PDF). Daarin wordt op M2 niveau, gebruik makend van het M3 niveau, een profiel neergezet waarbij het UML deel wordt gebruikt (maar niet veranderd), aangevuld met MIM-specifieke stereotypes. Dit is ook beschreven in sectie 1.7, maar vereist voor mijn gevoel nog wat meer toelichting. Ook belangrijk om aan gegeven dat we de M0 tot M3 indeling van de OMG juist niet gebruiken voor de representatie in Linked Data (want dat doen we zoals beschreven in sectie 1.8).

Voorstel is dus om sectie 1.7 te verduidelijken, en voorafgaand aangeven dat we MIM zien als de kern, waar meerdere representaties van kunnen zijn, zoals (voor nu) UML en LD

**Comment by rstap** [comment]
Hi Marco,
Ik heb net een verschillende antwoorden gelezen op eerdere opmerkingen die ik gemaakt heb. Als ik het goed lees wordt er nu aan een verduidelijking gewerkt om MIM als een OMG-profiel te beschouwen? Dat zou wat mij bereft wel helpen om MIM beter te begrijpen....ik ben benieuwd hoe de toelichting er uit gaat zien. 
Wat ik bij het lezen ook lastig vind is het gebruik van de term Linked Data in vergelijking met UML (wat uit een MIM model moet kunnen worden afgeleid). Ik zou haast denken dat hier de term ontologie of semantisch model meer op zijn plaats is. LD is een uitdrukkingsformaat om bv betekenis in de ontolgieen in uit te drukken (syntactisch in bv XML, ttl ed). Ik zou verwachten dan MIM naast UML-model, semantische modellen uitgedrukt in OWL-, SHACL- en/of Skos statements, die vervolgens zijn uitgedrukt in RDF/XML of RDF/TTL.

**Comment by lennartvanbergen-kadaster** [comment]
MIM is een taal en/of een aanpak om een informatiemodel te maken. 

In de MIM vocabulaire wordt in 1e instantie geen woord over UML of OWL gerept. 

De betekenis van een MIM objecttype wordt in 1e instantie dan ook zeker niet ontleend aan een UML-Class.  

Wanneer je MIM uitdrukt in UML dan kies je een goede representatie in UML. Bv. een UML-Class. Hierbij houd je ook rekening met het OO gedachtengoed, oftewel dat het informatiemodel wat je maakt correct is. Uiteraard is het streven dat dit een correcte uitdrukking is in UML. 

Verder is MIM bedoeld om praktisch werkbaar te zijn, en niet te verzanden in theoretische discussies. 
Zodra er een concreet voorbeeld is waar het mis gaat qua interpretatie, in een concreet informatiemodel, omdat bv. iemand iets onbedoeld niet helemaal correct doet, dan kan en mag je daar die persoon gewoon op aanspreken en een tip geven hoe diegene dat beter kan doen. Als er sprake is van een goed argument, dan zal diegene dat vast wel doen.
