### ISSUE TITLE
Definitie past niet goed op een abstracte objecttype (mail FK punt 3)

### ISSUE THREAD

**Issue by JvGldr** [Geonovum/MIM-Werkomgeving#119]
Door de verwijzing naar 'in de werkelijkheid' past de definitie niet goed op abstracte objecttypen.
Suggestie: Abstract = Je maakt er geen instantie van. NB: in linked data kan het wel.

**Comment by lennartvanbergen-kadaster** [comment]
Gaat om MIM 1.01 en 1.1 paragraaf 2.5.2. 

Deze definities met in de werkelijkheid zijn specifiek bedoeld om te voorkomen dat men abstracte objecttypes als objecten gaat zien. 

Met abstract wordt bedoeld: niet concreet, er zijn geen instanties van. Per definitie. 

Met de opmerking; in de werkelijkheid wordt bedoeld dat het om concrete dingen gaat. Het gaat om die duiding. Als je in een informatiedomein dus geen Dieren en geen Honden kan hebben, maar alleen Tekkels en Herdershonden, en je wilt wel aangeven dat bepaalde eigenschappen bij een Hond in het algemeen horen, dan geef je aan dat Hond abstract is en de generalisatie van Tekkel en Herdershond. 

Je kan ook best in een bepaalde situatie een abstracte klasse concreet maken. In allerlei technieken kan het wel. Maar dan wilt nog niet zeggen dat het functioneel zinvol is. 

De zin: in de werkelijkheid klopt dus wel, hoort bij object, en hoort niet bij abstract. 

--

De opmerking, in linked data kan het wel vind ik hier niet zo op zijn plek. Ik begrijp dat je over een Dier kan redeneren en over Hond en een Tekkel ook. Een generalisatie mag in MIM gewoon concreet zijn (niet abstract).

**Comment by lennartvanbergen-kadaster** [comment]
Is geworden: 

>   **Definitie Objecttype**  
>   De typering van een groep objecten die binnen een
>   domein relevant zijn en als gelijksoortig worden beschouwd.

De objecten die in het beschouwde domein onderkend worden behoren altijd tot een concreet objecttype, en niet tot een abstract objecttype. Abstracte objecttypes worden wel gebruikt in de modellering, om generalisaties aan te duiden en de definitie. Zo kan bij het objecttype Pand bijvoorbeeld aangegeven worden dat dit een 'Element in de fysieke leefomgeving' is, en dat deze laatste als een abstract objecctype gezien moet worden (in ons domein). Meer over abstracte objecttypes is beschreven in [Abstracte objecttypes en concrete objecten].

--

(in de werkelijkheid is verwijderd). Dit stond al in de definitie van object, en leidde daarom een beetje af, omdat een objecttype ook abstract kan zijn. Een object kan niet abstract zijn, een objecttype wel. Abstracte objecttypes horen ook goed onder de definitie van objecttype te kunnen vallen. 

Verder een toelichting opgenomen over abstracte objecttypes en een verwijzing naar de paragraaf in Regels en afspraken.

**Comment by architolk** [comment]
Ik ben net bezig met een final check op het model, en het valt me op dat we een "Indicatie abstract object" hebben. Zou het niet beter zijn om deze te veranderen in "Indicatie abstract" of "Indicatie abstract objecttype" (voorkeur voor het eerste). Nu is onduidelijk of de indicatie gaat over abstracte objecten (en dat je die dus kunt hebben...), of dat het gaat om abstract objecttypen (dat is hetgeen we hier bedoelen). Voor de volledigheid heb ik in sectie 2.12 deze indicatie ook toegevoegd (deze ontbrak nog), met een verwijzing naar de sectie die daarover gaat. De definitie heb ik daarbij wel moeten "verzinnen", omdat deze nog niet bestond (wel in het hoofdstuk over UML, maar die is specifiek voor UML en past niet goed op de LD invulling).

**Comment by architolk** [comment]
ps: verzinnen bleek mee te vallen, we hadden hier al eens een zinssnede voor bedacht (die stond echter nog niet op de juiste plaats)

**Comment by lennartvanbergen-kadaster** [comment]
Ja kan, maar is een nieuw issue. Overigens is dit in EA geen data, dus het kan heel makkelijk mee met vrijwel geen impact. Wel weer werk, voor maar een klein detail. Liever opvoeren als niet-blokkerend issue voor MIM 1.1 - klein, prio 3.
