### ISSUE TITLE
Metadata van het informatiemodel zelf en van de packages/subgroepen hierbinnen

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#12]
Grotere uitbreiding op de standaard. Mogelijk hoort dit in MIM, mogelijk erbuiten, mogelijk deels binnen, deels buiten. Diverse keuzes te maken. 

- Package: conceptueel/logisch - Om aan te geven dat een package in EA een conceptueel model bevat of een logisch model (of een toepassingsmodel)

- Apart profiel voor conceptueel of logisch (plus een vertaling)?			

- Om aan te geven dat een package in EA objecten bevat uit het betreffende domein, en niet 'ongetypeerd' is. We kennen bv. wel extern, die heeft wel een stereotype. 

- Iets met UML-version en UML-phase op model niveau. 

- In welk metamodel en op welke extensie is het IM gemodelleerd, en op welke versie daarvan?

Richting: een aantal van deze gebruikt een modelleur als deze een conceptueel of logisch IM maakt, een aantal komen vooral terug bij toepassingen ervan, zoals producten of API's of services. Modelleurs van IM modellen geven aan welke in MIM horen en welke bij toepassingen.

**Comment by PalmJanssen** [comment]
zie ook #10

**Comment by dkrijtenburg-GNM** [comment]
afspraken in overleg op 13 mei 2019:

1. Package: conceptueel/logisch - Om aan te geven dat een package in EA een conceptueel model bevat of een logisch model (of een toepassingsmodel) :  **stereotype 'informatiemodel' toevoegen op niveau package. tag value naam :  TYPE INFORMATIEMODEL  - die geeft aan of het een conceptueel informatiemodel is of een logisch informatiemodel**
2. - Apart profiel voor conceptueel of logisch (plus een vertaling)? - **Nee, blijkt niet nodig**
3 - Om aan te geven dat een package in EA objecten bevat uit het betreffende domein, en niet 'ongetypeerd' is. We kennen bv. wel extern, die heeft wel een stereotype. : **voorstel is stereotype DOMEIN  gebruiken**
4 - Iets met UML-version en UML-phase op model niveau.: **Nee, voorlopig niet voor MIM, kan wel in eigen extensie van een informatiemodel**
5 - In welk metamodel en op welke extensie is het IM gemodelleerd, en op welke versie daarvan? : Ja, opnemen als metadata bij modelelement 'informatiemodel'. **Naam van Metamodel en de Versie van het Metamodel, daarnaast ook (optioneel) de Versie van de extensie van een informatiemodel**

**Comment by ThiesMesdag** [comment]
Tekstvoorstel: 

(H2. 20)

**19a Domein** - *Stereotype «Domein»*: De UML-representatie van een domein
package uitgedrukt in UML-package (metaclass)

>   **Definitie Domein**
>   Een groepering van constructies uit het domein dat met het informatiemodel beschreven wordt.

(H2.3.5)

**Specificatie voor «Domein»**

Domein packages worden naar de volgende aspecten gespecificeerd:

| **Aspect**      | **Kardinaliteit**  | **Toelichting**                                                                                                                                                                                         | **In UML 2.5**                       | **In EA**       |
|------------------------|--------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------|-----------------|
| **Naam**               | 1                  | Algemeen metagegeven. *De naam van het domein package.*                                                                                                                                                 | *name van de metaclass Namedelement* | *Name*          | 
| **Locatie**            | 1                  | Algemeen metagegeven.                                                                                                                                                                                   |                                      | *Tagged value*  | 
| **Definitie**          | 1                  | Algemeen metagegeven. *De beschrijving van de afbakeninig van het (sub)domein dat het package beschrijft. Bijvoorbeeld: Beschrijving van een onroerende zaak en zijn relaties met andere objecttypen.*  | *Body van de metaclass Comment*      | *Notes*         | 
| **Herkomst**           | 1                  | Algemeen metagegeven. *De registratie of het informatiemodel waaraan het package ontleend is. Bij een domein is de herkomst altijd de eigen organisatie.*                                               |                                      | *Tagged value*  |
| **Informatiemodel**    | 1                  | Algemeen metagegeven. *De beschrijving van de aard van het informatiemodel in het package: een conceptueel, een logisch of een toepassingsmodel.*                                                       |                                      | *Tagged value*  |

**Comment by ThiesMesdag** [comment]
TV _informatiemodel_ vind ik niet echt duidelijk. Beter lijkt mij iets als: "_Karakter_" (synoniem van aard)
Ik heb het nu als verplicht opgenomen, maar is volgens mij alleen van toepassing op het bovenste package. Misschien ook alleen op model niveau (is dat nog een apart package?)

Evt ook de tv _informatiemodel/karakter_ opnemen bij _view_ en _extern_ package definitie

**Comment by PalmJanssen** [comment]
- modelelement Informatiemodel nog toevoegen. Tagged value type informatiemodel: conceptueel, logisch, technisch.

**Comment by ThiesMesdag** [comment]
Ik heb het tekst voorstel hiervoor uitgebreid met de definities van de modelelementen en de tagge value tekst aangepast. Dit moet nog gereviewd worden maar lijkt mij af. Als akkoord dan kan de tekst md van hierboven (https://github.com/Geonovum/MIM-Werkomgeving/issues/12#issuecomment-495111244 ) worden toegevoegd aan de werkversie.

**Comment by lennartvanbergen-kadaster** [comment]
Ad. Aard/karakter van informatiemodel.

In MIM wordt in 1.5 de term: Type informatiemodel gebruikt. Die term gebruiken in de TV en de ervan  lijkt me wel zo consistent.

groeten,
Lennart

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by dkrijtenburg-GNM** [comment]
Ter Consultatie

**Onderwerp**:
Metadata van het informatiemodel zelf en van de packages/subgroepen hierbinnen

**Oplossing**:


Aspect | Kardinaliteit | Toelichting | In UML 2.5 | In EA
-- | -- | -- | -- | --
Naam | 1 | Algemeen metagegeven. | name van de metaclass Namedelement | Name
Definitie | 1 | Algemeen metagegeven. | Body van de metaclass Comment | Notes
Type Informatiemodel | 1 | Algemeen metagegeven. |   | Tagged value

**Comment by dkrijtenburg-GNM** [comment]
Aspecten zijn terig tevinden in de documentatie van MIM 1.0.1 :
https://docs.geostandaarden.nl/mim/mim10/

**Comment by ArjanLoeffen** [comment]
Tav. <<informatiemodel>>:

Ik stel voor dit aspect op te nemen een tweede (onderdeel van de) MIM specificatie. Nu is dat "Grouping" genoemd. Daarvoor is een complete spec geïmplementeerd. Hierin zijn onder andere de packages ondergebracht. Packages organiseren o.a. de UML constructs van de MIM standaard. Dus <<extern>>, <<domein>> etc. en ook in lijn met onderhavig voorstel: <<informatiemodel>>. 

Dan ook vaststellen hoe zich dat verhoudt tot <<basismodel>> versus <<toepassing>> versus evt. varianten hiervan in extensies.

Zie #19

**Comment by jacblom** [comment]
Namens Han Welmer:

Ik begrijp dat er momenteel twee onderdelen zijn: MIM sec en MIM Grouping. Gezien het feit dat desondanks dit issue opsteekt, wil ik ervoor pleiten deze twee zaken te integreren.

Naar mijn mening bieden de bestaande stereotypes en bijbehorende tagged values van MIM-Grouping voldoende functionaliteit voor de geuite wensen.

Ik neem aan dat ik daarmee dezelfde mening heb als Arjan Loeffen.

**Comment by ThiesMesdag** [comment]
Punt besproken, tekst van https://github.com/Geonovum/MIM-Werkomgeving/issues/12#issuecomment-495111244 wordt toegevoegd in hoofdstuk packages.
Grouping die niet binnen het informatiemodel valt nemen niet in de specificatie van MIM op, maar is wel belangrijk in de context van de toepassing.
