### ISSUE TITLE
In de tekst opnemen dat het gebruik van Sparx EA niet verplicht is (mail FK punt 5)

### ISSUE THREAD

**Issue by JvGldr** [Geonovum/MIM-Werkomgeving#120]
Rechttrekken a la par. 4.4. alternatieve pakketten benoemen

**Comment by lennartvanbergen-kadaster** [comment]
Met dit punt zijn we het helemaal eens. Dit zal helder worden aangegeven. 

Het netste zou eigenlijk zijn om dit naar de bijlage te verplaatsen, maar omdat veel organisaties dit gebruiken is het ook wel gebruiksvriendelijk om in de gewone tabellen terug te zien, als laatste kolom. We zetten het daarom in algemeenheid neer in het begin van het UML hoofdstuk. Wellicht dat we dit als documentaire slag nog een keer kunnen oppakken, bv. als er nog andere uitwerkingen bij komen.

**Comment by lennartvanbergen-kadaster** [comment]
Opgenomen in hoofdstuk UML. 

De 2e en 4e kolom bevatten de uitdrukking van het MIM in Sparx Enterprise Architect. Deze gebruikt Class (i.p.v. UML-Class). Deze UML tool is (uiteraard) geen onderdeel van de MIM specificatie. Het is zeker niet verplicht om deze te gebruiken, u kunt uw eigen tool gebruiken. Deze kolom staat erbij om illustratief aan te geven dat het soms nodig kan zijn om, afhankelijk van de tool, net iets specifieker aan te geven hoe het MIM in de tool exact uitgedrukt wordt. 

--

Nog te overwegen: andere tools noemen, in een paragraaf: Tool ondersteuning.

**Comment by GeraldGrootRoessink** [comment]
FYI:  DUO gebruikt Magic Draw als vergelijkbare UML-tool en daarmee maken we SKOS+linked data modellen op basis van rdf/shacl/owl zoals beschreven in de MIM 1.1 specificatie.  Dit zou dan weer getransformeerd moeten kunnen worden en ingeladen in Sparx.  Moet nog uitgetest.
