### ISSUE TITLE
Niet elke normreferentie is conform MIM (Mail FK punt 6)

### ISSUE THREAD

**Issue by JvGldr** [Geonovum/MIM-Werkomgeving#121]
De vigerende versie van NEN 3610 is niet afgestemd op MIM. De nieuwe versie wil er wel rekening mee gaan houden. In hoeverre is het handig om een niet-MIM-conforme standaard als NEN 3610/A1:2016 hier als normreferentie te noemen?

Voorstel: Versie-informatie weglaten, net als bij de twee genoemde ISO-normen.

**Comment by JvGldr** [comment]
Tabel is aangepast, note is toegevoegd @lennartvanbergen-kadaster  wil jij de note nog even controleren?

**Comment by lennartvanbergen-kadaster** [comment]
Ja, lijkt me goed. Echter, de linkjes werken niet meer. 

Tekst iets aangepast nog om de gedachte in de opmerking van Frank er beter uit te laten komen.

De versies van de genoemde referenties zijn bewust niet opgenomen, zodat het mogelijk is om gebruik te maken van nieuwere versies van deze referenties. Wanneer er nieuwe versies uitkomen van de genoemde normreferenties dan wordt er gecheckt of MIM hier nog mee in lijn is. Wanneer dit niet zo is, dan wordt eraan gewerkt om dit weer met elkaar in lijn te brengen, zoals MIM 'upward compatible' is en blijft. 

@FrankKooij kan jij je vinden in deze formulering?
