### ISSUE TITLE
Geen verplichte naamgevingsregel voor conceptuele modellen (Mail FK punt 8)

### ISSUE THREAD

**Issue by JvGldr** [Geonovum/MIM-Werkomgeving#123]
De regel verplicht dat je "natuurlijke taal, die dicht bij de gebruiker staat" gebruikt. Maar wat als voor sommige gebruikers Camel Case handiger is? Wie help je ermee om dat dan niet te mogen gebruiken?

Oplossingsrichting: controleren wat er nu in MIM wordt voorschreven, natuurlijke taal (geen camelCase) als aanbeveling opnemen. Zie ook issue #107

**Comment by lennartvanbergen-kadaster** [comment]
Het is wel echt de bedoeling om in een conceptueel informatiemodel de taal te gebruiken die mensen/experts in een domein gebruiken en niet een schrijfwijze die gericht is op eenvoudig voor de techniek. Die conversie naar machine leesbaar is super nuttig, maar hoort bij een logisch model. 

Ik ken geen enkele catalogus van een basisregistratie en geen enkel conceptueel informatiemodel waarin CamelCase gebruikt wordt. 

We kennen niet zoiets als een strong recommendation als een middenweg tussen regel en aanbeveling. 

Inschatting is daarom dat dit niet echt geen concreet issue is, maar meer een inschatting. Laten we daarom wachten met tot er een concreet (en terecht) voorbeeld wordt gegeven.
