### ISSUE TITLE
Onduidelijk voorbeeld (Mail FK punt 9)

### ISSUE THREAD

**Issue by JvGldr** [Geonovum/MIM-Werkomgeving#124]
Voorbeeld 6 in 5.3.1 | Onduidelijk voorbeeld | Ik kan uit dit voorbeeld niet opmaken wat men mij probeert duidelijk te   maken. | Voorbeeld verduidelijken of een ander voorbeeld kiezen.

**Comment by lennartvanbergen-kadaster** [comment]
Er stond e.e.a. aan dingen in die wel nuttige informatie zijn, maar niet als onderdeel van een fijn leesbaar voorbeeld, dat leidde af. De nuttige informatie verwijderd uit het voorbeeld. Voor MIM was deze informatie niet nuttig ook. 

Is geworden: 

_Een voorbeeld van het hergebruik van een gegevensgroeptype door meerdere objecttypen is de specificatie voor het Brondocument in de basisregistratie BAG. Het gegevensgroeptype Brondocument is qua betekenis en structuur voor alle objecttypes gelijk. De definitie en specificatie ervan wordt daarom hergebruikt bij alle objecttypes. Het brondocument wordt binnen de BAG niet gezien als een van de typen objecten van de BAG, en daarom is het geen objecttype maar een gegevensgroeptype._

@FrankKooij hopelijk is dit een beter leesbaar voorbeeld geworden.
