### ISSUE TITLE
Kwaliteit concreter maken in kwaliteitseisen voor specifieke kwaliteitsdimensies (Mail DG punt 11) 

### ISSUE THREAD

**Issue by JvGldr** [Geonovum/MIM-Werkomgeving#125]
Er wordt voorgesteld om een eigenschap "kwaliteit" bij objecttypen op te nemen. De omschrijving is echter zo abstract dat onduidelijk is wat wordt bedoeld (eisen? karakteristieken? regels? welke kwaliteitseigenschappen en dimensies?)

Oplossingsrichting: Uitleg van kwaliteitscriterium overnemen uit stelselcatalogus basisregistraties van Logius.

**Comment by ThiesMesdag** [comment]
Nu: 

> Voor objecttypen die deel uitmaken van een registratie betreft dit de waarborgen voor de juistheid van de in de registratie opgenomen objecten van het desbetreffende type.

In de stelselcatalogus:

> De door de registratie aangeduide mate waarin het begrip of gegevenselement volledig, juist, actueel, nauwkeurig en betrouwbaar is.

Samengevoegd zou dit kunnen worden: 

**Beschrijving van de mate waarin in de registratie opgenomen objecten van het desbetreffende type volledig, juist, actueel, nauwkeurig en betrouwbaar zijn.** 

Daar kun je hele boekwerken over schrijven, dus wij (Kadaster) vullen die standaard met: 

> Zie kwaliteitshandvest op www.kadaster.nl/kwaliteitshandvest. 

Een referentie naar een (globale) beschrijving van de kwaliteit van de gehele registratie. over het objecten van het betreffende typen zegt het niet zoveel.

In de BAG catalogus is het als volgt geformuleerd:

> Een Woonplaats bestaat als hiertoe door het bevoegde gemeentelijke orgaan als zodanig een besluit is genomen. 

Dat zegt dus eigenlijk ook niets over de kwaliteit.

Bij de BRP over geboorteland persoon

> Administratief 99% correct

Dat zegt al meer, maar wat het precies betekent weet ik ook niet.

Bij de BRV het volgende:

> Kwaliteitsborging via jaarlijkse audit, APK- en andere keuringen, terugmeldproces (Wegenverkeerswet 1994, artikel 43c), correctie-/wijzigingsproces (Wegenverkeerswet 1994, artikel 43e).

ook interessant in de BRV doen ze ook wel eens:
> conform NHR

En bij de NHR is het vervolgens niet vermeld bij het betreffende concept.

Mijn conclusie is dat we het wel beter kunnen beschrijven zoals ik het hiervoor heb voorgesteld, maar dat we ons moeten afvragen of het wel een zinvol metadata element is.
