### ISSUE TITLE
Afstemming tussen MIM 1.1 en NTA 8035 (Mail EOpunt 12)

### ISSUE THREAD

**Issue by JvGldr** [Geonovum/MIM-Werkomgeving#126]
Zorg voor wederzijdse duiding en naadloze afstemming tussen MIM 1.1 en NTA 8035. En gebruik desgewenst het GWSW als test case om te zorgen dat beide werelden verenigd worden en in de praktijk tot goed bruikbare informatiemodellen en data-uitwisseling leiden.

Oplossingsrichting: Kennissessie organiseren om beide standaarden op elkaar af te stemmen.

**Comment by mickbaggen** [comment]
Met de publicatie van de herziene NEN 2660-1 en NEN 2660-2 in april 2022 is de NTA 8035 komen te vervallen.
