### ISSUE TITLE
Attribuutsoort en relatiesoort versus attribuut en begrip (Mail DG punt 13)

### ISSUE THREAD

**Issue by JvGldr** [Geonovum/MIM-Werkomgeving#127]
Het is onvoldoende duidelijk waarom gevestigde begrippen als "attribuut" en "relatie" moeten worden gevolgd door de postfix "soort". Dit lijkt op een additioneel metaniveau te duiden, terwijl dat niet het geval is.

Oplossingsrichting: uitleg toevoegen bij objecttype, attribuutsoort en relatiesoort.

**Comment by PalmJanssen** [comment]
Deze tekst toegevoegd:
Bij attribuutsoort:
Een attribuutsoort is de metaklasse waarmee kenmerken van een instantie van objecttype worden vastgelegd. Het zijn de kenmerken waarvoor gegevens worden bijgehouden.

Bij relatiesoort:
*Toelichting:* Objecten hebben eigenschappen die gemodelleerd kunnen worden met
attribuutsoorten maar ook met relatiesoorten naar andere objecttypen. Relatiesoort is de metaklasse waarmee deze eigenschappen worden beschreven.
