### ISSUE TITLE
Identificeren classificerende attribuutsoort

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#128]
In een UML MIM model is het niet altijd gebruikelijk om classificaties van een objecttype ook als objecttypen te definiëren. In een Linked Data MIM model is dit wel gebruikelijk. Dergelijke objecttypen hebben geen onderscheidende attribuutsoorten of relatiesoorten t.o.v. hun supertype. In een UML MIM model worden dergelijke classificaties soms ondergebracht in een classificerende attribuutsoort, waaraan een datatype hangt met de mogelijke waarden (classificaties). Zie bijvoorbeeld de attribuutsoort "openbareRuimteType" met als datatype "TypeOpenbareRuimte" met waarden als "Weg", "Terrein", "Water". In het Linked Data model zijn deze waarden afzonderlijke objecttypen als subtypen van het objecttype "OpenbareRuimte".

Het moet mogelijk zijn om:
- Expliciet de classificaties als waarden op te nemen bij een datatype, waarbij duidelijk is dat deze waarden subtypen zijn van een bepaald objecttype;
- Expliciet de subtypen van een objecttype opnemen, waarbij duidelijk is dat deze subtypen ook de waarden zijn van een bepaald datatype.

(met op: in dit requirement is de attribuutsoort feitelijk niet van belang, maar kan wel gebruikt worden in de link tussen het objecttype en het datatype)

**Comment by architolk** [comment]
Voorstel: "indicatieClassificerend" als aspect bij attribuutsoort opnemen. Zowel in het algemeen hoofdstuk, als in de vertalingen naar UML en LD

**Comment by PalmJanssen** [comment]
De waarde van de TV Indicatie classificerend is JA of NEE. Dit moet nog toegevoegd worden.

Dit is toegevoegd.

In de UML diagrammen is de TV Indicatie classificerend toegevoegd. (nog niet in Respec)
