### ISSUE TITLE
Genereren XSD's in GML ISO profiel - hoe aangeven

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#13]
Generatie naar GML feature collection, heeft dit beschrijvingen nodig op het metamodel op logisch niveau?

Duiding: mag niet in IM, hoort in product. Niet MIM.
 
Richting: Imvertor parameter voor aansturing generatie (niet in UML), een how-to hulpdocument maken met een voorbeeld, Peter Lentjes?

**Comment by dkrijtenburg-GNM** [comment]
let op : dit is tooling BEHORENDE BIJ  1.1 beta. Wordt dit gelijk opgeleverd bij 1.1 beta?
wens is dat de versienummering van de tooling gelijk loopt met MIM of heel duidelijk is gelinked
