### ISSUE TITLE
Datum Opname als metadata bij (alle) modelelementen 

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#130]
Deze ontbreekt nu per ongeluk op 1 plek, bij Generalisatie (en mogelijk elders nog vergeten...). Dit gaan we nog toevoegen, in algemeenheid.

**Comment by PalmJanssen** [comment]
Procesinfo:
- verwerkt in uml diagrammen
- verwerkt in hfst 3
- niet verwerkt in hstk 4
