### ISSUE TITLE
Verwijzen naar modelelementen uit het eigen model of een extern model (enhancement)

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#131]
Ik wil graag nog wel als enhancement kijken of we het verwijzen naar externe definities wat eleganter op kunnen lossen. Bijvoorbeeld met een metadata veld: externe definitie - waarin dan een URI of een andersoortige verwijzing, te weten de systematiek die het externe definitie hanteert voor verwijzingen.

Dit naar aanleiding van #104 - die we hebben opgelost met een conventie, maar dit kan wellicht wat explicieter en eleganter.

**Comment by dkrijtenburg-GNM** [comment]
is dit een y-versie of een z-versie issue?

**Comment by JanCampschroer** [comment]
Komt er mogelijk op neer dat je in een gegevensmodel niet formeel kunt uitdrukken dat je een naar een andere populatie (van gegevensobjecten) kijkt.

**Comment by lennartvanbergen-kadaster** [comment]
Om dit op te lossen wordt een y issue.
