### ISSUE TITLE
Multiple supertypes en static/mixin

### ISSUE THREAD

**Issue by ArjanLoeffen** [Geonovum/MIM-Werkomgeving#132]
Zover ik nu kan zien zijn meerdere supertypen voor één subtype niet mogelijk. Is dat juist, en kunnen we uitleggen waarom dat zo is?
Ook zou ik graag zien dat we een standpunt innemen rondom de inzet van _Static liskov_ relaties: https://en.wikipedia.org/wiki/Liskov_substitution_principle

**Comment by lennartvanbergen-kadaster** [comment]
Ik zie het ook. Maar dat was niet de bedoeling. Je mag meerdere generalisaties aanbrengen. Bij Kadaster doen we dit, bv. om op de juiste plek in een generalisatie hiërarchie koppelingen naar INSPIRE te kunnen maken. Het is niet altijd mogelijk om dit op het hoogste niveau te doen.

**Comment by lennartvanbergen-kadaster** [comment]
Is al sinds 1.0 kardinaliteit 0..1

Als Kadaster hebben we dus een extensie. Het is op zich wel een wens vanuit Kadaster om dat 0..* te maken, als andere organisaties dat ook willen. Zolang wij de enige zijn is het tot het zover is dus een item voor in de Kadaster extensie.

**Comment by ArjanLoeffen** [comment]
Technische mogelijkheid om multiple inheritance te realiseren kan door bepaalde superklassen als "Mix-in" of "Static" te identificeren. Zie http://inspire-extensions.wetransform.to/patterns/multiple-inheritance.html. 

Om dit moment gebruiken Imvertor modellen ook wel stereo Static op de generalisatie. Inspire spreekt (zover ik kan nagaan) over Mix-in, dat hetzelfde beoogt.

Dus meenemen in de volgende MIM?

**Comment by PalmJanssen** [comment]
Het multiple stereotype issue is opgelost in #160 en is in versie 1.1.1 toegestaan.

De mixin of static is een ander (wel gerelateerd) onderwerp. Vraag is of we dat voor versie 1.1.1 doen.

**Comment by PalmJanssen** [comment]
Verder uitzoeken voor opname 1.1.1.
Voorkeur static (of static liskov) als stereotype op generalisatie

**Comment by lennartvanbergen-kadaster** [comment]
https://en.wikipedia.org/wiki/Liskov_substitution_principle

**Comment by PalmJanssen** [comment]
even wat dingen opgezocht over liskov en mixin. Deze zin kom ik tegen:
Liskov substitutional principle (LSP)

In 1977 Barbara Liskov defined her substitutional principle: an object from the subtype can appear in every place where its supertype's objects can. That is one of the most fundamental rule in object-orientation: a derived object can appear everywhere the base object can.

The problem is, that this does not hold for mixins.

Hieruit concludeer is dat een mixin juist niet voldoet aan het liskov principe.

Voorstel is om de relatie daarom een mixin relatie te noemen ipv static of static liskov.

De definitie van de mixin generalisatie is  langs deze lijn: Each mixin target is a collection of methods or properties that can be injected into the mixin source class. Mixin classes are typically narrow in scope and not meant to be extended by themselves.

(opmerking: INSPIRE gebruikt gmlMixin als tagged value op een klasse. Dus niet op de relatie maar op de klasse. Dit is opzich gebruikelijk maar maakt de mixin minder zichtbaar en zorgt dat de mixin een klasse-eigenschap is terwijl een relatie eigenschap meer voor de hand ligt)

Voor het metamodel wordt het dan zo iets:
![image](https://user-images.githubusercontent.com/9932784/144034745-2dd89437-889f-4030-ad6b-171fcf459c25.png)

**Comment by pmaria** [comment]
We lopen hier het gevaar om concepten uit object-georienteerde software ontwikkeling te verwarren met informatiemodellering. 

Een mixin in het object-georienteerde paradigma is een manier om functies en gedrag uit verschillende software-objecten (meestal interfaces) te combineren in 1 object, zonder dat je daarbij overerving gebruikt. In programmeertalen die geen multiple inheritance ondersteunen is dit een manier om toch multiple inheritance te kunnen simuleren, omdat je het software-object middels de interface op plekken kunt gebruiken waar die interface verwacht wordt.

Een mixin is dus niet een specialisatie van generalisatie en zou niet op die manier opgenomen moeten worden in het metamodel.

Bij informatiemodellering hebben we het niet over software-objecten met functies en toestanden, maar over verzamelingen van objecten en deelverzamelingen / intersecties etc. 

We willen middels multiple supertypes dan ook uitdrukken dat een object tot meerder verzamelingen behoort. En daarmee dus ook eigenschappen kan hebben die horen bij deze verzamelingen. Deze informatie is van semantische waarde en kan gebruikt worden voor kennisafleidingen.

In een conceptueel model lijkt het dan ook prima en gewenst om multiple inheritance (via generalisatie) toe te passen.

Dat neemt niet weg dat je in een logisch en technisch model alsnog zult moeten bepalen wat je in een dergelijke situatie moet doen. Een mixin-achtig construct zou daar uitkomst kunnen bieden.

Volgens mij hebben we in MIM al iets wat heel erg op een mixin-construct lijkt: Gegevensgroep. 

> De attribuutsoorten van het gegevensgroeptype zijn semantisch gezien eigenschappen van het objecttype. Echter, vanwege samenhangend gedrag (ze horen semantisch bij elkaar, ze wijzigen bijvoorbeeld gelijktijdig e.d.) zijn deze ondergebracht in een apart modelelement. Het onderbrengen van attribuutsoorten in een groep c.q. in het modelelement gegevensgroeptype, is een modelleerkeuze, het is niet perse noodzakelijk.

Hoewel daar nog een discussie over loopt in #170 
Volgens mij moeten eerst kijken of we daar niet al de oplossing mee in handen hebben.

**Comment by PalmJanssen** [comment]
@ pano. Goede observaties. Zeker ook dat multiple inheritance pas een probleem kan zijn bij logische modellen en dus eigenlijk een oplossing gezocht wordt voor de implementatie-omgeving. De vraag is dan inderdaad of de oplossing niet is om de multiple inheritance van het conceptuele model in het logische model op te lossen door de mixin (of copy in)  gelijk operationeel toe te passen, bijvoorbeeld met een gegevensgroeptype. Je krijgt daarmee wel een groot verschil tussen conceptueel en logisch. De mixin constructie houdt beide dichter bij elkaar.

Mixin is geen constructie die veel binnen één model gebruikt. Binnen één model zal je het waarschijnlijk anders kunnen oplossen. Het is meer een constructie om relaties tussen modellen of extensie op modellen te maken.

Ik voeg deze link toe waarin mixin gebruik binnen INSPIRE wordt uitgelegd: http://inspire-extensions.wetransform.to/patterns/multiple-inheritance.html

**Comment by pmaria** [comment]
Dit is iets voor een logisch model. Hoort niet thuis in een conceptueel model.
