### ISSUE TITLE
Mogelijk geen waarde in diagrammen in bijlage staan op Nee maar moet Ja zijn

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#133]
Bij attribuutsoort en relatiesoort (en rol) staat nu: mogelijk geen waarde: Nee 

De Nee mag weg (of als dat niet kan, maak er Ja van)

**Comment by lennartvanbergen-kadaster** [comment]
Mag ook in 1.11 wmb

**Comment by PalmJanssen** [comment]
daarmee  wordt bedoeld dat de default nee is. Maar is mogelijk verwarrend in dit diagram

**Comment by lennartvanbergen-kadaster** [comment]
Aah. Ok, dan vervalt dit item.

**Comment by PalmJanssen** [comment]
Ik heb de default Nee waarde toch weggehaald uit de diagrammen. Het voegt geen informatie toe
