### ISSUE TITLE
Configuratie issue: MIM respec verwijzing naar vorige versie werkt niet

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/MIM-Werkomgeving#134]
In config.js staat:

```
previousPublishDate: "2019-06-19",    	    // Format is "YYY-MM-DD"
previousMaturity: "GN-DEF",                 // kies 1 van deze 3 regels
```

Dit levert een gebroken link op:

> Vorige versie:
> https://docs.geostandaarden.nl/mim/def-st-mim11-20190619/

Op deze URL bestaat geen document. 

Wel is op deze docs URL een 'bevroren werkversie' van MIM 1.1gepubliceerd: 
https://docs.geostandaarden.nl/mim/wv-st-mim11-20191029/

Oplossen: 
``previousPublishDate`` en ``previousMaturity`` invullen met de juiste datum en status.

**Comment by dkrijtenburg-GNM** [comment]
opgelost
