### ISSUE TITLE
MDG: Gestructureerd datatype als stereotypekeuze bij een class

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/MIM-Werkomgeving#136]
Di is een issue voor het MDG EA profiel

Een class kan nu alleen maar een objecttype of een gegevensgroep zijn. Wenselijk is om ook het stereotype Gestructureerd datatype toe te kunnen kennen. Zelfde geldt voor Keuze.

**Comment by lennartvanbergen-kadaster** [comment]
Dit is een issue wat al zeker 3x is besproken en afgevoerd.  

We willen maar 1 modellering in UML. Een Datatype is niet hetzelfde als een Class. Dat behoeft geen nadere uitleg. 

Een gestructureerd datatype is gedefinieerd in MIM, uitgedrukt in UML, als een stereotype op een UML-datatype. 

Aangezien een gestructureerd datatype een datatype is, hoort daar heel correct een UML-Datatype bij (en niet een UML-Class).

**Comment by PalmJanssen** [comment]
Dit heeft betrekking op de EA omgeving. Ik gebruik het nieuwe EA profiel om de NEN3610:2011 naar de MIM1.1 om te zetten. In die modellen is een EA:Class met het stereotype DataType gebruikt om een DataType aan te geven. Daar is in NEN 3610 niets mis mee. Voor de MIM toepassing wel. Het was handig geweest als in het MIM EA profiel dat stereotype op een EA:class had gekund. Maar dat staat het dus niet toe. Dat is inderdaad het zuiverst.

**Comment by lennartvanbergen-kadaster** [comment]
De staande afspraak is om voor MIM datatypes in UML het UML datatype te gebruiken, zoals UML het altijd bedoeld heeft. 

Ik zie geen reden om bij de overzetting van oude NEN3610 modellen naar nieuwe NEN3610 modellen het op de nette (en enige juiste) manier te doen.

**Comment by PalmJanssen** [comment]
OK. Is voor nu geen issue meer.
