### ISSUE TITLE
conceptenregister: definities missen o.a. leestekens van type é

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/MIM-Werkomgeving#138]
Publicatie in conceptenregister.

De volgende definitie mist de é in de tekst. Mogelijk komt dat ook bij andere begrippen en leestekens voor:

[https://definities.geostandaarden.nl/imkl/doc/begrip/Kabelbed](https://definities.geostandaarden.nl/imkl/doc/begrip/Kabelbed)

**Kabelbed of Geul**
Ruimtebeslag dat door een gemeenschappelijk trac van n of meer kabels buizen HDPE- en of mantelbuizen die toebehoren aan n netbeheerder - wordt gevormd.

dit moet zijn:
Ruimtebeslag dat door een gemeenschappelijk tracé van één of meer kabels, buizen, HDPE- en/of mantelbuizen – die toebehoren aan één netbeheerder - wordt gevormd.

**Comment by lennartvanbergen-kadaster** [comment]
@PalmJanssen is dit eentje voor MIM?

**Comment by PalmJanssen** [comment]
Nee. Foutje.
