### ISSUE TITLE
Primitief datatype voor integer en real toevoegen

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/MIM-Werkomgeving#141]
Van Maarten van de Broek (werkend aan IMWOZ)

•	Toevoegen primitiefDatatypen voor Integer en Real naast het nu bestaande primitiefDatatype voor String
Voor Strings definieert MIM1.1 het stereotype 'Primitief Datatype' met als tagged values onder andere Lengte en Formeel patroon. Voor gehele en reële getallen is er behoefte aan een analoog 'Primitieve Integer' en Primitieve Real' met als tagged value onder andere totalDigits, minExclusive, maxExclusive, minInclusive, maxInclusive en fractionalDigits (de laatste alleen voor Primitive Real). Voor de definities van deze tagged values wordt aangesloten bij de definities in XSD Schema. Primitive Integer en Primitive Real hebben geen tagged value voor formeel patroon, omdat regular expressions alleen worden toegepast op char's. Graag op korte termijn uitsluitsel over het toevoegen van deze twee extra stereotypen, want dan kan de Waarderingskamer hier desgewenst gebruik van maken.

**Comment by PalmJanssen** [comment]
voorstel:

Verifieer de lijst van MIM primitieve datatypen en publiceer die ergens voor operationeel gebruik

**Comment by Gtrouborst** [comment]
### Actie
 - **Wilko**: gaat EA inrichten met deze datatypes en xmi's publiceren ASAP
 - **Paul**: Paul gaat definities toevoegen in EA/xmi
 - **Gerard**: `.ttl` maken voor `definities.geostandaarden.nl`  + in MIM1.2-documentatie 5.1.1 regel opnemen onder tabel met link naar `register.geostandaarden.nl`.

### Additioneel
 - **Wilko**: mapping files maken voor Imvertor

**Comment by Gtrouborst** [comment]
Tekst incl. to do note dat link naar register,geostandaarden opgenomen moet worden. Punt 2 en 3 gaan niet mee in v1.2.
