### ISSUE TITLE
Metagegevens bij relatieklasse ontbreken - toevoegen analoog aan relatiesoort

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/MIM-Werkomgeving#143]
Een MIM:Relatieklasse heeft een zeer beperkte set aan meta-eigenschappen. Er is een wens om dit uit te breiden. Minimaal met een TV Toelichting

**Comment by PalmJanssen** [comment]
Het is in feite een set aan gegevens die een instantie van een relatie beschrijven. De set aan gegevens heeft een identificatie en is instantieerbaar. Een huwelijk is een voorbeeld van een relatieklasse. Er is volgens mij geen reden om een relatieklasse minder uitvoerig te beschrijven dan een Objecttype.

Voorstel: zelfde metagegevens als een objecttype

**Comment by PalmJanssen** [comment]
Relatieklasse is nu als specialisatie van relatiesoort opgenomen. Voorstel is om dit niet te doen en het als verbijzondering van Objecttype op te nemen. De Relatieklasse heeft daarbij ook Attribuutsoorten en Gegevensgroepen

**Comment by PalmJanssen** [comment]
Voor nu 'gewoon' TV toevoegen. Inclusief kardinaleit. In latere  versie mogelijk anders modelleren.

**Comment by PalmJanssen** [comment]
Het is een discussie of relatieklasse alle metagegevens heeft die een objecttype heeft of alle metagegevens van een relatiesoort. In MIM 1.1 is relatieklasse een directe specialisatie van relatiesoort. Als voorstel zijn daarom alle relatiesoort metagegevens via overerving ook bij relatieklasse opgenomen:

![image](https://user-images.githubusercontent.com/9932784/144030075-e46af2b2-b1c8-4d8a-a599-c291e4f060e2.png)

**Comment by PalmJanssen** [comment]
Procesinformatie:
- tabel voor relatieklasse in h3 aangepast. Is nu een kopie van tabel voor relatiesoort.
- aanpassing in uml diagrammen is gedaan maar nog niet gepubliceerd.
- aanpassing in h4 nog niet gebeurd.

**Comment by architolk** [comment]
Er lijkt nog een foutje te zitten in de Metagegevens bij relatieklasse: ook de binding met Attribuutsoort ontbreekt. Hierdoor is het nu onmogelijk volgens het Metamodel om een Attribuutsoort aan een Relatieklasse te hangen, waarmee het hele idee van de toegevoegde waarden van een Relatieklasse eigenlijk wegvalt. Dit is waarschijnlijk nooit de bedoeling geweest, daarom voorstel om het ook dit metagegeven toe te voegen aan Relatieklasse (overeenkomstig Objecttype en Gegevensgroeptype) in H2. Dit zal dan automatisch ook consequenties hebben voor H3 en H4 (toevoegen van een extra binding)
