### ISSUE TITLE
HTML fouten en gebroken link in gepubliceerde versie

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/MIM-Werkomgeving#147]
In de 1.1 def versie van het MIM zitten nog diverse HTML fouten (`<div>` tags met niet toegestane attributen, een `<p>` binnen een `<pre>`, etc.) 

Ook is de link naar de NEN3610 standaard gebroken. 

Graag oplossen in volgende versie.

**Comment by dkrijtenburg-GNM** [comment]
veel typo's er uit gehaald, ook de gebroken link hersteld, en diverse fouten (alle?) opgelost.

**Comment by lvdbrink** [comment]
Volgens mij goed zo!
