### ISSUE TITLE
UML voorbeelden voor relatiekeuze toevoegen

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/MIM-Werkomgeving#150]
Het keuze stereotype voor relaties is vrij abstract en moeilijk te begrijpen. Waarom staat de voorbeelden er niet in:

![image](https://user-images.githubusercontent.com/9932784/111344680-defb2600-867c-11eb-86fd-4de12f13dd7f.png)
![image](https://user-images.githubusercontent.com/9932784/111344838-08b44d00-867d-11eb-8ee2-34bdcd3577a3.png)

**Comment by lennartvanbergen-kadaster** [comment]
Hier is ook een issue van bij 
https://github.com/Imvertor/Imvertor-Maven/issues/186 
Wel goed om die er ook bij te pakken.

**Comment by PalmJanssen** [comment]
Zoals ik het begrijp helpt een toevoeging van onderstaand UML als voorbeeld uitwerking bij voorbeeld 9 van https://docs.geostandaarden.nl/mim/def-st-mim-20201023/#keuze.

![image](https://user-images.githubusercontent.com/9932784/137110323-6e5aec25-a8ba-46ca-ba5b-aa4b1bd0b525.png)




Figuur X: Voorbeeld van Keuze tussen relatiedoelen uitgewerkt in UML.

**Comment by PalmJanssen** [comment]
aangepast uml voorbeeld

![image](https://user-images.githubusercontent.com/9932784/139872754-a29a807f-6d35-4a6e-98ca-96bdeb014095.png)

**Comment by lennartvanbergen-kadaster** [comment]
Er zit een relatie met https://github.com/Geonovum/MIM-Werkomgeving/issues/171 waarin er sprake is van een keuze tussen 2 relaties (hier uitgewerkt is 1 relatie, die 2 targets heeft).
