### ISSUE TITLE
MIM - historie aanpassen

### ISSUE THREAD

**Issue by dkrijtenburg-GNM** [Geonovum/MIM-Werkomgeving#151]
materiele en formele historie aanpassen naar tijdlijn geldigheid en tijdstip registratie in de lijn van NEN 3610

**Comment by lennartvanbergen-kadaster** [comment]
Alsmede, de standaardisatie die t.b.v. de SOR heeft plaatsgevonden samen met VNG, waarderingskamer, Geonovum, Kadaster e.a. 

Dit is hetzelfde meen ik ... maar MIM is in principe NEN3610 'loos'. 

De metagegevens in MIM geven aan: hou je formele historie bij Ja/Nee. We kunnen de implementatie ook voorschrijven, conform NEN3610, maar dat lukte eerder niet vanwege dat dit niet exact hetzelfde was als in StUF (moment van verwerking in de registratie wat 1 moment, en geen tijdslijn). Wellicht dat het met de bril van nu en de eisen aan de modellering van de SOR wel kan...

**Comment by ThiesMesdag** [comment]
Aanvulling nav bespreking, ook toevoegen dat foutherstel valt niet onder te historietags valt.

**Comment by lennartvanbergen** [comment]
Dit gaat niet over NEN3610. 

Dit gaat over het metagegeven of een verandering invloed heeft op: 

- tijdslijn geldigheid

- tijdslijn registratie 

en dat de huidige metagegevens geen fijne naam hebben en wat achterlopen in deze zin.

**Comment by lennartvanbergen** [comment]
Voorstel: 
- heeft tijdslijn geldigheid
- heeft tijdslijn registratie 

Deze verklaren we tot gelijkwaardig met indicatie materiële historie en formele historie, het zijn alternatieve termen (en de oude term wordt t.z.t uitgefaseerd bij 2.0, hier maken we een opmerking over). 

De tekst mag iets uitgebreider. We zetten er dingen bij zoals: 

H5 
Deze metagegevens geven op conceptueel niveau wat aan over de veranderlijkheid van de eigenschappen van een objecttype. Deze metagegevens worden daarom typisch gezien gespecificeerd in een conceptueel informatiemodel. 

Wanneer een eigenschap veranderlijk in de tijd is, zoals de lengte van een natuurlijk persoon, dan is het vaak relevant om hier historie over op te bouwen middels een tijdslijn geldigheid. Vul dan de waarde 'ja' in. Het opbouwen van historie is echter niet verplicht. Wanneer het opbouwen van historie niet relevant is, omdat alleen de actuele toestand relevant is, gebruik dan de waarde nee. Merk op dat met dit metagegeven niet aangegeven kan worden of een eigenschap veranderlijk in de tijd is, er heeft een vertaalslag plaatsgevonden naar wat dit betekent voor het bijhouden van een tijdslijn geldigheid. 

Wanneer een eigenschap van een object onveranderlijk in de tijd is, zoals een geboortedatum, dan is het vaak niet relevant om hierover een tijdslijn geldigheid op te bouwen. Vul dan bij de eigenschap van het objecttype de waarde nee in. Het gegeven dat we kennen voor deze eigenschap zal dan eenmalig worden vastgesteld en hierna altijd gelijk blijven (het mogelijk maken van foutherstel is geen reden om voor dit metageven ja in te vullen). Desalniettemin kan het zo zijn dat voor een eigenschap het wel; relevant is om te weten wanneer het onveranderlijke gegeven geldig is geworden, gebruik dan de waarde ja. 

In een logisch gegevensmodel kunnen voorgenoemde metagegevens uitgewerkt worden naar concrete tijdslijnen, met metagegevens zoals bijvoorbeeld:

- voor de tijdslijn geldigheid bijvoorbeeld: 'begin geldigheid' en 'eind geldigheid' om aan te geven wanneer een gegeven, of de hele set van gegevens van een object, geldig zijn. Wanneer een gegeven voor een eigenschap van een object verandert dan begint er een nieuwe periode van geldigheid. 
- voor de tijdslijn registratie bijvoorbeeld: een 'registratiemoment' van een gegeven, en wanneer er voor dezelfde eigenschap een nieuw gegeven geregistreerd wordt dan is het oude gegeven per dit nieuwe registratiemoment niet meer het meest actuele gegeven voor deze eigenschap. 

Er zijn op het niveau van een logisch gegevensmodel meerdere uitwerkingen mogelijk. MIM is niet voorschrijvend voor hoe deze uitwerking er precies uit moet zien en de uitwerking kan ook verschillen per aard van een model. Zo zal het niet voor elke bevraging nodig zijn om de tijdslijnen te kennen en uit te wisselen. 

Tot slot, het is van belang om te weten welke gegevens bij echte eigenschappen van een objecttype horen, zoals een geboortedatum en een lengte van een natuurlijk persoon, en welke gegevens metadata zijn, zoals de data die we bijhouden voor bijvoorbeeld begin geldigheid en registratiemoment. Deze laatste zijn geen eigenschappen van een natuurlijk persoon. Anders gezegd, de gegevens die bij de tijdslijnen horen zijn altijd metadata.

**Comment by PalmJanssen** [comment]
@Gtrouborst, procesopmerking: deze is al in pull request #346 verwerkt en gemerged in de master.

Maar: 
- afwisselend wordt er tijdlijn en tijdslijn geschreven, dat moet nog door de editor gelijkgetrokken worden naar tijdlijn (zonder s).
-  waarden ja en nee staan afwisselend met hoofd- en kleine letter. Moet zijn met hoofdletter 'Ja' en 'Nee'

- Moet ook nog in UML diagrammen worden verwerkt. Doe jij dat Gerard?

@pano Dit is nog niet verwerkt in hoofdstuk 4. Kan jij dat fixen?

**Comment by Gtrouborst** [comment]
@PalmJanssen Yes, pak ik op!

**Comment by Gtrouborst** [comment]
#### Controlevraag
@PalmJanssen: aanpassing van de diagrammen gaat om het **toevoegen van de metagegevens** `heeft tijdlijn geldigheid` en `heeft tijdlijn registratie` bij `«Attribuutsoort»`, `«Relatiesoort»`, `«Relatieklasse»` en `«Externe koppeling»` toch?

![image](https://github.com/Geonovum/MIM-Werkomgeving/assets/36916421/1c427ecc-b426-4452-aec5-a31a58fc439c)

**Comment by Gtrouborst** [comment]
Verwerkt in documentatie
