### ISSUE TITLE
Is er al een Ontologie MIM conform

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/MIM-Werkomgeving#152]
Is er al een MIM conforme ontologie gemaakt bij Geonovum of ergens anders?

**Comment by lennartvanbergen-kadaster** [comment]
Wat wordt hier bedoeld met ontologie: een MIM paragraaf 1.6 niveau 1: begrippenkader? 

Of een ontologie met objecttypen die een ontologische relatie met elkaar hebben, op niveau 2: conceptueel informatiemodel 
(niet te verwarren met een model van skos:concepts)

**Comment by PalmJanssen** [comment]
niveau 2

**Comment by lennartvanbergen-kadaster** [comment]
RSGB deed dat. IMBAG heeft het. IMKAD is eigenlijk 2 en 3, het is 2, uitgebreid met wat niveau 3 aspecten.

**Comment by dkrijtenburg-GNM** [comment]
voorbeeld Thies : https://github.com/bp4mc2/bp4mc2-zvg/tree/master/informatiemodel/mim

**Comment by dkrijtenburg-GNM** [comment]
voorbeeld op website

**Comment by dkrijtenburg-GNM** [comment]
gecheckt bij Linda op 7-6-21:  haar antwoord: Heb ik niet in beeld. Binnen Disgeo willen we dit doen. Binnen Geonovum nog niet eerder gedaan.
