### ISSUE TITLE
Metagegeven Lengte normatief vastleggen wat de betekenis en de notatiewijze is

### ISSUE THREAD

**Issue by wilkoquak** [Geonovum/MIM-Werkomgeving#153]
Voor het metagegeven Lengte staat normatief beschreven dat het 'de aanduiding van de lengte van een gegeven' bevat. In de toelichting staat dan een aantal voorbeelden hoe dit metagegeven gebruikt kan worden. Echter dit is niet normatief waardoor eenduidige invulling van die metagegeven niet gegarandeerd is.

Voorstel: zorg voor een normatieve invulling zodat deze gebruikt kan worden bij het automatisch verwerken van MIM modellen.

**Comment by JanCampschroer** [comment]
ja

**Comment by wilkoquak** [comment]
Nog een extra toevoeging. In sommige gevallen is het gewenst alleen een maximum aantal cijfers achter de komma te specificieren. Dat kan nu niet. Voorstel: Een waarde '*,2' specificeert alleen dat er twee cijfers achter de komma moeten komen.

**Comment by wilkoquak** [comment]
En nog een nabrander. In uitwisseling is het gebruikelijk voorloopnullen en naloopnullen weg te laten terwijl er nu explicit dat het om de lengte gaat. Je zou dus eigen 0001 moeten uitwisselen bij een getal met lengte 4.

Voorstel: Definieer het metagegeven Lengte als de maximale lengte.

Wilko Quak (007)

**Comment by lennartvanbergen-kadaster** [comment]
Het leuke aan 0001 is dat het geen Integer is, maar een String die je alleen mag vullen met getallen, wat je via een reguliere expressie kan specificeren.   

Voor 0001 kan je dus lengte 4 kiezen (precies).  

4 betekent precies 4
1..4 betekent 1 t/m 4.

**Comment by lennartvanbergen-kadaster** [comment]
> Nog een extra toevoeging. In sommige gevallen is het gewenst alleen een maximum aantal cijfers achter de komma te specificieren. Dat kan nu niet. Voorstel: Een waarde '*,2' specificeert alleen dat er twee cijfers achter de komma moeten komen.

Je bedoeld hier elk getal voor de komma, "oneindig" lang, maar na de komma precies 2? 

Ja, dat is een omissie. Eens met voorstel *,2

**Comment by JanCampschroer** [comment]
Blijkbaar is er verschil in betekenis afhankelijk van wat voor datatype je hebt.  Mogelijk moet je (vergelijkbaar met de manier waarop het bij Patroon is gedaan) stellen dat:
- bij CharacterString de mogelijk patronen zijn:
>  ..M (maximaal M) , 
> N..M  (minimaal N maximaal M) , 
> N.. (minimaal N)

- bij Decimal de mogelijke patronen zijn:
> G,D (maximaal G cijfers voor de komma (de gehelen) en maximaal D na de komma (voor- en achterloopnullen mag)
> ..,D  (geen maximum voor de gehelen)

**Comment by wilkoquak** [comment]
Bij decimalen ben ik bij nader inzien niet blij met het modelleren van het aantal cijfers voor de komma: op die manier probeer je op een indirecte manier controle te krijgen over de maximum en mimimum waarde die je kunt uitwisselen. Daar zou eigenlijk een patroon Minumumwaarde en Maximumwaarde voor moeten komen.

**Comment by JanCampschroer** [comment]
Als we Lengte alleen toestaan bij String, dan is er geen ambivalentie.
Bij numerieke datatypen heb je optioneel een minimale (inclusief) en optioneel een maximale (inclusief) waarde. 
Bij het decimal datatype heb je aanvullend nog een precisie: het aantal cijfers achter de komma.

**Comment by wilkoquak** [comment]
Helemaal mee eens Jan. Ook in de xml-schema specificatie (https://www.w3.org/TR/xmlschema-2/ ) is length wel toegestaan voor het type string maar niet voor getallen.  Overigens stel ik voor om met de MIM specificatie zo dicht mogeijk bij de specificatie van facets in xml-schema. Ze hebben er daar ongetwijfeld goed over nagedacht en xml-schema is ook vaak de plek waar deze mim constructies worden gevalideerd.

**Comment by lennartvanbergen-kadaster** [comment]
Het staat in de toelichting, en dus leest Wilko, dat is niet normatief. Hij vraagt dus, leg het normatief vast.

**Comment by pmaria** [comment]
Is er in MIM ook **exact** beschreven wat je allemaal als waarde van het metagegeven `Lengte` kunt opnemen?

Er staat wel bij [de beschrijving van het metagegeven](https://docs.geostandaarden.nl/mim/mim/#metagegeven-lengte-domein-van-een-waarde-van-een-gegeven):

> Bijvoorbeeld: ‘1’ als de lengte exact 1 is; ‘1..2’ als de lengte 1 tot en met 2 lang kan zijn; '‘1,2’ voor Decimale getallen met 1 cijfer voor de komma en 2 erna. Dit is van -9,99 tot +9,99; Dit is nog verder toegelicht in hoofdstuk [Afspraken & Regels].

Echter, ik kan in het hoofdstuk [Afspraken & Regels](https://docs.geostandaarden.nl/mim/mim/#afspraken-regels) verder niks hierover vinden.

**Comment by lennartvanbergen-kadaster** [comment]
Lengte 1..2 betekent: minimaal 1 en maximaal 2, dit is inclusief.

**Comment by lennartvanbergen-kadaster** [comment]
https://github.com/Geonovum/MIM-Werkomgeving/pull/210

**Comment by lennartvanbergen-kadaster** [comment]
@wilkoquak zo? https://geonovum.github.io/MIM-Werkomgeving/

**Comment by architolk** [comment]
De huidige beschrijving leid tot een breaking change, omdat nu een lengte van "99" betekent dat de maximale lengte "99", zonder dat een minimum lengte is gedefinieerd. Met de verandering zou het betekenen dat de lengte EXACT "99" moet zijn, dus zowel minimum als maximum. Dit kan ook uitgedrukt worden met "99..99". Voorstel is dus om de betekenis van "99" te laten zijn: "Maximum lengte is 99, minimum is niet gedefinieerd".

**Comment by PalmJanssen** [comment]
> De huidige beschrijving leid tot een breaking change, omdat nu een lengte van "99" betekent dat de maximale lengte "99", zonder dat een minimum lengte is gedefinieerd. Met de verandering zou het betekenen dat de lengte EXACT "99" moet zijn, dus zowel minimum als maximum. Dit kan ook uitgedrukt worden met "99..99". Voorstel is dus om de betekenis van "99" te laten zijn: "Maximum lengte is 99, minimum is niet gedefinieerd".

Volgens mij betekent 99:  exact 99. Het is geen range.
1..99 is wel een range

**Comment by lennartvanbergen-kadaster** [comment]
Het gaat erom hoe lang een gegeven mag zijn. 

We hebben een aantal use cases, met en zonder range en met strings of getallen. 

**CharacterString** 
Opmerking: merk op dat de string 0001 bestaat. De lengte kan bij CharactersStrings vaststaan. 

Een attribuutsoort 'identificatieChar', een characterstring met precies lengte 16 
lengte 16
(je zou ook kunnen zeggen 16..16 maar een exact aantal aanduiden met een range lijkt mij niet de bedoeling) 

Een attribuutsoort 'naam', characterstring, met minimale lengte 2 en maximale lengte onbegrensd 
lengte: 2.. 

Een attribuutsoort 'naam', characterstring, met minimale lengte 2 en maximale lengte 200 
lengte 2..200 

**Getallen** 
Opmerking: merk op dat het getal 0001 niet bestaat, dit is gewoon het getal 1. De lengte kan je dus niet vastzetten met een range 1..4, dat is niet zinvol. 4 betekent bij getallen al 1..4. 

Een attribuutsoort 'pensioenleeftijd', integer met precies lengte 2
lengte 2 
+ een patroon, 2 geeft enkel de ruimte aan en bij getallen van 1 of 2 lang is dat altijd 2.  
(je zou ook kunnen zeggen 2..2 maar een exacte lengte aanduiden met een range lijkt mij niet de bedoeling) 

Een attribuutsoort 'geluidsniveau' (in decibel), integer, met minimale lengte 2 en maximale lengte 3
lengte 3 
+ een patroon, 3 geeft enkel de ruimte aan en bij getallen van 2 of 3 lang is dat altijd 3.  
(je zou ook kunnen zeggen 2..3 maar zie opmerking) 

Een attribuutsoort 'identificatieInt', een characterstring met precies lengte 16 
lengte 16
+ een patroon, 16 geeft enkel de ruimte aan, het getal 000000000000000001 bestaat niet. Als je wilt kunnen beginnen met 0 dan kies je CharacterString als basis, met precies lengte 16  
(je zou ook kunnen zeggen 16..16 maar een exact aantal aanduiden met een range lijkt mij niet de bedoeling) 

Een attribuutsoort 'percentage0', integer, tussen 0 en 100 
lengte 3 

Een attribuutsoort 'percentage2', decimaal, tussen 0 en 100 met altijd precies 2 cijfers achter de komma. 
lengte 3,2 
(je zou ook kunnen zeggen 1..3,2 maar zie opmerking over getallen) 

Een attribuutsoort 'percentage12', decimaal, tussen 0 en 100 met 1 of 2 cijfers achter de komma. 
lengte 3,2 
(je zou ook kunnen zeggen 1..3,1..2 maar zie opmerking) 

Floating numbers worden eigenlijk nooit gebruikt in modellen die wij maken, maar die zijn heel makkelijk; floating point met maximale lengte 32: lengte 32 (en kies het datatype wat bij Float past) 

Als je kijkt naar hoe dit bv. mapped op een XSD dan zie je: 

Voor string; 
length | Specifies the exact number of characters or list items allowed. Must be equal to or greater than zero
maxLength | Specifies the maximum number of characters or list items allowed. Must be equal to or greater than zero
minLength | Specifies the minimum number of characters or list items allowed. Must be equal to or greater than zero

lengte 16 --> length 16
lengte: 2.. --> minLength 2 
lengte 2..200 --> minLength 2 maxLength 200 

Voor getallen: 
fractionDigits | Specifies the maximum number of decimal places allowed. Must be equal to or greater than zero
totalDigits | Specifies the exact number of digits allowed. Must be greater than zero

Zonder decimalen: 
lengte 2 --> totalDigits 2
lengte 3 --> totalDigits 3 
lengte 16 --> totalDigits 16 
lengte 32 --> totalDigits 16 

merk op dat het om de lengte van een getal gaat, het is voor dit metagegeven niet erg dat je het minimum niet op kan geven. Dit doe je met een patroon of een minInclusief, je kan geen minLength of length opgeven voor getallen.  

Decimalen: 
lengte 3,2 --> lengte 3 --> totalDigits 5,  fractionDigits 2 

merk op: 3+2 = 5. Je kan ook kiezen voor het aantal getallen voor de komma niet op te geven, maar functioneel is dat wel gewenst om op te kunnen geven. In een XSD moet je daar dus iets extra's mee. 

merk op, je kan bij een getal niet aangeven: 1 of 2 achter de komma. Dat moet je met een patroon doen. 

Zoals je ziet heeft het bij getallen geen zin om 1..3,1..2 te specificeren. 

floating point met totale lengte 32 --> total digits 32

**Comment by architolk** [comment]
Ook al via de email rechtstreeks aan Lennart gestuurd, op een vraag van Lennart "waarom voorstel om bij lengte = '15' er voor te kiezen om dit te laten betekenen: _maximaal_ 15 in plaats van _precies_ 15, zie hieronder mijn antwoord:

De reden was de originele vertaling van mim:lengte naar sh:maxLength. Het uitgangspunt daarbij was dat mim:lengte eigenlijk betekende “de maximaal mogelijke lengte”, dus niet iets dat lijkt op een cardinaliteit.
Zie: https://docs.geostandaarden.nl/mim/mim/#transformatie-lengte
En zie vervolgens: https://www.w3.org/TR/shacl/#MaxLengthConstraintComponent
 
De reden om te denken dat “lengte” zoiets zou betekenen, was simpelweg omdat het nogal raar is om te praten over een minimale lengte bij “lengtes van velden”. Maar een maximale lengte is vaak wel heel relevant. Vooral bij string-velden, maar ook bij getallen kun je daar wat bij voorstellen.
 
Ook als je iets doet als “5,2” dan bedoel je eigenlijk: maximaal 5 getallen voor de komma’s – NA de komma bedoel je juist weer precies , maar da’s ook logisch – want het gaat dan om preciezie-achter-de-komma.
 
Met andere woorden: het gebruik van lengte als een maximum ligt meer voor de hand dan het gebruik van lengte als een minimum. Het gebruik van een notatiewijze binnen lengte, zoals bij kardinaliteit is eigenlijk heel ongebruikelijk.
 
Met andere woorden: mensen zullen kardinaliteit “1” lezen als “minimum 1, maximum 1”, terwijl mensen een “lengte” veld zullen lezen als “maximaal zoveel karakters”. Denk bv maar eens aan datamodellen waar wordt gesproken over VARCHAR(50). Dan wordt niet bedoeld precies lengte 50, maar juist maximaal 50. Of NUMBER(9), dan wordt bedoeld: een nummer van maximaal 9 cijfers, niet precies 9…
 
Daarom ook mijn voorstel: “1..1” is heel logisch, “5..” of “..99” is ook heel logisch – en als je dan toch iets wilt uitdrukken zonder gebruik van de “..” notatie, doe het dan zoals mensen verwachten bij dergelijke velden…
 
De nieuwe tekst in de transformatie is nu hier te lezen: https://geonovum.github.io/MIM-Werkomgeving/#transformatie-lengte
Deze tekst maakt het wel mogelijk om de wijziging doorgevoerd te krijgen (dus met mogelijkheid om ook minumum en maximum door te voeren), maar gaat uit van de suggestie die ik deed.

**Comment by lennartvanbergen-kadaster** [comment]
Voor getallen is het logisch en gebruikelijk inderdaad om alleen een maximaal aan te geven. 

Bij karakters komt het vaker voor dat er ook een minimum aan de orde is. Maar als we alleen een maximum specificeren voor karakters, dan zeggen we dus ook dat een minimum niet gespecificeerd kan worden. Terwijl dit ook best vaak nodig is. 

We kunnen dus 2 kanten op: alleen het maximum specificeren, of preciezer zijn door precies een lengte of ook een minimum specificeren. 

Op dit moment is de uitwerking in H2: maximum, precies en ook een minimum. 

Vanwege dat we precies ook aan willen geven bij karakters, en wat in bv. een XSD of JSON schema ook kan, is '16' al gereserveerd voor precies 16 en niet voor maximaal 16. 

Ik begrijp dat 16 maximaal 16 zou kunnen betekenen en 16..16 precies 16, maar voor mij voelt 16 beter als precies 16. Hoe oud ben je? 16. Ja ok, maar hoe oud ben je precies? Nou, 16..16. Ik volg hier liever de UML conventie: 16 betekent precies 16 en niet 1..16.

Goed, het is wellicht een kwestie van smaak. We moeten een knoop doorhakken.

**Comment by lennartvanbergen-kadaster** [comment]
Er staat nu in ieder geval in H2 

>   **Definitie Lengte**  
>   De aanduiding van de lengte van een gegeven, volgens de aangegeven notatiewijze.

De notatiewijze en de betekenis is als volgt: 

Voor karakters:  

| **Notatie** | **Betekenis**                                                                              |
|-------------|--------------------------------------------------------------------------------------------|
| 1           | De lengte is precies 1                                                                     |
| 2..         | De lengte is minimaal 1 (inclusief 1) of meer (onbegrensd)                                 |
| 1..9        | De lengte is minimaal 1 en maximaal 80 (inclusief 9)                                      |

Voor getallen:

| **Notatie** | **Betekenis**                                                                              |
|-------------|--------------------------------------------------------------------------------------------|
| 3           | De lengte is maximaal 3 (inclusief 3, dus 1, 2 of 3) voor de komma      |  
| 3,2         | De lengte is maximaal 3 (inclusief 3, dus 1, 2 of 3) voor de komma, en maximaal 2 getallen na de komma  |    

Andere getallen van 1 of 2 of 3 of 9 kunnen uiteraard gebruikt worden om er de lengte mee te specificeren. 

*Toelichting*

Het gaat bij deze lengte om hoe lang een gegevens in functionele zin mag zijn. Dus, hoeveel karakters en hoeveel getallen voor en na de komma.  

Bijvoorbeeld: 
* Een naam van een persoon met minimale lengte 2 en onbegrensd: CharacterString, lengte 2.. 
* Een naam van een openbare ruimte met minimale lengte 2 en maximale lengte 80: CharacterString, lengte 2..80 
* Een identificatie als getal, van maximaal lengte 16: Integer, lengte 16 
* Een identificatie van precies lengte 16, met voorloopnullen: CharacterString, lengte 16 
* Een percentage met 2 getallen achter de komma: Decimal, lengte 3,2 

Voorheen vaak gebruikt: 
* AN80 komt overeen met CharacterString, lengte 1..80  
* N8 komt met Integer, lengte 8 
* N3,2 komt overeen met Decimal, lengte 3,2

**Comment by architolk** [comment]
Ik zie inderdaad dat in een XSD de waarde xsd:length betekent "precies 15". In SHACL heb je zo'n element niet, maar alleen sh:minLength en sh:maxLength. Hoewel het een breaking-change betekent, is hier wel sprake van een bijzonder kleine breaking-change, namelijk alleen in de transformatie in 1 geval van dit specifieke veldje. Ik vind het op zich prima om het zo te maken als Lennart voorstelt, dan is het in ieder geval volledig identiek aan de kardinaliteit-notatie, dus introduceren we niets nieuws. Indien we hiervoor gaan, moet deze transformatie nog wel ietsje aangepast worden in de tabel:  https://geonovum.github.io/MIM-Werkomgeving/#transformatie-lengte
