### ISSUE TITLE
Metamodel - taxonomische structuur is onduideljk

### ISSUE THREAD

**Issue by mickbaggen** [Geonovum/MIM-Werkomgeving#154]
Uit de diagrammen, waarmee de structuur van het MIM metamodel wordt weergegeven, is niet duidelijk hoe de taxonomie van de MIM metaclasses is opgebouwd. Er zijn slechts een paar generalisatie relaties te zien:  Relatiesoort-Relatieklasse, Relatierol-Relatierol doel, Datatype met 5 subtypen. Zijn dit de enige relaties, of zijn er meer?

**Comment by lennartvanbergen-kadaster** [comment]
Volgens mij staat ze er allemaal wel in (mogelijk 1 gemist, zal het dubbelchecken). Welke had je eventueel nog meer verwacht (als taxonomie tussen de modelelementen)?

**Comment by mickbaggen** [comment]
In analogie met het metamodel van UML, RDFS/OWL, NEN 2660-1 en andere metamodellen zou ik verwachten dat alle metaclasses in een taxonomie zijn opgenomen met een gemeenschappelijk RootElement. Hier wordt dan bv onderscheid gemaakt tussen class-achtige dingen (Objecttype, Datatype etc), relaties, packages etc. Ik zie dat hier niet terug.

PS het gebruik van deze structuur is geen verplichting, maar helpt wel om de opbouw van het metamodel beter te begrijpen.

**Comment by PalmJanssen** [comment]
In de koppeling en uitdrukking van MIM in UML in hoofdstuk 3 doen we dat wel. We koppelen daar aan de UML metaklassen, die hun eigen taxonomie hebben. https://docs.geostandaarden.nl/mim/def-st-mim-20201023/#kern-0. We hebben daar dan wel een taalbinding. In het algemene deel van hoofdstuk 2 hebben we dat niet gedaan. Het klopt dat je daar dan geen root elementen in hebt.

**Comment by lennartvanbergen-kadaster** [comment]
Ik vind het wel een goed idee van Mick, en idd terecht punt als iemand een volledig eigen metaklasse zou willen toevoegen, al zou je als norm denk ik daar dan wel bij betrokken willen worden, want dat is dan natuurlijk wel erg interessant.
