### ISSUE TITLE
Metamodel - oplijning metaclasses in tabellen en diagrammen

### ISSUE THREAD

**Issue by mickbaggen** [Geonovum/MIM-Werkomgeving#156]
In Par. 2.1 en de documentatie in 2.2 t/m 2.7 is de oplijning tussen metaclasses in tabellen, diagrammen en tekst niet compleet. Voorbeelden:

Datatype: wel in View 1 of 2 Diagram, niet in View 1 of 2 Tabel
Relatierol (abstract) in View 3b: is al genoemd in Tabel 1, niet duidelijk of dit dezelfde metaclass is.
Relatierol (keuze), relatierol doel (keuze) in View 3a, use case 4: niet duidelijk of dit separate metaclasses zijn.
De drie metaclasses generalisatie, externe koppeling en relatiesoort uit View 1 zijn waarschijnlijk subtypen (of instanties) van Relatie (par. 2.3). Waar is de documentatie van MIM Relatie te vinden?
Waar is de documentatie van MIM Waardelijst (par. 2.4) te vinden?
De vier metaclasses uit view 3d zijn waarschijnlijk subtypen (of instanties?) van Package (par 2.6). Waar is de documentatie van MIM Package te vinden?

PS JE kunt niet terugvallen op UML om b.v. MIM Relatie of MIM Package te gebruiken, want UML "bestaat niet": MIM is nadrukkelijk bedoeld als 1een stand alone metamodel.

**Comment by ThiesMesdag** [comment]
Ik heb het idee dat deze issues in de huidige conceptversie 1.2 niet meer op dezelfde manier spelen. De lijstjes en de diagrammen zijn volgens mij in sync. Door de link naar de definitie in de lijstjes kan je zien dat het om dezelfde begrippen gaat en wat de definities zijn. Het enige punt wat niet opgelost is, is de generalisatie, die is niet uitgewerkt als een relatie in een van de diagrammen.

**Comment by mickbaggen** [comment]
Volgens mij is het issue nog niet geheel opgelost: de MIM Metaclasses Package en Modelelement uit figuur 10 worden nergens in Paragraaf 2.2 (Structuur metamodel) expliciet besproken.

**Comment by Gtrouborst** [comment]
@mickbaggen Dankjewel, dat klopt inderdaad! Ik heropen het issue. 

Ook al zijn `«Package»` en `«Modelelement»` abstracte klassen in het metamodel en dus niet voor gebruikers van MIM toepasbaar, ben ik het met je eens dat je dit wel moet noemen: beide begrippen komen veelvuldig voor in de documentatie.

- Iets over `«Modelelement»` zou meteen in één van de eerste alinea's van par 2.2 kunnen.
- Iets over `«Package»` in 2.2.3.

In beide gevallen zou ik ze niet in de bijbehorende lijstjes van die paragraaf opnemen, zodat je voor een gebruiker duidelijk onderscheid maakt tussen de concrete modelelementen die je kunt toepassen als je volgens MIM modelleert en de abstracte klassen die in het metamodel nodig zijn.

> **Note**
> **Suggestie**: [`«Package»`](https://geonovum.github.io/MIM-Werkomgeving/#package ) wordt in 2.3.5 gedefinieerd. Misschien is het geen gek idee om aan het begin van 2.3 ook `«Modelelement»` de definiëren?

**Comment by mickbaggen** [comment]
@Gtrouborst, merk op dat de MIM MetaClasses Datatype en Relatierol ook abstract zijn, maar toch in de lijsten in Paragraaf 2.2 zijn opgenomen. Het lijkt me zinvol om dit op een uniforme wijze te hanteren.

PS Merk op dat in de figuren van Paragraaf 2 het aanduiden van abstracte MetaClasses ook niet eenduidig plaatsvindt. Soms is het cursief, soms niet. Het lijkt me zinvol om dit ook op een uniforme wijze te hanteren.

**Comment by Gtrouborst** [comment]
Dank @mickbaggen: @PalmJanssen pakt dit op (of heeft het inmiddels al verwerkt).

**Comment by PalmJanssen** [comment]
verwerkt in pull request: #356
