### ISSUE TITLE
Metamodel - relatie-instanties tussen metaclasses niet beschreven

### ISSUE THREAD

**Issue by mickbaggen** [Geonovum/MIM-Werkomgeving#157]
In hst 2 worden de relaties (met hun cardinaliteiten) tussen de diverse metaclasses wel getoond in de diverse diagrammen. maar worden verder niet expliciet beschreven of gerefereerd vanuit de tekst. Voorbeeld:

Relatie Objecttype (bron) [1] - bezit - Relatiesoort [0..*]
Relatie Relatiesoort [0..*] - verwijst naar - (doel) Objecttype [0..1]

**Comment by lennartvanbergen-kadaster** [comment]
hallo Mick, ik neem aan dat je bedoeld zoals onderstaande tekst (uit MIM), maar dan voor alle model-elementen uit het diagram? 

> De verbindingen tussen de modelelementen geven aan welke combinaties kunnen voorkomen op metamodelniveau, oftewel welke modelelementen in een informatiemodel met elkaar gecombineerd kunnen worden. Bijvoorbeeld:
> 
> Een objecttype kan verbonden worden met een attribuutsoort. In een informatiemodel kan je attribuutsoorten dus aan een objecttype toekennen. Een attribuutsoort kan in het informatiemodel vervolgens weer als type een datatype krijgen.
> Een objecttype kan verbonden worden met een relatiesoort en deze relatiesoort kan weer verbonden worden met een objecttype. Dit geeft aan dat de relatiesoort een modelelement is dat twee objecttypen met elkaar verbindt. Een objecttype kan dus niet rechtstreeks verbonden worden met een ander objecttype.
> Een objecttype kan verbonden worden met een gegevensgroep en deze gegevensgroep kan weer verbonden worden met een gegevensgroeptype. Een objecttype kan dus niet rechtstreeks verbonden worden met een gegevensgroeptype. In een informatiemodel is een gegevensgroep een eigenschap van het objecttype en kan je aangeven dat deze gegevensgroep als type een gegevensgroeptype heeft.
>

**Comment by mickbaggen** [comment]
Klopt!

**Comment by lennartvanbergen-kadaster** [comment]
Ok, dat valt onder documentatie. Zeker bij generalisatie kan dat helpen, die vind ik zelf ook moeilijk te volgen in diagram vorm. Vermoed dat deze in de volgende documentatieslag mee komt.
