### ISSUE TITLE
Generalisatie in 2.1.1 - multiple inheritance mag (wel) 

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#160]
https://docs.geostandaarden.nl/mim/def-st-mim-20201023/#kern

Generalisatie: multiple inheritance mag toch? 1 objecttype mag meer dan 1 Generalisaties hebben. De supertype rol tussen Objecttype en Generalisatie moet dan toch 0..* zijn? 

En wat is de naam van deze relatie van objecttype naar generalisatie? Is dit: bezit? 

En wat is de naam van deze relatie van generalisatie naar objecttype? Is dit: verwijst naar? 

Of, meer default, "specialisaties en/of generalisaties / heeft als generalisatie(s)"?

**Comment by mickbaggen** [comment]
Multiple inheritance is in UML en OWL toegestaan. In het NEN 2660-1 metamodel wordt dit echter niet ondersteund (alleen single inheritance). In plaats daarvan kunnen concepten rollen spelen in relaties. Voorbeeld: "een persoon IS een subtype van organisme, en SPEELT de rol van vriend/echtgenoot/medewerker in de relaties vriendschap/huwelijk/arbeidsrelatie." Ofwel: een persoon IS dus geen subtype van vriend/echtgenoot/medewerker.

**Comment by lennartvanbergen-kadaster** [comment]
Aanvulling: 
In het metamodel zit nu een Generalisatie. Deze staat op zichzelf. Deze kent zijn subtype en kent zijn supertype. 

Echter, in het metamodel in UML H2.1 is gemodelleerd: objecttype heeft een relatie naar generalisatie, en generalisatie heeft geen relatie naar objecttype. Dus, generalisatie kent alleen een uitgaande relatie.  

Wat is de bedoeling? Moeten we Generalisatie eigenlijk modelleren als relatieklasse, of eigenlijk met ook een relatie van Generalisatie naar Objecttype die het subtype is?

**Comment by PalmJanssen** [comment]
Het staat er nu in mim 1.1 zo in:
![image](https://user-images.githubusercontent.com/9932784/137112692-68610f7c-5bf9-4bb5-b85a-1046eaab8e43.png)

Dit geeft inderdaad niet aan dat een objecttype een supertype kan zijn van een subtype. In feite is dat de inverse relatie van subtype->supertype. Maar we doen niet aan inverse relaties. Daarom deze supertype->subtype relatie ook expliciet opgenomen. Dat levert dit op:
![image](https://user-images.githubusercontent.com/9932784/137114944-72f0f98e-3e5c-466b-ba8e-d814b79e00c3.png)
Hier staat nu dat:
1: een objecttype als subtype kan verwijzen naar 0..* generieke supertypes
2: een objecttype als supertype kan verwijzen naar 0..* specifiekere subtypes

Opmerking 1: Nu zit er ook meervoudige overerving in.
Opmerking 2: Dat zou dan ook voor Datatype moeten gelden. En waarom eigenlijk niet voor gegevensgroep? (maak ik nieuwe issue van).

**Comment by PalmJanssen** [comment]
Ook interessant om te zien hoe UML de metaklasse Generalization definieert:

In feite hetzelfde, behalve dat er een metaklasse "Classifier" tussen Class en Generalization zit.
![image](https://user-images.githubusercontent.com/9932784/137117081-ce5943aa-6284-40fa-8f35-f41ec0b4b953.png)

**Comment by PalmJanssen** [comment]
proces info:
- verwerkt in UML diagrammen.
- - tekst toegevoegd in hfst 2
