### ISSUE TITLE
Waardenbereik van indicatie Abstract: ja of nee (een boolean)

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#161]
In H2 staat: https://docs.geostandaarden.nl/mim/def-st-mim-20201023/#metagegeven-indicatie-abstract-object

Enumeratiewaarde. Maar er staat niet aangegeven welke enumeraties mogelijk zijn. 

Het lijkt logisch om hier te kiezen tussen primitief datatype boolean of Waardenbereik Ja, Nee, zoals opgenomen in https://docs.geostandaarden.nl/mim/def-st-mim-20201023/#toegestane-waarden-voor-bepaalde-metadata-gegevens

Het is niet zozeer een echte value, het is meer een modelmatige constructie, omdat elke modelleertaal hier een constructie voor heeft. Gezien dit niet nillable kan zijn en OF, OF is, en bij de linked data uitwerking ook gekozen is voor boolean, neig ik ernaar om dat al op H2 niveau aan te geven als boolean.

**Comment by lennartvanbergen-kadaster** [comment]
Duiding: waardebereik is niet aangegeven, en er staat iets bij toepassing op model-elementen wat niet klopt. 

Voorstel: tekst verbeteren in H2, te weten 2.8.2.27 en in 2.9. - voor modelelementen die van het type objecttype zijn. Zie onderstaande tekstvoorstel. 

WAS
2.8.2.27 Metagegeven: indicatie abstract object
Definitie Indicatie abstract object
Indicatie dat het objecttype een generalisatie is, waarvan een object als specialisatie altijd voorkomt in de hoedanigheid van een (en slechts één) van de specialisaties van het betreffende objecttype.

Toelichting

Een abstract objecttype moet altijd de generalisatie zijn van één of meerdere specialisaties. Bijvoorbeeld het abstract objecttype "Voertuig", met concrete specialisaties "Auto", "Fiets" en "Bromfiets".

Zie ook sectie Abstracte objecttypes en concrete objecten waar een nadere uitleg wordt gegeven van het fenomeen abstract objecttypen.

Toepassing: enumeratiewaarde **<-- dit is fout** 

--
Voorstel:

WORDT
Toepassing: objecttype

(alleen deze laatste zin is anders) 

--


2.9 Toegestane waarden voor (bepaalde) metadata gegevens

Toevoegen aan tabel: 

indicatie abstract object            Ja, Nee

**Comment by PalmJanssen** [comment]
opmerking: onder een abstract objecttype mogen toch ook nog 1 of meerdere abstracte objecttypes voorkomen?

Ik zou de definitie simpeler houden en alleen betrekking laten hebben op het objecttype zelf: Indien abstract dan is het objecttype niet instantieerbaar. 

Opmerking: Dat is het enige wat het objecttype weet. Wat er als mogelijke specialisaties gebeurt daar weet het objecttype niets van.

**Comment by lennartvanbergen-kadaster** [comment]
Eens, prima, al was dat niet waar dit issue over ging (zie voorstel), maar wel eens met je voorstel om ook de tekst te verbeteren.

**Comment by PalmJanssen** [comment]
@lennartvanbergen-kadaster  deze is nog niet verwerkt.

**Comment by lennartvanbergen-kadaster** [comment]
Verwerken in H2 en H3, in H2 een metagegeven, in H3 verwijzen naar zie metagegeven. Eerst: tekst verbeteren, zodat de definitie is: een object wat je niet kan instantieren, maar wel een generalisatie is van een specialisatie. De specialisatie hoeft zich niet in het informatiemodel zelf te bevinden.

**Comment by architolk** [comment]
Ten behoeve van de LD verwerking: ik ga er vanuit dat het een boolean blijft? "indicaties" zijn over het algemeen zo bedoeld. Zie ook de andere boolean velden die we al hebben. (NB: in EA en bijna alle UI tools wordt een boolean gerepresenteerd met een checkbox. Daarmee wordt (bijna) altijd verondersteld dat de checkbox altijd is voor-ingevuld met de default waarde "false", en een check in de checkbox betekent de defaultwaarde "true". Indien het veld echter optioneel moet zijn, en er onderscheid gemaakt moet worden tussen "niet ingevuld", "true" en "false", dan is mogelijk het gebruik van een enumeratie handiger, omdat het veld dan leeggelaten kan worden (en ook weer leeggehaald kan worden). In de use interface wordt het dan echter geen checkbox meer, maar een drop-down-list.

**Comment by lennartvanbergen-kadaster** [comment]
@architolk ja. 

Het gaat er meer om dat de definitie voor sommige mensen niet helder is (en daar kan ik inkomen) en dat de doelgroep het beter kan volgen  als we het hebben over objecten als instanties van objecttypen.

**Comment by lennartvanbergen-kadaster** [comment]
Was: 
Definitie Indicatie abstract object
Indicatie dat het objecttype een generalisatie is, waarvan een object als specialisatie altijd voorkomt in de hoedanigheid van een (en slechts één) van de specialisaties van het betreffende objecttype.

Is geworden 

>   **Definitie Indicatie abstract object**  
>   Een indicatie die aangeeft of er objecten _kunnen_ bestaan die getypeerd worden als zijnde objecten (instanties) van alleen dit objecttype. Een abstract objecttype moet altijd de generalisatie zijn van één of meerdere objecttypes die niet abstract zijn. 

N.B. Eén informatiemodel kan een abstract objecttype bevatten die _binnen dit informatiemodel_ een generalisatie is van geen enkel objecttype. Deze niet abstracte objecttypen kunnen zich immers ook buiten het informatiemodel bevinden en aldaar worden gespecificeerd. Dit komt voor bij informatiemodellen die een abstracte typering definieren waarop (concretere) informatiemodellen willen aansluiten en nadere invulling aan geven.  

*Toelichting*

Niet abstract wordt ook vaak wel genoemd: concreet. 

Bijvoorbeeld het abstract objecttype "Voertuig", met concrete specialisaties "Auto", "Fiets" en "Bromfiets". Dit betekent dat er geen voertuigen mogen bestaan die alleen maar een voertuig zijn en waarbij in het midden gelaten mag worden of het een Auto, Fiets, Bromfiets betreft. Als het "Voertuig" daarentegen niet als abstract is gemodelleerd, dan mogen er wel voertuigen bestaan die alleen maar een voertuig zijn en niet een Auto, Fiets of Bromfiets. In beide gevallen kan er over de objecten gesproken worden als zijnde een voertuig en kunnen deze objecten in algemene zin als zodanig behandeld worden (zoals een generalisatie bedoeld is). 

Wanneer een objecttype niet abstract is, oftewel concreet, dan kunnen er objecten bestaan die een instantie van objecttype zijn. 

Wanneer een objecttype wel abstract is, dan kunnen er geen objecten bestaan die een instantie van dit objecttype zijn. Er moet dan altijd sprake zijn van een concreet (niet abstract) objecttype die het abstracte objecttype als generalisatie heeft. Objecten zijn dan instanties van dit concrete objecttype en geen instanties van het abstracte objecttype. Wel voldoen deze objecten beide objecttype definities en kunnen deze objecten in algemene zin als zodanig behandeld worden.
