### ISSUE TITLE
Kleine naam issues in de verbindingen tussen modelelementen vanuit hetzelfde modelelement

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#164]
_Vanuit machine-leesbaar maken metamodel 2.1_ 

Er zitten soms wat verschillen tussen namen in diagrammen en in metadata velden in de documentatie. Even nalopen. 
* informatiemodel type (spatie mist in metamodel?)

metamodel: 
bevat komt vaker voor, uitgaande relatienaam is niet uniek. Kan dit worden: bevat attribuutsoorten, bevat relatiesoorten enz? 

Er zitten soms wat namen die niet uniek zijn in het metamodel, zoals 'bezit'. Soms heeft een naam 'gebruikt', soms 'bezit', soms 'heeft', wat is de conventie?

Mogen de metamodel namen uniek zijn binnen de context van 1 modelelement, bv. bezit attribuutsoorten en bezit relatiesoorten hebben als source objecttype, in bv. een XSD geeft dit issues, 2x bezit mag niet. Niet dat XSD leidend is, maar als dit kan is het wel fijn.  

Objecttype _gebruikt_ attribuutsoorten komt niet heel intuitief over als de fijnst passende naam.

**Comment by lennartvanbergen-kadaster** [comment]
Voorstel: nalopen en rechttrekken.

**Comment by PalmJanssen** [comment]
Voorstel:
Kijk eens naar dit MIM - UML.

- Ik heb alle uitgaande relatienamen binnen de context van een klasse uniek benoemd.
- Ik heb alle voor relatienamen het  zelfde patroon gebruikt: een combinatie van een werkwoord en de naam van de doelklasse (of rol daarvan)
- dit werkt goed voor de MIM serialisatie indien de relatienamen wordt gebruikt.
Bijvoorbeeld een Objecttype krijgt dan in de serialisatie de volgende properties:
- heeft attribuut
- heeft gegevensgroep
- heeft relatiesoort
- heeft externe koppeling
- verwijst naar supertype

![image](https://user-images.githubusercontent.com/9932784/147120369-600a49c6-f271-4fb3-b98c-3014b6efef8c.png)

**Comment by lennartvanbergen-kadaster** [comment]
ok

**Comment by kad-mesdat** [comment]
Ja ok

**Comment by architolk** [comment]
De verwerking in H4 loopt tegen een uitdaging aan: het lijkt erop dat er een issue gaat ontstaan in de alignment tussen H2, H3 en H4: de vraag is of de (meta)relatiesoortnamen overgenomen moeten worden, of de (meta)relatierolnamen aan de doel-kant. Dit laatste is tot op heden gebeurd en ook in lijn met hoofdstuk 6, maar lijkt nu in H2 anders te worden? (Actie: overleg tussen @PalmJanssen en @lennartvanbergen-kadaster en mijzelf)

**Comment by architolk** [comment]
Opgelost voor nu door zowel de bindingsnaam als de naam van het metagegeven zelf op te nemen, vervolgdiscussie in nieuw item over herziening/formalisatie taalongebonden metamodel van MIM.

**Comment by lennartvanbergen-kadaster** [comment]
Akkoord met de oplossing voor nu (vanwege planning en vanwege anders te veel impact op LD deel). 

Voor het vervolg; 

Persoonlijk vind ik: 
`objecttype` `attribuutsoort` niet fijn lezen. 
(`<modelelement>` `rol naam`) 

'objecttype' 'heeft attribuutsoort' leest prettiger. 

Als er een zin van gemaakt wordt, met alleen modelelement en relatie rol dan wordt het: 
objecttype attribuutsoort attribuutsoort 
(`<modelelement>` `rol naam` `doel modelelement`)

De rol van een attribuutsoort is dat deze in de relatie tussen objecttype en attribuutsoort de rol attribuutsoort heeft. Dit komt bij mij niet over als informatief. 

In UML heet deze bv. owned attribute, waardoor duidelijk is dat de het objecttype/UML-class de owner is van het attribuut. `heeft attribuut` is hier een prima vertaling van in mijn optiek. 

Nou is overal heeft of has toevoegen in de IT erg ongebruikelijk, JSON schema gebruikt ook gewoon properties: en niet has properties: 

Wat ik me vooral afvraag is OF we op metamodel niveau zowel rolnamen als relatienamen nodig hebben. 

We hebben het nu omzeild door beide vormen op te schrijven maar dat standaardiseert natuurlijk niet lekker. Ik wil hier zeker z.s.m. in 1.1.2. mee aan de gang, zodat er zo min mogelijk impact is op mensen die aan de slag gaan met implementaties waarbij deze naamgeving van belang is. 

Gelukkig is dit op veel plekken niet aan de orde, maar bv. bij het mim;vocabulaire wel en bij het mim-export formaat.

**Comment by lennartvanbergen-kadaster** [comment]
Nog even waar het om ging in dit issue: dat is dat de namen van verbindingen van modelelement A naar andere modelelementen  waar A mee verbonden mag worden uniek zijn. Dat is zo in deze oplossing. Dus dit item kan naar done en dan kunnen we het verwerken.

**Comment by lennartvanbergen-kadaster** [comment]
Ik heb dit er ook maar bijgezet in H3: 

>   **Naam en Alias**

In hoofdstuk 2 wordt de naam van een modelelement en de alias van deze naam beschreven. 
Hier wordt beschreven dat de naam van een modelelement meerdere schrijfwijzes kan hebben, te weten:
* een 'normale schrijfwijze' in natuurlijke taal, zoals Onroerende zaak 
* een 'technischere schrijfwijze' in bijvoorbeeld camel case, zoals OnroerendeZaak 

In een UML diagram heeft een modelelement ook altijd een naam, te weten een _name_ omdat het een UML-named element is. 

Een modelleur kan er voor kiezen om de 'normale schrijfwijze' van de naam van het modelelement in UML op te nemen: 

* in de `name` van een named element, bv.de name van een UML-Class, of 
* in de tagged value `alias` 
 
Deze `alias` wordt alleen gebruikt wanneer de modelleur ervoor heeft gekozen om de 'technischere schrijfwijze' in de _name_ op te nemen.
De 'natuurlijke schrijfwijze' kan dan geborgd worden in de `alias`. 

In principe zijn beide uitwisselbaar, het gaat immers om hetzelfde modelelement en de naam is hetzelfde, alleen de schrijfwijze is anders.

Het is aan de informatiemodel beheerder om te kiezen wanneer welke schrijfwijze wordt gebruikt. Bijvoorbeeld voor documentatie doeleinden t.b.v. gewone gebruikers wordt de normale schrijfwijze gebruikt en voor uitwerkingen op MIM niveau 3 en 4 de technischere schrijfwijze. Het is ook prima om beide op niveau 3 en 4 een plek te geven zodat beide gebruikt kunnen worden naar gelang.
