### ISSUE TITLE
Wat mag er in een package zitten specificeren

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#165]
_Vanuit machine-leesbaar maken metamodel 2.1_

Sommige mim-elementen zitten niet in een package, zoals attribuutsoort. Want die zit in objecttype. Maar objecttype kan wel weer in package zitten, net als datatype, gegevensgroeptype, keuze. Hier lijkt geen specificatie van te zijn. 

Er is geen diagram waar dit in staat. Er is geen tekst waar dit in staat. Beide zijn nodig.

**Comment by lennartvanbergen-kadaster** [comment]
Het zijn: 
* Objecttype 
* Gegevensgroeptype 
* Datatype (alle varianten) 
* Relatieklasse
* Keuze

**Comment by lvdbrink** [comment]
Hmm, ja, goede vraag. Wat is in OWL/SHACL het equivalent van een package. Volgens mij is dat er niet echt. In [MIM 6.4 Transformatie MIM - RDFS/OWL/SHACL](https://docs.geostandaarden.nl/mim/mim/#transformatie-mim-rdfs-owl-shacl) staat in de mapping bij Package 'n.v.t.'. De verdeling van modelelementen over packages heeft wel gevolgen voor de namespaces in je ontologie.

Maar, in een ontologie staan attribuutsoorten en relatiesoorten wel in een namespace.

**Comment by lennartvanbergen-kadaster** [comment]
Ok, beginnen we eens met 

Ik denk eerlijk gezegd dat dingen zoals URI domein en/of namespace beter op objectniveau gespecificeerd kan worden dan op package niveau (dat lijkt me niet lekker passen als ik naar onze packages kijk). 

Dan zijn we er voor nu wel uit.

**Comment by lennartvanbergen-kadaster** [comment]
Voorstel zoals eerder aangegeven is akkoord.

**Comment by PalmJanssen** [comment]
procesinfo:
- verwerkt in hfst 2.6

**Comment by architolk** [comment]
Het is incorrect om te veronderstellen dat in LD er geen transformatie is beschreven voor packages. Het klopt dat mim:Package niet wordt getransformeerd, maar dat kan ook niet, want het is een abstracte klasse: mim:Package zelf wordt dus niet getransformeerd, maar de daadwerkelijke concrete klassen. Dat zijn mim:Domein, mim:View en mim:Extern. Alleen voor mim:Informatiemodel is er geen transformatie beschreven. Ik vermoed omdat dit feitelijk altijd de "root" is in een UML model, maar feitelijk zelf geen inhoud heeft. Dat stelt Lennart hierboven ook. Voor LD was er tot op heden echter nog geen binding gemaakt tussen de owl:Ontology en de modelelementen, simpelweg omdat MIM dat nog niet voorschreef. Aangezien dit nu wel is gedaan, kan dat ook worden toegevoegd in de transformatie. rdfs:isDefinedBy lijkt daarbij de meest voor de hand liggende. Voorlopig kan dan in de transformatie ook als regel opgenomen worden dat voor rdfs:isDefinedBy daarbij voor een attribuutsoort in de transformatie de waarde uit het bijbehorende Objecttype of Gegevensgroeptype overgenomen wordt.

**Comment by architolk** [comment]
@PalmJanssen : in H2 wordt beschreven welke Modelelementen er in een specifieke subklasse van Package mogen voorkomen. Echter, in H3 komt dit niet meer terug: in het plaatje van Package wordt bv geen relatie "opgenomen in" gelegd tussen een package en de modelelementen die in een package zitten. ook is in H3 geen binding beschreven in de tabel van package of de subklassen van package.

**Comment by pmaria** [comment]
> Alleen voor mim:Informatiemodel is er geen transformatie beschreven. Ik vermoed omdat dit feitelijk altijd de "root" is in een UML model, maar feitelijk zelf geen inhoud heeft. Dat stelt Lennart hierboven ook. 

Hmm er stond(?) nergens in MIM dat je geen modelelementen direct onder Informatiemodel zou kunnen plaatsen.

Nu nog staat er bijv. bij de beschrijving van domein:

> Een informatiemodel **kan** onderverdeeld worden in meerdere packages, waarbij aangegeven wordt dat deze de modellering van de informatie van het domein bevatten.

Blijkbaar is er nu een (breaking?) change doorgevoerd dat dit niet meer kan. Hoewel de beschrijving dit niet strict uitsluit:

> In een informatiemodel package mogen alleen domein of view packages opgenomen worden. Beide kunnen meertallig voorkomen en de volgorde is hierbij niet van belang. Een extern package bevindt zich buiten het package informatiemodel.

Over:
> @PalmJanssen : in H2 wordt beschreven welke Modelelementen er in een specifieke subklasse van Package mogen voorkomen. Echter, in H3 komt dit niet meer terug: in het plaatje van Package wordt bv geen relatie "opgenomen in" gelegd tussen een package en de modelelementen die in een package zitten. ook is in H3 geen binding beschreven in de tabel van package of de subklassen van package.

Eens dit moet wel goed beschreven worden. Ivm impact op LD transformatie. Daarnaast zou de huidige transformatie van packages naar ontologieën ook eens onder de loep genomen moeten worden. Ik weet niet of dit voor alle package types even logisch is.
