### ISSUE TITLE
Welke metagegevens zijn verplicht en welke optioneel (2.8) en is er sprake van defaults bij verplichte?

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#166]
Bv. Kardinaliteit - staat niet bij dat het verplicht is. Alsmede, er staat ook niet wat de default is. Even alles nalopen. Staat wel in H3, maar hoort ook in 2.

**Comment by PalmJanssen** [comment]
Ik zie dat het al als tekst is opgenomen:

Een objecttype **gebruikt** attributen voor het specificeren van eigenschappen.

Een attribuut met het stereotype gegevensgroep **heeft** als waardetype een gegevensgroeptype

Een gestructutreerd datatype **bevat** meerdere data elementen.

Misschien door vet lettertype accentueren?

**Comment by PalmJanssen** [comment]
Dit moet nog even wachten op de nieuwe namen voor relaties in het MIM - UML zie #164.

**Comment by PalmJanssen** [comment]
Nog niet verwerkt. Is denk ik ook niet nodig.
> [ opmerking van Lennart aan @PalmJanssen voor diagram: de volgende zijn denk ik onterecht optioneel:
> identificerend (bij attribuutsoort), identificerend (bij relatiesoort) en aggregatietype 'none' (is engels nodig)? Maak jij deze nog verplicht in je diagram?

**Comment by architolk** [comment]
@lennartvanbergen-kadaster : in de tekst van sectie 2.9 staat nu "Type aggregatie", dit hoort "Aggregatietype" te zijn

**Comment by architolk** [comment]
@lennartvanbergen-kadaster, @PalmJanssen : zouden de volgende metagegevens ook nog een default waarde nodig hebben (ook verplicht metagegevens):
- Indicatie abstract (default: "nee"?)
- Authentiek (default: "overige authenticiteit"? - wellicht nog beter: niet verplicht maken?)
- Mogelijk geen waarde (default: "nee"?)
- Unidirectioneel (default: "ja"?)

**Comment by lennartvanbergen-kadaster** [comment]
Indicatie abstract (default: "nee"?) OK 
Authentiek (default: "overige authenticiteit"? - wellicht nog beter: niet verplicht maken?) --> zie issue #235 
Mogelijk geen waarde (default: "nee"?) OK 
Unidirectioneel (default: "ja"?) OK
