### ISSUE TITLE
Vertaling naar  engels opnemen in een bijlage

### ISSUE THREAD

**Issue by ArjanLoeffen** [Geonovum/MIM-Werkomgeving#17]
Een model kan conform MIM ook worden uitgedrukt in engelse namen voor de opgegeven stereotypen en tagged values. Deze vertaling moet worden geaccordeerd door de commissie, en bijgevoegd als normatieve bijlage. 

Ik stel ook voor de namen voor constructies in de nederlandse variant dan ook nederlands te maken. Dus bij niet "union" maar "keuze" e.d.

**Comment by dkrijtenburg-GNM** [comment]
oorspronkelijke indiener is Linda van den Brink

**Comment by dkrijtenburg-GNM** [comment]
voorstel voor tekst (overgenomen van BRO) 

MIM is een specificatie die is ontstaan vanuit de behoeften van enkele basisregistraties en afnemers daarvan. Daarbij is de aansluiting bij internationale (geo)normen gewaarborgd. Echter de preciese aansluiting bij die normen is niet altijd expliciet gemaakt in MIM. 
Met name de relatie met de modelleertechnieken van de ISO 19100 serie is van belang. Deze ISO standaarden vormen de ondergrond voor o.a. Inspire en NEN3610. 
In het volgende overzicht geldt het volgende
Kolom Aard waarden:
•	ST Stereotype
•	TV Tagged value naam
•	VAL tagged value waarde
Kolom MIM benaming ISO waarden:
•	Als schuin gedrukt, dan is de naam overgenomen voor dezelfde constructie uit het General Feature Model [ISO 19109].
Kolom Reden waarden:
•	Vertaling = Hetzelfde ding, vertaald in het Engels. De aansluiting bij ISO 19100 serie wordt daarbij expliciet gezocht.
•	Precisering = De naam maakt de aard van het stereotype preciezer.



Aard | [MIM 1.1] | MIM benaming  ISO | Reden
-- | -- | -- | --
ST | Objecttype | FeatureType   [ISO 19109] GF_FeatureType | Vertaling
ST | Attribuutsoort | AttributeType   [ISO 19109] GF_AttributeType | Vertaling
ST | Gegevensgroeptype | AttributeGroupType | Vertaling en   precisering
ST | Gegevensgroep | AttributeGroup | Vertaling en   precisering
ST | Relatiesoort | AssociationType   [ISO 19109] GF_AssociationType | Vertaling
ST | Relatieklasse | AssociationClass | Vertaling
ST | Externe koppeling | ExternalLink | Vertaling
ST | Relatierol | AssociationRole   [ISO 19109] GF_AssociationRole | Vertaling
ST | Referentielijst | ReferenceList | Vertaling
ST | Referentie element | ReferenceElement | Vertaling
ST | Enumeratie | Enumeration | Vertaling
ST | Enumeratiewaarde | Enum | Vertaling
ST | CodeList | CodeList [ISO 19103] | -
ST | Datatype | SimpleType | Vertaling en   precisering
ST | Complex datatype | ComplexType | Vertaling
ST | Data element | DataElement | Vertaling
ST | Union | Union   Defines a union data   type. | -
ST | Union element | UnionElement | Vertaling
ST | Extern | External | Vertaling
ST | View | View | Vertaling
TV | Beheerder | Administrator | Vertaling
TV | Data locatie | Data location | Vertaling
TV | Datum opname | Date recorded | Vertaling
TV | Eigenaar | Owned by | Vertaling
TV | Formeel patroon | Formal pattern | Vertaling
TV | Herkomst | Source | Vertaling
TV | Herkomst definitie | Origin of definition | Vertaling
TV | Indicatie authentiek | Indication authentic | Vertaling
TV | Indicatie formele historie | Indication formal history | Vertaling
TV | Indicatie materiële historie | Indication material history | Vertaling
TV | Kwaliteit | Quality | Vertaling
TV | Lengte | Length | Vertaling
TV | Locatie | Location | Vertaling
TV | Mogelijk geen waarde | Voidable | Vertaling
TV | Patroon | Pattern | Vertaling
TV | Populatie | Population | Vertaling
TV | Regels | Rules | Vertaling
TV | Toelichting | Description | Vertaling
VAL | Ja | Yes | Vertaling
VAL | Nee | No | Vertaling
VAL | Zie groep | See group | Vertaling
VAL | Authentiek | Authentic | Vertaling
VAL | Basisgegeven | Base data | Vertaling
VAL | Landelijk kerngegeven | National base data | Vertaling
VAL | Gemeentelijk   kerngegeven | Municipal base data | Vertaling
VAL | Overig | Other | Vertaling

**Comment by ArjanLoeffen** [comment]
Ik stel ook de volgende aanpassingen naar Nederlandse namen voor:

- CodeList -> Codelijst
- Datatype -> Primitief datatype
- Union - > Keuze
- Union element - > Keuze element

Ik stel ook voor de namen niet letterkast gevoelig te maken. Ook geen reden om de termen aan elkaar te plakken vermoed ik. Dus  niet ReferenceElement maar Reference element. Featuretype lijkt me wel correct, dat zou in het engels ook één woord zijn?
Ik vraag me ook af wat uit de discussie zou komen als we conceptuele modellen gaan koppelen met ISO 19* modellen die meer "logisch" van aard zijn. Zouden we daarom voor "Objecttype" moeten/kunnen kiezen als we de engelse MIM opvatten als conceptueel?

**Comment by dkrijtenburg-GNM** [comment]
let op : opmerkingen van Arjan zijn nog NIET verwerkt!

**Comment by PalmJanssen** [comment]
Deze twee zijn verwerkt in respec. Nog niet in UML

Union - > Keuze
Union element - > Keuze element

**Comment by ArjanLoeffen** [comment]
Waar staan we nu? 
Ehn hoe verhoudt zich dit met de primitieve datatypen: CharacterString, Real, DateTime etc. Daarvan wordt gezegd dat dat op GAB is gebaseerd, dus in ieder geval uitgelegd, maar wel raar voor een nederlandstalig model.

Graag prio!
