### ISSUE TITLE
Keuzes beter structureren

### ISSUE THREAD

**Issue by lennartvanbergen** [Geonovum/MIM-Werkomgeving#171]
Keuze tussen datatypes 

Keuze tussen eigenschappen van een object (attribuutsoorten, relatiesoorten, externe koppeling - niet per 1 type MIM-element)

**Comment by dkrijtenburg-GNM** [comment]
UML-voorbeeld toevoegen

**Comment by kad-mesdat** [comment]
DIt issue is gerelateerd aan de vraag van https://github.com/Geonovum/MIM-Werkomgeving/issues/158. De tekst van 2.7.2 kan idd wel wat helderder. Hieronder voorstellen daarvoor:

> Een Keuze kan op meerdere plekken gebruikt worden, en maakt het mogelijk waar in het metamodel normaal gesproken maar één mogelijkheid bestaat, een opsomming te geven van meerdere mogelijkheden, waarbij in een concreet geval altijd precies één van deze mogelijkheden wordt gebruikt.

Een Keuze maakt het mogelijk een opsomming te geven van meerdere mogelijkheden, waarbij in een concreet geval altijd precies één van deze mogelijkheden wordt gebruikt. Er zijn verschillende plekken waar dit gebruikt kan worden. 

> Een belangrijk voordeel van deze modellering is dat de kardinaliteiten zuiver gehouden kunnen worden. Anders gezegd, er kan mee voorkomen worden dat een kardinaliteit van bijvoorbeeld twee kenmerken eerst optioneel gemaakt moet worden en dat hierna via een constraint deze toch weer verplicht gemaakt moeten worden, voor precies één van de mogelijkheden. Het is aan de modelleur om te kiezen voor een constraint of een Keuze.

Een belangrijk voordeel van het gebruik van de Keuze ten opzichte van een constraint is dat de kardinaliteiten zuiver gehouden kunnen worden. Bij het gebruik van een constraint zie je vaak dat de kardinaliteit van bijvoorbeeld twee kenmerken optioneel gemaakt is en om vervolgens via de constraint toch weer verplicht gemaakt te worden, voor precies één van de mogelijkheden. 

> Het is niet de bedoeling om twee attribuutsoorten te modelleren met elk een datatype en de attribuutsoorten optioneel te maken.

> Zonder de mogelijkheid van keuze, zou je te maken krijgen met twee attribuutsoorten met bijbehorend datatype. Echter, in dat geval mogen de attribuutsoorten niet dezelfde naam hebben, aangezien deze bij hetzelfde objecttype horen. Ook zou de kardinaliteit niet kloppen: die zou dan [0..1] moeten worden, maar dat doet geen recht aan het feit dat er één verplicht aanwezig moet zijn, en er ook geen twee naast elkaar mogen zijn. De werkelijke kardinaliteit is [1..1].

_Dit kan volgens mij weg. Maar zo niet, dan liever zo:_
Bij een modellering zonder Keuze zou je te maken krijgen met een attribuutsoort per datatype, maar met een verschillende naam, hoewel ze betrekking hebben op hetzelfde kenmerk. Ook zou de kardinialiteit niet kloppen: die zou dan [0..1] moeten worden, maar dat doet geen recht aan het feit dat er één verplicht aanwezig moet zijn, en er ook geen twee naast elkaar mogen zijn. De werkelijke kardinaliteit is [1..1].


Bij de twee usecases over attribuut keuze heb ik echt een visuele weergave nodig. Volgt later

**Comment by dkrijtenburg-GNM** [comment]
lennart werkt dit verder uit na afstemming met Pano en Paul op 22-2-23

**Comment by ThiesMesdag** [comment]
![image](https://github.com/Geonovum/MIM-Werkomgeving/assets/11945098/386dc4ef-cc67-4cef-9bde-42942c865275)

Nog toevoegen in tekst ? Metagegeven: heeft keuze-eigenschappen

Toepassing: Objecttype, Keuze.

**Comment by ThiesMesdag** [comment]
Bovenstaande plaatje is nog niet helemaal goed (De binding van een keuze tussen attribuutsoorten/gegevensgroep is geen relatie maar een attribuut met keuze type (stereotype)). Verder is de vraag of dit te implementeren zou zijn. 
Omdat er nog geen acute praktijkvraag voor is lijkt het ons verstandig om dat eerst uit te zoeken. Dus deze gaat naar een volgende release.

**Comment by Gtrouborst** [comment]
Tekst en figuur/figuren zijn aangepast en opgenomen in de documentatie van MIM1.2
