### ISSUE TITLE
metadata Identificerend op een relatiesoort staat wel in H2 maar is verder niet uitgewerkt in H3 en H4.

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#176]
H2: https://docs.geostandaarden.nl/mim/def-st-mim-20201023/#metagegeven-identificerend

In de tekst staat dat het op relatiesoort mag. 

Er mist nog een 'toepassing op modelelementen' stukje in deze beschrijving, wat bij andere metadata wel staat. 

In H3: staat dit metagegeven Identificerend echter niet benoemd. 
https://docs.geostandaarden.nl/mim/def-st-mim-20201023/#specificatie-metagegevens-voor-relaties

In H4 ontbreekt het ook. 
https://docs.geostandaarden.nl/mim/def-st-mim-20201023/#specificatie-metagegevens-voor-relaties-0 
en dus ook niet in bijlage 6. 

In bijlage 6.1.2 en in het UML-profiel voor EA ontbreekt het derhalve ook.
https://docs.geostandaarden.nl/mim/def-st-mim-20201023/#modelelementen-en-metagegevens-als-diagram

PS. Identificerend = Ja of true meenemen.

**Comment by PalmJanssen** [comment]
Dat kan in de diagrammen worden verwerkt. Voorbeeld voor relatiesoort. De TV identificerend is toegevoegd:
![image](https://user-images.githubusercontent.com/9932784/140908246-f9f9d34f-4835-45ca-9428-feb55235aaa5.png)

**Comment by lennartvanbergen-kadaster** [comment]
@architolk identificerend op referentie element nodig, of mag dat weg in H4?

**Comment by PalmJanssen** [comment]
identificerend staat ook in hfst 3 bij referentie element: https://docs.geostandaarden.nl/mim/def-st-mim-20201023/#specificatie-metagegevens-voor-waardenlijsten

Ik denk dat dat hier vandaan komt. Ik kan me voorstellen dat het om het identificerend item (attribuut) in een referentielijst gaat. In de referentie lijst [cbscode, gemeentenaamNL, gemeentenaamFr) kan cbscode het identificerende item zijn.

In het UML in bijlage 6.1.2 staat trouwens bij referentie element het metagegeven identificatie. Dat moet dan identificerend zijn.

![image](https://user-images.githubusercontent.com/9932784/144237357-be080280-299c-4ad6-bbdb-2331c6ed0289.png)

**Comment by lennartvanbergen-kadaster** [comment]
Dus, van toepassing op attribuutsoorten, relatiesoorten (alle soorten) en waardelijsten. 

Voor attribuutsoorten en relatiesoorten wordt het gebruikt als identificatie van een object. Als meerdere eigenschappen identificerend zijn dan is er sprake van een samengestelde identificatie.

Voor referentielijsten geeft het aan welke referentie elementen identificerend zijn binnen de referentielijst. 

Tekst oud is te veel gebaseerd op unieke sleutels van objecten. Iets algemener maken. 

2.8.2.9 Metagegeven: Identificerend
Definitie Identificerend
Een kenmerk van een objecttype die aangeeft of deze eigenschap uniek identificerend is voor alle objecten in de populatie van objecten van dit objecttype.

Toelichting: objecten hebben, of krijgen, in een administatie of gegevensvoorziening vaak één identificerend kenmerk. Het kan ook zijn dat een aantal kenmerken in combinatie identificerend zijn, zoals twee attibuutsoorten of een attribuutsoort en een relatiesoort. De combinatie met een relatiesoort wordt alleen gedaan voor objecttypes die zelf geen unieke aanduiding hebben en daarom deze moeten samenstellen met de unieke aanduiding van een gerelateerde objecttype.

toepassing: attribuutsoort, alle relaties (relatiesoort, relatieklasse, externe koppeling), waardelijsten op het identificerende gegeven in de waardelijst. 

----
**Voorstel** 

2.8.2.9 Metagegeven: Identificerend
Definitie Identificerend
Een aanduiding dat een kenmerk of een combinatie van kenmerken van een objecttype uniek identificerend is of zijn voor alle objecten in de populatie van objecten van dit objecttype, of de aanduiding dat referentie element of combinatie van referentie elementen uniek identificerend is of zijn voor alle lijst items in een referentielijst.  

Toelichting: objecten hebben, of krijgen, in een administratie of gegevensvoorziening vaak één identificerend kenmerk. Het kan ook zijn dat een aantal kenmerken in combinatie identificerend zijn, zoals twee attribuutsoorten of een attribuutsoort en een relatiesoort. De combinatie met een relatiesoort wordt alleen gedaan voor objecttypes die zelf geen unieke aanduiding hebben en daarom deze moeten samenstellen met de unieke aanduiding van een gerelateerde objecttype. 

Referentielijsten is het enige type waardelijst die dit dit metagegeven kan hebben, omdat de enumeratie zelf identificerend is en de uniek identificerende code van een codelijst zich buiten het informatiemodel bevindt.

Toepassing: attribuutsoort, alle relaties (relatiesoort, relatierol, relatieklasse, externe koppeling), referentie element. 

**einde voorstel** 
----

H3 en H4: deze van toepassing zijnde modelelementen nalopen en toevoegen aan de tabellen als identificerend er nog niet bij staat.

**Comment by PalmJanssen** [comment]
Twee aanpassing aan definitie:

1) een combinatie is ook enkelvoud
2) voor referentie element is het zover als ik zie altijd maar één referentie element dat de sleutel is is, nooit een combinatie van meerdere elementen.

2.8.2.9 Metagegeven: Identificerend
Definitie Identificerend
Een aanduiding dat een kenmerk of een combinatie van kenmerken van een objecttype uniek identificerend is voor alle objecten in de populatie van objecten van dit objecttype, of de aanduiding dat een referentie element uniek identificerend is voor alle lijst items in een referentielijst.

**Comment by lennartvanbergen-kadaster** [comment]
Verwerkt, zie eerdere post die geupdate is.

**Comment by PalmJanssen** [comment]
Ik merk op dat EA geen IsID heeft voor relaties en relatierollen. In UML specs heeft een property wel een IsID. Een property is daarbij een attribute of een ownedEnd van een associatie.

**Comment by lennartvanbergen-kadaster** [comment]
Dan is de UML uitwerking wel met isID en de EA uitwerking met tv identificerend.

**Comment by PalmJanssen** [comment]
procesinformatie:
- in alle diagrammen verwerkt

**Comment by architolk** [comment]
@lennartvanbergen-kadaster het veld "identificerend" is opgenomen in het LD model omdat het ook in de tabel voorkomt van eigenschappen van Referentielement (zie: https://geonovum.github.io/MIM-Werkomgeving/#specificatie-metagegevens-voor-waardenlijsten). Vermoedelijk moet hij uit de tabel worden gehaald?

**Comment by lennartvanbergen-kadaster** [comment]
Bij referentie element zit identificerend er in omdat in specifiek het geval een een referentielijst het niet eenduidig is welk element identificerend is. 

- Bij een enumeratie is de enumeratie waarde zelf identificerend. 
- Bij een codelijst is de code die in de codelijst staat opgenomen identificerend  
- Bij een referentielijst ... staan vaak wel 3 a 5 elementen genoemd, en soms is het zo dat 1 daarvan (of soms meerdere) identificerend is - bv. een landenlijst met landen en een landcode, de landcode is dan identificerend. 

Je kan je afvragen of de waardelijst wel of niet een vorm van een modellering van een object is. 

1. In principe kan het zijn dat de lijst met waarden een 'tot waardelijst gemaakte set van objecten' is, oftewel **afgeleid** is van een collectie van objecten en eigenschappen daarvan. Als dit zo is en we staan dit toe, dan hebben die objecten ook identificaties en dan is handig om te weten hoe je dat object wat ooit gebruikt is, kan vinden (bv. om de waardelijst periodiek bij te werken, als de naam van het land anders is geworden, en de code hetzelfde is gebleven). 
2. Je kan echter ook stellen dat een waardelijst per definitie nooit een vorm van modellering van een object is, en dan is een identificerend referentie element niet zinvol. 

Vooralsnog zitten we op de lijn dat de 1e insteek mag. 

Let wel, bij een waardelijst blijft het per (MIM) definitie een vastgepinde lijst met waarden. Deze waarden en bijbehorende data kunnen echter afgeleid zijn van een bepaalde collectie van objecten die elders leven. Dit is echter geen eis, vandaar dat er nergens in MIM staat dat ten minste 1 referentie element identificerend moet zijn.
