### ISSUE TITLE
Indicatie classificerend en indicatie afleidbaar staan verkeerd om uitgewerkt in UML 

### ISSUE THREAD

**Issue by ArjanLoeffen** [Geonovum/MIM-Werkomgeving#177]
In de standaard is opgenomen:

![image](https://user-images.githubusercontent.com/12828217/132848463-27bfce0c-a3f7-45d3-a476-08bc76a680b5.png)

Volgens mij moet dit net omgedraaid worden. Indicatie afleidbaar is UML derived; Indicatie classificerend is een tagged value.

**Comment by lennartvanbergen-kadaster** [comment]
Correct, nemen we mee bij MIM 1.1**1** , ga hier maar alvast vanuit.
