### ISSUE TITLE
«Externe koppeling» metadata mist kardinaliteit in de documentatie

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#178]
Kardinaliteit target is wel nodig. 

Wellicht is er nog e.e.a. nuttig, wat relatiesoort wel heeft, maar externe koppeling niet.

**Comment by lennartvanbergen-kadaster** [comment]
@dkrijtenburg-GNM deze staat op Done, maar is ie ook doorgevoerd?

**Comment by PalmJanssen** [comment]
procesinfo:
- verwerkt in hfst 2
- verwerkt in hoofdstuk 3
- niet verwerkt in hfst 4

Opmerking: Metagegeven Aggregatietype was in MIM 1.1 in uml opgenomen als Type aggregatie. Dit is een bug want het moet volgens hfstk 2 Aggregatietype zijn. Dit is nu voor 1.1.1 in het UML aangepast naar Aggregatietype.
