### ISSUE TITLE
Opnemen van een tagged value voor versies/varianten van metamodel

### ISSUE THREAD

**Issue by ArjanLoeffen** [Geonovum/MIM-Werkomgeving#18]
Als je MIM toepast moet je kunnen aangeven welke insteek/extension/profile je kiest. Dus bijvoorbeeld conceptueel of logisch, en/of KKG-ISO profile, en of NEN3610, en wellicht ook welke variant van MIG (grouping) je volgt. Dit moet dus expliciet zijn opgenomen op het opgeleverde model, waardoor ook allerlei verwerkingslogica (validatie etc.) daaruit kan worden afgeleid.

Ik vermoed dat dat onderdeel moet worden van MIG, en ik ben bereid daar een voorstel voor te doen.

**Comment by lennartvanbergen-kadaster** [comment]
Analoog aan item #12

Nieuwe aspecten bij informatiemodel:

MIM versie:
Modellering: tagged value bij package Informatiemodel
Definitie: de versie van MIM.
Bijvoorbeeld: 1.01 of 1.1

MIM taal:
Modellering: tagged value bij package Informatiemodel
Definitie: aanduiding van de taal waarin het informatiemodel gemodelleerd is.
Voorbeeld: EN of NL

MIM extensie:
Modellering: tagged value bij package Informatiemodel
Definitie: de aanduiding van een extensie op MIM.
Voorbeeld: Kadaster, of NEN3610, of Kadaster NEN3610

MIM extensie versie:
Modellering: tagged value bij package Informatiemodel
Definitie: de versie van een extensie op MIM.
Bijvoorbeeld: 0.5 of 1.1a

**Comment by dkrijtenburg-GNM** [comment]
ter consultatie

**Onderwerp**:
Opnemen van een tagged value voor versies/varianten van metamodel

**Oplossing**:
Analoog aan item #12

Nieuwe aspecten bij informatiemodel:

MIM versie:
Modellering: tagged value bij package Informatiemodel
Verplicht
Definitie: de versie van MIM.
Toelichting: de versie van de MIM specificatie die gebruikt is om het informatiemodel in uit te drukken.
Bijvoorbeeld: 1.01 of 1.1

MIM taal:
Modellering: tagged value bij package Informatiemodel
Optioneel
Definitie: aanduiding van de taal die gebruikt is voor de modelelementen.
Toelichting: een modelelement Keuze heet in het Engels union.
Voorbeeld: EN of NL

MIM extensie:
Modellering: tagged value bij package Informatiemodel
Optioneel
Definitie: de aanduiding van een extensie op MIM.
Voorbeeld: Kadaster, of NEN3610:2020.

**Comment by ArjanLoeffen** [comment]
Mee eens. 
We gaan er dus bij dit voorstel van uit dat de MIM extensie versie _op zich_  onafhankelijk is van de MIM versie. En dat de versie van de extensie, als deze aangrijpt op een latere MIM versie, dan ook gewoon wordt opgehoogd.

Anders zou de MIM extensie versie al voldoende zijn; daarin ligt de MIM versie besloten.

**Comment by jacblom** [comment]
Mede namens Han Welmer:

Eens met het voorstel en de opmerking van Arjan.
De processing mode bij het aanbieden van een model aan Imvertor kan hiermee vereenvoudigd worden.

**Comment by PalmJanssen** [comment]
Dank voor commentaar.
Wordt ongewijzigd doorgevoerd.

**Comment by PalmJanssen** [comment]
Is aangepast in tekst.
Nog niet aangepast in UML.

**Comment by PalmJanssen** [comment]
Voeg ook de optie alternatief 1 of alternatief 2 toe.
