### ISSUE TITLE
MIM LD: rdfs:label -> skos:prefLabel

### ISSUE THREAD

**Issue by kad-rowla** [Geonovum/MIM-Werkomgeving#181]
Mag ik voorstellen dat `rdfs:label` wordt `skos:prefLabel`, want `skos:altLabel` wordt soms ook gebruikt. 

Dit wordt gedaan om ervoor te zorgen dat er een duidelijke afbakening is tussen verschillende labels die verschillende beoogde toepassingen kunnen hebben.

**Comment by dkrijtenburg-GNM** [comment]
voor 1.2 beantwoorden of een uitwerking maken

**Comment by pmaria** [comment]
Hoewel `skos:prefLabel` in sommige gevallen ook wordt gebruikt voor het beschrijven van de naam van een klasse of eigenschap in RDF, is het gebruikelijker om `rdfs:label` te gebruiken. Verder is met #198 het gebruik van `skos:altLabel` ook herzien.
Er is daarmee momenteel geen zwaarwegende reden om `skos:prefLabel` te verkiezen boven `rdfs:label`.
