### ISSUE TITLE
MIM LD: De waarde van 'rdfs:label' (of beter 'skos:prefLabel') zou niet hetzelfde moeten zijn als 'skos:altLabel'.

### ISSUE THREAD

**Issue by kad-rowla** [Geonovum/MIM-Werkomgeving#182]
Als aanvulling op issue #181 zijn er gevallen waarin de waarde van `rdfs:label` en `skos:altLabel` hetzelfde is. Voor semantische doeleinden zou dit niet het geval moeten zijn.  `skos:altLabel` mag alleen worden gebruikt als een extra labelwaarde voor een klasse of eigenschap vereist is en dan moet het voorkeurslabel worden geïdentificeerd met een `skos:prefLabel`.

**Comment by dkrijtenburg-GNM** [comment]
check of dit nog een issue is

**Comment by pmaria** [comment]
Met oplossen van #198 wordt `skos:altLabel` niet meer gebruikt in de LD transformatie van het metagegeven `alias`. Hiermee komt `skos:altLabel` ook niet meer voor in een gegenereerde ontologie. Daarmee is dit geen issue meer.
