### ISSUE TITLE
MIM LD: Kleine foutjes met '%20' in de IRIs

### ISSUE THREAD

**Issue by kad-rowla** [Geonovum/MIM-Werkomgeving#183]
Hier zijn een aantal voorbeelden van, waaronder:
- `bag:Openbare%20ruimte`
- `bag:type%20adresseerbaar%20object`
- `bag:ligt%20aan`

**Comment by dkrijtenburg-GNM** [comment]
waarschijnlijk geen issue, wordt gecheckt bij indiener

**Comment by pmaria** [comment]
@kad-rowla deze issues zijn niet voor de MIM standaard, maar hebben te maken met een specifieke toepassing van de LD transformatieregels op een specifiek MIM model. Ik stel voor om dit issue te sluiten. Het specifieke issue moet in de toepassing of het model opgelost worden.
