### ISSUE TITLE
MIM LD: Definities ontbreken voor eigenschappen

### ISSUE THREAD

**Issue by kad-rowla** [Geonovum/MIM-Werkomgeving#184]
Definities zijn beschikbaar voor alle klassen en het zou een leuke toevoeging zijn om ook de definities van eigenschappen op te nemen.

**Comment by dkrijtenburg-GNM** [comment]
@pmaria : als je wil dat deze meegaat in MIM 1.2 dan graag zsm uitwerken

**Comment by pmaria** [comment]
De kern van het probleem zit in het nog niet zo scherpe onderscheid tussen niveau 2 en 3, waardoor je vanuit het LD-perspectief vreemde modelconstructies krijgt.

Voor nu is onderstaande denk ik voldoende.

> Als het gaat om 2 objecttypen met elk een eigenschap en deze eigenschappen dezelfde naam hebben, dat is in eerdere versies al geadresseerd. https://docs.geostandaarden.nl/mim/mim/#dezelfde-naam-en-of-definitie-gebruiken-voor-meerdere-modelelementen

Voor nu kunnen we dit issue sluiten.
