### ISSUE TITLE
URI van model en modelelementen voor publicatie op het web

### ISSUE THREAD

**Issue by lennartvanbergen** [Geonovum/MIM-Werkomgeving#188]
Behoefte: een model zelf publiceren op het web, met per modelelement een URI. Volgens webstandaarden en volgens de URI strategie.

Bv. voor de BAG 
http://bag.basisregistraties.overheid.nl/def/bag
voor het model 

Bv. voor BAG Pand
http://bag.basisregistraties.overheid.nl/def/bag/pand 

Dit is een locatie van een model of model element op het web, de URI van een domein. 

Op dit moment kan je een informatiemodel wel uitdrukken in een LD ontology. maar de prefix van de URI bv bag:http://bag.basisregistraties.overheid.nl/def/bag kan je nergens kwijt. 

Vraag is ook of dit bij het informatiemodel hoort of een configuratie naast het informatiemodel zou moeten zijn. 

Configuratie lijkt logisch omdat het een serialisatie concern is. Echter, als het ook functioneel nuttig is dan zou dat mooi zijn. 

Het zit in de buurt van het domein van identificatie van een object, maar eigenschappen zoals naam Vraag is even hoe dit gegeven te noemen. Is er een term in de URI strategie, en MIM zelf maakt onderscheidt tussen model en modelelement (en bindingen).

**Comment by architolk** [comment]
Het is hier niet bedoeld als serialisatie-issue, maar juist als identificatie-issue (dwz: wat is daadwerkelijk de identiteit van een modelelement). Het heeft dan ook raakvlakken met issue #104. De uitwerking zou kunnen zijn om een namespace-mogelijkheid toe te voegen op package-niveau, waardoor je een URI zou kunnen vormen op basis van de namespace en de naam van een modelelement. Wel moet je dan nog mogelijkheden hebben om dit standaard-gedrag te overrulen, zoals ook in issue #104 beschreven.

**Comment by dkrijtenburg-GNM** [comment]
er wordt gedacht aan een niet verplichte tag value

**Comment by kad-mesdat** [comment]
Zie voor beiden #188 en #104 ook https://github.com/Geonovum/WaU-UC3/blob/0f47096ae28bdaa139d0ef86140e56f69281a2ad/mim2rdf.md

**Comment by kad-mesdat** [comment]
Hieronder een voorstel voor een toevoeging aan "2.8.1 Specificatie metagegevens informatiemodel", gebaseerd op de link in de voorgaande comment. Vermoedelijk moeten deze ook worden toegevoegd voor <<extern>> en <<view>> packages.



#### Metagegeven: **Basis-URI**

>   **Definitie Basis-URI**  
>   De standaard basis URI voor elk element in dit informatiemodel.

*Toelichting* Een uniform resource identifier (URI) is een compacte reeks tekens die een abstracte of fysieke bron identificeert. Een basis-URI is een het gemeenschappelijke deel van deze reeks tekens die voor alle elementen in het informatiemodel geldig is. Dit metagegeven is verplicht. De basis-URI moet absoluut zijn (inclusief het protocol (http(s)://)) en eindigen met een "/". Bijvoorbeeld: http://bag.basisregristraties.overheid.nl/

*Toepassing*: informatiemodel (verplicht)

#### Metagegeven: **Ontologie URI**

>   **Definitie Ontologie URI**  
>   De standaard URI voor de ontlogie waar de elementen uit dit informatiemodel in zijn opgenomen. 

*Toelichting* De ontologie URI is over het algemeen gelijk aan de basis-URI minus het laatste karakter. Bijvoorbeeld: http://bag.basisregristraties.overheid.nl

*Toepassing*: informatiemodel (optioneel)

#### Metagegeven: **Schema basis-URI**

>   **Definitie Schema basis-URI**  
>   De standaard URI voor de elementen die in de shapes graph (an owl:Ontology) van het informatiemodel zijn opgenomen.

*Toelichting* De Schema basis-URI is over het algemeen gelijk aan de basis-URI. Bijvoorbeeld: http://bag.basisregristraties.overheid.nl/

*Toepassing*: informatiemodel (optioneel)

#### Metagegeven: **Schema URI**

>   **Definitie Schema URI**  
>   De standaard URI voor het schema (de shapes graph (an owl:Ontology)) zelf.

*Toelichting* De schema base uri is over het algemeen gelijk aan de base URI minus het laatste karakter. Bijvoorbeeld: http://bag.basisregristraties.overheid.nl. 

*Toepassing*: informatiemodel (optioneel)

**Comment by Gtrouborst** [comment]
`URI` van model en modelelementen voor publicatie op het web toegevoegd aan documentatie **MIM1.2**

**Comment by Gtrouborst** [comment]
Wijzigingen in document doorgevoerd.
