### ISSUE TITLE
Introductie van grouping (aanvullend op MIM)

### ISSUE THREAD

**Issue by ArjanLoeffen** [Geonovum/MIM-Werkomgeving#19]
Grouping moet worden geïntroduceerd als metamodel náást MIM. Het betreft de wijze waarop de modelelementen worden samengebracht in domeinen, packages, met onderlingen relaties, versies, e.d. 

Grouping is (grofweg) gelijk voor de huidige gebruikers gebouwd in de Imvertor omgeving, maar verschillen zijn er. Ik ben bereid een eerste voorstel aan te bieden voor een standaard. Samen met MIM zou dan het MIG (Metamodel voor Grouping, of een betere naam) een werkbare eenheid kunnen vormen, waarin alles wat je aantreft in een opgeleverd model kunt herleiden tot afspraken.

**Comment by dkrijtenburg-GNM** [comment]
beschrijven in HIM?

**Comment by dkrijtenburg-GNM** [comment]
geonovum wijst dit toe aan  Arjan Loeffen

**Comment by ArjanLoeffen** [comment]
Dick kun je aangeven hoe en waar ik mijn bijdragen kan leveren?

Arjan vanaf mobiel

Op di 19 feb. 2019 13:14 schreef dkrijtenburg-GNM <notifications@github.com:

**Comment by dkrijtenburg-GNM** [comment]
Als je je bestand in Word aanlevert, kunnen wij het via markdown in Respec zetten.

**Comment by ArjanLoeffen** [comment]
Als ik het verzoek ontvang zal ik deze specificatie proberen op te leveren.

**Comment by lennartvanbergen-kadaster** [comment]
We hebben een paar keer gesproken over hoe dit op te delen. Uitkomst is wel gestabiliseerd. 

De metadata die vereist is voor een informatiemodel zit in MIM. Alle andere, die ook zeer nuttig is, voor applicaties en productmodellen en services zit niet in MIM. Grouping bestaat derhalve uit twee lagen. Aan Arjan is gevraagd om dit tweede deel in te vullen en kritisch te kijken naar het eerste deel.

**Comment by lennartvanbergen-kadaster** [comment]
Bij deze moet opgemerkt worden dat grouping aspecten die breder zijn dan de packages in MIM niet meegenomen zijn bij de afhandeling van dit issue. Als die ook gewenst zijn, of als dat de oorspronkelijk wens was, dan moet dit issue opnieuw worden ingebracht - als aanvulling op MIM. 

Ter controle, @ArjanLoeffen , hoe zie jij dit? Als die aanvulling inderdaad een wens is, zou je die nog eens willen opvoeren?
