### ISSUE TITLE
Keuze tussen relatiesoorten (use case 5) 

### ISSUE THREAD

**Issue by lennartvanbergen** [Geonovum/MIM-Werkomgeving#190]
Dit issue is (meen ik) ooit opgevoerd omdat we een discussie hadden over hoe dit eruit zou moeten zien en Kadaster de enige was die dit ging gebruiken en het daarom te planning niet heeft gehaald. 

Daarom heet het issue: keuze tussen relatiesoorten. 

Het woord doel komt zeg maar niet voor in deze use case. 

Het betreft dan ook niet use case 4, maar de nog op te voeren use case 5. 

Use case 5 is zeg maar een relatie van A naar B en A naar C en 1 van de 2 relaties is verplicht. Ze worden dan soms beide zijn 0..1 gemaakt + een constraint dat je 1 van de 2 moet invullen. Ze kunnen immers niet allebei 1..1 kunnen zijn.

Use case 5: een keuze tussen relatiesoorten. Er is sprake van een relatiesoort R1 en een relatiesoort R2. R1 heeft als doel een object van objecttype D1 en R2 heeft als doel een object van objecttype 2. In MIM modelleren we daarom een keuze met als uitgaande relatiesoorten R1 en R2. Het maken van deze keuze is verplicht.

Vervoersmiddel --> relatie zonder naam met stereotype keuze (zonder kardinaliteit en zonder definitie) --> EigenaarKeuze met stereotype keuze. In bv. een XSD wordt dit een choice.

EigenaarKeuze heeft een relatiesoort R1 naar objecttype D1 en heeft een relatiesoort R2 naar objecttype D2.

De kardinaliteit zit op de relatiesoort zoals gebruikelijk, maar is ofwel 1..1 ofwel 1..* aan de target kant. Aan de source kant hangt dit af van de gewone kardinaliteit van de relatie zoals normaal, kan 0, 1 of * zijn.

**Comment by dkrijtenburg-GNM** [comment]
in discussie meenemen of dit al dan niet in de plaats moet komen van keuzes tussen relatiedoelen

**Comment by ThiesMesdag** [comment]
Invoegen na keuzerelatiedoel en voor contstraint

Uitwerking in plaatje:
![image](https://github.com/Geonovum/MIM-Werkomgeving/assets/11945098/ba2671f8-4fa7-455f-9e22-d94075e97faa)

Metagegeven: heeft keuzerelatiesoort
Verkorte schrijfwijze: keuzerelatiesoort

Definitie heeft keuzerelatiesoort
De binding van een keuze uit relatiesoorten aan een objecttype.

Toelichting

Een keuze tussen relatiesoorten kan als eigenschap aan een objecttype worden gekoppeld.

Toepassing: Objecttype, Keuze.

--- 
ook nog plaatje en tekst in hoofdstuk 3

**Comment by PalmJanssen** [comment]
Ditzelfde moet natuurlijk ook werken voor de keuze uit verschillende benoemde relatie-einden. In dit geval 'contactPersoon' en 'contactOrganisatie'

**Comment by ThiesMesdag** [comment]
Plaatjes aangepast

**Comment by lennartvanbergen** [comment]
@ThiesMesdag kan je de naamgevingsconventie nog volgen voor de relaties? 
Bv. 
relatienaam: heeft als contactpersoon
rolnaam: contactpersoon 
relatienaam: wordt  vertegenwoordigd door organisatie 
rolnaam: organisatiecontact

Inderdaad zoals Paul aangeeft zowel rol leidend als relatie leidend meenemen, liefst in hetzelfde plaatje. Het is immers ook dezelfde use case, alleen de uitwerking is per variant net anders. Alleen wat verplicht en optioneel is verschilt bij een variant. Aangezien je bij beide varianten beide mag invullen, zou ik ze beide invullen, dan hebben we maar 1 plaatje nodig voor 1 use case voor beide varianten. In H2 is dat ook wel prettig. 

@PalmJanssen overigens, ditzelfde zou dan ook gedaan horen te worden voor use case 4. Dit diagram heeft nu geen rolnaam op de relatiesoort. Voorstel: pas deze ook aan, noem de relatie: heeft als eigenaar en als rol: eigenaar. Kan jij dit oppakken?

Ik heb een pull request gemaakt voor H2 als start:  https://github.com/Geonovum/MIM-Werkomgeving/pull/332

**Comment by Gtrouborst** [comment]
Beschikbare wijzigingen overgenomen voor consultatie.
