### ISSUE TITLE
Begrip is aspect van Enumeratiewaarde

### ISSUE THREAD

**Issue by ArjanLoeffen** [Geonovum/MIM-Werkomgeving#191]
Enumeratiewaarde heeft mogelijk een definitie, maar geen gekoppeld begrip. Volgens mij is dat een omissie. Graag toevoegen.

Meer in het algemeen is deze koppeling niet strak:
Definitie, dan mogelijk begrip, en misschien ook wel andersom.

- heeft definitie maar geen begrip: domein, extern, informatiemodel, view, relatierol.
- heeft begrip maar geen definitie: datatype, generalisatie.

**Comment by ArjanLoeffen** [comment]
Verkeerde discussie.

**Comment by ArjanLoeffen** [comment]
Oh nee, wel de goede plek. Ik heropen.

**Comment by PalmJanssen** [comment]
Dit is opgelost in versie 1.1.1

![image](https://user-images.githubusercontent.com/9932784/207287276-de74488d-6643-41f7-a3c2-16db48fce96b.png)
