### ISSUE TITLE
Domein niet van toepassing op Referentie element

### ISSUE THREAD

**Issue by ArjanLoeffen** [Geonovum/MIM-Werkomgeving#192]
Domein (aspecten van een waarde/data) is gedefinieerd voor een Referentie element.

Ik kan dat niet thuisbrengen. Ik neem aan dat het bedoeld is om de gegevens die worden ingelezen aan banden te leggen. Dat is echter de verkeerde plek om dat te doen: de validatie daarvan dient plaats te hebben in de beheeromgeving van de referentielijst, niet in het aanroepende model. Ik wil voorstellen deze metagegevens hier te verwijderen.

**Comment by lennartvanbergen** [comment]
Zie https://docs.geostandaarden.nl/mim/mim/#specificatie-metagegevens-voor-waardenlijsten
referentielijst 
heeft datatype - is opgelost tijdens verbeteren van bindingen .

**Comment by lennartvanbergen** [comment]
close maar
