### ISSUE TITLE
MIM in XML als export/serialisatie formaat

### ISSUE THREAD

**Issue by lennartvanbergen** [Geonovum/MIM-Werkomgeving#197]
Organisaties die model-gedreven willen verder werken met een informatiemodel hebben behoefte aan een export formaat waarmee dit fijn kan. 

We zien het zitten om een XML te maken die in MIM-taal hetzelfde aangeeft als MIM H2 en H3 en H4. Voor H4-LD is al een uitwerking gemaakt in bijlage 6.4 maar voor de niet-LD wereld nog niet. 

Dit is een groot item. De beschrijving hierboven is op hoofdlijnen. Nadere toelichting en invulling volgt. 

We zien dit als onderdeel van MIM 1.1.1. - het hoort hierbij. Het kan op zich los van de 1.1.1. versie van de standaard, kort erna, worden opgeleverd maar we proberen het tegelijk te doen.

**Comment by lennartvanbergen-kadaster** [comment]
@pmaria @joostfarla @architolk @PalmJanssen @wilkoquak om watcher op te worden.

**Comment by lennartvanbergen-kadaster** [comment]
In ieder geval nodig: 

https://github.com/Geonovum/MIM-Werkomgeving/issues/164
https://github.com/Geonovum/MIM-Werkomgeving/issues/165
https://github.com/Geonovum/MIM-Werkomgeving/issues/166
https://github.com/Geonovum/MIM-Werkomgeving/issues/167
https://github.com/Geonovum/MIM-Werkomgeving/issues/168
https://github.com/Geonovum/MIM-Werkomgeving/issues/176

Deze gaan mee met MIM 1.1.1.

**Comment by lennartvanbergen-kadaster** [comment]
Het stappenplan om te komen tot het MIM export formaat en de algemene beschrijving van dit onderwerp is bij Lennart op te vragen. We pakken dit op wat mij betreft als een project(je) nadat MIM 1.1.1. gereed is, en publiceren dit later als add-on op MIM 1.1.1. (als 1.1.2 of gewoon bij 1.1.1.). We willen er eerst een paar keer mee werken voordat we 'm echt publiceren als een versie.

**Comment by lennartvanbergen-kadaster** [comment]
Plan: mim-export formaat 1 stap verder brengen, met kernteam, nog zonder community erbij, in navolging van MIM 1.1.1. 
Kernteam: usual suspecs van Geonovum, Kadaster, Armatiek + afspreken rollen (Dick) 
Randvoorwaarde: MIM 1.1.1. - wat dat zijn de bevindingen van de vorige stap (MIM groep) --> gereed. 

Vertrekpunt: wat er nu ligt, mim-export formaat wat Kadaster heeft en de next versie die Armatiek al heeft gemaakt. 
Bekijken wat er nu ligt, samen met kernteam punten opvoeren in github en hier samen aan werken. 
- De meeste punten staan al in MIM 1.1.1. --> deze oppakken
- Een aantal nog open gebleven punten uit discussiëren (die ook niet in MIM 1.1.1. zijn aangemeld).  
- Sommige punten zullen ook gaandeweg gevonden worden. 

Punten verwerken in mim-export formaat (XML) en in documentvorm bij MIM onderbrengen, bv. in bijlage analoog aan 6.4 - gaandeweg samen bepalen wat de beste plek is. 

Hierna: in community brengen als 0.9 versie behorende bij MIM 1.1.1 versie, met verzoek om deze te gebruiken en feedback te vragen + dan verder door ontwikkelen onder versiebeheer. 

Doorlooptijd: 0,5 dag per week aan werken, gedurende 1 a 2 maanden. 

Hierna, kan wel of niet onderdeel van het plan zijn, nog nader te bepalen met kernteam: 
- De model-gedreven modules die al gemaakt zijn op het "oude" formaat naar de nieuwe versie brengen + in OS brengen op imvertor.org van in ieder geval de transformatie van mim-export formaat in XML naar LD (bijlage 6.4) 
- Aanpassingen in software om een database schema te genereren 
- MIM verbeteringen die we ondertussen vinden die puur met MIM te maken hebben, deze bij MIM zelf aanmelden.

**Comment by lennartvanbergen-kadaster** [comment]
Er is een XSD en een XML voorbeeld die er nu is. 

We willen de XSD kunnen genereren via Imvertor vanuit het metamodel in UML.

**Comment by lennartvanbergen-kadaster** [comment]
[mim-export LVBAG met XSD.zip](https://github.com/Geonovum/MIM-Werkomgeving/files/8117211/mim-export.LVBAG.met.XSD.zip)

**Comment by lennartvanbergen-kadaster** [comment]
[MIMCM-Fietsenwinkel-1.0.0-2-20210901-20220126-130701.zip](https://github.com/Geonovum/MIM-Werkomgeving/files/8117212/MIMCM-Fietsenwinkel-1.0.0-2-20210901-20220126-130701.zip)

**Comment by lennartvanbergen-kadaster** [comment]
De XML en de XSD zitten in de folder /mim

**Comment by ArjanLoeffen** [comment]
We hebben een bijeenkomst gehad. @lennartvanbergen-kadaster heeft enkele aantekeningen gemaakt. Mijn reactie op enkele daarvan, Lennart, is dit een hanteerbare vorm?

> •	<mim-ref:Interface> interfaces kent MIM niet. Link met conceptual schema’s. Welke CharacterString dan? Hoe maken we dit fijn voor developers.

Interfaces kunnen eigenlijk “alles” representeren. Wanneer dat wordt aangetroffen worden (in Imvertor context) de conceptual schema’s geraadpleegd. Als info over de interface beschikbaar is (en dat moet eigenlijk wel, anders is het een fout) kan datgene wat de interface representeert worden ingevoegd op die plek. Dat kan een MIM construct zijn zoals een datatype (wat het eigenlijk altijd is), maar ook iets anders, wat niet per definitie conform MIM is. Op deze manier is het wellicht mogelijk interfaces “op te lossen”. Vraag is of dat ook de bedoeling is van de MIM serialisatie; het trekt dan dus info naar binnen die niet in het IM zelf zichtbaar/beschikbaar is. 

> •	Documentatie. Korte toelichting/def. Links naar MIM voor uitgebreidere. Tips voor implementatie opnemen ergens.

Ik vraag me af of dit wel een goede weg is. Een lijkje naar de standaard, dat kan ik me voorstellen. Maar méér zou ik eigenlijk zie als ballast: een KIM serialisatie moeten we niet zien als lesmateriaal maar data waarop software wordt gebouwd.

> •	Schema in 4 files, resolved of aparte schema in zelfde namespace? Misschien is 4 te veel.

Ik snap niet waarom we “bang” zouden moeten zijn van meerdere schema’s. De manier waarop deze elkaar aanroepen is transparant en volgt een standaard. Het is n.m.m. de verkeerde vorm van “vereenvoudiging”. Een gebruiker van de mim serialisatie die het schema bekijkt doet dat in een tool, en die presenteert (als het een goede tool daarvoor is) de  schema’s in één view.

> •	Sommige dingen zijn niet mim-ext te weten als het niet in MIM staat.

Wat bedoel je? Graag uitleg.

> •	<xhtml:body> om rijke tekst te ondersteunen, bullits, cursief.

Interessant is de aanname dat uitleggende tekst een zekere tekststructuur heeft. Dat is denk ik correct: het is voor menselijke consumptie bedoeld. De meest gangbare manier om tekststructuur te coderen is XHTML dus dat lijkt me een goede basis voor de serialisatie standaard. 

> •	Schema validatie op extensies?

Waarom valideren we een MIM serialisatie? Omdat software vertrouwen moet hebben dat de serialisatie klopt. Wanneer je alleen in het MIM domein beweegt hebben we een schema beschikbaar. Bewegen we in MIM _gebaseerd_ domein, dan komen daar extra validatie eisen bij. Dus schema constructies bovenop de standaard MIM constructies. Dat zijn beperkingen en uitbreidingen van de MIM standaard. Dus dat is een uitdaging: hoe zet je zo’n schema in elkaar, zodat ook een bedrijfsspecifiek MIM serialisatie schema de lading dekt?

> •	1 XSD of aparte XSD voor relatiesoort of rol leidend met super XSD.

Mijn gevoel zegt dat twee XSD’s voor deze twee benaderingen het beste zouden zijn. Er is dan één gezamenlijke XSD waarin alle gemeenschappelijke constructies zijn opgenomen. Zover ik weet levert alleen relatierol/soort leidend verschillende serialisatie op. Dus kan het bij deze opsplitsing blijven.

**Comment by dkrijtenburg-GNM** [comment]
@PalmJanssen. Kan deze worden gesloten?

**Comment by PalmJanssen** [comment]
Is afgehandeld met publicatie van de mim 1.1.1 serialisatie
