### ISSUE TITLE
Alias is voor bedoeld om meerdere schrijfwijzen te ondersteunen (zoals camel case) en niet zo zeer als een 'alternatieve naam' (een echt andere naam, een synoniem)

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#198]
Afgesplitst van https://github.com/Geonovum/MIM-Werkomgeving/issues/164

Alias tekst in H3: voorbeeld is verkeerd om (tekst kolom is in verkeerde rij verwerkt). 

Duidelijker aangeven dat alias bedoeld is voor een camel case variant van de naam.

Mapping naar LD is niet: altLabel. Beter lijkt een gewoon metagegeven zoals bv. ook datum opname. 

Wellicht is het beter om deze in EA te modelleren als metagegeven / tagged value, want de alias van EA wordt wel al vaker gebruikt voor andere dingen en de herkomst van dit issue, Dit laatste, er een metagegeven van maken in EA, is niet gebeurd. Dit valt strikt genomen ook buiten MIM, en moet ook eerst afgestemd worden (impact op implementatie).

**Comment by lennartvanbergen-kadaster** [comment]
Dikke van dale: anders gezegd, ook genoemd.

Het gaat om de alternatieve naam. Alias is op zich een goede term hiervoor. 

Het gaat om termen en woorden van dingen en eigenschappen van dingen en daar een alternatieve naam voor. 

Deze kan je toekennen aan alle modelelementen, die geen package zijn. 

Niet bedoeld om gewone woorden om te zeten naar camel case of snake case schrijfwijze. 
Niet bedoeld voor: vertaling naar een andere taal. 

Je mag wel in je logische informatiemodel een camel case schrijf wijze hanteren en deze dan in de alias in gewoon Nederlands uitschrijven. Zo wordt het ook gebruikt en is het bedoeld. 

Tekstvoorstel: 


2.8.2.3 Metagegeven: Alias
Definitie Alias
De alternatieve weergave van de naam in natuurlijke taal.

Toelichting

Als de naam van het modelelement in het informatiemodel bijvoorbeeld zonder spaties is geschreven, dan kan in de alias de naam in natuurlijke taal worden opgenomen. De term in natuurlijke taal kan dan gebruikt worden waar dat gewenst is. De alias is bedoeld als alternatieve schrijfwijze, en heeft verder geen andere betekenis. De alias is optioneel (zie verder ook Naamgevingsconventies).

Bijvoorbeeld: in het logische informatiemodel heet een objecttype OnroerendeZaak. Dit objecttype heeft als alias: Onroerende zaak. 

Toepassing: alle modelelementen die een naam hebben, uitgezonderd de Enumeratiewaarde en packages. 

NB: de alias wordt ook gebruikt voor een alternatieve weergave van een enumeratie waarde (in UML modellen de UML-EnumerationLiteral). De ‘naam’ betreft hier een daadwerkelijk waarde, waarin de naam gelijk staat aan de waarde. Het is daarom expliciet ongewenst om hiervoor een alternatieve naamgeving te gebruiken. De alias wordt hier, mede daarom, gebruikt voor wat anders, te weten een alternatieve _weergave_ in de vorm van een code (niet een alternatieve _naam_).

**Comment by lennartvanbergen-kadaster** [comment]
**Tekstvoorstel: 2.8.2.3 Metagegeven: Alias**

Definitie Alias
De alternatieve weergave van de naam in natuurlijke taal.

Toelichting

Als de naam van het modelelement in het informatiemodel bijvoorbeeld zonder spaties is geschreven, dan kan in de alias de naam in natuurlijke taal worden opgenomen. De term in natuurlijke taal kan dan gebruikt worden waar dat gewenst is. De alias is bedoeld als alternatieve schrijfwijze, en heeft verder geen andere betekenis. De alias is optioneel (zie verder ook Naamgevingsconventies).

Bijvoorbeeld: in het logische informatiemodel heet een objecttype OnroerendeZaak. Dit objecttype heeft als alias: Onroerende zaak. 

Toepassing: alle modelelementen die een naam hebben, uitgezonderd de Enumeratiewaarde en packages. 

NB: de alias wordt ook gebruikt voor een alternatieve weergave van een enumeratie waarde (in UML modellen de UML-EnumerationLiteral). De ‘naam’ betreft hier een daadwerkelijk waarde, waarin de naam gelijk staat aan de waarde. Het is daarom expliciet ongewenst om hiervoor een alternatieve naamgeving te gebruiken. De alias wordt hier, mede daarom, gebruikt voor wat anders, te weten een alternatieve _weergave_ in de vorm van een code (niet een alternatieve _naam_).

**Comment by lennartvanbergen-kadaster** [comment]
Uitwerking in H3 UML is al goed. 
Uitwerking in H4 LD - verifiëren @pmaria en @architolk

**Comment by pmaria** [comment]
> Definitie Alias
> De alternatieve weergave van de naam in natuurlijke taal.

"Weergave" klinkt als de manier waarop de naam getoond wordt. 

"Natuurlijke taal" is volgens mij te beperkend. 'Foo_Bar' is geen natuurlijke taal, maar misschien wil je het wel als alternatieve naam voor een modelelement gebruiken.

Waarom niet: "de alternatieve naam?"

> [...] De alias is bedoeld als alternatieve schrijfwijze [...]

Alternatieve schrijfwijze is iets anders als een alias of alternatieve naam.

> De alias [...]  is bedoeld als alternatieve schrijfwijze, en heeft verder geen andere betekenis.

Vraag die bij mij oppopt: Waarom hebben we alias dan eigenlijk nodig?

> NB: de alias wordt ook gebruikt voor een alternatieve weergave van een enumeratie waarde (in UML modellen de UML-EnumerationLiteral). De ‘naam’ betreft hier een daadwerkelijk waarde, waarin de naam gelijk staat aan de waarde. Het is daarom expliciet ongewenst om hiervoor een alternatieve naamgeving te gebruiken. De alias wordt hier, mede daarom, gebruikt voor wat anders, te weten een alternatieve weergave in de vorm van een code (niet een alternatieve naam).

Een alias heeft dus een andere betekenis afhankelijk van op welk modelelement het toegepast wordt? Dat lijkt mij niet wenselijk.

Momenteel wordt alias gemapt naar `skos:altLabel`. Dat zou goed passen op "de alternatieve naam".
Wel is het zo dat je vaak meer dan 1 alternatieve naam zou kunnen bedenken voor iets. Kan dat hier ook?

Vraag is dan wederom: Wat is de beoogde use case van dit metagegeven?

**Comment by lennartvanbergen-kadaster** [comment]
De essentie van waarom we dit metagegeven hebben is om de originele naam in natuurlijke taal te kunnen behouden wanneer we op logisch niveau of technisch niveau de naam naar een camelcase of andere case schrijfwijze omzetten en de spaties, diakrieten of andere onhandige tekens voor de techniek ertussenuit fietsen. 

Aangepast: 

**Voorstel voor 2.8.2.3 Metagegeven: Alias**

Definitie Alias 
De weergave van de naam van een modelelement in natuurlijke taal (niet technisch).

Toelichting:

Als de naam van iets wat in het informatiemodel gemodelleerd wordt spaties, diakrieten of verbindingstreepjes bevat, zoals een objecttype 'Onroerende zaak' of een attribuutsoort 'geïnspireerd op', dan kan er gekozen worden om deze naam in het informatiemodel zo op te schrijven dat hier in de techniek makkelijker mee te werken is. Denk aan: 'geinspireerd op' (geen diakrieten) of 'OnroerendeZaak' (camelcase notatiewijze). Wanneer de originele schrijfwijze in natuurlijke taal van belang is kan deze worden opgenomen in het metagegeven _alias_.  

Het is niet de bedoeling om (andersom) in de alias de technische makkelijkere naam op te nemen. 

De alias wordt ook gebruikt voor een alternatieve weergave van een enumeratie waarde. De ‘naam’ betreft hier een daadwerkelijk waarde, zoals 'Nederlands', waarin de naam gelijk staat aan de waarde en dit moet zo blijven, maar als er sprake is van een voor documentatie doeleinden bedoelde codering van deze enumeratie waarde dan kan deze code in de alias worden opgenomen. 

Toepassing: objecttype, attribuutsoort, gegevensgroep, relatiesoort, relatierol, relatieklasse en externe koppeling en (expliciet niet voor packages en Enumeratiewaarde) 

--
Einde voorstel 
--

Als iemand een betere term heeft, dat kan, dan horen we deze graag, maar dan moeten we dat in een y-versie van MIM verwerken. Maak dan een nieuw issue aan. 

--
Uitwerking in H3: alle modelelementen nalopen om te kijken of alias daar bij staat. Ten minste voor objecttype, attribuutsoort, relatiesoort, relatieklasse en externe koppeling, gegevensgroep, gegevensgroeptype.

**Comment by pmaria** [comment]
**Samenvatting:**

Indien `alias` gevuld wordt `alias` gebruikt als waarde voor `rdfs:label`.

Indien `alias` niet gevuld wordt `naam` gebruikt als waarde voor `rdfs:label`.

`skos:altLabel` wordt niet meer gebruikt.

---

## Voorstel:

**Aanpassing van [6.4.9.1 transformatie: naam](https://docs.geostandaarden.nl/mim/mim/#transformatie-naam):**

> De naam van een modelelement

Een `mim:naam` wordt in samenspel met `mim:alias` getranformeerd naar een `rdfs:label`.
Wanneer `mim:alias` gespecificeerd is voor het modelelement wordt de waarde van `mim:alias` gebruikt voor de waarde van `rdfs:label`. Zo niet, wordt de waarde van `mim:naam` gebruikt.

```sparql
CONSTRUCT {
  ?subject rdfs:label ?label
}
WHERE {
  ?modelelement mim:naam ?naam.
  OPTIONAL {
    ?modelelement mim:alias ?alias .
  } 
  ?subject mim:equivalent ?modelelement.
  BIND (COALESCE(?alias, ?naam) as ?label)
}
```

**Aanpassing van [6.4.9.2 transformatie: alias](https://docs.geostandaarden.nl/mim/mim/#transformatie-alias):**

> De weergave van de naam van een modelelement in natuurlijke taal (niet technisch).

Zie ([6.4.9.1 transformatie: naam](https://docs.geostandaarden.nl/mim/mim/#transformatie-naam)

**Comment by pmaria** [comment]
@architolk Zou jij https://github.com/Geonovum/MIM-Werkomgeving/issues/198#issuecomment-998727466 kunnen reviewen?

**Comment by lennartvanbergen-kadaster** [comment]
Misschien is alias niet helemaal een fijne term voor wat we ermee bedoelen, maar kan niet hier nu opgelost worden. Nieuw issue gemaakt: https://github.com/Geonovum/MIM-Werkomgeving/issues/208

**Comment by PalmJanssen** [comment]
Alias ontbreekt in hfst 3 bij:
- packages (informatiemodel, domein etc)
- keuze
- enumeratie
- enumeratiewaarde
- primitief datatype
- gestructureerd datatype
- data element
- constraint

in de UML diagrammen ontbreekt alias bij:
- enumeratiewaarde
- packages
- constraint


Voorstel overal alias toestaan behalve bij packages en enumeratiewaarde (waarom eigenlijk) en constraints.

**Comment by PalmJanssen** [comment]
Proces info:
- verwerkt in tekst hfst 2 en hfst 3.
- nog niet in hfst 4 verwerkt

**Comment by lennartvanbergen-kadaster** [comment]
Ja, is terecht dat het bij de items in die lijst ontbreekt.

**Comment by architolk** [comment]
@pmaria: jou voorstel zou ik zo 1-2-3 niet overnemen. Het is namelijk totaal niet duidelijk wat mim:naam en mim:alias precies betekenen. Hiervoor heeft Lennart een nieuw issue aangemaakt. In LD wordt het rdfs:label gebruikt als DE naam van een modelelement (klassen en eigenschappen). Soms wordt dat CamelCase gedaan, soms met diacrieten en soms zonder diacrieten. Dat hangt denk ik ook veel af of je het LD model als een niveau 2, 3 of 4 model leest. Maar in ieder geval zou ik zeggen: het geen je in een EA model in het "naam" veldje neerzet. Het EA alias veld is veel meer obscuur. Ik zou daar dus niet de rdfs:label inzetten, tenzij een overduidelijke definitie van "alias" is gegeven. Zo wordt bv ook door MIM gebruikers wel eens de alias gebruikt om de engelstalige term in te zetten... Zolang de Naamgevingsconventies niet formeel zijn gemaakt in MIM, lijkt me de huidige werkwijze prima: geen aanpassingen dan dus nodig aan de LD transformatie.

**Comment by architolk** [comment]
Aanvullend: ALS alias wordt bedoeld als de "voorkeursterm", dan zou hiervoor het veld skos:prefLabel gebruikt kunnen worden i.p.v. de skos:altLabel. Merk wel op dat de definitie van Alias in deze Z-versie (x.y.z) 180-graden gedraaid is, van "Alternatieve naam" naar "Naam die de voorkeur heeft, indien aanwezig". Wellicht is voor deze Z-versie beter om het veld Alias helemaal niet meer te vertalen, en meer fundamentele wijzigingen toe te passen in het andere issue van Lennart

**Comment by architolk** [comment]
Voorstel om de tekst van de definitie aan te passen: "De alternatieve weergave van de naam van een modelelement in natuurlijke taal (niet technisch)". Toevoeging dus van het woordje "alternatief". Immers: de "echte" naam is het veld mim:naam, dus dit is een alternatieve weergave.

**Comment by pmaria** [comment]
@architolk het voorstel was een zo nauw mogelijke afspiegeling van het [voorstel van Lennart](https://github.com/Geonovum/MIM-Werkomgeving/issues/198#issuecomment-984785365). Dat is volgens mij nog steeds het geval.

Op zich ben ik het grotendeels eens met je opmerkingen. We hebben eerder ook veel discussie gehad over `alias` en de  verschillende manieren waarop het nu gebruikt wordt.

> Het is namelijk totaal niet duidelijk wat mim:naam en mim:alias precies betekenen.

Inderdaad. Maar toch transformeren we het naar specifieke eigenschappen in Linked Data met een duidelijke betekenis. Momenteel is dat voor alias `skos:altLabel`. Dit past mijns inziens niet bij de beschrijving die Lennart gemaakt heeft.

Ook met jouw toevoeging van "alternatieve" is het gebruik van `skos:altLabel` hier in twijfel te trekken. Het gaat hier om een alternatieve weergave, of beter schrijfwijze (en ook nog eens de natuurlijke taal schrijfwijze ), en niet om een alternatieve term/naam. Het doel van alias lijkt hier zo specifiek te zijn dat het wellicht beter is om `mim:alias` niet te vertalen, maar over te nemen als eigenschap.

**Comment by lennartvanbergen-kadaster** [comment]
Het is mijn inziens wel duidelijk, je kan het alleen niet reverse engineeren vanuit EA kennis. 

Waar het om gaat is dat we de naam in natuurlijke taal willen bewaren wanneer iemand in een logisch model er een technische naam van maakt. 

Dus, als je de normale naam van het ding/onderwerp wilt weten: 
ALS de alias niet is gevuld: neem de naam van het modelelement.
ALS de alias wel is gevuld: neem de naam die in de alias staat. 

Zo is het bedoeld. 

In LD zou ik daarom zeggen: 
gebruik voor de voorkeursnaam altijd de naam in natuurlijke taal 
gebruik als alternatieve naam de technische schrijfwijze, als daar sprake van is. 

Wellicht heeft LD geen notie van namen en een technische schrijfwijze voor "dezelfde" naam, maar ik kan me goed voorstellen van wel want in een URI gebruik je ook een naam en dat is degene in een technische schrijfwijze.

**Comment by architolk** [comment]
@pmaria : het overnemen van mim:alias as is vind ik een mooie uitkomst van deze discussie. Inderdaad is de onduidelijkheid over de betekenis van mim:alias dusdanig dat het beter is om deze niet te willen vertalen naar wat dan ook.

**Comment by lennartvanbergen-kadaster** [comment]
De definitie van alias is heel helder, hier staat altijd en alleen de normale schrijfwijze in. Wat is hier onduidelijk aan?

De eis is dat het in het LD model geheel duidelijk is waar de naam in de gewone schrijfwijze te vinden is en waar de naam in camel-case. En niet: dat hangt af van wat iemand in het informatiemodel bij de naam van het model element gebruikt. 

Aan de UML kant is dit heel helder aan te geven. Als dit in LD niet kan, en het daarom onduidelijk is, dan zij het zo.

**Comment by lennartvanbergen-kadaster** [comment]
mim:naam is inderdaad gewoon de naam van het modelelement ("in H2") . 

Dus aan de LD kant (in H4) is er geen issue.

Er is mogelijk zelfs geen behoefte om de technische(re) naam onder te brengen in LD (?)

Denk aan, heel losjes geformuleerd, een: 
`mim:naam-technische-schrijfwijze` of `mim:naam-logisch` 
 
(als die behoefte er wel is, dan ontbreekt in H2 nog een plek om de technische schrijfwijze van het modelelement in onder te brengen) 

--

Misschien zie ik dan een issue op de export van een UML model in relatie tot LD, wanneer het UML model naar LD wordt getransformeerd (via H2, niet rechtstreeks van H3 naar H4). 

Bij deze export zou de normale schrijfwijze dan in de export terecht moeten (kunnen) komen als mim:naam, zodat deze te mappen is naar de mim:naam en naar LD:preflabel. 

In UML modelleer je mim:naam in: 
- UML:name als deze de normale schrijfwijze bevat 
OF in 
- UML:alias als de alias normale schrijfwijze bevat, en in de UML:name staat dan de technische schrijfwijze 

Volgens het eerder beschreven algoritme, maar dit is dan een intern stukje mapping van een UML model naar een MIM export, komt dan afhankelijk van de situatie de normale schrijfwijze terecht in de export als mim:naam. 

Waarbij de vraag voor LD dan alsnog ook is: is er behoefte aan de wat technischere naam? Want aan de UML kant is deze data voorhanden in de export, er is alleen nog geen mim:technische-schrijfwijze-naam en dus ook nog geen mapping hiernaartoe.

**Comment by lennartvanbergen-kadaster** [comment]
Eens met dat alias in LD een losse eigenschap (metagegeven/"tagged value") wordt. 

In UML hoofdstuk is nog toegevoegd dat je beide kan gebruiken en dat er hetzelfde modelelement mee bedoeld wordt, waarbij alleen de schrijfwijze anders is, maar wel echt hetzelfde woord wordt bedoeld.
