### ISSUE TITLE
Toelichting niet overal mogelijk waar die verwacht wordt

### ISSUE THREAD

**Issue by RuudKathmann** [Geonovum/MIM-Werkomgeving#199]
Bijvoorbeeld het metagegeven “Toelichting” staat als volgt gedefinieerd:

![image](https://user-images.githubusercontent.com/53537350/145880569-3bfdf3c2-51c7-4324-979d-7042ee60f83e.png)

Nu willen wij binnen het IMWOZ keuzes zowel voorzien van een definitie als een toelichting. Volgens de beschreven toepassing zou dat moeten kunnen.

Maar bij de opsomming van de tagged values van Keuze staat wel de definitie, maar niet de toelichting.

![image](https://user-images.githubusercontent.com/53537350/145880721-58c7b00e-d824-446e-bd4b-4cd7bcf26722.png)
 
We kunnen onze toelichtingen dus niet kwijt. 

Datzelfde probleem hebben we bij relaties:
 
![image](https://user-images.githubusercontent.com/53537350/145880769-c8854ee0-24f4-4306-acc9-c650356427cb.png)

![image](https://user-images.githubusercontent.com/53537350/145880849-9c9efd59-db32-4855-b43a-8511d2c24fa2.png)

Het zou mooi zijn als we op meer plaatsen een toelichting zouden kunnen geven.

**Comment by lennartvanbergen-kadaster** [comment]
Toelichting is in principe bedoeld op alle plekken waar een definitie ook aan de orde is. Mogelijk dat dit ergens vergeten is om door te voeren. Je kan altijd met de hand overigens een tagged value Toelichting toevoegen, als tijdelijke workaround.

**Comment by lennartvanbergen-kadaster** [comment]
Verwacht wordt: 
per modelelement waarbij de betekenis van data wordt gedefinieerd: 
- een definitie 
- een toelichting op de definitie
- een herkomst van de definitie 
- 
(herkomst zelf heeft meer te maken met een domein aanduiding en niet met de betekenis van data dus deze laat ik hier even buiten beschouwing) 

Modelelementen met een definitie, maar zonder een toelichting: 

3.2.2.1 Relatiesoort is leidend (alternatief 1)
Relatierol 
+ toelichting 
+ herkomst definitie 

3.2.2.2 Relatierol is leidend (alternatief 2)
Relatiesoort
+ toelichting 
+ herkomst definitie 

Relatierol 
+ toelichting 

Relatieklasse 
+ toelichting 
+ herkomst definitie 

Externe koppeling 
+ definitie 
+ toelichting 
+ herkomst definitie 

Referentielijst 
+ herkomst definitie 

Referentie element 
+ herkomst definitie 

Codelijst --> heet nog codelist, moet codelijst zijn 
+ toelichting 
+ herkomst definitie 

Primitief datatype, gestructureerd datatype, data element, keuze,  
+ toelichting 
+ herkomst definitie 

Enumeratie 
+ herkomst definitie 
+ toelichting 

Enumeratiewaarde 
+ herkomst definitie 
+ toelichting 

--
Bij packages heb ik eigenlijk het idee dat definitie hier niet de juiste match is. Liever zie ik hier alleen: omschrijving. 

Voor een z-versie kunnen we dit niet gaan aanpassen. Ik stel voor dat we een keuze maken tussen:
- nu even niks aanpassen 
- vanwege consistentie hier definitie laten staan en toelichting en herkomst definitie en herkomst verwachten 
- we hier omschrijving en herkomst verwachten en dit toevoegen en als tip geven: gebruik de definitie hiervoor maar niet meer.

**Comment by lennartvanbergen-kadaster** [comment]
@PalmJanssen eens? Dan komt dit er ook bij in het diagram van de metadata gegevens.

**Comment by PalmJanssen** [comment]
Lijkt me prima. Omdat Imvertor een standaard catalogus genereert kan met de Tagged Value Toelichting bij al deze elementen het gebruik worden toegelicht.

**Comment by PalmJanssen** [comment]
Proces informatie:
- toegevoegd aan UML diagrammen

**Comment by ArjanLoeffen** [comment]
Toelichting komt dus op alle modelelementen hieronder, net zoals deze Definitie hebben, maar overal optioneel: Graag jullie okay zodat we dat kunnen overnemen in Imvertor OS.

- Objecttype
- Attribuutsoort
- Gegevensgroeptype
- Relatiesoort
- Referentielijst	
- Referentie element
- Codelijst
- Gegevensgroep
- Relatierol
- Relatieklasse
- Enumeratie
- Primitief datatype
- Gestructureerd datatype
- Keuze
- Data element
- Datatype
- Enumeratiewaarde

**Comment by RuudKathmann** [comment]
Lijkt mij een mooie oplossing.

Wat ons betreft Okay

**Comment by PalmJanssen** [comment]
> Toelichting komt dus op alle modelelementen hieronder, net zoals deze Definitie hebben, maar overal optioneel: Graag jullie okay zodat we dat kunnen overnemen in Imvertor OS.

Hier wordt aan gewerkt. Je vergeet nog externe koppeling

**Comment by lennartvanbergen-kadaster** [comment]
@ArjanLoeffen niet op alles wat een definitie heeft, voor packages namelijk niet. De rest wel inderdaad. Zie lijst.

**Comment by ArjanLoeffen** [comment]
Ik heb nu twee dingen doorgevoerd.

1/ 
In de MIM 1.1 standaard is nu de toelichting toegestaan op alle elementen zoals eerder in dit issue beschreven. Nergens verplicht.

2/ 
In MIM 1.1 documentatie is de toelichting op alle elementen getoond waar ook een definitie kan worden getoond.

Achtergrond:
De documentatie voor Waarderingskamer volgt een "standaard" MIM 1.1 documentatievorm. Deze is ook onderdeel gemaakt van MIM 1.1 configuratie. Dit is meer een "afspraak" die we maken mbt. hoe je MIM 1.1 modellen in documentatie kunt omzetten.

In deze documentatievorm heb ik nu te toelichting opgenomen op alle constructies die ook een definitie kunnen hebben. dat kunnen we fijner uitwerken, maar daarmee is nu de WK geholpen. Als iemand ergens géén toelichting opneemt wordt deze ook niet getoond (het veld is ook niet "leeg") in de documentatie.

**Comment by architolk** [comment]
Nog wel een klein dingetje: dit issue lijkt iets meer op te pakken dan alleen toelichting waar ook een definitie was. Er zijn (lijken?) ook definities bij te zijn gekomen waar ze er eerst niet waren. Aangezien definitie (normaal gesproken) verplicht is, lijkt me dat een breaking change? Ik zou voorstellen om het daar OF niet te doen, OF overal optioneel. Zelfde geldt overigens ook voor herkomst en herkomst-definitie

**Comment by ArjanLoeffen** [comment]
> Nog wel een klein dingetje: dit issue lijkt iets meer op te pakken dan alleen toelichting waar ook een definitie was. Er zijn (lijken?) ook definities bij te zijn gekomen waar ze er eerst niet waren. Aangezien definitie (normaal gesproken) verplicht is, lijkt me dat een breaking change? Ik zou voorstellen om het daar OF niet te doen, OF overal optioneel. Zelfde geldt overigens ook voor herkomst en herkomst-definitie

@architolk Dat is wel iets, als we in Imvertor een (herkomst) definitie opnemen waar die niet thuishoort. Als ik het goed zie gebeurt dat niet. Geef anders even aan waar dat gebeurt. Ik heb de configuratie gehouden tegen MIM 1.2, omdat dat toch de variant wordt die we gaan hanteren (?) en we geen klachten krijgen op huidige 1.1.1.
