### ISSUE TITLE
TV "Locatie" beter vaststellen

### ISSUE THREAD

**Issue by ArjanLoeffen** [Geonovum/MIM-Werkomgeving#2]
Locatie moet kunnen worden bepaald voor codelijsten en referentielijsten. Waar vind je de betreffende codes/waarden?

In MIM is nu vastgesteld:

- Locatie is op attribuutsoort optioneel.
- Locatie is op codelist verplicht.
- Locatie is op referentielijst niet opgegeven (ik neem aan verplicht?).

Hoe moet ik dat opvatten? Volgens mij is er iets mis. Ik zou zeggen: alles optioneel, met een extra regel dat óf op de attribuutsoort, óf op het type van de attribuutsoort de locatie moet zijn opgegeven.
 
ps. ik kijk nog naar versie 1.0 14 juni 2017

**Comment by lvdbrink** [comment]
Dat Locatie ontbreekt op Referentielijst in MIM is raar; ook bij een Referentielijst wil je kunnen aangeven wat de locatie ervan is.

**Comment by PalmJanssen** [comment]
zie ook #24

**Comment by architolk** [comment]
Dit issue heeft veel samenhang met issue #24. Zou kunnen dat dit issue is opgelost met de oplossing van issue #24. Blijft wel dat voor Arjen L. het "probleem" is dat hij niet weet wat de opmaak van de betreffende waardelijsten is: wat voor formaat zijn die waardelijsten daar dan beschikbaar? Zie ook issue bij de transformatie naar RDF. Ik denk dat het wenselijk is om aanvullende informatie toe te voegen, zodat duidelijk is wat het formaat is van de externe plek (bv genericode, rdf, etc.)

**Comment by lennartvanbergen-kadaster** [comment]
Ja, is clone van #24
