### ISSUE TITLE
Geen beschrijving voor metagegevens populatie en kwaliteit

### ISSUE THREAD

**Issue by joerivanes** [Geonovum/MIM-Werkomgeving#201]
Er staat op dit moment geen beschrijving voor populatie en kwaliteit in [Paragraaf 2.8](https://docs.geostandaarden.nl/mim/mim/#specificatie-metagegevens) van MIM. Graag toevoegen, want kan erg bruikbaar zijn om de scope van een model in vast te leggen.

**Comment by lennartvanbergen-kadaster** [comment]
@PalmJanssen kan deze nog mee? Het is weinig werk, maar het is ook bijna kerst... de definities staan al in H3 en ze zijn al uitgewerkt in H3 en H4.

**Comment by PalmJanssen** [comment]
komt in orde

**Comment by dkrijtenburg-GNM** [comment]
check of dit niet al in mim 1.1.1 is opgenomen

**Comment by Gtrouborst** [comment]
Populatie en kwaliteit documentair consistenter gemaakt. Een aantal voorbeelden toegevoegd om aan te geven hoe populatie bedoeld is.
