### ISSUE TITLE
Verwijzen van informatiemodel naar model van begrippen 

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/MIM-Werkomgeving#21]
Het wordt steeds meer gebruikelijk dat een informatiemodel zelf geen concepten definieert maar toepast. Dus voor objecttype concepten gebruikt uit bijvoorbeeld een conceptenbibliotheek. Er is nu nog geen plaats om de locatie (uri) van het concept op te nemen.

Voorstel:
voeg een tagged value: 'conceptverwijzing' toe.

**Comment by PalmJanssen** [comment]
Uitwerking in 20180321 MIM-KKG - link tussen model van begrippen en IM (concepten) - final.pdf

**Comment by dkrijtenburg-GNM** [comment]
zie ook #29

**Comment by PalmJanssen** [comment]
Voorsteloplossing:

Creeer een metadata element ‘begrip’:
Metadata element: begrip
Kardinaliteit: 0..*. 
Beschrijving: verwijzing naar een begrip. De verwijzing heeft de vorm van een term of een URI.

Koppel dit metadata element aan:
Objecttype,
Attribuutsoort
relatiesoort
Relatierol
Gegevensgroep
Data element
Enumeratiewaarde
Referentie element
Union element

**Comment by dkrijtenburg-GNM** [comment]
Ter consultatie:
**Onderwerp**:
Er is behoefte aan: 
1.	Specificeren van de traceerbaarheid vanuit een IM naar concepten uit het model van begrippen.
 Dit is typisch gewenst wanneer er eerst een begrippenkader met concepten (skos:concepts) zelfstandig wordt opgesteld. We noemen dit in MIM een model van begrippen (voor de uitleg van deze term, zie §1.5 van MIM versie 1.0). Vervolgens worden deze begrippen gebruikt om handmatig te vertalen/modelleren naar/tot een IM. Dit is onder andere nodig is voor Kadaster en voor DSO. 

2.	Het automatisch genereren van een begrippenkader c.q. model van begrippen, vanuit het IM. 
Dit ten behoeve van de conceptenbibliotheek van Geonovum. Daarin worden momenteel informatiemodellen ingeladen, maar de intentie is om ook concepten (skos:concepts) te presenteren, zoals bedoeld in wat MIM/KKG een model van begrippen noemt. Dit is nodig voor Geonovum. 

**Oplossing**:

Metadata element: begrip
Kardinaliteit: 0..*. 
Beschrijving: verwijzing naar een begrip, vanuit een modelelement. De verwijzing heeft de vorm van een term of een URI. Voor meer informatie, zie hoofdstuk 3. 
UML 2.5: UML-Property. 

Voetnoot bij kardinaliteit *: het metadata element wordt meerdere malen opgenomen. 
Voetnoot bij representatie in Enterprise Architect: tagged value. Dit is net zoals bij alle andere tagged values. 

MIM Hoofdstuk 3

Verwijzing van een modelelement naar een begrip 

Het metadata element “begrip” uit paragraaf 2.3 is bedoeld om de traceability tussen een modelelement in een IM en een begrip uit een model van begrippen (zoals bedoeld in paragraaf 1.5) te borgen. Anders gezegd, om aan te geven dát een modelelement een weergave is van het betreffende begrip op IM niveau. Het begrip zelf is opgenomen in een model van begrippen. Aldaar is meer informatie te vinden over het begrip zelf. De verwijzing geeft aan dat het model element op informatiemodel niveau een invulling geeft aan het begrip.

In de definitie van metadata begrip staat dat de verwijzing de vorm heeft van een term of van een URI. 
•	Als je kiest voor een term, vul dan de naam in van het begrip. Bijvoorbeeld: Natuurlijk persoon. Geef indien mogelijk ook deze naam een goede plek in de definitie en/of toelichting van het modelelement.    
•	Als je kiest voor een URI, kies dan voor de URI dat dit begrip identificeert. Deze zal verwijzen naar een skos:Concept . Dit houdt in dat als iemand naar deze URI gaat (bijvoorbeeld met een browser, dit wordt “het resolven van een URI” genoemd), deze persoon informatie krijgt over het betreffende begrip. Bijvoorbeeld: http://brk.basisregistraties.overheid.nl/id/begrip/Perceel 

Veelal betreft één modelelement één begrip . De verwijzing naar dit begrip wordt dan opgenomen in deze metadata. 

Het metadata element begrip mag achteraf toegevoegd worden. Het is immers mogelijk dat bijvoorbeeld het informatiemodel eerder opgesteld wordt dan het model van begrippen, of dat het initieel niet bekend is wat van een modelelement het bijbehorende begrip is, of dat een model van begrippen uitgebreid wordt met een extra begrip. Het criterium om een begrip op te nemen in een model van begrippen is geen onderdeel van dit metamodel. Het is zelfs mogelijk dat een modelelement initieel niet als een begrip gezien wordt, maar dat het modelelement op een gegeven moment zodanig een begrip wordt, dat deze wordt opgenomen in het model van begrippen. In alle gevallen geldt, neem de metadata op zodra dit mogelijk is. Als het metadata element begrip wordt weggelaten, of de metadata die erin op genomen kan worden wordt leeggelaten c.q. de verwijzing naar het begrip (nog) niet gemaakt kan worden, dan is de betekenis hiervan dat het niet bekend is of er sprake is van een begrip.

Het is zeker niet zo dat elk modelelement een begrip is in het model van begrippen. Het metadata element mag weggelaten worden en de metadata mag leeggelaten worden. Vaak kan bij objecttypes en attribuutsoorten wel een verwijzing opgenomen naar een begrip en is dit niet zinvol bij datatypen, maar dit is geen harde regel. Bijvoorbeeld: een koopsom van een huis wordt uitgedrukt met een bedrag. In het domein is de koopsom wel een begrip, maar het modelelement bedrag bijvoorbeeld niet. Valuta is dan zeker geen begrip, en een euro al helemaal niet. In dit geval wordt het metadata element begrip weggelaten, omdat euro niet als zodanig terugkomt in het bij het IM behorende model van begrippen. Merk hierbij op dat het metadata element begrip een ander metadata element is dan het metadata element definitie. Bij het metadata element definitie kan in de beschrijving natuurlijk wel gebruik gemaakt worden van een URI, om te verwijzen naar de internationaal gepubliceerde definitie. 

Bij het opnemen van het begrip is het van belang om zeer zorgvuldig te zijn. Bijvoorbeeld: het kan zijn dat in het model van begrippen een Natuurlijk persoon en een Niet natuurlijk persoon zijn opgenomen, terwijl in het informatiemodel alleen het modelelement Persoon is opgenomen, alsmede een attribuutsoort ‘type’, waarbij het datatype een waardenlijst is, met als mogelijke waarden ‘NP’ en ‘NNP’ en ‘overig’. De verwijzing naar het begrip Natuurlijk persoon hoort in dit geval gelegd te worden vanuit de waarde ‘NP’ en niet vanuit het modelelement Persoon.  

Aanbeveling: de verwijzing vanuit het eigen informatiemodel naar een begrip is altijd een verwijzing naar een begrip dat behoort tot het eigen model van begrippen. Voor begrippen die domein specifiek zijn is dit altijd zo en zal de aan URI van het begrip ook te herkennen zijn dat dit zo is. Er zijn echter situaties denkbaar waarin een begrip een URI heeft die extern is aan het eigen model van begrippen. Het begrip is dan klaarblijkelijk wel relevant voor het eigen domein, en behoort daarom dan ook tot het eigen model van begrippen, ondanks dat de URI extern is. Een externe URI komt bijvoorbeeld voor als het eigen informatiemodel modelelementen uit een ander informatiemodel heeft overgenomen, zoals bedoeld bij het stereotype «view» of «extern». Of bijvoorbeeld omdat het begrip weliswaar in gebruik is binnen het eigen domein, maar ontleent is aan een ander domein c.q. een ander model van begrippen, met als doel om aan te geven dat de betekenis gelijk is. Dit is mogelijk en toegestaan. In de praktijk wordt een begrip dat ontleend is van een ander model van begrippen echter veelal met een eigen URI en een eigen beschrijving opgenomen in het eigen model van begrippen. Dit komt doordat in het eigen domein meestal op een eigen manier tegen het begrip wordt aangekeken, of omdat het niet de bedoeling is dat het eigen model van begrippen automatisch meebeweegt zodra de definitie uit het andere domein verandert. Merk op dat het MIM niet gaat over hoe een model van begrippen wordt gemodelleerd.

**Comment by dkrijtenburg-GNM** [comment]
Achtergrondinformatie : 
https://github.com/Geonovum/MIM-Werkomgeving/blob/master/Werkversie/MIM%201.1%20in%20wording/Verzoek/begrip/20180410%20MIM-KKG%20-%20link%20tussen%20model%20van%20begrippen%20en%20IM%20(concepten)%20-%20final%201.01.docx

**Comment by ArjanLoeffen** [comment]
Mee eens.

Toevoeging: 
De wijze waarop een begrip als term zich verhoudt tot een link (van term naar weblocatie of ID) is onderdeel van de extensie. Het staat dus in de MIM standaard "vrij" dit in de vullen; in de extensie leggen we vast hoe dat begrip wordt vertaald naar een URI oid..

De validatie van de term en/of URI valt buiten de MIM standaard. Er zijn dus in de MIM standaard géén regels vastgelegd. (Of willen we expliciet naar de Overheids URI strategie verwijzen? Ik zou dat vermijden.)

**Comment by GeraldGrootRoessink** [comment]
Goed idee om verwijzingen naar begrippen (a.k.a skos:Concept) op te nemen. Ik verwacht dat dit overheidsbreed semantische harmonisatie helpt mogelijk maken.  

Wel een vraag: hoe gaan we om met het MIM-elementkenmerk "definitie" in een informatie/datamodel in relatie tot de skos:definition en andere noteringen bij een begrip. In het beste geval zijn is de semantische inhoud dubbel en in het slechtste geval tegenstrijdig. We hebben denk ik invoerinstructie nodig.

**Comment by jacblom** [comment]
Namens Han Welmer:

Wat is in dit kader nog het doel van de tagged values ' Definitie'  en ' Bron definitie'?
Als dit niet samenvalt met de verwijzing naar 'Begrip', dan eens met het voorstel.

**Comment by lennartvanbergen-kadaster** [comment]
Ik zie geen bezwaren, maar wel een vraag t.b.t. 

Ten aanzien van definities in het semantische model: het semantische model heeft in principe eigen definities. Deze tekst die in de definitie staat kan je integraal overnemen naar je informatiemodel, als deze 1 op 1 geschikt is. Maar dat is beheer, 

In de basis is een skos:definition de definitie van een concept. De mim definitie is de definitie van het informatiemodel element. Beide hebben bestaansrecht, en kunnen van elkaar afwijken. Ook kan de definitie van een skos concept anders in elkaar steken of apart aangepast worden, zonder dat ... etc. 

Beheermatig zou je inderdaad de begrip link kunnen volgen en de tekst integraal overnemen naar je informatiemodel, maar dat is een keuze van de beheerder. 

Dit gezegd hebbende, wellicht kan de toelichting beter. Zijn er tekstverbeteringen nodig? Zo ja, dan graag een suggestie.

**Comment by lennartvanbergen-kadaster** [comment]
Toepassing: alle modelelementen met een naam, behalve constraint. 

Voor datatypen zal het doorgaans niet ingevuld worden, voor waardelijsten die een ontologische typering aangeven/willen behouden voor het objecttype (zonder subtyperingen) kan  per waarde in de waardelijst een begrip gekoppeld worden. Omdat de waardelijst buiten het model gedefinieerd wordt, worden de begrippen bij de waardelijst bijgehouden, en niet bij de waardes in de waardelijst.

**Comment by lennartvanbergen-kadaster** [comment]
Voor packages ook niet relevant. 

TODO: uitzoeken of het voor enumeratie waarden wel kan worden opgenomen. Zeker als de voorkeurs modellering van dergelijke typeringen een enumeratie is.

**Comment by lennartvanbergen-kadaster** [comment]
Deze is verwerkt. In Algemeen, in UML en in Nadere afspraken en Regels. Ik heb deze niet verwerkt in LD. Dit laat ik aan @architolk over. Nog niet deze sluiten dus.

**Comment by architolk** [comment]
Verwerkt in LD versie.
