### ISSUE TITLE
Metagegevens relatiesoort en externe koppeling - dezelfde hanteren 

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#225]
Voor externe koppeling wil je ook historie kunnen aangeven en of het aan aggregatie relatie is enz. Het lijkt dus nuttig om de metagegevens gelijk te trekken (even wel nagaan of dat echt met alle is of met de meeste).

**Comment by lennartvanbergen-kadaster** [comment]
Voorstel: allemaal gelijk.

**Comment by PalmJanssen** [comment]
Eens en verwerkt:

![image](https://user-images.githubusercontent.com/9932784/150529763-83522bf3-a017-474a-9dc8-f43c0452f48e.png)

**Comment by ArjanLoeffen** [comment]
Wordt ook verwerkt in Imvertor OS support voor MIM 1.1.1 en daarmee in 1.2.
