### ISSUE TITLE
hoe toevoegen locatie bij/van waardelijst (bij attribuutsoort union-element en data-element)?

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/MIM-Werkomgeving#24]
Via Peter Lentjes

Stereotype `<<Attribuutsoort>>` heeft een tagged value “Locatie”. Maar `<<Union element>>` en `<<Data element>>` hebben dit niet.
Maar attributen van een `<<Union>>` en `<<Gestructureerd datatype>>` kunnen ook een generieke waardelijst als type hebben, waarbij je de Locatie niet op kunt nemen bij het `<<Referentie lijst>>` element.

Denk aan `<<Gestructureerd datatype>>` TypeOppervlak (from Datatypen OnroerendeZaak) met  attribuut `<<Data element>>` soortGrootte.
`<<Data element>>` soortGrootte is van het type WaardeLijst (dus niet WaardeLijstSoortGrootte).  De locatie van de waardelijst kun je niet opnemen bij `<<Referentie lijst>>` Waardelijst, Dus moet het bij `<<Data element>>` soortGrootte. 

Daarom in KKG graag tagged value “Locatie” toevoegen aan `<<Union element>>` en `<<Data element>>` (zoals bij `<<Attribuutsoort>>`).

**Comment by dkrijtenburg-GNM** [comment]
ter consultatie
**onderwerp**:
hoe toevoegen locatie bij/van waardelijst (bij attribuutsoort union-element en data-element)?

De tagged value ‘locatie’ bij <<Attribuutsoort>> wordt gebruikt om ‘Als het type van het attribuutsoort een waardenlijst is, dan wordt hier de locatie waar deze te vinden is opgegeven.’

Voor <<Data element>> en <<Union element>> is deze mogelijkheid er nu niet. Het is bij deze elementen net zo goed mogelijk om een waardelijst als waardetype te hebben. Het is wat dat betreft correct om de tagged value ‘locatie’ toe re voegen aan deze elementen.

Maar het is eigenlijk vreemd dat de locatie van een waardelijst als meta-informatie bij een attribuutsoort is opgenomen. Het is namelijk meta-informatie behorend bij de waardelijst. <<Referentielijst>> heeft nu geen tagged value ‘locatie’. <<codeList> heeft het weer wel.


**oplossing**:
1) Neem ‘locatie’ alleen op bij elementen waarvan de inhoud extern (op een url) gepubliceerd wordt. Dit zijn <<CodeList>> en <<Referentielijst>>.
2) Verwijder ‘locatie’ bij <<Attribuutsoort>>

Tekstaanpassingen.
Voeg locatie toe bij tabellen van referentielijst en codelist.

UML aanpassingen: niet nodig. Locatie was al opgenomen in het UML model

EA-UMLprofiel aanpassingen: geen

**Comment by ArjanLoeffen** [comment]
Dick je bijdrage is niet leesbaar vanuit markdown. Graag editen.

**Comment by ArjanLoeffen** [comment]
Ter overweging:

@PalmJanssen stelt voor locatie bij attribuutsoort te verwijderen. In dat geval is het niet meer mogelijk standaard ontworpen waardenlijsten van een eigen locatie te voorzien per gebruikscontext, lees: attribuut. 

Mijn gevoel zegt dat het beter is wel een locatie van een lijst per attribuut op te geven.  Kadaster hanteert deze methode nu ook; lastig voor hun om dan zonder veel aanpassingen te voldoen aan de MIM standaard. (Er zijn dan dus meerdere soorten lijsten, en evenzoveel of méér locaties waar de data van die lijsten te vinden is. )

**Comment by RuudKathmann** [comment]
Het voorstel om locatie alleen toe te passen bij <<Codelist>> en <<Referentielijst>> en dus te schrappen bij <<attribuutsoort>> lijkt mij logisch. Het handhaven van <<attribuutsoort>> kan er denk ik toe leiden dat er strijdige verwijzingen komen, doordat vanuit <<attribuutsoort>> bijvoorbeeld verwezen wordt naar een oudere versie van een referentielijst dan bij de referentielijst. Datzelfde kan gebeuren wanneer vanuit twee attribuutsoorten de intentie is om dezelfde referentielijst te gebruiken, maar bij elk van de attribuutsoorten staat een andere locatie.

Ik ben dus gevoelsmatig voor het voorstel en deel de zorg van Arjan niet.

**Comment by jacblom** [comment]
Namens Han Welmer:

Eens met het voorstel om tagged value Locatie te verwijderen bij <<Attribuutsoort>> en alleen toe te laten bij <<Codelijst>> en <<Referentielijst>> en vooral de opmerking van Ruud.

**Comment by architolk** [comment]
Verwijderen bij <<attribuutsoort>> is ook wenselijk vanuit de transformatie naar het RDF model. In het RDF model is het onlogisch dat dit op het niveau van de attribuutsoort moet gebeuren, omdat het (zoals Paul al heeft aangegeven) geen eigenschap is van de attribuutsoort, maar van het datatype.

**Comment by PalmJanssen** [comment]
**Behandeling pre-consultatie:**
Dank voor het commentaar.

Opmerking:
De \ voorafgaand aan < is het escape teken om \<\<.....\>\> in de tekst te laten verschijnen
\<\<stereotype\>\>

De ingebrachte observaties zijn besproken. Conclusie is:
- locatie opnemen bij de Waardelijst.
- locatie (van de waardelijst) weghalen bij attribuut.

Locatie is daarmee een eigenschap van een Waardelijst. Als een attribuut een andere toepassing, deelverzameling of wat dan ook van dei Waardelijst nodig heeft, is dat in het model een andere lijst  (met een in die lijst opgenomen locatie).
