### ISSUE TITLE
Multipliciteit van Metagegeven Alias

### ISSUE THREAD

**Issue by joerivanes** [Geonovum/MIM-Werkomgeving#240]
Een Alias mag volgens de MIM standaard maar 1 keer voorkomen. In best veel gevallen zou het echter wenselijk kunnen zijn om meerdere aliassen op te nemen. Bijvoorbeeld wanneer de naam in meer dan 2 talen moet worden opgenomen en er ook nog naar de naam wordt verwezen met een afkorting.

Suggestie: Multipliciteit alias aanpassen naar [0..*]

**Comment by lennartvanbergen-kadaster** [comment]
Alias is sinds MIM 1.1.1. aangescherpt/verduidelijkt. 

Alias is (alleen) bedoeld om de normale, niet technische schrijfwijze van de naam van een modelelement in op te geven wanneer de naam van het model element in het model een technische schrijfwijze heeft gekregen en de normale, niet technische schrijfwijze anders verloren zou gaan. 

Het is niet bedoeld om er een synoniem of meertaligheid te ondersteunen. 

Als die wens, hoe maak ik mijn model meertalig, bestaat dan kan je ofwel zelf een goede mogelijkheid bedenken, ofwel de wens indienen, liefst beide.

**Comment by dkrijtenburg-GNM** [comment]
vervalt mogelijk volgens Lennart, check of het al opgelost is in MIM 1.1.1

**Comment by joerivanes** [comment]
In dat geval dekt Alias blijkbaar niet de gehele lading van wat gebruikers voor metagegevens willen opnemen bij hun model. Ik zal een wens hiervoor indienen.

**Comment by lennartvanbergen** [comment]
#291 is een vervolg op deze, met daarin de wens. Daar zal het vervolg vandaar komen. 

De verheldering van hoe de alias bedoeld is en dus ook de genoemde wensen niet invult is al doorgevoerd in 1.1.1. (alsmede, we schrijven in een standaard niet limitatief op wat we zoal niet bedoelen).

Rest ons slechts om dit issue te sluiten.
