### ISSUE TITLE
MIM serialisatie: MIM kent geen "Interfaces".

### ISSUE THREAD

**Issue by ArjanLoeffen** [Geonovum/MIM-Werkomgeving#242]
mim-ref:Interface interfaces kent MIM niet. Link met conceptual schema’s. Welke CharacterString dan? Hoe maken we dit fijn voor developers.

Zie ook #197

**Comment by ArjanLoeffen** [comment]
Interfaces kunnen eigenlijk “alles” representeren. Wanneer dat wordt aangetroffen worden (in Imvertor context) de conceptual schema’s geraadpleegd. Als info over de interface beschikbaar is (en dat moet eigenlijk wel, anders is het een fout) kan datgene wat de interface representeert worden ingevoegd op die plek. Dat kan een MIM construct zijn zoals een datatype (wat het eigenlijk altijd is), maar ook iets anders, wat niet per definitie conform MIM is. Op deze manier is het wellicht mogelijk interfaces “op te lossen”. Vraag is of dat ook de bedoeling is van de MIM serialisatie; het trekt dan dus info naar binnen die niet in het IM zelf zichtbaar/beschikbaar is.

**Comment by lennartvanbergen-kadaster** [comment]
Enerzijds gaat dit punt over: leuk dat er interface staan, maar de interface kan niet worden resolved. De gekozen implementatie van de interface staat nergens beschreven. 

Anderzijds gaat dit over: wat moet een ontwikkelaar met Interface ... 

Het informatiemodel zal zelf de technische implementatie van de interface ook niet weten ... dus de gebruiker van de mim-export moet dus in zijn eigen implementatie zelf eigen keuzes maken EN aparte software schrijven om om te gaan met interfaces. Dit lijkt onnodig veel werk en we willen drempels wegnemen. 

Met name omdat een interface kiezen toch ergens moet gebeuren in de client software is het niet nodig om in de MIM export XML hier val mee geconfronteerd te worden.  

Denkrichting 1; maak er gewoon xs:string van en xs:integer enz. in de mim-export XML. Degene die de mim-export XML inlees met software kan dit zelf mappen naar de implementatie die hij in zijn oplossing wilt gaan toepassen, zoals Long of Integer of integer of BigInteger of wat dan ook. Meestal wordt er een veilig type gekozen met genoeg ruimte erin, of als er een length is aangegeven kan daar rekening mee gehouden worden.

**Comment by ArjanLoeffen** [comment]
De standaard is n.m.m. niet expliciet over de rol van externe packages. Er wordt wel gesteld dat die bestaan, en "dat er iets in zit", en dat je dat kunt kopiëren naar je eigen UML model (sic). Maar dat is de helft van het verhaal. In je model wil je verwijzen naar de constructies in dat externe model. En je kunt dat doen middels typering of relaties. Dus gelden alle regels die bestaan voor constructies die we kunnen relateren en typeren in MIM 1.1.* óók voor de constructies in een extern model.

Het is dan raar om die externe constructies niet te representeren als "iets uit een extern model en mogelijk een onbekende modelleringswereld" . Destijds hebben we dat "interface" genoemd, zou ook "plaatsvervanger" kunnen zijn. Het is een "stub" (zo heten die dingen in een technische wereld), dat betekent: "hier houdt de model representatie op, en vul het zelf verder maar in".

Het kan geen "primitief datatype" of "objecttype" kunnen zijn, omdat we die info niet hebben (en niet willen meeslepen in ons model). 

Conclusie zou kunnen/moeten zijn dat we het in het midden laten. We leveren zo veel mogelijk info in de MIM serialisatie over deze "interface" (dus meer dan alleen de naam). Op basis daarvan moet een implementatie verder kunnen werken. Dus niet oplossen naar iets; dat is helaas implementatiewerk.

NB Imvertor heeft voorzieningen om die extra info te leveren.

**Comment by lennartvanbergen-kadaster** [comment]
Voorstel:

<mim:type>CharacterString</mim:type>
of
<mim-ref:DatatypeRef

en als het een zelf gedefinieerde is zoals bij AN-MES1:

<mim:type>
<mim-ref:DatatypeRef xlink:href="#datatypenalgemeen-primitiefdatatype-anmes1-d65955e674">AN-MES1</mim-ref:DatatypeRef>
</mim:type>

verwijst naar: 
<mim:datatypen>
<mim:PrimitiefDatatype id="datatypenalgemeen-primitiefdatatype-anmes1-d65955e674">
<mim:type>CharacterString</mim:type>


en niet: 

<mim:datatypen>
            <mim:PrimitiefDatatype id="datatypenalgemeen-primitiefdatatype-anmes1-d65955e674">
               <mim:supertype>
                  <mim:GeneralisatieDatatypes>
                     <mim:supertype>
                        <mim-ref:InterfaceRef xlink:href="#interface-characterstring-d65955e8363">CharacterString</mim-ref:InterfaceRef>
                     </mim:supertype>
                     <mim-ext:kenmerken>
                        <mim-ext:kenmerk naam="positie">100</mim-ext:kenmerk>
                     </mim-ext:kenmerken>
                  </mim:GeneralisatieDatatypes>
               </mim:supertype>
               <mim:naam>AN-MES1</mim:naam>
               <mim:definitie>
                  <xhtml:body>
                     <xhtml:p>Een datatype om aan te geven dat alleen europese tekens gebruikt mogen worden, die in de MES-1 set zitten. </xhtml:p>
                  </xhtml:body>
               </mim:definitie>
               <mim:herkomst></mim:herkomst>
               <mim:datumOpname></mim:datumOpname>
            </mim:PrimitiefDatatype>

**Comment by kad-mesdat** [comment]
Voor standaard MIM datatypen kunnen we toch "hard" definiëren wat de vertaling is naar xsd typen. Dus characterstring is xsi:string enz. De interface zou ik reserveren voor die gevallen dat er een complexere mapping nodig is die hergebruikt wordt vanuit een ander domein. 

Zou een interface ook kunnen verwijzen naar een te includeren xsd uit een ander domein? Bijvoorbeeld CityGML ten behoeven van de  Kadastrale kaart? 

Nu staat er alleen een gebruik met GMPoint als voorbeeld beschreven. (vlak onder https://docs.geostandaarden.nl/mim/mim/#example-13)

**Comment by PalmJanssen** [comment]
Weet niet of dit iets toevoegt.

Ik zie een interface type als een datatype waarvan je apart moet afspreken hoe de implementatie er uit ziet. De implementatie moet alle eigenschappen van het interface type realiseren. Het heet interface ipv datatype omdat er geen standaard recht toe recht aan implementatie regels zijn en er dus een beschrijving van de bijzondere uitwerking nodig is. Een Date is bijvoorbeeld een interface omdat het conceptueel een combinatie van Year, Month en Day is die gerealiseerd wordt (meestal) als integratie via YYYY-MM-DD

**Comment by lennartvanbergen-kadaster** [comment]
De beide vorige opmerkingen zijn in lijn met het voorstel. 

Voorstel akkoord.

**Comment by ArjanLoeffen** [comment]
Ik snap het voorstel nog niet helemaal.

We accepteren wel *Ref constructies, en die leggen we dan uit. Maar we accepteren geen Interface constructies. Snap niet waarom het een en niet het ander.

"Interface" is de meest zuivere aanpak, naam mag veranderen in iets anders wat mij betreft. Dus dan zou ik dus niks veranderen.

Maar als dat al is uitgediscussieerd komt het voorstel van lennart als ik het goed begrijp neer op het volgende. Bekijk het volgende voorbeeld met 3 attributen van 3 typen.

![image](https://user-images.githubusercontent.com/12828217/175549320-3bec4c5e-1540-41bf-97a0-e19dec3b986b.png)

Dat levert nu op (even de essentie):
```xml
<mim:Informatiemodel
    <!-- ... -->
    <mim:packages>
        <mim:Domein id="model-domein-model-d4255e18">
            <mim:naam>Model</mim:naam>
            <mim:datatypen>
                <mim:PrimitiefDatatype id="model-primitiefdatatype-lokaaltype-d4255e22">
                    <mim:naam>LokaalType</mim:naam>
                </mim:PrimitiefDatatype>
            </mim:datatypen>
            <mim:objecttypen>
                <mim:Objecttype id="model-objecttype-class1-d4255e33">
                    <mim:naam>Class1</mim:naam>
                    <mim:attribuutsoorten>
                        <mim:Attribuutsoort>
                            <mim:naam>externMIM</mim:naam>
                            <mim:type>
                                <mim-ref:InterfaceRef xlink:href="#interface-characterstring-d4255e156">CharacterString</mim-ref:InterfaceRef>
                            </mim:type>
                        </mim:Attribuutsoort>
                        <mim:Attribuutsoort>
                            <mim:naam>externGML</mim:naam>
                            <mim:type>
                                <mim-ref:InterfaceRef xlink:href="#interface-gmpoint-d4660e174">GM_Point</mim-ref:InterfaceRef>
                            </mim:type>
                        </mim:Attribuutsoort>
                        <mim:Attribuutsoort>
                            <mim:naam>lokaal</mim:naam>
                            <mim:type>
                                <mim-ref:DatatypeRef xlink:href="#model-primitiefdatatype-lokaaltype-d4255e22">LokaalType</mim-ref:DatatypeRef>
                            </mim:type>
                        </mim:Attribuutsoort>
                    </mim:attribuutsoorten>
                </mim:Objecttype>
            </mim:objecttypen>
        </mim:Domein>
        <mim:Extern id="OUTSIDE-1">
            <mim:naam>MIM11</mim:naam>
            <mim:interfaces>
                <mim:Interface id="interface-characterstring-d4255e156">
                    <mim:naam>CharacterString</mim:naam>
                </mim:Interface>
            </mim:interfaces>
        </mim:Extern>
        <mim:Extern id="OUTSIDE-2">
            <mim:naam>GML</mim:naam>
            <mim:interfaces>
                <mim:Interface id="interface-gmpoint-d4660e174">
                    <mim:naam>GM_Point</mim:naam>
                </mim:Interface>
            </mim:interfaces>
        </mim:Extern>
    </mim:packages>
</mim:Informatiemodel>
```

Dat zou dan worden:
```xml
<mim:Informatiemodel
    <mim:packages>
        <mim:Domein id="model-domein-model-d4255e18">
            <mim:naam>Model</mim:naam>
            <mim:datatypen>
                <mim:PrimitiefDatatype id="model-primitiefdatatype-lokaaltype-d4255e22">
                    <mim:naam>LokaalType</mim:naam>
                </mim:PrimitiefDatatype>
            </mim:datatypen>
            <mim:objecttypen>
                <mim:Objecttype id="model-objecttype-class1-d4255e33">
                    <mim:naam>Class1</mim:naam>
                    <mim:attribuutsoorten>
                        <mim:Attribuutsoort>
                            <mim:naam>externMIM</mim:naam>
                            <mim:type>
                                <mim:Datatype>CharacterString</mim:Datatype>
                            </mim:type>
                        </mim:Attribuutsoort>
                        <mim:Attribuutsoort>
                            <mim:naam>externGML</mim:naam>
                            <mim:type>
                               <mim:ExternDatatype>GM_Point</mim:ExternDatatype>
                            </mim:type>
                        </mim:Attribuutsoort>
                        <mim:Attribuutsoort>
                            <mim:naam>lokaal</mim:naam>
                            <mim:type>
                                <mim-ref:DatatypeRef xlink:href="#model-primitiefdatatype-lokaaltype-d4255e22">LokaalType</mim-ref:DatatypeRef>
                            </mim:type>
                        </mim:Attribuutsoort>
                    </mim:attribuutsoorten>
                </mim:Objecttype>
            </mim:objecttypen>
            <mim-ext:kenmerken>
                <mim-ext:kenmerk naam="release">20210401</mim-ext:kenmerk>
            </mim-ext:kenmerken>
        </mim:Domein>
        <mim:Extern id="OUTSIDE-1">
            <mim:naam>MIM11</mim:naam>
            <mim:interfaces>
                <mim:Interface id="interface-characterstring-d4255e156">
                    <mim:naam>CharacterString</mim:naam>
                </mim:Interface>
            </mim:interfaces>
        </mim:Extern>
        <mim:Extern id="OUTSIDE-2">
            <mim:naam>GML</mim:naam>
            <mim:interfaces>
                <mim:Interface id="interface-gmpoint-d4660e174">
                    <mim:naam>GM_Point</mim:naam>
                </mim:Interface>
            </mim:interfaces>
        </mim:Extern>
    </mim:packages>
</mim:Informatiemodel>
```

Zoals eerder gesteld wordt dan dus aangegeven dat `GM_Point` een datatype is. Dat kunnen we wel vastleggen in "conceptual schemas" en op basis daarvan dus die conclusie trekken. Als het een Objecttype was, zou het `ExternObjecttype`  worden.

**Comment by ArjanLoeffen** [comment]
Voor het XML schema van deze XML betekent dat de volgende aanpassingen:
- MIM primitieve Datatypen opnemen in het schema. Wordt <mim:Datatype>
- Externe interfaces: wordt <mim:ExternDatatype> of <mim:ExternObjecttype> etc. afhankelijk van conceptualschema

**Comment by ArjanLoeffen** [comment]
Dit is nu doorgevoerd in branch MIM serialisatie

**Comment by ArjanLoeffen** [comment]
Nog nalopen hoe het zit met InterfaceRef en KeuzeRef.

KeuzeDatatypeRef ook als datatype?
 
@ArjanLoeffen naar kijken, voorstel doen.

**Comment by lennartvanbergen** [comment]
KeuzeRef is wat te algemeen wellicht, maar dat gaat wel goed.

**Comment by dkrijtenburg-GNM** [comment]
@PalmJanssen : kan deze worden gesloten?

**Comment by PalmJanssen** [comment]
Kan worden afgesloten. MIM 1.1.1 serialisatie is inmiddels gepubliceerd
