### ISSUE TITLE
MIM serialisatie: Referentie naar MIM standaard toevoegen.

### ISSUE THREAD

**Issue by ArjanLoeffen** [Geonovum/MIM-Werkomgeving#243]
Documentatie. Korte toelichting/def. Links naar MIM voor uitgebreidere. Tips voor implementatie opnemen ergens.

Zie ook #197

**Comment by ArjanLoeffen** [comment]
Ik vraag me af of dit wel een goede weg is. Een linkje naar de standaard, dat kan ik me voorstellen. Maar méér zou ik eigenlijk zie als ballast: een MIM serialisatie moeten we niet zien als lesmateriaal maar data waarop software wordt gebouwd.

**Comment by lennartvanbergen-kadaster** [comment]
Nja, beetje eens, Maar 1 link naar de standaard als geheel is weer wat karig. Een beetje in de buurt lijkt me wel zo prettig. Of redelijk precies, als het kan. 

Ik realiseer me dat niet alle MIM elementen een URI hebben, dus dit voor elkaar maken lijkt ook nuttig. Maar totdat zo is,  

Het criterium: iedereen kan copy paste en CTRL find is ook best ok, mensen die met de MIM export aan de gang kunnen, kunnen dit prima. 

Let wel, als je een re-spec maakt van een informatiemodel wil je ook links opnemen naar de standaard dus ik vermoed dat het vaker terug gaat komen ... dit opnemen van links. 

Laten we voor deze 1.1 versie een niet al te tijdrovend midden kiezen en dan de ervaringen uit de praktijk ophalen en dan (pas) kiezen om het preciezer te doen. 

Bv. wel de link naar H2.X aangeven (1 paragraaf diep), maar niet dieper dan dat.

**Comment by lennartvanbergen-kadaster** [comment]
Voorstel: links toevoegen naar H2 naar 1 paragraaf diep. Gebaseerd op de links van de huidige re-spec (en niet dieper dan dit).  

Plus bovenin het document een link naar de nieuwe bijlage die we opnemen in MIM voor deze MIM serialisatie.

**Comment by lennartvanbergen-kadaster** [comment]
Akkoord.

**Comment by ArjanLoeffen** [comment]
Conclusie zoals ik 'm interpreteer:

Dat wordt één link bovenin (naar de standaard), en per onderdeel (alleeen de eerste keer dat deze voorkomt in de serialisatie) een link naar H2.* in de standaard. De link krijgt de vorm van een XML commentaarregel.  Dus bijvoorbeeld:

```
<mim:Informatiemodel>
    <!-- https://docs.geostandaarden.nl/mim/def-st-mim-20220217/#informatiemodel -->
    <mim:packages>
        <mim:Domein id="model-domein-model-d4255e18">
        <!-- https://docs.geostandaarden.nl/mim/def-st-mim-20220217/#domein -->
         etc...
```

De link is naar de standaard die de versie van MIM die is geserialiseerd beschrijft, niet naar "de laatste versie".

**Comment by ArjanLoeffen** [comment]
Dit moet geconfigureerd worden, en de config moet worden uitgelezen. 

Voorbeeld: voor mim:Informatiemodel vastleggen dat het kan worden teriggegvonden onder #informatiemodel binnen https://docs.geostandaarden.nl/mim/def-st-mim-20220217/. Ook die laatste link configureerbaar maken, omdat het mechanisme moet werken voor alle versies van MIM.

**Comment by ArjanLoeffen** [comment]
Accoord @lennartvanbergen
