### ISSUE TITLE
Tekst structuur van definitie en toelichting mag "rijke" tekst zijn 

### ISSUE THREAD

**Issue by ArjanLoeffen** [Geonovum/MIM-Werkomgeving#245]
xhtml:body om rijke tekst te ondersteunen, bullits, cursief.

Zie ook #197

**Comment by ArjanLoeffen** [comment]
Interessant is de aanname dat uitleggende tekst een zekere tekst structuur heeft. Dat is denk ik correct: het is voor menselijke consumptie bedoeld. De meest gangbare manier om tekst structuur te coderen is XHTML dus dat lijkt me een goede basis voor de serialisatie standaard.

**Comment by lennartvanbergen-kadaster** [comment]
Eens met AL

**Comment by lennartvanbergen-kadaster** [comment]
De MIM serialisatie is goed.

In MIM zelf aangeven dat de tekst bij een _definitie_ en een _toelichting_ "rijke" tekst mag zijn. Dit kan mee in de volgende MIM versie. Titel aangepast.
