### ISSUE TITLE
MIM serialisatie: extensies op MIM, met of zonder schema validatie en aanhaak specificatie

### ISSUE THREAD

**Issue by ArjanLoeffen** [Geonovum/MIM-Werkomgeving#246]
Schema validatie op extensies?

Zie ook #197

**Comment by ArjanLoeffen** [comment]
Waarom valideren we een MIM serialisatie? Omdat software vertrouwen moet hebben dat de serialisatie klopt. Wanneer je alleen in het MIM domein beweegt hebben we een schema beschikbaar. Bewegen we in MIM gebaseerd domein, dan komen daar extra validatie eisen bij. Dus schema constructies bovenop de standaard MIM constructies. Dat zijn beperkingen en uitbreidingen van de MIM standaard. Dus dat is een uitdaging: hoe zet je zo’n schema in elkaar, zodat ook een bedrijfsspecifiek MIM serialisatie schema de lading dekt?

**Comment by ArjanLoeffen** [comment]
Een andere opmerking uit #197 was: 
> DatumOpname is verplicht. In een extensie mag je ze excluden en weglaten. Nillable of optioneel dus. 

Volgens mij moeten we dit opvatten als een vorm van [XSD redefine](https://www.w3schools.com/xml/el_redefine.asp). Maar we maken het wel complex hiermee...

**Comment by lennartvanbergen-kadaster** [comment]
Voor metagegevens zou ik willen zeggen, ze zijn allemaal nillable. 

Voor een extensie zou ik willen zeggen: dit mag best een beetje generiek. Elke organisatie weet zelf prima welke extensies te hebben en kan daarmee aan de gang. 

Nou is het wel zo dat extensies ook gebruikt zullen en moeten worden door gebruikende partijen, dus dit is best een heikel punt, maar goed je kan niet zonder extensies dus ik denk het hoort er gewoon bij. 

De vraag is vooral: hoe expliciet moet een extensie zijn. 

Bv. Kadaster gebruikt **koppelklasse** als extra _modelelement_. Deze staat niet in MIM. Dus is altijd maatwerk voor elke partij die er wat mee doet. Al zou Kadaster kunnen zeggen: koppelklasse is een extensie van objecttype. Als we dat zouden kunnen aangeven, kan een gebruikende partij het als objecttype behandelen en alleen als nodig wat extra's doen. 

Bv. Kadaster gebruikt eigen _metagegevens_, zoals nen3610;domein en 'relatienaam inverse'. 

Je zou kunnen denken aan: als je een extensie maakt, maak dan ook een eigen XSD.

Voor 1.1. ben ik wel tevreden met wat er nu ligt, aangevuld met dat een extensie ding 1 van de volgende dingen kan zijn: 

* extensie in de vorm van een modelelement - hier moet je redelijk strikt mee omgaan ***
* extensie in de vorm van een metagegeven - hier kan je soepeler mee omgaan 
 
***: voor MIM 1.2 of hoger heb ik wel een wens om aan te kunnen geven dat een modelelement in een extensie een specialisatie is van een MIM element, of een geheel eigen ding of een metagegeven.

**Comment by ArjanLoeffen** [comment]
Het gaat om als voorbeeld:

![image](https://user-images.githubusercontent.com/12828217/164423368-af0336dc-c403-45fa-83a5-4e2e0007c38b.png)

Hier is de constructie mim-geonovum:is-afgeleid opgenomen; dit is dan een uitbreiding van  MIM schema, dat maximaal gevalideerd kan worden. Dat kan _niet_ met kenmerk. Er is dat software die deze mim-geonovum serialisatie kan uitvoeren. 

Dus 
1. optie kenmerk, niet valideerbaar, reeds beschikbaar, en generiek
2. optie eigen elementen als extensie in XML geimplementeerd in de extensie XSD, valideerbaar, moet door iemand worden gemaakt, en is specifiek voor een organisatie of zo.

**Comment by lennartvanbergen-kadaster** [comment]
Ik zie graag een aanpak, waarmee: 
a) organisaties zelf hun eigen extensies in de XML terug zien en er zelf wat mee kunnen doen 
b) afnemers er als ze willen zelf ook wat kunnen doen, omdat de extensie organisatie dit gedocumenteerd heeft ergens 

Wat wel van belang is bij de generieke aanpak is dat we de impact klein houden. Ik zie dat als volgt voor me: 

- voor metagegevens: als gewoon mim-ext **kenmerk** behandelen, is nu al zo in de XSD/XML  

Voorstel: zo doen. 
 
- voor modelelementen: als mim-ext **construct** behandelen, met als er MIM modelelementen en/of MIM-metagegevens inzitten deze weer in de mim namespace laten vallen, is nu al zo in de XSD/XML 

Voorstel: zo doen. 
 
- voor modelelementen die _ook_ een verbijzondering zijn van al bestaande MIM-elementen: aangeven dat dit zo is, dus bij deze modelelementen een extra metagegeven opnemen dat aangeeft van welk bestaand MIM-element het een specialisatie is. 

--

Deze discussie gaat wat mij betreft over dit laatste aspect (aangenomen dat de andere 2 qua voorstel ok zijn). 

Dit laatste punt moeten we denk ik uitwerken in de volgende MIM versie, maar het lijkt me nu al nuttig om dat ook in de XSD een plek te geven. 

Denkrichting: definieer in een organisatie specifieke extensie dat het eigen extensie-element een bepaalde **verhouding** heeft tot een al bestaand MIM-element als een specialisatie. Het MIM element is het supertype van het eigen extensie element. 

Voorbeeld: op metamodel niveau is een Koppelklasse een specialisatie van een mim:Objecttype 
Voorbeeld: mijnSuperBijzonderComplexDatatype is een specialisatie van mim:Datatype of van mim:Characterstring 

Deze verhouding is een _specialisatie_ en kunnen we specificeren op twee plekken: 

1. In het informatiemodel zelf, dus Koppelklasse ABC heeft als **extra metagegeven: mim:supertype = Objecttype** en koppelklasse DEF heeft dit extra metagegeven ook en daarin staat ook: mim-supertype = Objecttype

Een afnemer kan dan zien: ok, deze moet ik hetzelfde afhandelen als een objecttype. Dit zal goed gaan. Eventueel moet ik nog wat extra's doen als ik de bijzondere betekenis helemaal wil benutten.  

2. Met een organisatie specifieke extensie XSD met daarin een xs:extension

MIMFORMAT_Mim_Ext_Kadaster_v1.XSD 

```
<xs:element name="Koppelklasse" type="mim-ext-kad:Koppelklasse">
    <xs:annotation>
      <xs:documentation>Mijn uitleg</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="Koppelklasse">
    <xs:complexContent>
      <xs:extension base="mim:Objecttype">


```

Je kan deze extensie publiceren en ook implementeren in een export tool zodat deze XML er volgens deze XSD uitkomt. 

Einde voorstel.

**Comment by PalmJanssen** [comment]
In dit geval is koppelklasse blijkbaar een extensie van een bestaande MIM metaklasse. Dan kom je een heel eind met de extensie constructie. Maar als het dat niet is? Volgens mij hoef je in de serialisatie alleen te weten wat de metaklasse is. Hoe die geimplemeneerd moet worden in uitwisselformaat, database of wat dan ook wordt ergens anders beschreven.

**Comment by lennartvanbergen-kadaster** [comment]
Akkoord met 1.

**Comment by ArjanLoeffen** [comment]
Ik vind dat het niet correct is de standaard te beperken  in reikwijdte. Dus een multipliciteit van 1..* kan niet worden veranderd in 0..* in een extensie op de standaard. Ook kunnen geen kenmerken of modelelementen worden verwijderd. Dit zou namelijk de standaard ondermijnen.

Toch kan men willen aangeven dat bijvoorbeeld _enumeraties_ niet gebruikt worden. N.m.m. hoeft men dat niet via een schema constructie te regelen. Dat zijn afspraken die ook informeel, via heuristieken, of via software validaties kan realiseren. De standaard wordt daardoor niet beperkt in haar "werking". 

Het introduceren van een specifieke afgeleide XSD zal dus altijd een uibreiding betreffen. Dat verloopt via één van drie routes. het meest "veilig" en standaard-conform is n.m.m. de XSD redefine.

Voorbeelden bijgevoegd als [issue246.zip](https://github.com/Geonovum/MIM-Werkomgeving/files/9038332/issue246.zip)

## redefine 

[XSD redefine](https://www.w3schools.com/xml/el_redefine.asp) - dit staat toe een bestaande constructie uit te breiden met nieuwe elementen. Bijvoorbeeld: een extra kenmerk binnen een informatiemodel (voorbeeld: naast `/informatiemodel/informatiedomein` ook `/informatiemodel/release` toestaan).
In XSD zal alleen gebruik kunnen worden gemaakt van [XSD extension](https://www.w3schools.com/xml/el_extension.asp)

Voordeel: strakke controle op juiste uitbreiding, niet mogelijk om het standaard schema te omzeilen.
Nadeel: redefine ietwat lastig te specificeren, misschien niet alle tools ondersteunen deze constructie. 

## override 

[XSD override](https://www.w3.org/TR/xmlschema11-1/#override-schema) - In XML schema 1.1 is dit geïntroduceerd . Dit vervangt een constructie volledig door een nieuwe (uitbreiding) opbouw. 

Voordeel: Vrijheid om beperkingen én uitbreidingen vrijelijk in te voeren op iedere construct in het standaard schema.
Nadeel: de vraag is of 1.1 wel voldoende breed ondersteund wordt in software (Java ondersteunt het in [Xerces2](https://xerces.apache.org/xerces2-j/)). Ook kan men gemakkelijk afwijken van de standaard (dingen beperken/omgooien). Uitzoeken of bestaande constructies wel op de juiste manier, conform de standaard, kunnen worden vervangen, als dat de intentie is van de ontwikkelaar van dat schema (wat we wel veronderstellen). 

## nieuw schema

Aanpassen van een kopie van de XSD. Deze nieuwe XSD moet dus een correcte uitbreiding zijn van de vastgestelde (en in de norm opgenomen) XSD.

Voordeel: geen redefine nodig. Schema geeft "complete beeld" van de beoogde serialisatievorm.
Nadeel: makkelijk om het standaard schema te omzeilen. Geen standaard tools aanwezig om vergelijking tussen standaard en extensie "door te rekenen".

**Comment by ArjanLoeffen** [comment]
Eerste slag is als volgt gemaakt:

- Er is een basisschema dat alles bevat behalve de definitie van Relatiesoort en Relatierol.
- Er is een apart schema dat Relatiesoort & -Rol definitie bevat vanuit het perspectief van "Relatiesoort leidend".
- Er is een apart schema dat Relatiesoort & -Rol definitie bevat vanuit het perspectief van "Relatierol leidend".
- De laatste twee schema's includeren het basisschema.
- Een MIM serialisatie verwijst naar een van deze twee laatste schema varianten. 

Voorbeeld van de uitwerking van relatiesoort-leidend:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<mim:Objecttype xmlns:xlink="http://www.w3.org/1999/xlink"
 xmlns:mim-ref="http://www.geostandaarden.nl/mim-ref/informatiemodel/v1"
 xmlns:mim="http://www.geostandaarden.nl/mim/informatiemodel/v1"
 xmlns:mim-ext="http://www.geostandaarden.nl/mim-ext/informatiemodel/v1"
 xmlns:xhtml="http://www.w3.org/1999/xhtml"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.geostandaarden.nl/mim/informatiemodel/v1 MIMFORMAT_Mim_relatiesoort_v1.xsd" id="id1">
    <mim:naam>naam</mim:naam>
    <mim:herkomst>herkomst</mim:herkomst>
    <mim:definitie>definitie</mim:definitie>
    <mim:herkomstDefinitie>herkomstDefinitie</mim:herkomstDefinitie>
    <mim:datumOpname>2022-01-01</mim:datumOpname>
    <mim:indicatieAbstractObject>false</mim:indicatieAbstractObject>
    <mim:relatiesoorten>
        <mim:Relatiesoort>
            <mim:naam>relatiesoort</mim:naam>
            <mim:unidirectioneel>true</mim:unidirectioneel>
            <mim:doel>
                <mim-ref:ObjecttypeRef xlink:href="#id1"/>
            </mim:doel>
            <mim:aggregatietype>Geen</mim:aggregatietype>
            <mim:kardinaliteit>0..1</mim:kardinaliteit>
            <mim:herkomst>herkomst</mim:herkomst>
            <mim:definitie>definitie</mim:definitie>
            <mim:herkomstDefinitie>herkomstDefinitie</mim:herkomstDefinitie>
            <mim:datumOpname>2022-01-01</mim:datumOpname>
            <mim:indicatieMaterieleHistorie>false</mim:indicatieMaterieleHistorie>
            <mim:indicatieFormeleHistorie>false</mim:indicatieFormeleHistorie>
            <mim:authentiek>false</mim:authentiek>
            <mim:indicatieAfleidbaar>false</mim:indicatieAfleidbaar>
            <mim:mogelijkGeenWaarde>false</mim:mogelijkGeenWaarde>
            <mim:relatierollen>
                <mim:relatierolDoel>
                    <mim:naam>naam</mim:naam>
                    <mim:definitie>definitie</mim:definitie>
                </mim:relatierolDoel>
            </mim:relatierollen>
        </mim:Relatiesoort>
    </mim:relatiesoorten>
</mim:Objecttype>
```
Voorbeeld van de uitwerking van relatierol-leidend:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<mim:Objecttype xmlns:xlink="http://www.w3.org/1999/xlink"
 xmlns:mim-ref="http://www.geostandaarden.nl/mim-ref/informatiemodel/v1"
 xmlns:mim-ext="http://www.geostandaarden.nl/mim-ext/informatiemodel/v1"
 xmlns:mim="http://www.geostandaarden.nl/mim/informatiemodel/v1"
 xmlns:xhtml="http://www.w3.org/1999/xhtml"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.geostandaarden.nl/mim/informatiemodel/v1 MIMFORMAT_Mim_relatierol_v1.xsd" id="id1">
    <mim:naam>naam</mim:naam>
    <mim:herkomst>herkomst</mim:herkomst>
    <mim:definitie>definitie</mim:definitie>
    <mim:herkomstDefinitie>herkomstDefinitie</mim:herkomstDefinitie>
    <mim:datumOpname>2022-01-01</mim:datumOpname>
    <mim:indicatieAbstractObject>false</mim:indicatieAbstractObject>
    <mim:relatiesoorten>
        <mim:Relatiesoort>
            <mim:naam>relatiesoort</mim:naam>
            <mim:alias>alias</mim:alias>
            <mim:definitie>definitie</mim:definitie>
            <mim:relatierollen>
                <mim:RelatierolDoel>
                    <mim:naam>naam</mim:naam>
                    <mim:herkomst>herkomst</mim:herkomst>
                    <mim:definitie>definitie</mim:definitie>
                    <mim:herkomstDefinitie>herkomstDefinitie</mim:herkomstDefinitie>
                    <mim:datumOpname>2022-01-01</mim:datumOpname>
                    <mim:kardinaliteit>0..1</mim:kardinaliteit>
                    <mim:indicatieMaterieleHistorie>false</mim:indicatieMaterieleHistorie>
                    <mim:indicatieFormeleHistorie>false</mim:indicatieFormeleHistorie>
                    <mim:authentiek>false</mim:authentiek>
                    <mim:mogelijkGeenWaarde>false</mim:mogelijkGeenWaarde>
                </mim:RelatierolDoel>
            </mim:relatierollen>
        </mim:Relatiesoort>
    </mim:relatiesoorten>
</mim:Objecttype>
```

**Comment by melsk-r** [comment]
De volgende methode is gebaseerd op het gebruik van het XML-Schema element `xs:redefine`.
De uitdaging was het uitbreiden van de mim namespace met een element `koppelklasse` overal waar ook het element `objecttypen` toegestaan is. Uitgangspunt daarbij was dat het originele mim schema onaangetast blijft, we willen immers dat elke organisatie elementen kan toevoegen zonder daarbij wijzigingen aan te moeten brengen aan het originele mim schema.

Daartoe heb ik eerst het nieuwe schema 'VNGR_MimExt_v1.xsd' aangemaakt waarin ik het nieuwe element 'koppelklasse' en het door dat element te gebruiken complexType heb geplaatst. Dit schema heb ik als targetNamespace `http://www.vngr.nl/mim/informatiemodel/v1` gegeven.

	<xs:schema ... 
		xmlns:vngr-mim-ext="http://www.vngr.nl/mim/informatiemodel/v1"
		xmlns:mim="http://www.geostandaarden.nl/mim/informatiemodel/v1" 
		targetNamespace="http://www.vngr.nl/mim/informatiemodel/v1" >

		<xs:element name="koppelklasse" type="vngr-mim-ext:Koppelklasse"/>
		<xs:complexType name="Koppelklasse">
			<xs:sequence>
				<xs:element name="Koppelingsnaam" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:schema>

Vervolgens heb ik ook het schema 'VNGR_MimRedefine.xsd' aangemaakt dat dezelfde namespace als targetNamespace heeft als het mim schema (`http://www.geostandaarden.nl/mim/informatiemodel/v1`). Daarin heb ik een include gedaan van het mim schema en een import van het schema met het nieuwe element.
Ook heb ik daar de `xs:redefine` op het mim schema geplaatst met daarbinnen een nieuw complexType `Domein`. Binnen dat complexType is vervolgens een extrension op het originele complexType `Domein` geplaatst met alleen een verwijzing naar het element `koppelklasse` in het andere schema.

	<xs:schema ... 
		xmlns:vngr-mim-ext="http://www.vngr.nl/mim/informatiemodel/v1"
		xmlns:mim="http://www.geostandaarden.nl/mim/informatiemodel/v1"
		targetNamespace="http://www.geostandaarden.nl/mim/informatiemodel/v1">

		<xs:include schemaLocation="MIMFORMAT_Mim_v1.xsd"/>
		<xs:import namespace="http://www.vngr.nl/mim/informatiemodel/v1" schemaLocation="VNGR_MimExt_v1.xsd"/>

		<xs:redefine schemaLocation="MIMFORMAT_Mim_v1.xsd">
			<xs:complexType name="Domein">
				<xs:complexContent>
					<xs:extension base="mim:Domein">
						<xs:sequence>
							<xs:element ref="vngr-mim-ext:koppelklasse" minOccurs="0"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
		</xs:redefine>
	</xs:schema>

Met dit alles kan vervolgens de volgende XML instance worden vervaardigd:

	<mim:Informatiemodel ...
		xmlns:mim="http://www.geostandaarden.nl/mim/informatiemodel/v1" 
		xmlns:vngr-mim-ext="http://www.vngr.nl/mim/informatiemodel/v1" 
		xsi:schemaLocation="http://www.geostandaarden.nl/mim/informatiemodel/v1 VNGR_MimRedefine.xsd">

		<mim:naam>String</mim:naam>
		<mim:definitie/>
		<mim:herkomst>String</mim:herkomst>
		<mim:informatiemodeltype>String</mim:informatiemodeltype>
		<mim:informatiedomein>String</mim:informatiedomein>
		<mim:relatiemodelleringtype>Relatierol leidend</mim:relatiemodelleringtype>
		<mim:MIMVersie>String</mim:MIMVersie>
		<mim:packages>
			<mim:Domein id="Domein">
				<mim:naam>Informatiemodel MIM</mim:naam>
				<mim:objecttypen>
					<mim:Objecttype id="Objecttype">
						<mim:naam></mim:naam>
						<mim:herkomst></mim:herkomst>
						<mim:definitie></mim:definitie>
						<mim:herkomstDefinitie></mim:herkomstDefinitie>
						<mim:datumOpname></mim:datumOpname>
						<mim:indicatieAbstractObject>false</mim:indicatieAbstractObject>
					</mim:Objecttype>
				</mim:objecttypen>
				<vngr-mim-ext:koppelklasse>
					<vngr-mim-ext:Koppelingsnaam>Voorbeeld</vngr-mim-ext:Koppelingsnaam>
				</vngr-mim-ext:koppelklasse>
			</mim:Domein>
		</mim:packages>
	</mim:Informatiemodel>

De zip met deze bestanden vind je [hier](https://github.com/Geonovum/MIM-Werkomgeving/files/9121264/MIM-redefine.zip)

**Comment by ArjanLoeffen** [comment]
Ik denk dat redefine, voor wie daar behoefte aan heeft, de juiste aanpak is. Extension én restriction zijn beide op die manier te realiseren. Zie @melsk-r  oplossing.

**Comment by pmaria** [comment]
> Ik vind dat het niet correct is de standaard te beperken in reikwijdte. Dus een multipliciteit van 1..* kan niet worden veranderd in 0..* in een extensie op de standaard. Ook kunnen geen kenmerken of modelelementen worden verwijderd. Dit zou namelijk de standaard ondermijnen.
> 
> Toch kan men willen aangeven dat bijvoorbeeld enumeraties niet gebruikt worden. N.m.m. hoeft men dat niet via een schema constructie te regelen. Dat zijn afspraken die ook informeel, via heuristieken, of via software validaties kan realiseren. De standaard wordt daardoor niet beperkt in haar "werking".
> 
> Het introduceren van een specifieke afgeleide XSD zal dus altijd een uibreiding betreffen. Dat verloopt via één van drie routes. Het meest "veilig" en standaard-conform is n.m.m. de XSD redefine.

Het construct [`xs:redefine` is deprecated](https://www.w3.org/TR/xmlschema11-1/#element-redefine) in XML schema 1.1. Er wordt aangeraden om in de plaats daarvan kan [`xs:override`](https://www.w3.org/TR/xmlschema11-1/#element-override) te gebruiken.

Het mij niet handig om op een deprecated construct door te bouwen, dus lijkt het logisch om voor override te kiezen.

**Comment by ArjanLoeffen** [comment]
> Het mij niet handig om op een deprecated construct door te bouwen, dus lijkt het logisch om voor override te kiezen.

Dat is wat mij betreft prima, waarbij dus de strakkere controle van redefine vervalt. Als deze constructies deprecated is, moeten we dat volgen.

**Comment by ArjanLoeffen** [comment]
Dit betekent een extra taak voor Imvertor: https://github.com/Imvertor/Imvertor-Maven/issues/281

**Comment by ArjanLoeffen** [comment]
Nav overleg met @lennartvanbergen besloten extensies generiek te houden. Als nodig kan daarna ooit dit worden opgenomen in MIM 1.*

Generieke extensies (constructies en kenmerken) worden gevalideerd, maar niet zo exact als zou kunnen.

Accoord @lennartvanbergen.
