### ISSUE TITLE
MIM serialisatie: Hoe omgaan met termen in MIM serialisatie die niet in MIM voorkomen?

### ISSUE THREAD

**Issue by ArjanLoeffen** [Geonovum/MIM-Werkomgeving#248]
Voorbeeld: <mim:packages> wrapper. Heten package in tekst, staat niet in diagrammen. Nodig? 

Zie ook #197

**Comment by ArjanLoeffen** [comment]
Misschien de serialisatie nog eens doorlopen op termen die niet uit MIM komen en kijken of er een _natuurlijk_ alternatief dat wel uit MIM komt voor is.

**Comment by ArjanLoeffen** [comment]
Ook was dit een issue:
> MIM 1.1. – volledig en juist. O.a. De namen van het metamodel zijn niet altijd gevolgd, bv. een sequence attribuutsoorten (naam ooit gekozen). 

Ik neem aan dat dit hetzelfde betreft.

**Comment by lennartvanbergen-kadaster** [comment]
Enerzijds denk ik: als bepaalde wrappers nuttig zijn, en laten we hiervan uitgaan (tenzij we tot het inzicht bij die wrapper komen dat ie niet nodig is) dan kiezen we er indien mogelijk een MIM naam voor, zoals bij _packages_, hoewel dit geen modelelement is. 

Dit punt kan wel mee met; laten we een link toevoegen aan de MIM XSD elementen, daar waar er een MIM link voor te maken is, bv. omdat er een anchor voor is in de respec en met de hand een uitleg erbij zetten als het niet in MIM terug te vinden is.

**Comment by lennartvanbergen-kadaster** [comment]
Duplicaat.
