### ISSUE TITLE
MIM serialisatie: Element mim:GeneralisatieDatatypes lijkt niet juist gekozen

### ISSUE THREAD

**Issue by ArjanLoeffen** [Geonovum/MIM-Werkomgeving#249]
<mim:GeneralisatieDatatypes>Wrapper. Lijkt dubbelop, ik zie al <supertype> staan.

Zie ook #197

**Comment by lennartvanbergen-kadaster** [comment]
<mim:PrimitiefDatatype id="datatypenalgemeen-primitiefdatatype-anmes1-d64326e5970">
         <**mim:supertype**>
            <**mim:Generalisatie**>
               <mim:datumOpname/>
               <**mim:supertype**>
                  <mim-ref:InterfaceRef xlink:href="#mim11-interface-characterstring-d64326e6909">CharacterString</mim-ref:InterfaceRef>

De dikgedrukte items zeggen allemaal hetzelfde, waarom 3 lagen om dit aangeven?

**Comment by ArjanLoeffen** [comment]
Zie Primitief datatype:

![image](https://user-images.githubusercontent.com/12828217/164415552-8ae77b8d-695a-4f37-a9fa-6a6186f0f6d8.png)

- `<supertype>` nodig om aan te geven dat er een (of meerdere?) supertype zijn
- `<GeneralisatieDatatypes>` om aan te geven dat da via de MIM generalisatie gebeurt. Deze kan kenmerken hebben. Bijv, datum opname
-  `<supertype>` is een kenmerk van `<generalisatie>`

We volgen dus MIM op de voet.

**Comment by ArjanLoeffen** [comment]
NB: 
![image](https://user-images.githubusercontent.com/12828217/164417083-7a16e45e-daa4-40b6-8ade-447b049eb3e7.png)
Zoals je ziet is de supertype relatie én de generalisatie klasse expliciet gemaakt in de meta-UML. Die generalisatie klasse had eigenlijk moeten worden opgesplitst in twee vormen daarvan.

**Comment by PalmJanssen** [comment]
Besluit werkgroep:

Is verbose maar nodig. Geen wijziging.
