### ISSUE TITLE
Interne referentie naar 3.5 formeel patroon klopt niet

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/MIM-Werkomgeving#25]
In de tekst van het Metamodel document staat op pagina 28 onderaan: 

> (zie ook 'patroon' in 3.5)

Paragraaf 3.5 gaat echter over Domeinwaarden of lijsten.

**Comment by PalmJanssen** [comment]
Verwerkt.

Dit gedeelte van deze paragraaf is verplaatst naar paragraaf 3.1.1.
