### ISSUE TITLE
MIM serialisatie: Ref constructies

### ISSUE THREAD

**Issue by ArjanLoeffen** [Geonovum/MIM-Werkomgeving#250]
Ref constructies. ObjectRef. InterfaceRef. 

Zie ook #197

**Comment by ArjanLoeffen** [comment]
@lennartvanbergen-kadaster kun je deze nog verduidelijken?

**Comment by lennartvanbergen-kadaster** [comment]
Volgens mij was het punt hier dat de Ref constructie niet in MIM staat, maar wel in de XSD en dat dit wel handig is en fijn is, maar dat het ook goed is om even goed te beschrijven wat een Ref nou is.

**Comment by lennartvanbergen-kadaster** [comment]
Voorstel: bij de Ref constructie kort beschrijven hoe dit werkt. Dat het een referentie is naar iets wat in de XML staat en dat je er via 2 manieren kan komen, via xlink of via name matching.

**Comment by lennartvanbergen-kadaster** [comment]
Akkoord.

**Comment by ArjanLoeffen** [comment]
Voorstel voor de uitleg tekst:

```
In deze serialisatie komen xRef constructies voor, zoals ObjecttypeRef. 
Deze constructies zijn verwijzingen naar een constructie X elders in deze serialisatie. 
Via xlink:href attribuut wordt naar betreffende ID verwezen, voorafgegaan door een # teken.
```

**Comment by ArjanLoeffen** [comment]
Is nu accoord. (@lennartvanbergen okay)
