### ISSUE TITLE
MIM serialisatie: MIM versie als enum

### ISSUE THREAD

**Issue by ArjanLoeffen** [Geonovum/MIM-Werkomgeving#251]
Moeten we MIM versie als enum opnemen?

Zie ook #197

**Comment by lennartvanbergen-kadaster** [comment]
Met waardes 1.1 en 1.1.1. en later andere. 

We kunnen het open laten maar dan zijn alle waardes ineens mogelijk. Het lijkt zinvol om dit vaster te pinnen, omdat software die de MIM export verwerkt afhankelijk is van deze waarde en dan is vastpinnen eerder fijn dan niet fijn. 

Er valt zelfs na te denken om per MIM versie een aparte XSD te maken en de MIM versie per XSD te fixeren. 

Ik laat graag aan de ontwikkelaar minded mensen over wat hier handig is - voor gebruikers van deze MIM export.  

Minimale wens vanuit het onderzoek van Kadaster over de gebruiksvriendelijkheid van de huidige MIM export XML is dat er een enumeratie komt. Ik vermoed dat een XSD per MIM versie handig is (tenzij backwards compatible, dan kan de XSD meerdere MIM versies in de enumeratie krijgen).

**Comment by lennartvanbergen-kadaster** [comment]
Navragen bij ontwikkelaars. 

In dit specifieke geval nu gaat het om MIM versie 1.1.0 ondersteunen voor versie 1.0.0 van de XSD. 

Bij een nieuwe versie van MIM die leidt tot een breaking change, dan komt er een nieuwe XSD 2.0.0. dus daar speelt dit punt niet. Als MIM zelf een breaking change heeft, dan komt er een nieuwe XSD. 

Het gaat hier om een nieuwe MIM versie die backwards compatible is. 

De nieuwe XSD v2.0.0. zal MIM versie 1.1.1 en 1.1.2 ondersteunen met dezelfde XSD 

Is een enumeratie hier ok, waarbij de uitbreiding van de enum als een z versie in de XSD wordt verwerkt? Niet breaking dus. 

Is een regex hier ok die alleen 1.1.0 accepteert bij XSD versie 1.0.0.


Dan valt de XML uit als er een nieuwe versie in de enum komt. En dat is dan ook de bedoeling, want die versie kan je niet verwerken. 



Als // commentaar of enumeratie?

**Comment by lennartvanbergen-kadaster** [comment]
Voorstel voor nu: 

reguliere expressie: MIM versie 1.1.0 mag voor de huidige XSD versie 

we weten nu al dat MIM 1.1.1 een nieuwe XSD zal vereisen, dus die nieuwe XSD ondersteund dan MIM versie 1.1.1. - en dus dat een regex [1]/.[1]./[0-9] niet kan voor de huidige XSD versie

**Comment by lennartvanbergen-kadaster** [comment]
Besluit genomen door wekgroep. Voorstel ok.

**Comment by ArjanLoeffen** [comment]
Dat is mogelijk. Waarom wordt eigenlijk niet voor fixed gekozen?

Besluit is:
```xml
<xs:element name="MIMVersie">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value = "1.1.0"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
```
versus
```xml
  <xs:element name="MIMVersie" type="xs:string" fixed="1.1.0"/>
```

**Comment by ArjanLoeffen** [comment]
Is nu accoord. (@lennartvanbergen okay)
