### ISSUE TITLE
MIM serialisatie: MIM 1.1 naamgeving volgen

### ISSUE THREAD

**Issue by lennartvanbergen** [Geonovum/MIM-Werkomgeving#252]
[MIM serialisatie review.xlsx](https://github.com/Geonovum/MIM-Werkomgeving/files/8467777/MIM.serialisatie.review.xlsx)

**Comment by lennartvanbergen-kadaster** [comment]
Waar een naam gekozen moet worden en deze wel in MIM 1.1.1. staat volgen we uiteraard MIM 1.1.1.

**Comment by ArjanLoeffen** [comment]
We gaan uit van de opzet Construct-relatie-Construct. Da stramien willen we vasthouden. De namen van de relaties tussen metaclassen is nog niet helemaal synchroon. Dat nog even doornemen.

Wel hebben we meervoudsvormen gebruikt; is dat net acceptabel? Wel logisch: binnen relatiesoorten vallen mogelijk meerdere Relatiesoorten...

**Comment by PalmJanssen** [comment]
besluit werkgroep:
- gebruik dezelfde naamgeving voor kenmerken en metaklassen
- mim 1.1.0 is leidend
- betekent dat de meervoudsvormen voor relaties tussen metaklassen enkelvoud worden

**Comment by lennartvanbergen-kadaster** [comment]
En daar waar hiaten zijn in 1.1.0. vullen we deze aan met MIM 1.1.1.

**Comment by architolk** [comment]
In het metamodel is nog een opschoning nodig. Nu kent het metamodel zowel <klasse A> --- relatienaam --> <klasse B>, maar ook <klasse A> --- --> rolnaam B <klasseB> en zelfs <klasse A> rolnaam A --- --> rolnaam B <klasse B>. Conform MIM zelf wordt de 2e en 3e getransformeerd naar: rolNaam B is een eigenschap van klasse A en rolnaam A is een eigenschap van klasse B. Waar rolnamen afwijken van relatienamen dienen we het metamodel op te schonen. Op dit moment is in de Linked Data versie van het MIM de rolnaam leidend.

**Comment by PalmJanssen** [comment]
> Waar rolnamen afwijken van relatienamen dienen we het metamodel op te schonen.

Bedoel je hiermee dat de rolnaam identiek moet zijn aan de relatienaam en vice versa? Ik begrijp je punt maar dat was tot nu toe geen uitgangspunt. Dit blijft een controversieel onderwerp. Het is natuurlijk heel vreemd dat een implementatie andere 'eigenschapnamen' implementeert afhankelijk van keuze uit rolnaam of relatienaam. Het is dan ook een afspraak die op het niveau van het informatiemodel wordt gemaakt

**Comment by ArjanLoeffen** [comment]
> [MIM serialisatie review.xlsx](https://github.com/Geonovum/MIM-Werkomgeving/files/8467777/MIM.serialisatie.review.xlsx)

Ik zou graag een uitleg zien van dit XLSX overzicht. Is dat de geaccordeerd basis voor aanpassingen in de serialisatie?

**Comment by ArjanLoeffen** [comment]
Meervoudsvorm niet gebruiken, zeker weten? Je krijgt dan zoiets als:

![image](https://user-images.githubusercontent.com/12828217/176191835-018d4762-2f36-43fb-8f92-162a22b77777.png)

Ik vind dat als ontwikkelaar verwarrend, intuitief zou de groep datatypen "datatypen" moeten heten, niet "datatype". Ik vermoed dat de keuze voor datatype gevolg is van een doorgeschoten neiging om strikt aan de standaard te voldoen. En dat terwijl de standaard ook spreekt over "datatypen" en "objecttypen" etc. in de lopende tekst...

![image](https://user-images.githubusercontent.com/12828217/176192488-1ad4aef7-8aec-4b8c-9429-f3c88b21bf78.png)

**Comment by ArjanLoeffen** [comment]
Vooralsnog ga ik die meervoud/enkelvoudvorm niet doorvoeren. Ik vind de argumentatie niet goed.

**Comment by ArjanLoeffen** [comment]
Ik heb de XLSX doorgewerkt en aanpassingen doorgevoerd. Enkele aanpassingen niet of anders gedaan. 

Zie
[MIM.serialisatie.review - AL.xlsx](https://github.com/Geonovum/MIM-Werkomgeving/files/9180316/MIM.serialisatie.review.-.AL.xlsx)

**Comment by ArjanLoeffen** [comment]
Is nu accoord? (@lennartvanbergen okay) @PalmJanssen okay?

**Comment by PalmJanssen** [comment]
Als ik het goed begrijp wordt in de serialisatie voor de relaties (referenties) tussen elementen nu enkelvoud termen gebruikt. Dat had mijn voorkeur omdat het dan gelijk is aan de MIM term.

Een paar opmerkingen in excel. Kunnen we morgen naar kijken.
[MIM.serialisatie.review.-.AL-pj.xlsx](https://github.com/Geonovum/MIM-Werkomgeving/files/10032279/MIM.serialisatie.review.-.AL-pj.xlsx)

**Comment by PalmJanssen** [comment]
We hebben er samen naar gekeken. Ik heb geen opmerkingen meer.

**Comment by PalmJanssen** [comment]
Kan worden gesloten. MIM 1.1.1 serialisatie is inmiddels gepubliceerd
