### ISSUE TITLE
MIM serialisatie: waardelijsten die buiten het model gespecificeerd zijn, geef de specificatie hier ook van

### ISSUE THREAD

**Issue by lennartvanbergen** [Geonovum/MIM-Werkomgeving#253]
Codelist en referentielijst zijn vaak buiten het model gespecificeerd. Geef ook hier de specificatie van mee met de MIM export. 

Een referentielijst doet dit al (mits echt gedaan in het informatiemodel)  maar voor codelist is het raden. 

Bv. laat codelist extenden van referentielijst, of neem de structuur van de codelist ook op in het informatiemodel of in een extensie of ... iets/ergens (!).

**Comment by lennartvanbergen-kadaster** [comment]
@PalmJanssen Deze lijkt me iets voor Geonovum, aangezien G de enige is die codelist gebruikt.

**Comment by lennartvanbergen-kadaster** [comment]
Waar specificeer je de waardelijst en de **structuur** van de waarde, als aanwezig: 
- niet, want niet nodig voor data uitwisseling, de eigenschap met een gegeven erin volstaat
**- in het informatiemodel**
- in een specificatie die een aanvulling is op het informatiemodel  

De betekenis specificeer je bij de waardes elders. De betekent van de eigenschap dit dus wel in het informatiemodel, de betekent van de waarde zelf niet. Soms helemaal niet, bv. gemeente deventer, gemeente utrecht, hebben geen definitie nodig. Maar bv. bij _type openbare ruimte_ - bv. plein - is de betekenis wel van belang. 

En hoe vertaalt zich dit naar: 
- wat modelleer je in het IM? --> de betekenis zit in de eigenschap, de structuur van de data ook.
- wat wissel je uit?
- wat heb je nodig voor model-gedreven werken?

Wanneer moet je de hele waardelijst, dus code, waarde, en ook beschrijvende gegevens zoals definitie en toelichting, helemaal weten omdat je dit wilt gebruiken? 
- dropdown lijstjes 
- een code krijgt en je toont deze in het scherm, en de gebruiker wilt weten wat UUID1224 is. 

De identificatie van de waarde bij een codelist en referentielijst is nodig in de data uitwisseling. 
- Voor model-gedreven werken is de waarde zelf: wel nodig. 
- Voor model-gedreven werken is de _definitie_ van de waarde: niet nodig. 

Het punt voor ontwikkelaars is dat de specificatie van de waardelijst nu niet in het informatiemodel te vinden is en als je meer nodig hebt dan de code en/of de waarde dat je nu geen specificatie krijgt van de extra (meta) gegevens. 

Denk aan: de locatie van de waardelijst staat in het informatiemodel. Daar kan je de specificatie opvragen, bv. /locatie/mim-export.xml van sec de waardelijst ... 

Denk aan: altijd een referentie lijst gebruiken als je meer wilt vertellen in het informatiemodel, en dan alle relevante "kolommen" opnemen. 

zie ook:
https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/address-type

**Comment by lennartvanbergen-kadaster** [comment]
Optie 1: modelleer altijd een referentielijst, en neem hier de specificatie op van de data die voor je informatiemodel van belang is. 

Optie 2: los het op voor codelist (immers Enumeratie is al duidelijk en Refentielijst kan al duidelijk gemaakt worden). Spreek dus af dat bij codelijst dat het gaat om:

- een codelijst gaat als uitbreidbare enumeratie
- een lijst met codes
- een lijst met codes en waardes 
- een lijst meer meer specificaties dan code en/of waarde  

Beschrijf dit in MIM of in een extensie en geef een metagegeven op om welke variant het gaat. 

Optie 3: beschrijf goed waar je de _specificatie_ van de externe waardelijst kan vinden en hoe je die kan verwerken - als software (zonder menselijke tussenkomt). De waardelijst heeft al een locatie, maar dat is de locatie van de waardelijst zelf en niet van de _specificatie_ van de waardelijst. 

Kunnen de organisaties die vooral codelijst gebruiken hierin de lead nemen? Zij lopen immers hier vooral tegenaan.

**Comment by lennartvanbergen-kadaster** [comment]
Voor codelist = de gewone uitbreide enumeratie gaat alles goed. 

voor codelist = de andere 2 waar meer voor nodig is, voorstel wordt nader uitgewerkt door Geonovum.

**Comment by ArjanLoeffen** [comment]
> 

@PalmJanssen Zie ik het goed dat je nog geen voorstel hebt geformuleerd?

**Comment by PalmJanssen** [comment]
Moet ik nog doen

**Comment by PalmJanssen** [comment]
Mijn voorstel is om de codelijst eenvoudig te houden vergelijkbaar met de ISO toepassing: 
`<<CodeList>>` is a flexible enumeration that uses string values for expressing a list of potential values.

A code list can be used to describe an open enumeration.

Requierment: Code lists shall be used if none or only a few of the allowed values are known,
like a likely set, or an initial set.

Wel met de toevoeging dat een Codelijst buiten het model wordt beheerd. (en daar dus tagged values voor moet hebben).

Als je structuur in de codelijst wil definiëren dan kan je een `<<Referentielijst>>` gebruiken.

Actie op de MIM standaard hiervoor is beperkt tot aanpassing van de uitleg. Nu staat er dit:

_'De extern gepubliceerde waardenlijst bevat, naast gewone attributen, ook altijd één specifiek attribuut, met daarin de domeinwaarden die gebruikt mogen/moeten worden in de registratie. In het gebruik is een Codelijst daarom analoog aan een Enumeratie. Welk specifiek attribuut dit is en wat de betekenis daarvan is staat in de codelijst zelf gedefinieerd. '

Hierin gaat het wel over structuur van een codelijst. Kan wat mij betreft er uit. Dat TV zit nu ook niet in MIM.

We moeten denk ik wel iets opnemen over de referentie naar waarden in een codelijst. Voorstel is om dat met een URI te doen die bestaat uit de locatie van een codelijst (TV:Locatie) en de waarde. Dus uri = locatie/waarde. Bijvoorbeeld: www.auto.nl/automerken/mercedes

**Comment by PalmJanssen** [comment]
Voeg toe:

Profielspecificatie: Referentie naar het profiel dat de implementatie beschrijft.

Opmerking: MIM kan een aantal standaard profielen beschrijven. Bijvoorbeeld: Inspire toepassing, genericode.......

**Comment by lennartvanbergen** [comment]
eens

**Comment by PalmJanssen** [comment]
Tekstvoorstel:

Een codelijst wordt gebruikt voor de specificatie van een open waardelijst, een waardelijst waarin geen of nog niet alle waarden zijn gespecificeerd. Daarnaast geldt:
- Een codelijst is altijd extern aan het model gespecificeerd en beheerd.
- Een codelijst heeft geen structuur gedefinieerd in het model maar kan wel een structuur hebben, maar die is dan extern bepaald.

Als je structuur van een codelijst in het model wilt definiëren dan moet je een `<<Referentielijst>>` gebruiken.


Een codelijst heeft een aantal tagged values:

**Locatie (1):** de locatie (vaak een URI of URL) van de codelijst
**Doelformaat (1)**: het format waarin de waarden gepubliceerd zijn. Mogelijk een lijst opnemen van voor de hand liggende formaten: SKOS, CSV, ?
**Datatype** (1): datatype van de waarde. Een primitief type zoals bijvoorbeeld ChararcterString, Date, Integer, etc.
**Waarde item** (0..1): het item (of element) van de lijst dat de waarde representeert. Bijvoorbeeld pref label, label (UK), landnaam, landcode, enz. Alleen ingevuld als de codelijst een structuur heeft.
**Profielspecificatie** (0..1): Referentie naar het profiel dat de implementatie beschrijft. _Opmerking:_ MIM kan een aantal standaard profielen beschrijven. Bijvoorbeeld: Inspire toepassing, genericode.......

**Comment by ArjanLoeffen** [comment]
Vanuit het perspectief van Imvertor: die tagged values moeten nog worden toegevoegd en de beoogde functionaliteit worden beschreven en geïmplementeerd.

**Comment by PalmJanssen** [comment]
Opmerking: Ik stel voor om bij een codelijst niet op te nemen dat het per definitie een openlijst is. Het enige dat telt is dat het een  extern gepubliceerde lijst is.

**Comment by PalmJanssen** [comment]
Blijft als openlijst

**Comment by dkrijtenburg-GNM** [comment]
@PalmJanssen : kan deze worden gesloten nu de IMIM-serialisatie is opgeelverd?

**Comment by PalmJanssen** [comment]
\nee dit is een issue voor de MIM 1.2

**Comment by PalmJanssen** [comment]
Paul Verifieert hoe dit nu in het mim tekstdoc staat en past aan wat nog nodig is.

**Comment by PalmJanssen** [comment]
laatste kennis verwerkt in pull request #341
