### ISSUE TITLE
MIM serialisatie: apart document of bijlage maken

### ISSUE THREAD

**Issue by lennartvanbergen** [Geonovum/MIM-Werkomgeving#255]
De XSD is een deliverable, een voorbeeld XML ook en een bijlage in de re-spec waarin wat wordt uitgelegd over de serialisatie. T.z.t. wordt het een bijlage, bij 1.1 (1.1.0.) kunnen we wellicht geen bijlage achteraf toevoegen, en moeten we het nog even net wat anders oplossen.

**Comment by ArjanLoeffen** [comment]
Hier uitleggen hoe ref-elementen moeten worden begrepen. Zie #250 .

**Comment by lennartvanbergen** [comment]
@PalmJanssen deze stap zijn we nu aan toe. Zou jij willen aangeven waar we dit publiceren? Als service product bv. Uiteindelijk hoort deze, net als voor LD, een bijlage worden, zodra mogelijk.

**Comment by PalmJanssen** [comment]
Onderwerp noemen op [MIM website](https://www.geonovum.nl/geo-standaarden/metamodel-informatiemodellering-mim). 
XML schema publiceren als MIM product op [register.geostandaarden.nl](https://register.geostandaarden.nl/)

**Comment by lennartvanbergen** [comment]
zie email van 7 juni aan Paul, Paul heeft inmiddels opgepakt

**Comment by dkrijtenburg-GNM** [comment]
@PalmJanssen : kan deze worden gesloten? - je hebt nog wel aangegeven dat we het XML schema publiceren als MIM product op [register.geostandaarden.nl](https://register.geostandaarden.nl/) - geldt dat nog steeds>

**Comment by PalmJanssen** [comment]
is verwerkt

**Comment by PalmJanssen** [comment]
afgesloten
