### ISSUE TITLE
Toepassing isId kan beter worden beschreven

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/MIM-Werkomgeving#28]
isId is in KKG een UML constructie die de UML specificatie volgt. Het is geen tagged value, dus je kan geen waarde intypen. 

De hele KKG spec zegt niks over welke waarden voor IsId mogelijk zijn. 

In EA moet je de waarde kiezen uit een dropdown box. Daarin staat: true, of false (en niet 1 of 0 of Ja of Nee). Dat is dus de waarde. 

In xs:boolean is het ook 0 of 1 of True of False. Graag daar ook True en False gebruiken en niet 0 of 1.

**Comment by lennartvanbergen-kadaster** [comment]
Dit hoort in 2.2.6. 

Onderstaande tekst vervangt nummer 22 - Id. 

Identificerend - een eigenschap van een objecttype die aangeeft of deze eigenschap uniek identificerend is voor alle objecten in de populatie van objecten van dit objecttype. Dit is uitgedrukt als:
* de metaclass Property isID als het gaat om het modelelement attribuutsoort. De waarde van isID kan zijn: true of false. 
* stereotype <<id>> als het gaat om  het modelelement relatiesoort. 

_Toelichting_
Als er sprake is van een objecttype die meerdere eigenschappen kent met deze aanduiding _isID_ met waarde _true_ , dan betekent dit dat deze eigenschappen als combinatie uniek identificerend zijn (en niet, of niet altijd, op zichzelf).
