### ISSUE TITLE
Onduidelijkheid over de betekenis van "heeft datatype" (sectie 2.8.4.5)

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#283]
Sectie 2.8.4.5 spreekt van het metagegeven "(heeft) datatype". Echter, in sectie 2.8.2.23 wordt ook gesproken over een metagegeven "type", met vrijwel dezelfde betekenis. In het Linked Data model bestaat alleen het metagegeven "type" (als relatie tussen onder meer een Attribuutsoort en een Datatype).

Er lijkt hier sprake te zijn van een foutje: waarschijnlijk is 1 van de 2 overbodig. Voorstel (backwards compatibility): sectie 2.8.4.5 verwijderen.

**Comment by PalmJanssen** [comment]
Ja beide zit er nu in:

![image](https://github.com/Geonovum/MIM-Werkomgeving/assets/9932784/95dcecd3-2510-42c2-9375-905aa1dec191)

https://docs.geostandaarden.nl/mim/mim/#metagegeven-type

https://docs.geostandaarden.nl/mim/mim/#metagegeven-heeft-datatype


Wat is wijsheid:

Het metagegeven Type zou ik niet verwachten om dat het een binding tussen modelelementen beschrijft. Het zou dus bij de serie van [2.4.4](https://docs.geostandaarden.nl/mim/mim/#modelelementbindingen-metagegevens) horen. Maar die kan weer aangepast worden:

heeft datatype (verkorte schrijfwijze datatype) aanpassen naar:

1) heeft datatype (verkorte schrijfwijze type) of
2) heeft type (verkorte schrijfwijze type)

@marco @lennartvanbergen @pmaria

**Comment by architolk** [comment]
In het gehele model (en dus ook metamodel) hanteren we de regel dat de naam van de relatie (in dit geval "heeft datatype") puur de naam van de relatie is, en de rolnaam als naam van de eigenschap (metagegeven) wordt gehanteerd. Dus in dit geval zou het dus "type" zijn als meta-eigenschap en kan "heeft datatype" wordt verwijderd.

**Comment by PalmJanssen** [comment]
dit wordt het: heeft datatype (verkorte schrijfwijze type)

**Comment by Gtrouborst** [comment]
**Besluit**: dit wordt het: _heeft datatype_ (verkorte schrijfwijze: _type_)

Zie laatste comment van @PalmJanssen)
