### ISSUE TITLE
Foutieve verkorte naam voor "heeft enumeratiewaarde" (sectie 2.8.4.9)

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#285]
De verkorte naam in deze sectie is "enumeratiewaarde", echter het huidige model spreekt van "waarde". Hoewel "enumeratiewaarde" eigenlijk beter is, leidt dit tot een breuk in compatibility. Voorstel is om nu nog te spreken van de verkorte waarde "enumeratiewaarde" en in een volgende versie de naam aan te passen in "enumeratiewaarde", met bijbehorende modelwijziging.

**Comment by PalmJanssen** [comment]
@architolk Is dit belangrijk? Ik heb het idee dat er wel meer aanpassingen aan het LD model nodig zijn
De relatie heet nu trouwens 'bevat enumeratiewaarde'

ER moet wel iets aangepast worden, het UML model of https://docs.geostandaarden.nl/mim/mim/#metagegeven-bevat-enumeratiewaarde

**Comment by PalmJanssen** [comment]
wordt "waarde" in hoofdstuk 2 en 3. In  versie 2.0 wordt dit wel gerepareerd.

**Comment by architolk** [comment]
Prima, staat idd nu ook zo in het model: https://modellen.mim-standaard.nl/def/mim/#waarde
Goed om dit soort aanpassingen te doen met het metamodel 2.0
