### ISSUE TITLE
Inconsistente naamgeving keuzeattribuut, keuzerelatiedoel (sectie 2.8.4.12 en 2.8.4.13)

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#286]
Secties 2.8.4.12 en 2.8.4.13 hebben het over "keuzeattribuut" en "keuzerelatiedoel". Origineel was dit: "attribuutkeuze" en "doelkeuze". Die laatste twee zijn meer in lijn met sectie 2.8.4.11 (datatypekeuze). Bovendien is de nieuwe naamgeving niet in lijn met de originele naamgeving, en daarmee niet passend bij een minor release.

Voorstel: herstellen van de naamgeving, zonodig in de toekomst bij een major release namen herzien.

**Comment by PalmJanssen** [comment]
linke met #370

**Comment by PalmJanssen** [comment]
Dit is comment op 1.1.1 maar is ook nog geldig voor 1.2:

Behandeling:
Geprojecteerd op 1.2 (de 1.2 indeling van paragrafen)
De constatering is correct. De naamgeving is niet consequent en niet begrijpelijk.
[2.4.4.12](https://docs.geostandaarden.nl/mim/mim/#metagegeven-heeft-keuzeattribuut) zou heeft attribuutkeuze moeten zijn
[2.4.4.13](https://docs.geostandaarden.nl/mim/mim/#metagegeven-heeft-keuzerelatiedoel) zou heeft relatiedoelkeuze moeten zijn.
Heeft keuzerelatie wordt genoemd in [voorbeeld 5](https://geonovum.github.io/MIM-Werkomgeving/#example-keuze-tussen-2-of-meer-relatiesoorten-relatierollen-elk-afzonderlijk-betekenisvol) en zou heeft relatiekeuze moeten zijn.

Vraag is nu of we dit nog willen aanpassen want het past niet binnen een minor release.

**Comment by PalmJanssen** [comment]
sessie 29-2 akkoord.

**Comment by lennartvanbergen** [comment]
Bij H2 en H3 heeft een naam aanpassing geen impact en bij LD wel dus hetgeen wat uitgewerkt is bij LD maar leidend zijn hier. Het XML export formaat heeft dan de verkeerde naam, dat moeten we een keer rechttrekken, maar dat blijft wel lopen omdat in UML er geen metagegeven is, maar alleen wat blokjes en pijltjes.

**Comment by PalmJanssen** [comment]
Uit sessie 2024-03-20: Er zijn twee backwards comp issues:
- of BW comp met LD toepassing
- of BW comp met serialisatie toepassing.
We kiezen voor BW met LD toepassing. In de Serialisatie toepassing passen we ook niets aan en laten we de oude waarde staan
