### ISSUE TITLE
Transformatie indicatie abstract object te strikt - redactie

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#288]
De huidige transformatie indicatie abstract object (sectie 6.4.9.24, https://docs.geostandaarden.nl/mim/mim/#transformatie-indicatie-abstract-object) kent zowel het rechtstreeks overnemen van de indicatie, als een transformatie naar shacl. Die laatste transformatie gaat er vanuit dat zowel de type-triple naar de abstracte klasse als de niet-abstracte subklasse aanwezig zijn. Dat hoeft niet zo te zijn (en zal in de praktijk vaak juist niet het geval zijn: een triple die afleidbaar is, moet er toch zijn voordat de shacl-regel wordt getoetst).

Voorstel: deze extra shacl regel weghalen uit de transformatie.

**Comment by architolk** [comment]
Ik ben het eens met het voorstel van de indiener :-)

**Comment by Gtrouborst** [comment]
@architolk, begrijp ik goed dat het om de met geel gemarkeerde regel in onderstaand screenshot gaat?
![image](https://github.com/Geonovum/MIM-Werkomgeving/assets/36916421/9a58b49f-4c86-40d2-8891-eb10d2ef6518)

**Comment by Gtrouborst** [comment]
@architolk @pmaria: zou één van jullie dit willen oppakken? Jullie zitten beter in deze materie.
