### ISSUE TITLE
De betekenis van mim:locatie is niet consistent doorgevoerd

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#289]
In sectie 2.8.2.22 (https://docs.geostandaarden.nl/mim/mim/#metagegeven-locatie) staat aangegeven dat dit metagegeven alleen van toepassing is op waardelijsten.

Echter, in sectie 6.4.3 (https://docs.geostandaarden.nl/mim/mim/#uri-munting) wordt juist aangegeven dat dit metagegeven van belang is bij het munten van URI's en dat dit gegeven ook aanwezig (kan zijn) bij een package (en de specialisaties daarvan).

Verzoek is om dit in 1.2 aan te passen in sectie 2.8.2.22 en ook in de tagged-values van het UML profiel, zodat deze namespace goed kan worden opgevoerd zodat bij de transformatie ook de juiste URI's gemunt kunnen worden.

**Comment by architolk** [comment]
Wellicht is deze achterhaald met de introductie van URI op modelelement-niveau?

**Comment by PalmJanssen** [comment]
Locatie bij een waardelijst heeft een andere toepassing dan URI op modelelement niveau. Het is de locatie waar de waardelijst te vinden is dat kan een URI zijn of iets anders. Omdat waardelijst nu ook een Modelelement identificatie krijgt (een URI) kan ik mij voorstellen dat in sommige gevallen de waarde voor Locatie en Modelelement identificatie gelijk is. Is dat erg?
@architolk

**Comment by PalmJanssen** [comment]
URIU gaat Modelelement identificatie heten

**Comment by architolk** [comment]
Locatie was oorspronkelijk gebruikt in hfdst 6 om de transformatie uit te voeren en de modelidentificatie (in LD een URI) te bepalen. Dit gaat nu anders (Modelidentificatie = URI en wordt default gevormd conform regels). Dit moet dan nog wel goed verwerkt worden in de transformatieregels van hfdst 6!

**Comment by PalmJanssen** [comment]
Niet meer relevant.
