### ISSUE TITLE
Maak concept en conceptverwijzing expliciet

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/MIM-Werkomgeving#29]
Input vanuit DSO gegevenscatalogus. via Marco Brattinga, Arjan Santema

Context:
Informatiemodellen worden gebruikt om een beschrijving te geven van de wijze waarop een administratie is georganiseerd. Bij zo’n informatiemodel kan een onderscheid gemaakt worden tussen de beschrijving van het domein zelf (in termen van concepten en hun samenhang), en de beschrijving de administratie (in termen van onder andere entiteittypen, attribuuttypen en relatietypen). Dit onderscheid hoeft niet gemaakt te worden: er kan ook verondersteld worden dat de beschrijving van het domein en de beschrijving van de administratie by design overeen komen. Er kan gekozen worden om een informatiemodel te maken met alleen de beschrijving van de administratie, met verwijzingen naar de beschrijving van het domein, zonder deze beschrijvingen zelf op te nemen in de administratie. En ook kan een informatiemodel alleen bedoeld zijn als een beschrijving van het domein. Alle varianten zijn denkbaar.

Het huidige KKG metamodel mist op dit moment de mogelijkheid om dergelijke nuances aan te brengen. Aangezien de Linked Data vocabulaires altijd expliciet onderscheid maken tussen de beschrijving van het domein zelf (op basis van SKOS concepts) en de beschrijving van de administratie (op basis van RDF/RDFS/OWL en SHACL), is nu geen eenduidige vertaling mogelijk, zonder mogelijk geweld aan te doen aan de beoogde betekenis van het informatiemodel, zoals opgesteld door de originele auteur. De huidige Stelselcatalogus DSO (ook beoogd voor de conceptenbibliotheek van Geonovum), neemt daarom een “veilige” aanname, en vertaalt een KKG informatiemodel altijd puur naar RDF/RDFS/OWL en SHACL, waarbij geen SKOS concepts worden aangemaakt (maar eventueel wel gebruik gemaakt wordt van eigenschappen als skos:definition).

Wens:
Het is gewenst om het onderscheid aan te kunnen geven. Ook is het wenselijk om zo nodig een verwijzing te maken vanuit een informatiemodel-element naar het betreffende concept. Hiermee wordt het mogelijk om op een eenduidige wijze KKG informatiemodellen om te zetten naar Linked Data, met volledig behoudt van de betekenis zoals beoogd door de originele auteur. Dit maakt het mogelijk dat Geonovum haar conceptenbibliotheek kan vullen op basis van KKG informatiemodellen, het Kadaster kan verwijzingen aanbrengen in haar informatiemodellen naar concepten (die bij het Kadaster buiten het informatiemodel worden beheerd), en binnen de context van het DSO kan helderheid ontstaan hoe de DSO Stelselcatalogus gevoed moet worden op basis van de informatiemodellen binnen het DSO.

Mogelijk invulling:
Om inzicht te geven in een mogelijke oplossing die zou voldoen aan onze wens, zou gedacht kunnen worden aan het toevoegen van een stereotype “Concept” en een tag “conceptverwijzing”. Andere oplossingen zijn ook denkbaar. 

Marco

**Comment by PalmJanssen** [comment]
Uitgewerkt in:
20180321 MIM-KKG - link tussen model van begrippen en IM (concepten) - final.pdf

**Comment by dkrijtenburg-GNM** [comment]
clone van #21
