### ISSUE TITLE
van KKG naar MIM

### ISSUE THREAD

**Issue by dkrijtenburg-GNM** [Geonovum/MIM-Werkomgeving#30]

**Comment by dkrijtenburg-GNM** [comment]
zowel MIM als HIM ont-KKG-en, inclusief UML-profiel + totale check

**Comment by JvG-GNM** [comment]
Tekst -> Jan
UML -> Paul

**Comment by JvG-GNM** [comment]
Aangepast:
KING -> VNG Realisatie
KKG -> MIM

**Comment by dkrijtenburg-GNM** [comment]
Mooi!
Nb het Him-document staat hier ook nog vol mee.  Apart klusje dus.

Dick Krijtenburg
Geonovum
senior adviseur
a:Barchman Wuytierslaan 10, 3818 LH Amersfoort
p:Postbus 508, 3800 AM Amersfoort
t: +31 (0)33 4604100 m:+ 31 (0)6 10867322
e: d.krijtenburg@geonovum.nl
i:www.geonovum.nl

________________________________
Van: Jan van Gelder <notifications@github.com>
Verzonden: dinsdag, maart 5, 2019 11:35 AM
Aan: Geonovum/MIM-Werkomgeving
CC: Dick Krijtenburg; Author
Onderwerp: Re: [Geonovum/MIM-Werkomgeving] van KKG naar MIM (#30)


Aangepast:
KING -> VNG Realisatie
KKG -> MIM

**Comment by PalmJanssen** [comment]
Aanpassing in UML EA profiel.
