### ISSUE TITLE
Documentatie: bijschriften ontbreken bij (lijst met) figuren

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/MIM-Werkomgeving#318]
### Issue
De werkversie van de documentatie voor MIM1.2 maakt gebruik van de meest actuele versie van ReSpec. Hierin worden figuren op een andere manier beschreven dat in de MIM-documentatie tot dusver gebruikelijk was. De figuren worden in de nieuwe versie wel weergegeven, maar bijschriften ontbreken. Hierdoor heeft de geautomatiseerde _lijst met figuren_ (_Table of Figures_; _ToF_) geen functie.

### Voorstel
Maak optimaal gebruik van de [mogelijkheden die ReSpec biedt](https://github.com/w3c/respec/wiki/figure) door alle **figuren** te **voorzien van** een **bijschrift**. 

#### Format oud in `markdown` format
```md
![](media/informatiemodel.png)
```
#### Format nieuw in `html` format
```html
<figure id="informatiemodel">
  <img src="media/informatiemodel.png" alt="" />
  <figcaption>Wat is een informatiemodel?</figcaption>
</figure>
```

#### Invulinstructie
| html tag/attribute | instructie |
| --- | --- |
| `id` | Korte unieke naam ter identificatie van de figuur | 
| `src` | Relatieve locatie van de figuur in de repo (Voor het omzetten de oorspronkelijke url). | 
| `figcaption` | Voeg een bijschrift toe |

**Comment by Gtrouborst** [comment]
@dkrijtenburg-GNM 
Er staat een branch klaar met de naam: `318-documentatie-bijschriften-figuren`. Ik heb alle figuren omgezet in het nieuwe format (zie het voorbeeld in de issue-omschrijving). Wil jij in onderstaande bestanden de figuren voorzien van een bijschrift en dan naar die branch pushen? 

| bestandsnaam            | aantal figuren  |
| :----------------------- | ---------------:|
| `AfsprakenRegels.md`    | `01`              |
| `Diagrammen.md`         | `10`              |
| `Inleiding.md`          | `01`              |
| `MetamodelAlgemeen.md`  | `10`              |   
| `MetamodelLD.md`        | `10`              |
| `MetamodelUML.md`       | `09`              |

**Comment by dkrijtenburg-GNM** [comment]
Gerard,

Even gecheckt, maar ik zie nog geen tekst bij de lijst met figuren staan, of ben ik te voorbarig?

Groet

Dick




Van: Gtrouborst ***@***.***>
Verzonden: donderdag 6 juli 2023 11:50
Aan: Geonovum/MIM-Werkomgeving ***@***.***>
CC: Dick Krijtenburg ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Geonovum/MIM-Werkomgeving] Documentatie: bijschriften ontbreken bij (lijst met) figuren (Issue #318)


Closed #318<https://github.com/Geonovum/MIM-Werkomgeving/issues/318> as completed via #323<https://github.com/Geonovum/MIM-Werkomgeving/pull/323>.
