### ISSUE TITLE
TV "Waarde mogelijk onbekend" ook opnemen in Specificatie voor «Gegevensgroep»

### ISSUE THREAD

**Issue by ArjanLoeffen** [Geonovum/MIM-Werkomgeving#32]
TV "Waarde mogelijk onbekend" ook opnemen in Specificatie voor «Gegevensgroep». Het is naar mijn mening mogelijk dat een gegevensgroep niet kan/mag worden opgegeven, zoals dat ook voor attributen geldt.

**Comment by PalmJanssen** [comment]
Er is verwarring of het 'waarde mogelijk onbekend is' moet zijn of 'kenmerk onbekend'. Ontbreekt de data of ontbreekt het kenmerk. Kijk dan ook naar deze definitie (nog doen). Als je het vanuit de kenmerk kant bekijkt dan is het ook voor gegevensgroep van toepassing. Als je het vanuit de data kant bekijkt is het niet van toepassing. Je kan dan ook op de attribuutsoorten in het gegevensgroeptype individueel 'waarde mogelijk onbekend' zetten. Maar is dat zinvol?

Wat betekent het als bij Gegevensgroep 'nee' is ingevuld en voor een aantal attribuutsoorten in het Gegevensgroeptype voor een 'Ja' is ingevuld. En andersom.

**Comment by PalmJanssen** [comment]
Paul gaat het verder uitwerken in notitie.

**Comment by lennartvanbergen-kadaster** [comment]
Alleen kenmerken die een waarde kunnen krijgen hebben dit metagegeven. Er is bewust gekozen om waarde onbekend alleen hierop te specificeren. 

Dat dit betekent dat we op elk attribuut dan op ja gezet moet worden, tsja, dat is 5 minuten werk. Vind ik niet zinvol om voor dergelijke tijdwinsten een specificatie op te stellen.
