### ISSUE TITLE
Documentatie: tussenkoppen tag geven

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/MIM-Werkomgeving#321]
### Issue
Veel tussenkoppen in MIM1.1.1 zijn dikgedrukte tekst. De koppen hebben daardoor alleen visueel betekenis, maar niet inhoudelijk.

### Voorstel
Voorzie alle koppen een markdown of html tag

**Comment by PalmJanssen** [comment]
besluit: akkoord

**Comment by Gtrouborst** [comment]
Hierin een grote slag gemaakt. Voor versie 1.2 al een flinke verbetering. Voor versie 2.0 is het mooi om de algehele structuur weer eens kritisch onder de lopen te nemen.
