### ISSUE TITLE
Aspect "waarde" ontbreekt in de tekst

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#33]
In het figuur wordt een relatie afgebeeld tussen een enumeratie en een waarde. Deze relatie komt niet terug als aspect in de tekst. Hierdoor ontbreekt de definitie van dit aspect.

- [ ] Toevoegen van het aspect in de tabel van enumeratie.

**Comment by PalmJanssen** [comment]
zie #36

**Comment by architolk** [comment]
Zie ook issue #55: dit element ontbreekt in de specificatietabel van enumeratie.

**Comment by PalmJanssen** [comment]
Zie ook #57
