### ISSUE TITLE
Foutje in Respec documentatie van MIM

### ISSUE THREAD

**Issue by melsk-r** [Geonovum/MIM-Werkomgeving#335]
In de Respec documentatie van het MIM komt na paragraaf '2.8.3 Specificatie metagegevens modelelement bindingen' paragraaf '2.8.4 Structuur metamodel'. Ik vermoed dat die laatste paragraaf titel er per ongeluk in terecht is gekomen want de paragrafen 2.8.4.1 t/m 2.8.4.14 lijken me juist thuis te horen onder paragraaf 2.8.3.

**Comment by Gtrouborst** [comment]
@melsk-r Ik zie dit inderdaad terug in de laatste gepubliceerde versie (**MIM 1.1.1**). Op dit moment werken aan [**MIM 1.2**](https://geonovum.github.io/MIM-Werkomgeving/#modelelementbindingen-metagegevens). Hierin is de structuur van het hoofdstuk herzien (en daarmee hopelijk verbeterd). Het issue dat jij aankaart komt hierin niet meer voor.
