### ISSUE TITLE
Aspect "union element" ontbreekt in de tekst

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#34]
In het figuur wordt een relatie afgebeeld tussen een union en een union element. Deze relatie komt niet terug als aspect in de tekst. Hierdoor ontbreekt de definitie van dit aspect.

- [ ] Toevoegen van het aspect in de tabel van union.

**Comment by PalmJanssen** [comment]
zie #36

**Comment by architolk** [comment]
Zie ook issue #55: dit element ontbreekt in de specificatietabel van union

**Comment by PalmJanssen** [comment]
Zie ook #57
