### ISSUE TITLE
Aspect "data element" ontbreekt in de tekst

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#35]
In het figuur wordt een relatie afgebeeld tussen een gestructureerd datatype en een data element. Deze relatie komt niet terug als aspect in de tekst. Hierdoor ontbreekt de definitie van dit aspect.

- [ ] Toevoegen van het aspect in de tabel van gestructureerd datatype.

**Comment by PalmJanssen** [comment]
zie #36

**Comment by architolk** [comment]
Zie ook issue #55: dit element ontbreekt in de specificatietabel van gestructureerd datatype

**Comment by PalmJanssen** [comment]
Zie ook #57
