### ISSUE TITLE
Pas voor interne referenties in het document respec's inner document expansion toe

### ISSUE THREAD

**Issue by pmaria** [Geonovum/MIM-Werkomgeving#358]
Momenteel worden er vaak custom links gedefinieerd naar interne paragrafen en figuren. Dit leidt snel tot broken links. Zie #352.

Het beste is om overal gebruik te maken van  "Inner-document expansion" zoals beschreven in https://respec.org/docs/#reference-shorthands.

**Comment by Gtrouborst** [comment]
Wijzigingen meegenomen in #357
