### ISSUE TITLE
Aspect "referentie element" ontbreekt in de tekst

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#36]
In het figuur wordt een relatie afgebeeld tussen een referentielijst en een referentie element. Deze relatie komt niet terug als aspect in de tekst. Hierdoor ontbreekt de definitie van dit aspect.

- [ ] Toevoegen van het aspect in de tabel van referentielijst.

**Comment by PalmJanssen** [comment]
Deze referenties zijn inherent aan het algemene UML profiel. Opname ervan in het MIM profiel is niet nodig omdat ze niet benoemd in een instantie van dit metamodel terugkomen.

Noot: Het kan zijn dat het voor een toepassing van dit metamodel in een andere omgeving (linked data) het wel nodig is om deze modelelementen te gebruiken en van definities te voorzien.

**Comment by architolk** [comment]
Zie ook issue #55: dit element ontbreekt in de specificatietabel van referentielijst. Het bijzonder is dat we dit voor andere onderdelen wel doen, en het veld wel gewoon in het diagram staat. Ik zou verwachten dat we een volledige beschrijving opnemen in de specificatietabel. We missen nu ook de definitie.

**Comment by PalmJanssen** [comment]
Dit is hetzelfde als issue #57.
Mijn voorstel is om dit wel volledig te gaan beschrijven. Dus bijvoorbeeld bij Referentielijst: 'bezit element' (van type Referentie element)
