### ISSUE TITLE
6.4.5.9 en 6.4.10 extra controle of UML-aanpassingen ook in LD zijn opgenomen

### ISSUE THREAD

**Issue by dkrijtenburg-GNM** [Geonovum/MIM-Werkomgeving#365]
overall extra controle of UML-aanpassingen ook in LD zijn opgenomen

nav opmerking Gerald Groot Roessink

6.4.5.9 en 6.4.10
Referentielijst  is een waardenlijst die buiten het model is gedefinieerd i.t.t. tot een Enumeratie.  Dit MIM-element  is te transformeren naar een Nodeshape met een sh:targetClass naar een owl:Class (6.4.5.9). 
In paragraaf 6.4.10 voor de omgekeerde transformatie staat in de tabel:  mim:Referentielijst = Een nodeshape die gelinkt is aan een skos:inScheme of skos:member. Dat werkt ook door in de CONSTRUCT-queries  in https://docs.geostandaarden.nl/mim/vv-st-mim-20200225/media/rdf2mim.sparql. Klopt dat wel?

Zorg dat deze paragrafen en het query voorbeeld in lijn zijn. Vooralsnog ga ik er van uit dat 6.4.5.9 klopt

**Comment by pmaria** [comment]
Opgesplitst in aparte issues:

[ ] - #477

**Comment by lennartvanbergen** [comment]
merk op, het metagegeven tekstopmaak is ook nieuw (staat sinds 1.2 in UML en in LD maar nog niet in 6.4)
