### ISSUE TITLE
Aspect "Identificerend" bij ReferentieElement abusievelijk "Identificatie" genoemd

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#37]
In het originele document staat bij ReferentieElement abusievelijk "Identificatie" voor het aspect "Identificerend".

- [ ] Aanpassen in het originele document.

**Comment by lennartvanbergen-kadaster** [comment]
Betreft 2.3.6. Specificatie voor «Referentie element» - bijna onderste rij in tabel

**Comment by PalmJanssen** [comment]
betreft 2.3.3 ipv 2.3.6

**Comment by PalmJanssen** [comment]
Is door lennart aangepast
