### ISSUE TITLE
2.4.3.28	 - profielspecificatie

### ISSUE THREAD

**Issue by dkrijtenburg-GNM** [Geonovum/MIM-Werkomgeving#376]
nav opmerking richard de wit

2.4.3.28	
Onduidelijk wat met Profielspecificatie bedoeld wordt.	

Om het duidelijker te maken aanvullen met voorbeeld(en).

**Comment by PalmJanssen** [comment]
@lennartvanbergen @thies Hebben jullie voorbeelden?

**Comment by ThiesMesdag** [comment]
Ik heb hier naar gekeken en geen passend voorbeeld kunnen vinden. We kunnen het ook deze paragraaf eerst weglaten wat mij betreft.

**Comment by PalmJanssen** [comment]
Geen voorbeeld opgenomen.
