### ISSUE TITLE
Modelaspecten versus meta-aspecten

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#38]
Bepaalde eigenschappen zijn werkelijk onderdeel van het model, andere eigenschappen zijn meer toelichtend, annoterend van aard. Wellicht zou een onderscheid gemaakt kunnen worden in owl:ObjectProperty/owl:DatatypeProperty versus owl:AnnotationProperty.

- [ ] Vaststellen wat we willen kiezen, en hoe dit in de tekst afgebeeld kan worden;
- [ ] Keuze per aspect. Daarbij kan ook gekeken worden naar overeenkomstige aspecten in bv RDFS en SKOS.

**Comment by dkrijtenburg-GNM** [comment]
beoordelen of dit in 1.1 opgepakt moet worden

**Comment by architolk** [comment]
Dit betreft een aanpassing in het RDF-deel van het MIM model. Wel zou het goed zijn om dit ook in de specificatie-tekst terug te laten komen.

**Comment by lennartvanbergen-kadaster** [comment]
@architolk  kan je 2 voorbeelden geven?

**Comment by architolk** [comment]
Ja, een mim:naam of een mim:definitie betreffen annotaties op het model (dwz: alleen voor mensen een betekenis), terwijl mim:subtype of mim:aggregatietype daadwerkelijk betekenis hebben voor het model (dwz: de computer moet er wat mee bij het beoordelen van het model).

**Comment by architolk** [comment]
@dkrijtenburg-GNM : deze hoeft wat mij betreft niet mee in 1.1, tenzij er vanuit de review opmerkingen op komen.
