### ISSUE TITLE
5.9 Historie redactie

### ISSUE THREAD

**Issue by dkrijtenburg-GNM** [Geonovum/MIM-Werkomgeving#386]
nav opmerking jacob vos

5.9 Historie	
In deze paragraaf wordt nog uitgegaan van de 'deprecated' metagegevens 'Indicatie materiële historie' en 'indicatie formele historie'.	

In deze paragraaf de metagegevens 'heeft tijdlijn geldigheid' en 'heeft tijdlijn registratie'.gebruiken.

**Comment by PalmJanssen** [comment]
verwerkt in master
