### ISSUE TITLE
3.2.1.1 «Objecttype» - en andere paragrafen	URI-verplicht

### ISSUE THREAD

**Issue by dkrijtenburg-GNM** [Geonovum/MIM-Werkomgeving#387]
nav opmerking jacob vos

3.2.1.1 «Objecttype» - en andere paragrafen	

We vinden het te ver gaan dat de metagegevens 'URI' en 'Is gedefinieerd in' worden verplicht gesteld voor objecttypen, attribuutsoorten, relatiesoorten, enz. Hiervan zien we de toegevoegde waarde niet. En het geeft extra beheerlast.	

Metagegevens 'URI' en 'Is gedefinieerd in' optioneel maken.

**Comment by pmaria** [comment]
Het argument van extra beheerlast is in mijn optiek niet terecht.

Het metagegeven URI is weliswaar verplicht gesteld, maar er is ook een defaultwaarde voor gespecificeerd (`{basisURI} + {modelelement.naam}`, waar basisURI ook een default waarde heeft van `urn:modelelement: + {informatiemodel.naam}: + {package.naam}` ). Dit is vergelijkbaar met andere metagegevens met een defaultwaarde.

Daarmee is de beheerlast van deze eigenschap, wanneer men er niet in geinteresseerd is, nihil.
Het betekent wel dat tooling zoals imvertor deze eigenschap moet kunnen afleiden. (@ArjanLoeffen hoe zie jij dit?)

Mijn voorstel is om dit verplicht te laten, maar nog verder te verduidelijken.
Ook zouden de relevante metagegevens opgenomen moeten worden in https://geonovum.github.io/MIM-Werkomgeving/#defaultwaarden.

**Comment by ArjanLoeffen** [comment]
Uit eerdere discussies is gebleken dat men het informatiemodel in EA als uitgangspunt neemt; later toegevoegde/afgeleide info is geen onderdeel van "het model". Als men dit nog steeds zo ziet (ik niet, trouwens), dan moet deze info helaas worden ingevoerd en klopt de opmerking van Dick.

**Comment by architolk** [comment]
Eens met Pano. Met betrekking tot wat het metamodel van MIM is: dat staat in Hoofdstuk 2. Het UML model en het LD model zijn daarvan afgeleiden. Daarbij geldt dat EA gebruikt kan worden om het MIM model te maken, waarbij je vervolgens MIM-compliant exports kunt genereren (documenten, "platte" XML of LD (XML/RDF, Turtle, JSON-LD representaties). In die exports is het terecht dat het ontbreken van een verplicht veld zonder dat er een default waarde is, als "fout" wordt aangemerkt (waarbij mijn voorkeur wel zou zijn dat de exporter probeert om toch nog een export te maken - dat is vooral handig is de situatie die Thies ook aangeeft bij Imvertor). In geval van een default waarde (zoals hier) zou er nooit een fout moeten komen, maar zou de export-faciliteit de default waarde moeten gebruiken m.i.

**Comment by lennartvanbergen** [comment]
Gaat dit om modelelement identificatie? 

Ik snap ook niet waarom dit URI heet. Mijn inziens hoort dit: modelelement identificatie zijn, met als datatype ervan een URI.

**Comment by ThiesMesdag** [comment]
Uri vervangen door modelelement identificatie met pull-request https://github.com/Geonovum/MIM-Werkomgeving/pull/500

**Comment by lennartvanbergen** [comment]
@ThiesMesdag staat deze terecht in todo? Of is deze opgelost via andere issues?

**Comment by ThiesMesdag** [comment]
Is inderdaad opgelost met pr https://github.com/Geonovum/MIM-Werkomgeving/pull/500, zal hem op done zetten.

**Comment by PalmJanssen** [comment]
uiteindelijke aanpassing:

De metaklasse Modelelement heeft een metagegeven `Identificatie` gekregen.

Definitie: De identificatie van een modelelement.
