### ISSUE TITLE
2.4.2.2 Metagegeven: URI i.c.m. 2.4.3.24 Metagegeven: Locatie	 - opmaak

### ISSUE THREAD

**Issue by dkrijtenburg-GNM** [Geonovum/MIM-Werkomgeving#390]
nav opmerking jacob vos

2.4.2.2 Metagegeven: URI i.c.m. 2.4.3.24 Metagegeven: Locatie	

"In de Toelichting staat dat de verwijzing mogelijk een URI is. Nu het nieuwe metagegeven 'URI' is geïntroduceerd, zorgt deze toelichting misschien voor verwarring. Namelijk over het verschil tussen 'Locatie' (gevuld met een URI) en 'URI' gevuld met een URI.

Bij 'Locatie' is 'URI' gebruikt als een soort van datatype (feitelijk een tekenreeks met het patroon van een URI) en bij 'URI' is de naam 'URI' gebruikt als attribuutnaam.

O.b.v. de definities is wel duidelijk dat als 'URI' wordt ingevuld bij een waardelijst het gaat om de identificatie van de waardelijst. En dat als er een URI wordt ingevuld bij 'Locatie' het een link is naar waar je de waardelijst (met z'n waarden) vindt."	

"Twee - niet elkaar uitsluitende - mogelijkheden:

1. Hernoemen van het metagegeven 'URI'. Deze naam zegt semantisch namelijk niets. De benaming doet aan een datatype denken.

2. Het is wellicht goed om het verschil tussen een URI in 'URI' en een URI in 'Locatie' expliciet te benoemen in par. 2.4.3.24."

**Comment by lennartvanbergen** [comment]
Eens met Jacob, is verwarrend. 

In ieder geval een beetje opgelost door aan te geven dat het hier om het datatype URI gaat en niet om het metagegeven URI.

Vervolg nodig: nader bespreken over gerelateerd onderwerp. Dat we een nieuw metagegeven URI hebben vind ik wat apart. Een URI is in MIM een datatype, of een specifieke vorm van een locatie, te weten een locatie op het internet. Liever verwijder ik URI.

**Comment by lennartvanbergen** [comment]
Deze wordt opgelost via #388 
(te weten dat deze niet de technische naam URI krijgt, maar model identificatie en modelelement identificatie, met als datatype URI)
