### ISSUE TITLE
overal - hoofd klein redactie

### ISSUE THREAD

**Issue by dkrijtenburg-GNM** [Geonovum/MIM-Werkomgeving#391]
nav opmerking wilko quak

**aanpakken, maar vervolgens ook iets voor 2.0 want werkt in alle modellen door ivm uitwisseling**

overal	
"Het MIM is niet altijd consequent met het gebruik van hoofdletter en kleine letters in de waardes van metagegevens. Zo kan het metagegeven 'Informatiemodel type' de waarde 'conceptueel' of 'logisch' hebben terwijl 'Relatiemodelleringstype' de waardes 'Relatiesoort leidend' of 'Relatierol leidend'. Hieruit zou je ten onrechte kunnen opmaken dat het bij het maken van een model niet uitmaakt of je kleine of grote letters gebruik voor deze metagegevens. 

Deze keuzevrijheid is onwenselijk omdat in uitwisselling van modellen nu beide waardes voorkomen en een vraag: geef mij alle informatiemodellen waarbij 'Informatiemodel type' de waarde 'conceptueel' heeft een onverwacht antwoord geeft."	

maak expliciet duidelijk dat waardes metagegevens hoofdlettergevoelig zijn. En ten overvloede ook dat de naam van het metagegeven hoofdlettergevoelig is.

**Comment by Gtrouborst** [comment]
Aangepast en verwerkt in de documentatie.
