### ISSUE TITLE
3.1.3.2	 vier of vijf - redactie

### ISSUE THREAD

**Issue by dkrijtenburg-GNM** [Geonovum/MIM-Werkomgeving#396]
nav opmerking arjan loeffen

3.1.3.2	
Er zijn vier situaties waarin een keuze toegepast wordt:	

"Nee, dat zijn  er 5. Dat is trouwens één meer dan in 1.1.1
Even verderop 3.1.3 wordt gesuggereerd dat het er 4 zijn. "

**Comment by Gtrouborst** [comment]
Zin aangepast en verwerkt in documentatie
