### ISSUE TITLE
EA type van Relatierol dient AssociationEnd te zijn.

### ISSUE THREAD

**Issue by LentjesP** [Geonovum/MIM-Werkomgeving#4]
In par 2.1.3 - View 4 staat dat MIM metaclass "Relatierol" EA type Attribute heeft. Dit moet echter AssociationEnd zijn. UML class Property is wel juist.

**Comment by PalmJanssen** [comment]
nog controleren

**Comment by PalmJanssen** [comment]
Is inderdaad een fout. Verbeterd in:

Relatierol In   Sparx EA
--
AssociationEnd
AssociationEnd
AssociationEnd
