### ISSUE TITLE
Tabel "datatype" gaat eigenlijk over "primitief datatype"

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#40]
In het originele document wordt gesproken over "Specificatie voor datatype". Dit is een typefout. De specificatie betreft die van primitief datatype.

- [ ] Aanpassen tekst in originele document.
- [ ] Shape datatype (de abstracte) leegmaken, de eigenschappen verhuizen (of niet...)
- [ ] Shape primitief datatype vullen, de eigenschappen verhuizen door aanpassing van de tekst.

**Comment by dkrijtenburg-GNM** [comment]
lijkt iets voor 1.0.1, toch?

**Comment by lennartvanbergen-kadaster** [comment]
Ja, 1.0.1 maar ik kan al 10 minuten niet vinden in het document... welke paragraaf/pagina gaat dit om?   
@architolk
