### ISSUE TITLE
overal redactie

### ISSUE THREAD

**Issue by dkrijtenburg-GNM** [Geonovum/MIM-Werkomgeving#402]
nav opmerking arjan loeffen

relatiemodelleringstype met of zonder s schrijven

consistent maken

**Comment by Gtrouborst** [comment]
Aangepast en verwerkt in documentatie: gekozen spelling: `relatiemodelleringstype` (met `s`)

> [!WARNING]
> @architolk, @pmaria: In LD kwamen URL's met beide spellingen voor:
>  - `http://bp4mc2.org/def/mim#relatiemodelleringtype` (zonder `s`)
>  - `http://bp4mc2.org/def/mim#relatiemodelleringstype` (met `s`)
>  In de documentatie is alles (incl. URL's): relatiemodelleringstype (met s). Willen jullie dat ook op <strong>BP4mc<sup>2</sup></strong> aanpassen?

**Comment by architolk** [comment]
In de ontologie staat het inderdaad al goed: https://modellen.mim-standaard.nl/def/mim/#relatiemodelleringstype
