### ISSUE TITLE
Aspect "authentiek" heeft meerdere definities

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#43]
Zie ook -> #54 

Voorstel algemene definitie:
Aanduiding of het aspect een authentiek gegeven betreft.

**Comment by lennartvanbergen-kadaster** [comment]
Metagegeven: Authentiek
Definitie Authentiek
Aanduiding of het kenmerk een authentiek gegeven betreft.
Toelichting
Bijvoorbeeld: authentiek. 
Dit is zo voor bijvoorbeeld het burger service nummer van een natuurlijk persoon. In de wet van bijvoorbeeld een basisregistratie ligt vast welke gegevens authentiek zijn. 
Een kenmerk is authentiek indien de juistheid (hoogwaardige kwaliteit) van het gegeven gewaarborgd wordt via  formele inwinningsprocessen en wettelijk regelingen. Authentieke gegevens moeten door alle overheidsinstellingen verplicht en zonder nader onderzoek, worden gebruikt bij de uitvoering van publiekrechtelijke taken. 
De in te vullen waarde komt uit: zie Tagged values en waardenbereik tagged values. 
Toepassing: alle modelelementen die een kenmerk (kunnen) zijn van een objecttype.
