### ISSUE TITLE
Aspect "kardinaliteit" heeft meerdere definities

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#44]
Zie ook #54 

Voorstel algemene definitie:
De kardinaliteit geeft aan hoeveel keer waarden van dit aspect kunnen voorkomen bij een object van het betreffende objecttype

**Comment by lennartvanbergen-kadaster** [comment]
Metagegeven: Kardinaliteit 
Definitie Kardinaliteit
De kardinaliteit geeft aan hoeveel keer waarden van dit kenmerk van een object kunnen voorkomen bij een object van het betreffende objecttype.
Toelichting
0..1: is soms niet beschikbaar 
1 : is altijd beschikbaar 
0..*: is niet altijd beschikbaar, kan meerdere malen voorkomen 
1..*: is altijd beschikbaar, kan meerdere malen voorkomen 
Indien een attribuutsoort deel uit maakt van een gegevensgroeptype, dan wordt de kardinaliteit vermeld van het attribuutsoort binnen het gegevensgroeptype. Voor de uiteindelijke kardinaliteit van hoe vaak een gegeven voorkomt bij het object moet rekening gehouden worden met de kardinaliteit van de gegevensgroep en met de kardinaliteit van de attribuutsoort.
Toepassing: alle modelelementen die een kenmerk (kunnen) zijn van een objecttype.
