### ISSUE TITLE
 2.4.3.37	Eenheid  redactie en  waardebereik duidelijk   maken

### ISSUE THREAD

**Issue by dkrijtenburg-GNM** [Geonovum/MIM-Werkomgeving#448]
nav opmerking jesse bakker 	

2.4.3.37	Eenheid	semantisch	

Er wordt gesteld dat een waarde uit https://units-of-measurement.org/ moet worden gebruikt. https://units-of-measurement.org/ is allereerst geen officiele bron van codes, maar een linked data encoding van UCUM met mapping naar verschillende andere eenheid-standaarden. Daarnaast is het onduidelijk welke waarde men zou moeten gebruiken. Is dat de Linked Data URI van de waarde, of 1 van de verschillende codes?	

Vernoem UCUM als standaard en gebruik de officiele specificatie (https://ucum.org/ucum). Beschrijf duidelijk het waardebereik van de waarde van het metagegeven eenheid. Beschrijf duidelijk hoe dit in de linked data taalbinding van MIM toegepast moet worden.

**Comment by architolk** [comment]
Het lijkt in ieder geval raar om in de definitie te verwijzen naar een website. Dit deel zou uit de definitie gehaald kunnen worden. Vervolgens zou in het algemeen verwezen kunnen worden naar UCUM, en dan in het LD stuk aangeven dat je gebruik maakt van de URLs zoals beschikbaar op https://units-of-measurement.org/. Dit lost voor de UML kant nog niets op... Zou er daarvoor niet een datatype o.i.d. moeten komen? Lijkt op een referentielijst? En wat is het primitieve datatype daarbij? is dat een URL? (dat lijkt nu de definitie wel te verplichten), of mag je in de UML-versie ook een code gebruiken?

**Comment by Gtrouborst** [comment]
Meerdere terechte opmerkingen.

1. In de definitie hoort geen URL.
2. Uitwerkingen van het metamodel in UML en LD horen thuis in respectievelijk H3 en H4.
3. In H2 zou dan een verwijzing naar UCUM kunnen komen (als dat de geprefereerde standaard is).
4. In H3 (UML) is `Eenheid` nu een vrij tekstveld (_Tagged Value_) bij `Attribuutsoort` en `Referentielijst`, er wordt m.a.w. niks voorgeschreven.
5. In H4 (LD) kan dan inderdaad een verwijzing naar https://units-of-measurement.org/ opgenomen worden.

**Comment by PalmJanssen** [comment]
@trouborst dinsdag bespreken

**Comment by Gtrouborst** [comment]
@PalmJanssen: zie tekstvoorstel bij [2.4.3.37](https://geonovum.github.io/MIM-Werkomgeving/#metagegeven-eenheid)

**Comment by Gtrouborst** [comment]
Tekst aangepast en verwerkt in documentatie: https://geonovum.github.io/MIM-Werkomgeving/#metagegeven-eenheid. Er is voor gekozen om te verwijzen naar https://units-of-measurement.org/.

**Comment by pmaria** [comment]
Dit issue is gesloten, maar volgens mij is er nog discussie nodig.

Momenteel wordt er in de toelichting verwezen naar het onofficiele https://units-of-measurement.org/ en een overzicht met voorbeelden van codes, maar nog nergens naar de officiele UCUM standaard (https://ucum.org/ucum). Dat lijkt me minimaal nodig.

Nu is er gekozen om de code te gebruiken in de UML taalbinding. De vraag is dan wat we gaan gebruiken aan de LD kant. 
Gezien de onduidelijke status van https://units-of-measurement.org/ neig ik naar in MIM-LD ook gebruiken van dezelfde code met eigenschap `mim:eenheid`. Bij de transformatie naar een ontologie zouden we dan de mogelijkheid van het gebruiken van deze bron kunnen beschrijven. Daarmee houden we de optie open, maar binden we ons niet vast.

@architolk wat is jouw mening?

**Comment by architolk** [comment]
Ik had hier al wat over gezegd: "Het lijkt in ieder geval raar om in de definitie te verwijzen naar een website. Dit deel zou uit de definitie gehaald kunnen worden. Vervolgens zou in het algemeen verwezen kunnen worden naar UCUM, en dan in het LD stuk aangeven dat je gebruik maakt van de URLs zoals beschikbaar op https://units-of-measurement.org/. Dit lost voor de UML kant nog niets op... Zou er daarvoor niet een datatype o.i.d. moeten komen? Lijkt op een referentielijst? En wat is het primitieve datatype daarbij? is dat een URL? (dat lijkt nu de definitie wel te verplichten), of mag je in de UML-versie ook een code gebruiken?". Dus ja, ik zit op jou lijn, maar er moet nog wel wat bij in het metamodel (referentielijst...)

**Comment by lennartvanbergen** [comment]
Misschien gewoon verwijzen naar de BINAS?

https://nl.wikipedia.org/wiki/Natuurkundige_grootheden_en_eenheden

**Comment by ThiesMesdag** [comment]
De officiele internationale standaard van SI wordt beheerd door: [Welcome - BIPM](https://www.bipm.org/en/) en daarbij hebben ze ook een LD pagina op https://si-digital-framework.org/SI?lang=en

Maar ook mogelijk om NEN3610 te volgen

**Comment by PalmJanssen** [comment]
NEN 3610 zegt dit:

![image](https://github.com/Geonovum/MIM-Werkomgeving/assets/9932784/0fcbf61b-3b7d-46a4-b881-bf05dd47d3e3)

**Comment by lennartvanbergen** [comment]
met dank aan Thies

De organisatie die er over gaat is: https://nl.wikipedia.org/wiki/SI-stelsel
Deze geeft aan, kijk op: https://nl.wikipedia.org/wiki/SI-stelsel
Hier heb je de unit of de unit expression van de quantity nodig omdat je een symbool niet goed kan intypen, zodat je: 'm.s-2' invult. Een paar voorbeeldjes neerzetten helpt ook.

Zegt NEN3610 hier niet ook wat over?

**Comment by Gtrouborst** [comment]
Na overleg besluit om te verwijzen naar https://si-digital-framework.org/SI?lang=en

**Comment by lennartvanbergen** [comment]
Ja, maar let op, symbool is een gereserveerd woord. We hebben de unit expression nodig van het symbool. Zoals bv. m2 en niet een m met een kleine 2 erboven. Kijk maar eens bij quantity en daarna op een symbol zoals bij area klikken.

**Comment by Gtrouborst** [comment]
@lennartvanbergen: dank voor deze toevoeging! Ik heb dit aangepast.

**Comment by architolk** [comment]
Als ik nu naar de uitwerking kijk, dan _lijkt_ het alsof de de eenheid van string veld is. Dat lijkt me niet helemaal juist. Het zou een (meta) codelijst moeten zijn (m.i.). Dus in het metamodel in UML en in de LD vocabulaire mappen we dit naar de codelijst (beheert buiten de MIM standaard, zoals de definitie van een codelijst stelt).

**Comment by architolk** [comment]
Eenheid is toegevoegd aan het LD model: in de beschrijving, in de ontologie (mim.ttl en mim-shapes.ttl) en in de transformatie. In de LD situatie is sprake van een mapping naar de URL's uit de UOM lijst. Dit issue kan wat mij betreft gesloten worden.
