### ISSUE TITLE
Aspect "indicatie formele historie" heeft meerdere definities

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#45]
Zie ook -> #54 

Voorstel algemene definitie:
Indicatie of de formele historie van het aspect te bevragen is. Formele historie geeft aan wanneer in de administratie een verandering bekend is, en is verwerkt

**Comment by lennartvanbergen-kadaster** [comment]
Metagegeven: Indicatie formele historie
Definitie Indicatie formele historie
Indicatie of de materiële historie van het kenmerk van het object bijgehouden wordt en te bevragen is. 
Toelichting
Bijvoorbeeld: Nee. Met te bevragen wordt bedoeld, er wordt historie bijgehouden op enerlei wijze, welke op enerlei wijze te bevragen is. 
De in te vullen waarde komt uit: zie Tagged values en waardenbereik tagged values. 
Formele historie geeft aan wanneer in de administratie een verandering bekend is, en is verwerkt.  Verdere toelichting, zie hoofdstuk 3.  
Zie hoofdstuk 3.  
Toepassing: alle modelelementen die een kenmerk (kunnen) zijn van objecttype (objecttype zelf heeft een eigen definitie van herkomst) en in het informatiemodel gedefinieerde datatypes (maar niet bij elementen van datatypes).
