### ISSUE TITLE
4.2.1		redactie	- diagrammen opnieuw genereren

### ISSUE THREAD

**Issue by dkrijtenburg-GNM** [Geonovum/MIM-Werkomgeving#452]
nav opmerking jesse bakker 

4.2.1		redactie	

De **diagrammen** zijn niet meer up-to-date met metamodel algemeen.	

> [!WARNING]
> Synchroniseer diagrammen in: **H2 Metamodel Algemeen**, **H3 Metamodel in UML**, **H4 Metamodel in LD** en **H6 Bijlagen**.
> Zie ook issue: #454 en #456.

**Comment by PalmJanssen** [comment]
Wordt aan gewerkt.
Voor UML zijn aanpassingen uitgevoerd

**Comment by PalmJanssen** [comment]
Voor LD ook uitgevoerd
