### ISSUE TITLE
Redactie - lucht tussen het metamodel algemeen en de twee uitwerkinge

### ISSUE THREAD

**Issue by dkrijtenburg-GNM** [Geonovum/MIM-Werkomgeving#456]
nav opmerking jesse bakker 			

redactie	

Er zit nog heel veel lucht tussen het metamodel algemeen en de twee uitwerkingen. **Het UML-metamodel introduceert zaken die nergens anders staan**. Het metamodel in LD mist hele concepten.	

> [!WARNING]
> Synchroniseer: **H2 Metamodel Algemeen**, **H3 Metamodel in UML**, **H4 Metamodel in LD** en **H6 Bijlagen**.
> Zie ook issue: #454.

> [!TIP]
> Uit issue #457 blijken de **figuren 10**, **23**, **33** en **45** niet overeen te komen met deze de toelichting in 2.3.6.1 “_Het_ `Informatiemodel` _is een_ `Package`, _te weten het hoofdpackage van het informatiemodel, waar alle subpackages die een informatiemodel beschrijven onder vallen, zoals Domein en View en extern._”

**Comment by lennartvanbergen** [comment]
Eentje ervan is erbij gekomen: tekstopmaak in H2 staat nu wel in H3 UML en H4 LD maar niet in 6.4
