### ISSUE TITLE
redactie - tekstuele opmerkingen

### ISSUE THREAD

**Issue by dkrijtenburg-GNM** [Geonovum/MIM-Werkomgeving#457]
N.a.v. opmerkingen van Pieter Bresters een hele verzameling tekstuele punten en een enkele vraag.

Het meeste is tekstueel hieronder per paragraaf:
 - [x] 1.1, 6e punt: er staat denk ik onbedoeld “. en” op het einde
 - [x] 1.3 1e alinea: er staat “oegepast” en mist de t 
 - [x] 1.3 2e alinea: er staat “aar” en mist de m
 - [x] 1.6.5 4e punt: er is geen bijlage 3
 - [x] 2 1e alinea: “beschrijving alle” moet zijn “beschrijving van alle”
 - [x] 2.3.1.2 laatste alinea: de laatste zin loopt raar op het einde
 - [x] 2.3.2.4 in toelichting: daar staat 2x “en de motor”
 - [x] 2.3.3.2: “voer” moet zijn “voor”
 - [x] 2.3.6.1: Figuren 10, 23, 33 en 45 komen niet helemaal overeen met deze Toelichting: “Het informatiemodel is een package, te weten het hoofdpackage van het informatiemodel, waar alle subpackages die een informatiemodel beschrijven onder vallen, zoals Domein en View en extern.” (oppakken in issue: #456
 - [x] 2.4.3.17: Mag dit ook voor een extern gegeven als bv de geometrie van een pand uit de BAG en is dit de plek om de conventie te melden dat je dan een “/” voor de naam van het afgeleide gegeven komt?
 - [x] 2.4.5.2: “altijd moet” -> “moet altijd”
 - [x] 5.1 2e punt: zoals wat?
 - [x] 5.1 opsomming: ik mis de zelf gedefinieerde datatypen in deze opsomming en ik zou de opsomming beginnen met de naam van het soort, zoals die ook in de daaropvolgende hoofstukjes is.
 - [x] 5.2 zou ik nummeren als 5.1.4, want die hoort bij de opsomming in par 5.1
 - [x] 5.7 de 2 voorbeelden hebben een verschillende opmaak.
 - [x] 5.8 is dit plaatje bruikbaar als voorbeeld:  
 - [ ] 5.9.3 Deze paragraaf gaat over het logische niveau. Waarom begint het dan over het conceptuele niveau? 
 - [x] 5.10 De link naar par 2.4.2 klopt niet. Is nu denk ik 2.4.3.17
 - [x] 5.12 2e alinea: “dit is vrijwel altijd is dit bij” is vreemd stukje tekst
 - [x] 5.12 laatste alinea: “le beheerder”?
 - [x] 5.18.1 misschien toevoegen dat de attribuut volgorde wel vaak invloed heeft op de volgorde in de schema’s en dat het er daarom toch vaak toe doet. Bij IMG hebben we een soort afspraak dat ID en geometrie altijd bovenin staan en daarna de rest in alfabetische volgorde.

**Comment by Gtrouborst** [comment]
@PalmJanssen: wat zou hier bedoeld worden?
Pieter geeft aan: **2.3.1.2 laatste alinea: de laatste zin loopt raar op het einde**

Moet er i.p.v. `zijn`, misschien `van` staan? Zo ja, dan vind ik het nog steeds niet duidelijk wat er met deze toevoeging bedoeld wordt.

**Comment by PalmJanssen** [comment]
De zin is pas te begrijpen als je het verhaal er voor gelezen hebt. Met deze aanpassing klopt de zin wel

Was: Immers een onderdeel van een gegeven representeert niet de gehele waarde van een feit en gebruikers van de informatievoorziening zijn meestal niet geïnteresseerd in gedeeltes zijn feiten.

Wordt: Immers een onderdeel van een gegeven representeert niet de gehele waarde van een feit en gebruikers van de informatievoorziening zijn meestal niet geïnteresseerd in gedeeltes van feiten.

**Comment by Gtrouborst** [comment]
Check: dankjewel @PalmJanssen!

**Comment by Gtrouborst** [comment]
@PalmJanssen:
1. Mag je `Indicatie afleidbaar` ook toepassen op een gegeven dat je afleid uit een ander (extern) informatiemodel?
1. Is het niet netter om de opsomming van datatypen in 5.1 uit te breiden van 4 naar 5, met als 5de: 5.1.5 _Gestructureerd datatype representeren als één gegevenselement_?

**Comment by PalmJanssen** [comment]
> 1. Mag je `Indicatie afleidbaar` ook toepassen op een gegeven dat je afleid uit een ander (extern) informatiemodel?

In de definitie zegt MIM daar niet over. In het voorbeeld wel

 _Bijvoorbeeld de ‘eigenaar’ van een huis kan worden afgeleid uit bepaalde andere gegevens die binnen het informatiemodel zijn vastgelegd._

Ik denk niet dat het mag omdat het externe model niet binnen de context van het model valt. Daar kun je dus niets overzeggen. Het gaat om der afhankelijkheid binnen het model aan te geven.

> 2\. Is het niet netter om de opsomming van datatypen in 5.1 uit te breiden van 4 naar 5, met als 5de: 5.1.5 _Gestructureerd datatype representeren als één gegevenselement_?

Ik zou verwachten:
5.1.4 Gestructureerd datatype
5.1.4.1 Gestructureerd datatype represente...

**Comment by Gtrouborst** [comment]
@PB-GNM zie het (bovenstaande) [antwoord van Paul](https://github.com/Geonovum/MIM-Werkomgeving/issues/457#issuecomment-1934125205) op de vraag: 
> Mag je Indicatie afleidbaar ook toepassen op een gegeven dat je afleid uit een ander (extern) informatiemodel?

Dit was naar aanleiding van jou opmerking/vraag: 
> 2.4.3.17: Mag dit ook voor een extern gegeven als bv de geometrie van een pand uit de BAG en is dit de plek om de conventie te melden dat je dan een “/” voor de naam van het afgeleide gegeven komt?

**Comment by Gtrouborst** [comment]
@PB-GNM: het lijkt erop dat er hier een link of iets dergelijks verloren is gegaan:

> 5.8 is dit plaatje bruikbaar als voorbeeld:

Kun jij het plaatje opnieuw delen?

**Comment by Gtrouborst** [comment]
@PalmJanssen: het lijkt erop dat `conceptuele niveau` in de eerste zin van [deze paragraaf](https://docs.geostandaarden.nl/mim/mim/#historie-op-logisch-niveau) eigenlijk `logische niveau` moet zijn. Klopt dat inderdaad?

**Comment by PB-GNM** [comment]
> @PB-GNM: het lijkt erop dat er hier een link of iets dergelijks verloren is gegaan:
> 
> > 5.8 is dit plaatje bruikbaar als voorbeeld:
> 
> Kun jij het plaatje opnieuw delen?
![image](https://github.com/Geonovum/MIM-Werkomgeving/assets/80040145/beb977f0-f600-4f1b-9113-87e4d20c275c)
