### ISSUE TITLE
Aspect "indicatie materiële historie" heeft meerdere definities

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#46]
Zie ook -> #54 

Voorstel algemene definitie:
Indicatie of de materiële historie van het aspect te bevragen is. Materiële historie geeft aan wanneer een verandering is opgetreden in de werkelijkheid die heeft geleid tot verandering de waarde van het aspect.

**Comment by lennartvanbergen-kadaster** [comment]
Metagegeven: Indicatie materiële historie
Definitie Indicatie materiele historie
Indicatie of de materiële historie van het kenmerk van het object te bevragen is. 
Toelichting
Bijvoorbeeld: Ja. Met te bevragen wordt bedoeld, er wordt historie bijgehouden op enerlei wijze, welke op enerlei wijze te bevragen is. 
De in te vullen waarde komt uit: zie Tagged values en waardenbereik tagged values. 
Materiele historie geeft aan wanneer in de administratie een verandering bekend is, en is verwerkt.  Verdere toelichting, zie hoofdstuk 3.  

Toepassing: alle modelelementen die een kenmerk (kunnen) zijn van objecttype (objecttype zelf heeft een eigen definitie van herkomst) en in het informatiemodel gedefinieerde datatypes (maar niet bij elementen van datatypes).
