### ISSUE TITLE
 Paragraaf 6.5

### ISSUE THREAD

**Issue by dkrijtenburg-GNM** [Geonovum/MIM-Werkomgeving#470]
issue uit mail VNG- Robert Melskens op 17-11-2023

Paragraaf 6.5
•	Geef aan in welke paragrafen de issues tot wijzigingen hebben geleid. Issue 202 is bijv. een voorbeeld van een issue waar ik geen idee heb waar de gerelateerde wijziging te vinden is. Er wordt geen paragraafnummer genoemd en er is ook geen relatie met een PR. 
•	De hyperlink '201' leidt naar issue 202.
•	Dat wat in de samenvatting van '245' wordt vermeldt zie ik niet terug in het document.

**Comment by PalmJanssen** [comment]
We begrijpen de wens en gaan kijken of we dit beter kunnen documenteren. Waarschijnlijk nog niet in deze versie.

Issue 201 moet niet naar issue 202 leiden. Dit wordt aangepast.

**Comment by Gtrouborst** [comment]
> Dat wat in de samenvatting van '245' wordt vermeldt zie ik niet terug in het document.

Aangepast, door wijzigingen in de documentstructuur correspondeerde de genoemde paragraaf niet.
