### ISSUE TITLE
Update MIM-LD voor keuze aanpassingen

### ISSUE THREAD

**Issue by pmaria** [Geonovum/MIM-Werkomgeving#479]
Keuze beschrijvingen zijn aangepast / uitgebreid maar nog niet verwerkt in MIM-LD

Relevante PRs:
- https://github.com/Geonovum/MIM-Werkomgeving/pull/309
- https://github.com/Geonovum/MIM-Werkomgeving/pull/332

**Comment by architolk** [comment]
Ik heb gekeken naar de aanpassingen die zijn gedaan, en of dit ook het LD model raakt. Ik denk het niet. Keuze was in het LD model altijd al als een modelconstruct gedefinieerd. Ook use case 5 was al opgenomen (keuze tussen relatiesoorten). Dit is gedaan met een keuzeconstraint, maar dat is wel een expliciet eigen modelelement (dus niet een gewone constraint, maar eentje die juist zegt dat er een keuze moet worden gemaakt tussen relatiesoorten). Wat mij betreft kan dit issue dus gesloten worden.
