### ISSUE TITLE
Aspect "herkomst definitie" heeft meerdere definities

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#48]
Zie ook -> #54 

Voorstel voor de algemene definitie:
De registratie of het informatiemodel waaruit de definitie is overgenomen dan wel een aanduiding die aangeeft uit welke bronnen de definitie is samengesteld.

**Comment by lennartvanbergen-kadaster** [comment]
Metagegeven: Herkomst definitie
Definitie Herkomst definitie
De registratie of het informatiemodel waaruit de definitie is overgenomen dan wel een aanduiding die aangeeft uit welke bronnen de definitie is samengesteld.
Toelichting
Meestal staat in dit metagegeven aangegeven ‘<mijn IM>’, bijvoorbeeld BRK als het om het informatiemodel van de BRK gaat. 
Maar de herkomst van de definitie van het kenmerk adres kan ook als waarde hebben: ‘BAG’. Of ‘BAG en BRK’, waarbij in de documentatie verder uitgelegd wordt wat dit betekent, zoals dat de definitie is overgenomen en vervolgens binnen het eigen informatiemodel verder aangescherpt is, of nader opgesplitst is in twee aparte definities. 
Dit metagegeven is niet bedoeld voor gevallen waarin een definitie alleen geïnspireerd is door een andere definitie, of de andere definitie daadwerkelijke dermate herdefinieerd dat de oorspronkelijke definitie niet meer van toepassing is. 
Het gaat erom dat het voor gebruikers helder is hoe informatie die aan dit informatiemodel voldoet zich verhoudt tot informatie die aan het andere informatiemodel voldoet. Het  metagegeven herkomst definitie schept hier duidelijkheid in. 
Toepassing: alle modelelementen die het metagegeven definitie kennen.
