### ISSUE TITLE
Update MIM-LD voor metagegeven URI en gerelateerde metagegevens

### ISSUE THREAD

**Issue by pmaria** [Geonovum/MIM-Werkomgeving#480]
Metagegeven URI en gerelateerde metagegevens zijn toegevoegd maar nog niet overal verwerkt in MIM-LD.

De plaatjes moeten in zowel metamodel UML als in metamodel LD nog aangepast worden , en de ontologie moet geupdatet worden.

Relevante PRs:
- https://github.com/Geonovum/MIM-Werkomgeving/pull/342

Afhankelijk van:
- https://github.com/Geonovum/MIM-Werkomgeving/issues/387

**Comment by lennartvanbergen** [comment]
en mogelijk model identificatie

**Comment by PalmJanssen** [comment]
Heb nu bij de metaklasse modelelement de tagged value Modelelement identificatie opgenomen:
![image](https://github.com/Geonovum/MIM-Werkomgeving/assets/9932784/7e21650f-62f9-4fc8-870d-4902f2e46fb0)

**Comment by pmaria** [comment]
De kardinaliteit zou 1..1 moeten zijn, toch?

**Comment by PalmJanssen** [comment]
Dat zou je willen, maar het is denk ik voor nu conditioneel, het is nu nog niet voor iedereen model van belang. Het kan dus wel conditioneel voor een model verplicht worden.

**Comment by lennartvanbergen** [comment]
Volgens mij hebben we afgesproken: 

1. model identificatie en modelelement identificatie is verplicht
2. default heeft deze een waarde zoals gespecificeerd in H5
3. in de meeste tools kan je deze waarde ook niet invullen. Als je dat wel wil, dan heb je daar iets voor nodig. Als je deze waarde wilt invullen, oftewel overrulen in EA dan vul je dan een tagged value in (maar deze voeren we niet door in 1.2). Het lijkt mij wel verwarrend om deze _tagged value_ voor het overrulen ook modelelement identificatie te noemen. Want het betreft het overrulen van de default.

**Comment by ThiesMesdag** [comment]
Ik heb het als volgt opgelost (toegevoegd de cursieve tekst):
tekst h2:
Metagegeven: Modelelement identificatie
_Modelelement identificatie De identificatie van een modelelement.
In de meeste modelleertools krijgt een modelelement automatisch een (technische) identificatie. Daarnaast kan een functionele identificatie_ modelelement identificatie bepaald worden aan de hand van de Naam van het modelelement en de Basis-URI van de package waarin het modelelement zich bevindt (op logisch niveau conform de naamgevingsconventies). Dit vormt de default waarde. In de meeste gevallen zal een modelleur dit metagegeven niet expliciet invullen maar uitgaan van de defaultwaarde.

In hoofdstuk 3 in de tabellen bij modelelement identificatie in uml: 

technisch: GUID of functioneel: Tagged value

uitgwerkt in pr 512
