### ISSUE TITLE
Aspect "definitie" heeft meerdere definities

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#49]
Zie ook -> #54 

Voorstel voor de algemene definitie:
De beschrijving van de betekenis van dit modelelement.

**Comment by lennartvanbergen-kadaster** [comment]
Metagegeven: Definitie
Definitie Definitie
De beschrijving van de betekenis van dit modelelement. 
Toelichting
Bijvoorbeeld: Een Pand is de kleinste, bij de totstandkoming functioneel en bouwkundig-constructief zelfstandige eenheid die direct en duurzaam met de aarde is verbonden en betreedbaar en afsluitbaar is.
De definitie volgt, indien aanwezig, de catalogus van de desbetreffende (basis)registratie of informatiemodel, mits deze het modelelement definieert vanuit een informatie en informatiemodel perspectief (er zijn ook andere definities mogelijk vanuit andere perspectieven,  zoals vanuit een juridisch perspectief, of vanuit het perspectief van een model van begrippen, zoals genoemd in paragraaf 1.5. Dergelijke definities kunnen hetzelfde zijn, of op het moment hetzelfde, of verschillend, of aanvullend op elkaar. Het is aan de beheerder van het informatiemodel om hier zorgvuldig mee om te gaan). 
Toepassing: alle modelelementen.
