### ISSUE TITLE
Aspect "herkomst" heeft meerdere definities

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#50]
Zie ook -> #54 

Voorstel voor de algemene definitie:
De registratie waaruit dit modelelement afkomstig is, of het informatiemodel waaraan dit modelelement is ontleend, dan wel de organisatie dit dit modelelement heeft toegevoegd.

**Comment by lennartvanbergen-kadaster** [comment]
Herkomst
Definitie Herkomst 
De registratie of het informatiemodel waaraan het modelelement ontleend is dan wel de eigen organisatie indien het door de eigen organisatie toegevoegd is.
Toelichting
Toepassing: alle modelelementen die een kenmerk (kunnen) zijn van objecttype (objecttype zelf heeft een eigen definitie van herkomst) en in het informatiemodel gedefinieerde datatypes (maar niet bij elementen van datatypes).

**Comment by lennartvanbergen-kadaster** [comment]
Verbeterd. 

Herkomst
Definitie Herkomst 
De registratie of het informatiemodel waaraan het modelelement ontleend is dan wel de eigen organisatie indien het door de eigen organisatie toegevoegd is.
Toelichting
Bijvoorbeeld: de herkomst van het kenmerk begrenzing van een Perceel heeft als waarde: ‘BRK’. BRK staat dan bijvoorbeeld in de bijbehorende documentatie uitgelegd als: de basisregistratie Kadaster.
Bijvoorbeeld: de herkomst van het kenmerk woonadres, wat bijvoorbeeld een «Relatiesoort» is van een Persoon in de basisregistatie Personen naar een Nummeraanduiding in de basisregistratie Adressen en Gebouwen (BAG), heeft als herkomst: ‘BRP’ (de basisregistratie Kadaster). Dit kenmerk woonadres wordt bijgehouden in de BRP en de source kant van de relatie zit in de BRP. De Nummeraanduiding zelf heeft in de BAG veeal als herkomst: BAG. Mochten echter de adresgegevens niet (direct of indirect) uit de BAG komen, maar bijvoorbeeld via een eigen inwinningsproces in een eigen registatie worden bijgehouden, dan de herkomst niet de BAG. 
Toepassing: alle modelelementen die een kenmerk (kunnen) zijn van objecttype (objecttype zelf heeft een eigen definitie van herkomst) en in het informatiemodel gedefinieerde datatypes (maar niet bij elementen van datatypes).
