### ISSUE TITLE
Metagegeven `Mixin` heeft kardinaliteit `0..1` en een defaultwaarde

### ISSUE THREAD

**Issue by pmaria** [Geonovum/MIM-Werkomgeving#507]
In hoofdstuk https://docs.geostandaarden.nl/mim/cv-st-mim-20231018/#generalisatie-tussen-objecttypes heeft metagegeven `Mixin` een kardinaliteit van `0..1`, maar in https://docs.geostandaarden.nl/mim/cv-st-mim-20231018/#defaultwaarden heeft `Mixin` defaultwaarde `Nee`.

De kardinaliteit zou `1..1` moeten zijn.

**Comment by PalmJanssen** [comment]
Klopt we zeggen dat metagegevens met een default waarde verplicht zijn. Vind ik wel weer een rare regel.
