### ISSUE TITLE
Introductie van abstracte klassen

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#51]
Enkele aspecten zijn generiek voor alle modelelementen, en zouden qua normalisatie beter thuishoren bij deze generieke modelelementen. Hierdoor ontbreken nu ook enkele termen die wel relevant zijn voor de definities.

- [ ] Toevoegen van de abstracte metaclass "modelelement";
- [ ] Toevoegen van de abstracte metaclass "aspect", die als subclasses de metaclasses "attribuutsoort", "gegevensgroep" en "relatierol" heeft;
- [ ] Toevoegen van de abstracte metaclass "klasse", die als subclasses de metaclasses "objecttype", "relatieklasse" en "gegevensgroeptype" heeft;
- [ ] Toevoegen van de abstracte metaclass "associatie", die als subclasses de metaclasses "externe koppeling" en "relatiesoort" heeft.

**Comment by dkrijtenburg-GNM** [comment]
graag oordeel of dit in 1.1 al opgepakt moet worden en zo ja, hoe.

**Comment by PalmJanssen** [comment]
overweging:
- voor een deel gebeurt dit door verbijzondering van UML (2.5) metaklassen.
- dit is een normalisatie issue. Vraag is of dat van belang is voor het metamodel.

**Comment by architolk** [comment]
Voor zover ik heb begrepen, is het de bedoeling dat we het MIM kunnen uitdrukken zonder specifiek te verwijzen naar UML metaklassen. De uitdaging waarin ik zit als ik naar het RDF model ga, is dat er geen UML metamodel in RDF bestaat. Ik kan daar dus niet naar verwijzen. Nu lijkt dit ook niet nodig, want ik kan naar de MIM-modellen verwijzen. In enkele gevallen is het echter gewenst om aan te kunnen geven dat bepaalde klassen zusjes/broers van elkaar zijn, en daarvoor heb ik de superklasse nodig. Voor de omzetting naar RDF vanuit de MIM specificatie is dit dus van belang voor het metamodel.

**Comment by PalmJanssen** [comment]
Het model is nu aan UML gekoppeld. Dat is weergegeven door de UML metaklassen als superklassen op te nemen. In versie 1.1 wordt losgekoppeld en alleen in de bijlage of apart hoofdstuk opgenomen als de UML implementatie van MIM. Op dezelfde manier komt er ook een RDF bijlage of hoofdstuk waarbij MIM klassen aan RDF elementen gekoppeld worden.

**Comment by PalmJanssen** [comment]
Kijk ook naar de NEN 2660. Die beschrijft modelelementen los van elke paradigma toepassing en kiest dan pas voor toepassing in een paradigma.

**Comment by architolk** [comment]
In de tekst wordt nu ook gesproken over "Metagegeven". Dit lijkt ook een relevante klasse, en vermoedelijk een synoniem van "Aspect".

**Comment by lennartvanbergen-kadaster** [comment]
Ik hou niet van abstracte metaclasses die als primair doel hebben om te de-normaliseren. 

Ik specificeer liever een bepaald kenmerk op 2 plekken, om te voorkomen dat we een flink aantal "onduidelijk" abstracte classes krijgen die eigenlijk bijna niks betekenen, of 1 op 1 vertaald/overgenomen zijn uit UML, terwijl UML niet perse de bron zou moeten zijn voor dergelijke abstracte classes.

**Comment by lennartvanbergen-kadaster** [comment]
Voorstel: issue sluiten, gewoon de metadata kenmerken per modelelement aangeven. 

@architolk @PalmJanssen @ThiesMesdag bespreken?

**Comment by dkrijtenburg-GNM** [comment]
Akkoord met voorstel. We kiezen er na overleg voor om dit issue te sluiten omdat de inhoud van het model er niet door verandert.
