### ISSUE TITLE
Aspect "naam" heeft meerdere definities

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#53]
Zie ook: -> #54

Voorstel voor de algemene definitie:
Een voor mensen leesbare term die als voorkeursterm wordt gebruikt in de afbeelding van dit modelelement.

**Comment by PalmJanssen** [comment]
Is al gerealiseerd: https://geonovum.github.io/MIM-Werkomgeving/#specificatie-metagegevens
