### ISSUE TITLE
Feasibility of Automatic MIM Annotations for Existing UML Models in EA

### ISSUE THREAD

**Issue by elena-slavco** [Geonovum/MIM-Werkomgeving#547]
Hello MIM Community,

We are exploring the possibility of enhancing our existing UML models within Enterprise Architect (EA) by implementing automatic MIM annotations. Our aim is to facilitate the transformation of these UML data models into OWL, specifically for models that were not originally created with the MIM standards in mind.

We think the MIM annotations can be based on EA elements . See the table below for our findings: 

| MIM| EA element|
| -------- | ------- |
|Objecttype | object of type Class , excluding Relatieklasse objects (see the annotation below)|
|Attribuutsoort | attributes |
|Generalisatie | connector of type Generalization |
|Relatiesoort | connectors of type Aggregation and Association|
|Relatieklasse | objects, whose value is in a PDATA1 for a connector of type Association |
|Relatierol  | destination and source of the connectors |
|Informatiemodel | direct children of root directory in EA |
|Domein | children of the direct children of the root directory|

We believe this automation could significantly improve our transformation process of UML data models to OWL, but we would appreciate insights and opinions from the community. Do you think it's feasible to implement such automatic annotations for existing UML models? Any feedback or experiences you could share would be invaluable.

Thank you for your input.

**Comment by PalmJanssen** [comment]
Hi Elena,

This might be a good way to explore. As I understand you want to explore automated attribution of MIM stereotypes and related tagged values to an existing UML. I normally import the MIM profile in an existing UML and then manually assign the stereotypes to individual modelelements and then synchronize each stereotype to attribute the tagged values. Indeed some work to be done.
Some automation might be welcome.

What would help if you have the info about stereotype extensions for EA (UML) metaclasses. I can send you the MIM EA development file if needed. This info can also be found in the [MIM toolbox file](https://register.geostandaarden.nl/informatiemodel/mim/1.2/).

This is an example of extensions on UML Attribute:
![image](https://github.com/Geonovum/MIM-Werkomgeving/assets/9932784/1960c12d-774c-47d4-8493-331a3e8af9dd)

Extensions of UML Class:

![image](https://github.com/Geonovum/MIM-Werkomgeving/assets/9932784/ca14c8f8-7c3c-46e9-825b-fc843c6ca124)

**Comment by elena-slavco** [comment]
Thank you @PalmJanssen !
