### ISSUE TITLE
Aspect "constraint" ontbreekt in de tekst

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#55]
In het figuur wordt een relatie afgebeeld tussen een objecttype, gegevensgroeptype c.q. relatieklasse en een Constraint. Deze relatie komt niet terug als aspect in de tekst. Hierdoor ontbreekt de definitie van dit aspect.

- [ ] Toevoegen van het aspect in de tabellen van respectievelijk objecttype, gegevensgroeptype en relatieklasse.

**Comment by lennartvanbergen-kadaster** [comment]
Lijkt op #57

**Comment by lennartvanbergen-kadaster** [comment]
@architolk Definitie staat in 2.2.6. item 23?

**Comment by PalmJanssen** [comment]
Klopt. Er is dus een definitie van Constraint in mim. Issue is daarmee opgelost

**Comment by architolk** [comment]
Dit klopt m.i. niet. Er is wel een definitie van de klasse Constraint, maar niet van de relatie constraint. Een klasse is iets anders dan een relatie, dus er zouden ook andere definities zijn? Ik mis dus een rij in de tabel in sectie 2.3.1 voor objecttype, gegevensgroeptype en relatieklasse

**Comment by architolk** [comment]
Zie opmerking op 5 juni: het issue is nog niet opgelost,  het element ontbreekt in sectie 2.3.1
