### ISSUE TITLE
Aspect "gegevensgroep" ontbreekt in de tekst

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#56]
In het figuur wordt een relatie "gegevensgroep" afgebeeld tussen een objecttype en een gegevensgroep, en gegevensgroeptype en gegevensgroep. Deze relatie komt niet terug als aspect in de tekst. Hierdoor ontbreekt de definitie van dit aspect.

- [ ] Toevoegen van het aspect in de tabel van objecttype en gegevensgroeptype

**Comment by lennartvanbergen-kadaster** [comment]
Lijkt op #57 

Betreft het diagram van het metamodel zelf in 2.1.1. Kern. Deze heeft namen gegeven aan hoe meta-modelelementen zich tot elkaar verhouden, maar deze namen zijn niet uitgelegd. 

Wat mij betreft heten deze allemaal: "allowed composition between components" of iets dergelijks, of 'can have as a property' of ... 

Vind ik niet nodig in 1.01. 

Is niet een klein ding. Gaat vermoedelijk nergens mis als we dit pas oplossing in 1.1.

**Comment by lennartvanbergen-kadaster** [comment]
@dkrijtenburg-GNM mag naar 1.1

**Comment by PalmJanssen** [comment]
zie #57
