### ISSUE TITLE
Aspect "attribuut" ontbreekt in de tekst

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#57]
In het figuur wordt een relatie "attribuut" afgebeeld tussen een objecttype en een attribuutsoort, en tussen gegevensgroeptype en attribuutsoort. Deze relatie komt niet terug als aspect in de tekst. Hierdoor ontbreekt de definitie van dit aspect.

- [ ] Toevoegen van het aspect in de tabel van objecttype c.q. gegevensgroeptype.

**Comment by lennartvanbergen-kadaster** [comment]
Betreft het diagram van het metamodel zelf in 2.1.1. Kern. Deze heeft namen gegeven aan hoe meta-modelelementen zich tot elkaar verhouden, maar deze namen zijn niet uitgelegd. 

Wat mij betreft heten deze allemaal: "allowed composition between components" of iets dergelijks, of 'can have as a property' of ... 

Vind ik niet nodig in 1.01. 

Is niet een klein ding. Gaat vermoedelijk nergens mis als we dit pas oplossing in 1.1.

**Comment by lennartvanbergen-kadaster** [comment]
@dkrijtenburg-GNM mag naar 1.1

**Comment by PalmJanssen** [comment]
overweging.
Tekst opnemen bij UML figuur dat namen van relaties en rollen alleen voor leesbaarheid zijn. Het zijn namelijk geen informatieelementen in het metamodel, geen metaklasse of stereotype of tagged value.
Dus bij toepassing MIM komen ze niet terug.

**Comment by architolk** [comment]
Het zijn relaties tussen elementen, en daarmee zijn het "dingen met een naam". Door ze niet in de tekst op te nemen, is onduidelijk wat de betekenis is van deze relatie. Wat mij betreft is voor versie 1.01 voldoende als in de betreffende tabellen een regel wordt toegevoegd met de naam van het aspect ("attribuut" dus), plus een korte definitie wat het betekent. Als dit een grote wijziging is, dan lijkt er iets fundamenteels te zijn gewijzigd, maar dat lijkt me niet: er ontbreekt alleen een stukje uitleg?

**Comment by PalmJanssen** [comment]
Gaan we met Marco bespreken

**Comment by PalmJanssen** [comment]
Nog even over nagedacht.
Deze rol en associatienamen zijn wel nodig om het metamodel volledig te beschrijven. Wat we in versie 1.0 doen is alleen de afzonderlijke modelelementen beschrijven op vooral de meta-aspecten die ze hebben en niet op hun functie (rol) in het model. Bijvoorbeeld een objecttype bezit attribuutsoorten en kan een supertype van een ander objecttype zijn enz. Evengoed hoort een attribuut bij een objecttype. Dit is een wezenlijk onderdeel van het metamodel maar dat nemen we voor kennis aan, maar zo voor de hand ligt dat niet. Dit is een probleem als je het metamodel naar een andere modeltaal converteert.

Oplossing is deze modelelementen wel opnemen in de tabellen. De tabel objecttype krijgt dan toevoegingen als 'bezit attribuut', 'verwijst naar generiek supertype', 'bezit externe relatie met gerelateerd objecttype', 'bezit relatie met targetrol', 'bezit gegevensgroep'. Eigenlijk is het dan pas een model.
@architolk , @lennartvanbergen-kadaster ben benieuwd hoe jullie dat zien.

**Comment by lennartvanbergen-kadaster** [comment]
Goed, je vraagt om een beschouwing. Eerste reactie hieronder. Al vermoed ik dat hier lang over gefilosofeerd kan worden. 

Ik zie 3 mogelijkheden: 

1.
UML kiest hier bewust voor een abstracter niveau van taal. Zoals: component, has, is, classifier, property. Wellicht dat UML en LD dezelfde metataal hanteren. Zo ja, dan kunnen we dat handhaven. 

Bv. property of, element/component of. 
objecttype - attribuutsoort: property of 
objecttype - relatiesoort: property of
objecttype - gegevensgroep: component of 
datatype - data element: component/element of

2. 
Wellicht is ook wel mooi om het functioneler te zien en niet te abstract, en het woord: eigenschap van (property) terug te laten komen, zodat het duidelijk is wat semantische relevante eigenschappen zijn, en wat gewoon structuur constructies zijn. 

Bv.
objecttype - attribuutsoort: eigenschap van object 
objecttype - relatiesoort: eigenschap van object 
objecttype - gegevensgroep: component van object 
gestructureerd datatype - data element: element 

Eigenschap: betekenisvol functioneel kenmerk van het desbetreffende onderwerp van gesprek. 
Component van object: component welke bestaat uit meerdere eigenschappen.
Element: onderdeel van het modelelement, die tezamen met andere onderdelen het modelelement als geheel vormt. 

3. 
Nog een andere insteek: noem ze allemaal: gerelateerd aan, om aan te geven dat er een relatie mogelijk is tussen bepaalde modelelementen, en dat dit tussen bepaalde andere modelelementen dit niet kan. Dat op metamodel niveau de verbanden tussen de elementen dan niet de best mogelijke naam en toelichting ... maar goed, het is niet incorrect.  

--
Ik heb een voorkeur voor de 2e, de meest functionele insteek, maar ik denk dat de meest correcte in de filosofie op dit niveau van metamodellen de 1e is. Maar goed, als hier fundamentele mismatches zijn tussen modelleerstijlen, dan overbrug ik die graag liever (mits correct) met de 2e of de 3e. 
-- 

Persoonlijk vind ik dit onderwerp niet zo van belang. De meerwaarde van MIM is voor mij vooral dat je er op een standaard manier informatiemodellen mee kan maken en dus de modellen vergelijkbaar worden en beter leesbaar en ook beter gegenereerd kunnen worden naar technische formaten, zodat niet elke keer yet another team of ontwikkelaar met zijn eigen smaak weer het zoveelste "optimale" dialect introduceert. 

In geen enkel informatiemodel komt deze metataal voor. Laten we dit dus vooral niet al te complex maken.

**Comment by PalmJanssen** [comment]
Klopt in een informatiemodel komt deze metataal niet voor maar impliciet zit het wel in elk model. In die zin is het essentieel om dat hier aan te geven. In feite staan deze elementnamen al in het MIM 1.0, maar ze zijn niet beschreven. Ik stel voor om de al opgenomen elementnamen te behouden. Dat komt ongeveer overeen met mogelijkheid 2: functionele namen, zo dicht mogelijk bij de rol die de target speelt in de relatie. Ik ga er daarbij van uit dat die rolnamen niet uniek hoeven te zijn binnen het hele metamodel maar wel vanuit binnen elke metaklasse.

dus:
objecttype - attribuutsoort: attribuut
objecttype - relatiesoort: relatietarget
objecttype - gegevensgroep: gegevensgroep
gestructureerd datatype - data element: element
attribuutsoort - datatype: type (waardetype?)
enumeratie - enumeratiewaarde: waarde

**Comment by PalmJanssen** [comment]
objecttype - attribuutsoort: attribuut
def: binding van een attribuutsoort als eigenschap aan een objecttype

objecttype - relatiesoort: relatietarget
def: het doeleinde van een relatie

objecttype - gegevensgroep: gegevensgroep
def: binding van een gegevensgroep als groep van eigenschappen aan een objecttype

attribuutsoort - datatype: type (waardetype?)
def: binding van een datatype als waardetype aan een attribuutsoort

Gegevensgroep - Gegevensgroeptype: groeptype
def: binding van een gegevensgroeptype aan zijn waardetype, een gegevensgroep

Gegevensgroeptype - Gegevensgroep: gegevensgroep
def: binding van een gegevensgroep als groep van eigenschappen aan een gegevensgroeptype

gestructureerd datatype - data element: data element
def: binding van een data element aan een datatype

enumeratie - enumeratiewaarde: waarde
def: binding van een waarde aan een waardelijst

Referentielijst - Referentie element
def: binding van een referentie element aan een referentielijst

Keuze - Keuze element
def: binding van een keuze element aan een keuze

Objecttype, Gegevensgroep, Relatieklasse - Constraint
def: binding van een constraint aan een klasse

Gestructureerd datatype - Data element: data element
def: binding van een data element aan een gestructureerd datatype
