### ISSUE TITLE
Aspect "alias" ontbreekt in de tekst en komt ook niet voor in het UML bestand

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#58]
Het aspect "alias" staat in het originele document niet in het diagram en ook niet in de tabellen, maar het wordt wel gebruikt als attribuut. Deze hoort in het originele document nog worden toegevoegd. In de RDF representatie is deze al toegevoegd, maar nu kan er nog geen verwijzing worden gemaakt (en er is geen definitie).

- [ ] Opnemen alias in het originele document.

**Comment by lennartvanbergen-kadaster** [comment]
In elke tabel in H2 die een rij heeft met daarin: Naam, moet direct eronder ook een rij krijgen met daarin: alias. 

Merk op: alle metadata aspecten hebben een definitie/toelichting, die - als er sprake is van een algemeen/vaker terugkerend metadata aspect - via een link uit moet komen bij:  paragraaf 2.3.1. Algemene metadata aspecten.  De oude paragraaf 2.3.1. wordt 2.3.2. en 2.3.2 wordt 2.3.3 etc

**Comment by lennartvanbergen-kadaster** [comment]
@Paul: bijlage II heeft alias nog niet opgenomen bij metadata aspecten.

**Comment by PalmJanssen** [comment]
Ik heb nog geen idee hoe de alias in een UML diagram getoond moet worden

**Comment by lennartvanbergen-kadaster** [comment]
Is een metadata aspect, zie 4.2 Bijlage II: Modelelementen en metagegevens als diagram

Verder hoeft het alleen bij H2 in de tabellen erbij. Hoeft niet in eerdere diagrammen (daar staan ook geen metadata aspecten).

**Comment by PalmJanssen** [comment]
Alias 0..1 toegevoegd bij alle modelelementen behalve enumeratiewaarde
