### ISSUE TITLE
Waarden voor typeAggregatie c.q. subklassen

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#59]
Het originele MiM document beschrijft niet welke waarden toegestaan zijn voor typeAggregatie. Logisch lijken "Geen", "Aggregatie" en "Compositie". Vanuit RDF perspectief zou er ook wat voor te zeggen zijn om dit niet met een predicate op te lossen, maar met subclasses.

- [ ] Aanpassen van het originele MiM document dat deze waarden beschreven worden;
- [ ] Afweging maken voor predicate versus subclasses.

**Comment by dkrijtenburg-GNM** [comment]
analoog aan authentiek, 2 van de 3

**Comment by lennartvanbergen-kadaster** [comment]
Betreft default modellering in UML. 
https://www.omg.org/spec/UML/2.5/About-UML/

9.9 Classifier Descriptions
9.9.1 AggregationKind [Enumeration]
9.9.1.1 Description
AggregationKind is an Enumeration for specifying the kind of aggregation of a Property.
9.9.1.2 Diagrams
• Properties
Unified Modeling Language 2.5 127
9.9.1.3 Literals
• none
Indicates that the Property has no aggregation.
• shared
Indicates that the Property has shared aggregation.
• composite
Indicates that the Property is aggregated compositely, i.e., the composite object has responsibility for the existence and storage of the composed objects (parts).

We kunnen deze Literals vertalen naar Nederlands, al zie ik de toegevoegde waarde van Nederlandse Literal values niet echt in. Komen deze overeen met de RDF aanpak, of is dit te UML gedacht?

Classifier in UML betekent classificeren op metamodel niveau. Er is in UML bewust gekozen om dit niet als UML-Class met een subclass te definiëren. Ik kan me daar wel wat bij voorstellen, omdat het een subclass van een modellering constructie is, en niet een classificatie van objecten/onderwerpen van gesprek. 

Hoe zit dit in RDF met subclassing? 

@architolk kan jij hier wat over aangeven?

**Comment by lennartvanbergen-kadaster** [comment]
De mogelijke typen zijn alvast beschreven in Algemeen.md bij Algemene metagegevens. Dit is nog in het Engels. Dit moeten we vermoedelijk nog Nederlands maken. Eerst even bespreken, dan verwerken.

**Comment by lennartvanbergen-kadaster** [comment]
Voorstel: 

Nederlandse termen hiervoor. 

None: geen 
Shared: gedeeld. 
Composite: compositie

**Comment by architolk** [comment]
Verwerkt in LD versie. Voorlopig geen subclasses, maar "gewoon" een lijstje.
