### ISSUE TITLE
hoe modelleer je een keuze tussen attribuutsoorten en/of relatiesoorten?

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/MIM-Werkomgeving#61]
De huidige definitie van Union in MIM is niet correct of niet volledig. Er staat dit:
Gestructureerd datatype, waarmee wordt aangegeven dat er meer dan één mogelijkheid is voor het datatype van een attribuut. Het attribuut zelf krijgt als datatype de union. De union biedt een keuze uit verschillende datatypes, elk afzonderlijk beschreven in een union element.

Het is echter: gestructureerd datatype zonder identiteit waarvan precies één van de eigenschappen aanwezig is in elke instantie.

Het faciliteert daarmee een keuze tussen 2 of meer attributen. Dat kan tevens gebruikt worden om tussen twee datatypen te kiezen.

**Comment by PalmJanssen** [comment]
te voorbarig is een 1.1 oplossing.
terugdraaien op versie 1.0.1

**Comment by PalmJanssen** [comment]
stereotype union is een alternatief voor een xor constraint.
Reguirements zijn nog niet bepaald. Waar wil je tussen kiezen:
- verschillende datatypen voor een attribuut. Wordt nu toegepast
- verschillende attribuutsoorten: Wordt nu toegepast
- relatiesoorten, relatieklassen (in onderzoek) kijk ook wat iso doet. Kijk ook naar xsd implementaties: Wordt nu toegepast (door Kadaster)
- gegevensgroepen: wordt nu toegepast

**Comment by PalmJanssen** [comment]
Thies stuurt relatiesoort keuze voorbeeld

**Comment by ThiesMesdag** [comment]
![image](https://user-images.githubusercontent.com/11945098/63281668-7f287780-c2ad-11e9-978b-010e0f7014c7.png)

Een voorbeeld van een union voor de keuze tussen een AKRPersoon (legacy) en een "IMKAD" Persoon uit het model van KIK-Inzage (zie productmodel KBO in "Productmodel KIK-Inzage versie 20170101.zip" op https://zakelijk.kadaster.nl/schemas)

**Comment by ThiesMesdag** [comment]
Als de union een equivalent is van de xor constraint is dit een interessante discussie met betrekking tot de betekenis van de UML xor constraint:
https://stuartgunter.wordpress.com/2011/04/03/opposing-views-on-the-uml-xor-constraint/

**Comment by architolk** [comment]
Op dit moment lijkt in het model Union element alleen een datatype te kunnen hebben (en lijkt daarmee op een Attribuutsoort), maar ook Relatiesoort staat in het voorbeeld van Thies. Dit wordt nu niet ondersteund (en ook niet in de mim voor Linked Data, hoewel de oplossing wel voor de hand lijkt te liggen). Wordt het metamodel hiermee niet erg complex? Lijkt handiger om Union Element dan weg te laten, en direct naar de betreffende onderdelen te gaan (wellicht via een Union :-D)

**Comment by ThiesMesdag** [comment]
In het voorbeeld gaat het om de keuze (xor) tussen een (IMKAD) "Persoon objecttype" of een "AKRHYPPersoon objecttype" als **target** van (een van) de relatie(s) naar de union. 
In de Union zijn de `<<union element>>` namen te interpreteren als de naam van de keuze mogelijkheid. Het zijn volgens mij niet attribuutsoorten binnen een objecttype van het soort `<<union>>` .
Met een constraint tussen twee relaties moet je de relaties waartussen je kan kiezen verschillend benoemen dus modelleer je toch iets anders. Het source object heeft dan relatie1 naar target _Persoon of relatie2 naar target _AKRHYPPersoon, in plaats van 1 relatie naar of het ene of het andere object.

**Comment by PalmJanssen** [comment]
Paul werkt dit verder uit.
- er zijn drie usecases:
keuze tussen: attributen die onder hoofdattribuut vallen
keuze tussen: datatypen die bij één attribuut horen
keuze tussen: associatietargets die bij één associatie horen

Ander aspect: `<<Union>>` wordt `<<Keuze>>`

**Comment by PalmJanssen** [comment]
Dit is een vrij uitgebreide modelleringsconstructie gerealiseerd met  stereotype `<<Keuze>>` (voormalig `<<Union>>'.
Kunnen jullie hier eens naar kijken?
@ThiesMesdag @architolk @lennartvanbergen-kadaster @lvdbrink

**Comment by lennartvanbergen-kadaster** [comment]
Ik heb twee belangrijke eisen aan de oplossing en een paar streefpunten. 

1. Deze aanpassing/verbetering van de modellering zorgt/borgt dat er evenzoveel kenmerken zijn als voor de aanpassing/verbetering. Het is niet de bedoeling dat andere modellering ervoor zorgt dat informatiemodellen "spook" kenmerken moeten introduceren om te voldoen aan de nieuwe modellering, of dat een relatiesoort ineens een UML-property wordt in plaats van een UML-association. 

2. Het moet duidelijk zijn om wat voor soort modelelement het gaat. Oftewel, tot nu toe was het duidelijk dat het om een datatype ging. Het mag niet zo zijn dat we eindigen met een keuze tussen keuze element ("geen idee meer wat dit is") en keuze element ("geen idee meer wat dit is"), waarbij het een mix van attribuutsoort of relatiesoort of datatype te maken, terwijl de lezer van het model mag raden wat het is. 

Verder, 
* mijn inziens is een keuze tussen een datatype zoals String en een relatiesoort onzinnig. Voor mij is het dus erg zinvol om onderscheidt te maken tussen een keuze tussen datatypes (zoals String of Integer, of Vlak of Multivlak) en een keuze tussen (betekenisvolle) kenmerken, zoals de relatie naar natuurlijk persoon Ingezetene, of relatie naar Rechtspersoon. 

* de standaard UML oplossing voor conditioneel verplichte kenmerken in de XOR hoek is een constraint. Deze is echter niet perse erg fijn, omdat constraints niet geautomatiseerd naar XML of JSON of ... kunnen worden vertaald. Maar generatie naar technische formaten is niet het leidende principe bij het maken van een informatiemodel. Ik zou dus graag zien dat we zoveel mogelijk UML en SKOS/OWL volgen voor het modelleren van dit soort XOR constraints, of deze in ieder geval meenemen in de afweging.

**Comment by lennartvanbergen-kadaster** [comment]
Ik zie in de definitie dat deze oplossing niet voldoet aan eis 1 en niet aan eis 2. 

Ad 1. De relatie rechtspersoon is een aanvullend kenmerk geworden, met een naam. Voorheen was die er niet. 

Ter overweging, een modellering zou kunnen zijn: <<keuze relatie>> om aan te geven dat de UML-association qua kenmerken nietszeggend is, en om ook de naam ervan weg te laten. 

Of een stereotype <<keuze>> verplaatsen naar een UML-property in het objecttype, en de UML-Class <<keuze>> als stereotype te geven: <<keuze type>>, analoog aan gegevensgroep en gegevensgroeptype. Hier kunnen we dan ook omgaan met de situatie waarin rechtspersoon wel bedoeld is als bekenisvol kenmerk, en we voorheen geen manieren hadden om dit te modelleren en nu wel. Waarbij aan dat de definitie leeg gelaten mag worden en dat het leeg laten van de definitie betekent dat het geen betekenisvol kenmerk is, maar een modelleertechnisch aanhaking mechanisme. 

Ad 2. Het feit dat de natuurlijke persoon een relatiesoort was, is verdwenen. 

Ter overweging, een modellering zou kunnen zijn: <<relatiesoort>> als uitgaande relatie vanuit <<Keuze>>. 

Tot nu toe vind ik het voorstel niet een verbetering t.a.v. de standaard UML-mogelijkheden.

**Comment by ThiesMesdag** [comment]
Lennart, ik zie niet wat je bedoelt in 
https://github.com/Geonovum/MIM-Werkomgeving/issues/61#issuecomment-534435383
met 

> de relatie rechtspersoon is een aanvullend kenmerk geworden, met een naam. 

Het hele idee is om hier te modelleren dat er een relatie is met de naam _betreft rechtspersoon_  die als target of wel een Natuurlijk Persoon ofwel een NietNatuurlijk Persoon heeft. 

Ad. 2 is dus ook niet aan de hand.

**Comment by lennartvanbergen-kadaster** [comment]
Ah. Dat kon ik niet lezen in het document. Als **betreft rechtspersoon** het (enige) gewenste kenmerk is, die ofwel X ofwel Y is, dan verwacht ik een stereotype < < relatiesoort > > op de relatie. 

Mijn vertrekpunt is 2 relaties, waarbij conditioneel ofwel X, ofwel Y aan de orde is. Dat is de essentie van deze change, de XOR relatie modelleren. Vanuit dit vertrekpunt, is er wel sprake van een 3e kenmerk wat geïntroduceerd wordt. Vandaar de opmerking. 

Bedoel je dat in eerder modelleringen er onterecht 2 relaties waren gemodelleerd en dat nu deze aanpak ook mogelijk is, we gelukkig maar 1 hoeven te modelleren? Zo ja, dan is dit inderdaad wel mooi. Dan is de use case: eigenlijk was er maar 1 kenmerk, en die kan of X of Y zijn, werkend gemodelleerd. En nu maken we het wel mogelijk, met maar 1 kenmerk. Ok, is ook een use case. 

Maar de belangrijkste use case is de XOR. Hoe doe je dat als er wel twee relaties zijn, en ofwel de ene, ofwel de andere is verplicht. 
* Deze twee relaties wil ik niet zien verdwijnen in de < < Keuze > > . 
* Hoe doe je deze use case dan, zonder een derde kenmerk te introduceren?

**Comment by lennartvanbergen-kadaster** [comment]
Ad 2. 

Ik mis relatiesoort bij betreft rechtspersoon. Ik nam dus aan dat hier geen < < relatiesoort > > aan de orde was, maar een betekenisloze aankoppeling op de XOR/Keuze. Vandaar dat het bij mij niet lekker loopt bij 2. Maar, stel dat ik deze wel lees als: < < relatie soort > > ... dan lijkt het de bedoeling dat in het < < keuze > > impliciet de < < relatiesoort > > gelezen moet worden bij elk < < keuze element > > ? 

Is dat zo? Dit heb ik niet gelezen in het begeleidend document. 

Zo'n aanpak is elegant mbt de metadata, want als je inderdaad vanuit het objecttype denkt kan je alle metadata daar kwijt, en dan verschuift dat niet naar de keuze. 

Ik zie nu een derde eis: 

3. het oorspronkelijk type modelelement mag niet veranderen door de modellering van keuze.  Oftewel, als het een relatiesoort was, moet het een relatiesoort blijven.

**Comment by ThiesMesdag** [comment]
De use case is inderdaad dat er maar 1 relatie is met of de ene of de andere target. De `<<relatiesoort>>` ontbreekt in het voorbeeld. 

Het klopt dus dat de xor tussen twee relaties niet beschreven is. 

Als dat de bedoeling was dan moeten we nog een variant bedenken. Niet de relatie naar de keuze is geeft betekenis (en is dus geen `<<relatiesoort>>`?) maar de keuze-elementen geven de betekenis. In dat geval kan het ook zo zijn dat de target van de beide keuze-elementen hetzelfde objecttype is. 
Bijvoorbeeld de keuze tussen een woonAdres en een bezoekAdres die beiden verwijzen naar een `<<Objecttype>>' Adres.

**Comment by lennartvanbergen-kadaster** [comment]
> * Voor een XOR tussen meerdere relaties kan dezelfde oplossing genomen worden met als tagged value: relatiesoort

Dat vraag ik me af. Ik wil geen nieuwe eigenschap introduceren als gevolg van een modelleerkeuze en ik wil de metagegevens niet kwijtraken. 

Ik zit eerder te denken aan: 

Uitgangssituatie: 2 eigenschappen - gewenst: XOR constraint
relatiesoort R1 
relatiesoort R2 

XOR toevoegen = maak een Keuze element van het UML-Class met stereotype < < Keuze >>. 
Verplaats de relaties R1 en R2 naar dit keuze element, zodat het Keuze element de nieuwe source wordt van deze relaties. De relaties blijven UML-association, en houden stereotype relatiesoort en houden hun metagegevens. 

Naam: blijft hetzelfde. 
Rol: blijft hetzelfde. 

Aankoppeling aan oorspronkelijk objecttype: 1 UML-assosiation met stereotype < < Keuze > > - zonder naam en zonder rol en zonder definitie. 

Bij een relatie horen source en target kardinaliteiten.
source: 1 of 1..*  
target 1..1 of 1..* 

Metadata van Keuze: zie union. 

-- 

Ik zie ook dat < < Keuze > > bij datatypes mogelijk anders gaat worden dan bij relaties. Immers, bij datatypes is het UML type een UML-datatype en bij relaties past dat niet. 

De keuze tussen datatypes is ook inherent anders dan de keuzes tussen kenmerken. Ik stel daarom voor om de ene: Kenmerken keuze te noemen, of < < XOR > > .

--

Verder, eens dat union niet als naam wordt gekozen. In verzamelingen leer is een union zo ongeveer het tegenovergestelde van XOR.  Ik zou in het Engels dan niet union willen houden als term. Of ... misschien is union niet bedoeld als verzamelingen leer woord, maar als ... en klopt het wel.

**Comment by PalmJanssen** [comment]
@lennartvanbergen-kadaster @ThiesMesdag @dkrijtenburg-GNM 

Bijgewerkt n a v discussie 3 -10-2019:
https://github.com/Geonovum/MIM-Werkomgeving/blob/master/Werkversie/UNION%20onderzoek/Union%20-%201.1%20uitwerking.md

**Comment by lennartvanbergen-kadaster** [comment]
Denklijn gekozen. 

We proberen modelelementen te behouden, zoals je zou modelleren bij een constraint, en als opsomming op te nemen in de keuze. Oftewel, attribuut 1 en 2 als modelelement Attribuutsoort verplaatsen we naar de Keuze, en zijn daar nog steeds attribuut 1 en 2 als modelelement Attribuutsoort. Alle modelelementen die opgenomen zijn in een UML-Class <<keuze>> (voor keuzes tussen <<attribuutsoort>>-en en/of <<relatiesoort>>-en) of in een UML-Datatype <<keuze>> (voor keuzes tussen datatypes) zijn een keuze mogelijkheid.

In UML: je ziet in de <<keuze>> MijnKeuze dan <<attribuutsoort>> a1 en <<attribuutsoort>> a2. Alle verdere aankoppelingen die in UML nodig zijn om dit aan elkaar te koppelen noemen we ook <<keuze>>.

Verder zijn er maar liefst 5 uses cases die we hiermee mogelijk maken: 
1. XOR tussen datatypen
2. XOR tussen attribuutsoorten
3. XOR tussen relatiesoorten 
in theorie ook tussen of attribuutsoort of relatiesoort, maar is nog niet om gevraagd.
4. 1 kenmerk is 1 relatiesoort, maar mag verwijzen naar ofwel objecttype A  ofwel objecttype B 
5. 1 kenmerk is 1 attribuutsoort, dit mag ofwel A zijn ofwel B (A en B zijn mogelijke verschijningsvormen van het attribuutsoort),

Voorbeelden zijn erg van belang in deze. In H Algemeen, maar ook in H UML en H LD.  

H Algemeen hierop aangepast

Keuze
Definitie Keuze Een opsomming van meerdere modelelementen, waarbij er maar van één tegelijkertijd sprake kan zijn.

Toelichting: De keuze is een alternatieve manier voor het modelleren van een constraint.

Een belangrijk voordeel van deze modellering is dat de kardinaliteiten zuiver gehouden kunnen worden. Anders gezegd, er kan mee voorkomen worden dat de kardinaliteit eerst optioneel gemaakt moet worden en hierna via een constraint weer verplicht gemaakt moeten worden, maar slechts voor één van de mogelijkheden. Het is aan de modelleur om te kiezen voor een constraint of een Keuze.

De intentie hierbij is om duidelijk aan te geven wat de eigenschappen van het object zijn, zonder hierbij nieuwe eigenschappen te introduceren als gevolg van de modellering. Hiervoor zijn een aantal gebruikstoepassingen.

Meerdere modelelementen waartussen een keuze gemaakt moet worden
Dit zijn keuzes waarbij er sprake is van twee (of meer) modelelementen, waarbij of de ene, of de andere ingevuld moet worden oftewel verplicht is. Dit heeft in de verzamelingenleer een XOR constraint.

Use case 1, er is bij één attribuutsoort sprake sprake van een XOR tussen datatypen: datatype is ofwel datatype A ofwel datatype B.

Voorbeeld: Attribuutsoort geometrie. Dit is een keuze uit Datatype Line of Datatype Polygon. De opsomming van beide keuzemogelijkheden noemen we de Keuze LineOrPolygon. Het maken van deze keuze is verplicht.

Merk op dat er geen nieuw Datatype is bijgekomen als gevolg van deze modellering t.a.v. een modellering met een constraint.

Use case 2, er is bij één objecttype sprake van een XOR tussen attribuutsoorten: ofwel attribuutsoort A ofwel attribuutsoort B is aan de orde en verplicht.

Voorbeeld: Objecttype Normwaarde heeft ofwel Attribuutsoort 'kwalitatieve waarde' ofwel Attribuutsoort 'kwantitatieve waarde', beide tegelijk mag niet voorkomen. De opsomming van beide keuzemogelijkheden noemen we de Keuze 'Waardetype keuze'. Het maken van deze keuze is verplicht.

Merk op dat er geen nieuwe Attribuutsoort is bijgekomen als gevolg van deze modellering t.a.v. een modellering met een constraint.

Use case 3, er is bij één objecttype sprake van een XOR tussen relatiesoorten: ofwel Relatiesoort A ofwel attribuutsoort B is aan de orde en verplicht.

Voorbeeld: Objecttype Juridische regel beschrijft ofwel een Activiteit, ofwel een Omgevingsnorm. Beide relaties hebben bestaansrecht en hebben op zichzelf betekenis, maar een Juridische regel kan maar over 1 van beide gaan (in dit voorbeeld).

De Relatiesoort 'beschrijft een activiteit' wijst naar Objecttype Activiteit, de Relatiesoort 'beschrijft een omgevingsnorm' wijst naar Objecttype Omgevingsnorm. De opsomming van beide keuzemogelijkheden noemen we de Keuze 'Regelbeschrijving keuze'. Het maken van deze keuze is verplicht.

Merk op dat er geen nieuwe Relatiesoorten zijn bijgekomen als gevolg van deze modellering t.a.v. een modellering met een constraint.

één modelelement waarbij er sprake is van een keuze
Use case 4, er is bij één objecttype sprake van één kenmerk, te weten een relatiesoort, die kan wijzen naar ofwel Objecttype A ofwel naar objecttype B.

Voorbeeld: Objecttype Vervoersmiddel heeft als Relatiesoort eigenaar ofwel een Objecttype Natuurlijk persoon, ofwel een Objecttype Niet natuurlijk persoon. We modelleren de verwijzing naar deze objecttypes als een Keuze 'Eigenaar keuze'. Het maken van deze keuze is verplicht.

Merk op dat er geen nieuwe Relatiesoort is bijgekomen als gevolg van deze modellering t.a.v. een modellering met een constraint. Er is maar sprake van één Relatiesoort.

Use case 5, er is bij één objecttype sprake van één kenmerk, te weten een Attribuutsoort A, die zelf als verschijningsvorm ofwel Attribuutsoort A1 kan zijn, ofwel Attribuutsoort A2 kan zijn.

Voorbeeld: het Attribuutsoort telefoonnummer van een Natuurlijk Persoon. Dit is ofwel een privenummer ofwel een werknummer. De opsomming van beide keuzemogelijkheden noemen we de Keuze TelefoonnummerSelectie.

Merk op dat er geen nieuwe Attribuutsoort is bijgekomen als gevolg van deze modellering t.a.v. een modellering met een constraint. Er is maar sprake van één Attribuutsoort.




<<keuze element>> komt daarmee te vervallen.

**Comment by lennartvanbergen-kadaster** [comment]
@Paul ik zet deze op jouw naam zodat je het UML hoofdstuk kan doen. Kan je 'm hierna doorzetten naar Marco @architolk ?

**Comment by architolk** [comment]
Er moet aan de LD kant (en ik vermoed ook aan het Algemene Metamodel) nog wel 1 en ander gebeuren: op dit is het niet geheel duidelijk hoe je vanuit het MIM metamodel kunt komen tot de drie gewenste keuzes. Met name relatiesoort lijkt niet goed te passen.

**Comment by lennartvanbergen-kadaster** [comment]
Zie ook: https://github.com/Geonovum/MIM-Werkomgeving/blob/master/Werkversie/UNION%20onderzoek/use-cases/use-cases.md

**Comment by lennartvanbergen-kadaster** [comment]
Is geworden: 

#### Keuze

Een *Keuze* is een opsomming van meerdere modelelementen, waarbij er maar van één tegelijkertijd sprake kan zijn.

*Toelichting:* Er kan altijd maar één van de mogelijkheden gekozen worden. De keuze is voor een aantal use cases een alternatieve manier voor het modelleren van een constraint. 

Een *Keuze* kan op meerdere plekken gebruikt worden, en maakt het mogelijk waar in het metamodel normaal gesproken maar één mogelijkheid bestaat, een opsomming te geven van meerdere mogelijkheden, waarbij in een concreet geval altijd precies één van deze mogelijkheden wordt gebruikt.

Een belangrijk voordeel van deze modellering is dat de kardinaliteiten zuiver gehouden kunnen worden. Anders gezegd, er kan mee voorkomen worden dat een kardinaliteit van bijvoorbeeld twee kenmerk eerst optioneel gemaakt moet worden en dat hierna via een constraint deze toch weer verplicht gemaakt moeten worden, voor precies één van de mogelijkheden. Het is aan de modelleur om te kiezen voor een constraint of een Keuze.

Dit document beschrijft zes use cases waarin het modelleren met een *Keuze* van toegevoegde waarde is. Zonder een dergelijke modelconstructie zou het nodig moeten zijn om met een expliciete constraint de keuze aan te geven.

Bij use cases 1 tot en met 4 gaat het over meerdere kenmerken, waartussen een keuze gemaakt moet worden omdat er van precies 1 sprake is/mag zijn. Dit is in MIM een keuze tussen twee (of meer) modelelementen. In de verzamelingenleer noemen we dit een XOR situatie. Hierbij is het vooral van belang dat er als gevolg van de modellering van een keuze in plaats van constraint er geen nieuwe kenmerken mogen ontstaan en ook geen kenmerken mogen wegvallen. De kenmerken van het object blijven gelijk.

##### Use case 1: een keuze tussen twee datatypen

Een objecttype heeft een attrituutsoort en het datatype hiervan is ofwel datatype A ofwel datatype B. In MIM modelleren we daarom 1  attribuutsoort met als datatype een keuze tussen het datatype A en het datatype B. Het maken van deze keuze is verplicht.

Voorbeeld: *Attribuutsoort* geometrie als kenmerk van een objecttype. Dit is een keuze uit *Datatype* Line of *Datatype* Polygon. De opsomming van beide keuzemogelijkheden noemen we de *Keuze* LineOrPolygon. 

Het is niet de bedoeling om twee attribuutsoorten te modelleren met elk een datatype en de attribuutsoorten optioneel te maken. 

Zonder de mogelijkheid van keuze, zou je te maken krijgen met twee attribuutsoorten met bijbehorend datatype. Echter, in dat geval mogen de attribuutsoorten niet dezelfde naam hebben, aangezien deze bij hetzelfde objecttype horen. Ook zou de kardinaliteit niet kloppen: die zou dan [0..1] moeten worden, maar dat doet geen recht aan het feit dat er één verplicht aanwezig moet zijn, en er ook geen twee naast elkaar mogen zijn. De werkelijke kardinaliteit is [1..1].

## Use case 2: een keuze tussen twee attribuutsoorten
Er is sprake van ofwel attribuutsoort A ofwel attribuutsoort B. In MIM modelleren we daarom een keuze tussen de 2 attribuutsoorten. 
Het maken van deze keuze is verplicht.

Voorbeeld: bij een objecttype "Betalingsopdracht" moet naast het bedrag ook een betalingskenmerk worden opgenomen of een omschrijving. Eén van beide moet worden ingevuld. Het is niet toegestaan dat beide velden worden ingevuld. We modelleren daarom een *Keuze* 'BetalingskenmerkOfOmschrijving' met daarin een *Attribuutsoort* betalingskenmerk en een *Attribuutsoort* omschrijving. 

Het is niet de bedoeling om een derde attribuutsoort, zoals BetalingskenmerkOfOmschrijving, te introduceren. We noemen BetalingskenmerkOfOmschrijving daarom een *Keuze*. 

Zonder de mogelijkheid van keuze zouden beide attribuutsoorten opgenomen zijn bij het objecttype als optionele velden, met een constraint dat een van beide gevuld moet zijn. Dit is in deze use-case niet echt een probleem. Wel is de kardinaliteit ook in dit geval dan niet erg duidelijk gemodelleerd: die zou dan [0..1] moeten worden, maar dat doet geen recht aan het feit dat er één verplicht aanwezig moet zijn, en er ook geen twee naast elkaar mogen zijn. De werkelijke kardinaliteit is [1..1] op de keuze zelf. Met een constraint is dit op zich wel correct te modelleren, maar met een modellering van een keuze is dit veel duidelijker.

## Use case 3: een keuze tussen twee relatiesoorten
Er is sprake van ofwel relatiesoort A ofwel relatiesoort B. In MIM modelleren we daarom een keuze tussen de 2 relatiesoorten. 
Het maken van deze keuze is verplicht.

Voorbeeld: een objecttype "Persoon" kan getrouwd zijn met een ander persoon, of een geregistreerd partnerschap hebben met een ander persoon. Het is niet mogelijk dat een persoon en getrouwd is en een geregistreerd partnerschap heeft met de andere persoon. We modelleren daarom een *Keuze* 'soort relatie' met daarin een *Relatiesoort* getrouwd en een *Relatiesoort* geregistreerd partnerschap.

Zonder de mogelijkheid van keuze zouden beide relatiesoorten opgenomen zijn bij het objecttype, met een optionele kardinaliteit. Hiermee is het echter niet duidelijk zichtbaar dat er slechts één van de twee relatiesoorten aanwezig mogen zijn. Met een constraint is dit op zich wel correct te modelleren, aan te geven dat precies 1 van beide verplicht is, maar met een modellering van een keuze is dit veel duidelijker.

--

Merk op: use case 2 en 3 zijn eigenlijk vergelijkbaar, bij use case 2 gaat het om attribuutsoorten, bij use case 3 gaat het om relatiesoorten. Vanuit het perspectief van keuze gaat het in beide gevallen om een keuze tussen twee modelelementen die verbonden zijn met een objecttype. Het is ook mogelijk om een keuze te hebben tussen attribuutsoort OF een relatiesoort. Dit werkt analoog, maar is in de use cases (nog) niet uitgewerkt.  

--

## Use case 4: Een keuze tussen twee relatiedoelen
Er is sprake van een relatiesoort welke wijst naar ofwel relatiedoel A ofwel relatiedoel B. In MIM modelleren we daarom een relatiesoort welke verwijst naar aarbij keuze tussen de 2 relatiedoelen. Het maken van deze keuze is verplicht.

Voorbeeld: een objecttype "Vervoersmiddel" heeft een eigenaar. Dit kan een persoon zijn, of een bedrijf, maar niet beiden. Er is sprake van één eigenaar" en een keuze tussen relatiedoel persoon (naar objecttype Persoon) en relatiedoel bedrijf (naar objecttype Bedrijf). We modelleren daarom een *Relatiesoort* eigenaar met een *Keuze* PersoonOfBedrijf met twee relatiedoelen, naar persoon en bedrijf.  

Het is niet de bedoeling om twee nieuwe relatiesoorten, persoon en bedrijf, te introduceren en relatiesoort eigenaar kwijt te raken. We noemen daarom een *Keuze* tussen relatiedoelen.

**Comment by lennartvanbergen-kadaster** [comment]
Wat nu niet verwerkt is, zijn de use cases 5 en 6 van https://github.com/Geonovum/MIM-Werkomgeving/blob/master/Werkversie/UNION%20onderzoek/use-cases/use-cases.md

Dit los inplannen ...
