### ISSUE TITLE
Klasse met stereotype Keuze

### ISSUE THREAD

**Issue by JvGldr** [Geonovum/MIM-Werkomgeving#63]
Klasse met stereotype Keuze (met attributen met stereotype KeuzeElement) leidt bij XSD generatie tot een XSD-Union (keuze uit datatypes, waarbij elk attribuut een unieke datatype heeft). Daarmee missen we een MIM modellering die leidt tot een XSD-Choice (keuze uit attributen, waarbij elk attribuut een unieke naam heeft).
(BRO - Han Welmer)

**Comment by JvGldr** [comment]
Eventueel issue voor 1.1 maar deze lijkt me in eerste instantie niet in scope voor MIM; MIM zegt namelijk niets over welke XSD constructie er zou moeten worden gevormd vanuit een MIM constructie. De vraag is dan, moet je in MIM kunnen uitdrukken of je een keuze uit datatypes of een keuze uit attributen bedoelt.

**Comment by HanWelmer** [comment]
Er zullen zeker situaties zijn waar er een overap zit tussen 'keuze uit datatypen' en 'keuze uit attributen'. Maar het verschil kan inzichtelijk gemaakt worden door uit te spreken dat een 'keuze uit datatypen' invloed heeft op het domein en dat een 'keuze uit attributen' invloed heeft op de semantiek.

Voorbeeld 1: 'keuze uit datatypen' : een attribuut met als type een getalswaarde waarbij het domein bestaat uit 0..50, 100..200 en 475 .. 800, waarbij de 3 bereiken zijn gedefinieerd als 3 specialisaties van Integer.

Voorbeeld 2: 'keuze uit attributen': een attribuut met als betekenis de gegevens over een te amputeren ledemaat: linkerarm:Arm, rechterarm: Arm, linkerbeen:Been, rechterbeen:Been, waarbij Arm en Been nader te definiëren Objecten of Gegevensgroepen zijn.

Voorbeeld 2 is nu niet mogelijk in MIM, omdat er meerdere keuzeElementen zijn met hetzelfde type (maar ze hebben wel unieke attribuutnamen).

**Comment by lennartvanbergen-kadaster** [comment]
Keuze uit datatypen is wezenlijk anders dan keuze uit kenmerken zoals attribuutsoort of relatiesoort. Dit laatste kan in MIM geïmplementeerd worden met een constraint. Er is een wens die al bestaat, dit item is 'dubbel', zie #61

**Comment by lennartvanbergen-kadaster** [comment]
Duplicate. Zie #61
