### ISSUE TITLE
MIM als uitbreiding van NEN3610

### ISSUE THREAD

**Issue by JvGldr** [Geonovum/MIM-Werkomgeving#64]
Mijn indruk is dat MIM als uitbreiding van NEN 3610 niet altijd even sterk is doordacht. Bijvoorbeeld, NEN3610 kent voor Klassen de stereotypen FeatureType en DataType. MIM kent voor Klassen meer stereotypen, zoals FeatureType, AttributeGroupType, StructuredDataType, PrimitiveDataType, Union (en Enumeration, Codelist en ReferenceList). Wat daarbij de doelen, gevolgen voor XSD, voordelen en nadelen zijn is, in ieder geval mij, niet altijd duidelijk, zelfs niet na meervoudige lezing van de MIM handleiding.
(BRO - Han Welmer)

**Comment by lennartvanbergen-kadaster** [comment]
Een structured data type bestaat uit meerdere componenten, bv. 15 decibel. Dit is anders dan bij een primitief datatype zoals String. Dit verschil expliciet maken is wat MIM doet. In XSD land komt dat overeen met complex datatype of simple datatype. Hier wordt dit verschil ook gemaakt. 

Dit is nuttig voor van alles, o.a. voor het kunnen opnemen van definities per component. Zelfde geldt bv. voor een gegevensgroep of een attribuutsoort, twee compleet verschillende dingen. De ene is immers een groep van atttribuutsoorten. Het kunnen herkennen van dit soort verschillen is in MIM mogelijk en zichtbaar. Vandaar. 

Bij generatie naar XML is een objecttype een element en een attribuut ook en een datatype bestaande uit meerdere componenten ook. Het heet allemaal element. Daarom is XML ook niet geschikt als specificatie taal, ook niet bedoeld als zodanig. Het is maar net op welk detailniveau een specificatie zich wilt begeven. Bij uitgebreide expressieve informatiemodellen heb je het nodig. Dit kan je weer terug schalen naar minder expressief, desgewenst.

**Comment by PalmJanssen** [comment]
Hier nog aan toegevoegd.
NEN 3610 heeft nauwelijks afspraken voor het opnemen van metagegevens, beschrijvende data, van modelelementen: herkomst, kwaliteit, patroon e.d.
Voor MIM is dat een belangrijk onderdeel dat in de tagged values is opgenomen. Die tagged values zijn gekoppeld aan stereotypen. Dus zelfs als een modelelement gewoon herkenbaar is in het UML, bijvoorbeeld een attribuutsoort, dan krijgt het toch een stereotype. Het heeft immers een aparte set aan metagegevens.
