### ISSUE TITLE
Enumeratie waarde - metadata Code - modelleren met alias houdbaar?

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#65]
Een uitzondering is gemaakt voor UML modellen voor de UML-EnumerationLiteral. De ‘naam’ betreft hier een daadwerkelijk waarde, waarin de naam gelijk staat aan de waarde. Het is daarom expliciet ongewenst om hiervoor een alternatieve naamgeving te gebruiken. De alias wordt hier, mede daarom, gebruikt voor (alleen) de modellering van het metadata aspect Code, welke aanvullend is op naam (niet een alternatief van naam).

**Comment by PalmJanssen** [comment]
Waarom niet de Alias gebruiken als een mogelijkheid voor een andere taal? Of wat de modelleur er ook mee wil. Specifiek voor code reserveren lijkt mij te streng. Of is daar heel veel behoefte aan?

**Comment by PalmJanssen** [comment]
Afgehandeld. Er hoeft niets te veranderen.
Code wordt ingevuld in het EA veld Alias.
Let op dat het EA UML profiel dat goed doet. Dus geen TV Code heeft.

**Comment by lennartvanbergen-kadaster** [comment]
Ja, wordt bij alle andere modelelementen als alternatieve naam gebruikt. Alleen bij enumeratie is er gekozen in sec UML voor de alias en niet voor een extra tagged value.
