### ISSUE TITLE
MIM uitbreiden met Linked Data Vocabulaire

### ISSUE THREAD

**Issue by dkrijtenburg-GNM** [Geonovum/MIM-Werkomgeving#67]

**Comment by lennartvanbergen-kadaster** [comment]
Graag alle issues even hierin opnemen, zodat dit een totaal item wordt.

**Comment by dkrijtenburg-GNM** [comment]
acties naar aanleding van bijeenkomst 10 juli 2019 -ver MIM en linked data
 
MIM document implementatieneutraal maken, met hoofdstuk voor MIM-UML. TODO. 
Lennart
[MB] Deze lijkt gerelateerd aan https://github.com/Geonovum/MIM-Werkomgeving/issues/51
 
Van MIM een MIM-LD vocabulaire maken. Gedaan.
Review door o.a. Lennart
[MB] Handig om hier idd een issue van te maken. Overigens moet ik nog een update doen, waarbij ik de MiM 1.1 zaken in meeneem. Daarna lijkt me review het meest handig (hoewel je er nu al naar kan kijken)
 
Benodigde toevoegingen aan MIM inventariseren vanuit MIM-LD vocabulaire. Gedaan.
Niet Lennart [MB] Dit hoeft geen issue meer te zijn, hiervoor zijn de issues al opgenomen.
 
MIM uitbreiden met benodigde toevoegingen voor specificeren informatiemodel in MIM-LD.  
Deels gedaan, openstaande bespreken. Marco, Lennart, Paul [MB] Bedoel je hiermee 2* of 3*? Dus gaat dit om de toevoeging m.b.t. de 1-op-1 vertaling, of de toevoegingen om naar een instantieerbaar LD model te komen? Dit is nog niet gebeurt. 2* is al voldoende gedaan en hiervoor zijn de issues aangemaakt, 3* is nog niet gedaan, maar nu even te vroeg om hier een issue voor aan te maken, want dit volgt uit een ander issue: het maken van de vertaling naar een instantieerbaar LD model.
 
MIM document, hoofdstuk MIM-LD toevoegen, of linken naar gepubliceerde versie. 
Hopelijk linken. Wat mij betreft Linda en Marco, redactie Paul, Lennart [MB] Grotendeels linken inderdaad. Maar je zuilt ook een stukje beschrijving willen toevoegen denk ik. Overigens staat dit denk ik ook al deels in de huidige README.md in de /rdf directory, dit zou dan naar het MiM document zelf kunnen.
 
Benodigde toevoegingen aan MIM inventariseren vanuit de behoefte om te controle of data voldoet aan het informatiemodel. 
Niet Lennart [MB] Ik weet niet helemaal wat je hiermee bedoeld. Ik vermoed eigenlijk het “transformeren naar een instantieerbaar LD model”. Klopt dat?
 
MIM uitbreiden met benodigde toevoegingen voor voorgaande punt. 
Lennart en Paul [MB] Eens, maar nog geen issue: de issues komen uit het vorige punt, en dan opvoeren.
 
Handreiking maken waar je op moet letten, kan wellicht ook kort als ondersteunende documentatie, of door verwijzing naar NEN3610 document. 
Team, o.a. Lennart

**Comment by dkrijtenburg-GNM** [comment]
Dit issue kan worden gesloten omdat dit uiteenvalt in een aantal issues waar in de tekst naar wordt verwezen.
