### ISSUE TITLE
Wijziging rationeel in rationaal in omschrijving primitief datatype Real

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/MIM-Werkomgeving#68]
In de tabel onder het kopje [primitieve datatypes](https://docs.geostandaarden.nl/mim/mim10/#primitive-datatypes) gaat het over **rationEle getallen**, dit moeten volgens mij **rationAle getallen** zijn.

**Comment by dkrijtenburg-GNM** [comment]
verwerkt door Paul
