### ISSUE TITLE
Stereotypen en aspecten toekennen aan Enumeratie en Enumeratiewaarde

### ISSUE THREAD

**Issue by LentjesP** [Geonovum/MIM-Werkomgeving#7]
De MIM elementen Enumeratie een Enumeratiewaarde hebben geen stereotype. De reden is dat deze deze elementen geen tagged value(s) nodig hebben voor de meta aspecten.

Maar ook voor deze elementen kan het zinvol zijn om de meta-aspecten "Herkomst", "Herkomst definitie" en "Toelichting" ook op te nemen als tagged values en dus ook stereotypen voor deze elementen te definiëren.

**Comment by PalmJanssen** [comment]
Er is nu een MIM stereo type enumeratie. In het UML profiel zie je die naast de enumeration aanduiding. Dat kan ik nog niet verhelpen.
Enumeratiewaarde heeft 4 metakenmerken
