### ISSUE TITLE
MIM-LD vocabulaire maken

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#70]
Bestaande MIM 1.0**1** 1-op-1 overzetten naar een MIM vocabulaire. 

Is al gedaan voor MIM 1.0.0 

In MIM 1.01 zijn een aantal issues opgelost die nodig waren voor de 1-op-1 overzetting. 

Daar waar e.e.a. nog steeds niet goed kan of extra vereist is inventariseren, en als losse issues opvoeren. Na oplossen daarvan MIM-LD vocabulaire bijwerken en het geheel consistent maken.

**Comment by lennartvanbergen-kadaster** [comment]
Doel: MIM-LD op basis van 1.01 publiceren zodat mensen ernaar kunnen kijken, ter review aanbieden aan de mensen die dit willen.

**Comment by architolk** [comment]
De voorgestelde uitwerking van dit issue is voor deze consultatie in te zien op:
https://github.com/Geonovum/MIM-Werkomgeving/blob/master/Werkversie/rdf/README.md

**Comment by dkrijtenburg-GNM** [comment]
Ter consultatie
Onderwerp:
Het maken van een MIM-LD-vocabulaire

Oplossing : 
De voorgestelde uitwerking van dit issue is voor deze consultatie in te zien op:
https://github.com/Geonovum/MIM-Werkomgeving/blob/master/Werkversie/rdf/README.md

**Comment by jacblom** [comment]
Namens Han Welmer:

Binnen MIM is expliciet per model de keuze opengelaten of daarbij de Relatiesoort leidend is of de Relatierol. Deze vrijheid moeten we behouden.

Ik vermoed dat de werkwijze zoals beschreven bij interpretatie vooronderstelt dat Relatiesoort leidend is. De interpretatie moet dan worden aangepast opdat beide situaties worden ondersteund.

**Comment by architolk** [comment]
Inderdaad. Beide varianten moeten uitgewerkt worden. Op dit moment is slechts 1 variant uitgewerkt en zal de andere nog voor 1.1 uitgewerkt moeten worden.

**Comment by architolk** [comment]
Beide varianten uitgewerkt.
