### ISSUE TITLE
MIM-LD - MIM document, hoofdstuk MIM-LD toevoegen

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#71]
Na review en review verwerking van MIM-LD, zie issue https://github.com/Geonovum/MIM-Werkomgeving/issues/70 moet deze netjes in het document (md) opgenomen/ingebed worden.

**Comment by JvGldr** [comment]
Gedaan, het UML hoofdstuk is gesplitst in een algemeen en een UML deel. Een nieuw document is toegevoegd tbv. een MIM hoofdstuk over "Linked Data"
