### ISSUE TITLE
MIM-LD - bestaand informatiemodel transformeren naar een instantieerbaar LD model

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#72]
Ter toets. 

Items die hieruit komen, met name als iets niet goed lukt, worden geïnventariseerd en als issues opgevoerd. Deze kunnen van invloed zijn op MIM zelf, of kunnen als toelichting of ondersteuning in een handreiking terechtkomen. Als van invloed op MIM zelf, dan doorvoeren, de anderen kunnen later en elders.

**Comment by architolk** [comment]
Eerste versie is gemaakt in: https://github.com/Geonovum/MIM-Werkomgeving/blob/master/Werkversie/rdf/transformatie.md

**Comment by GeraldGrootRoessink** [comment]
Mooi werk en heel herkenbaar. Hierbij mijn review:
### Objecttype
- Voorlopig: optie a)
Deze voorlopige keuze gaat voor DUO niet werken en ik denk ook dat optie  a) overheidsbreed niet kan werken.  Wij hebben gekozen voor een “canoniek model”  waarin het wel uniek moet zijn en daarnaast per systeem / per uitwisseling specifieke modellen (inderdaad namespaces).  Specifieke objecttypen (en gegevensgroepen) kunnen dezelfde naam hebben, maar wel inhoudelijk afwijken. 
### Attribuutsoort
- Voorlopige aanname: alle namen van attribuutsoorten zijn uniek.
Deze voorlopige keuze voor datatypeproperties heeft DUO ook gemaakt. Altijd in het canoniek model. Maar er is nog een probleem: de kardinaliteit tussen klasse en property. Zoals hierboven aangegeven kan een property (bijvoorbeeld naam of begindatum) bij meerdere klassen voorkomen, maar met verschillende kardinaliteiten. Die eigenschap hangt in SHACL aan de sh:Propertyshape. Vandaar dat de URI van de sh:propertyshape bij ons ook de naam van de klasse (objecttype) bevat. De URI van de owl:datatypeproperty heeft dat niet.
- De transformatie houdt nog niet rekening met het feit dat sommige datatypen in RDF juist geen literals zijn, maar resources. In die gevallen zou dus niet gesproken moeten worden over een owl:DatatypeProperty, maar een owl:ObjectProperty. Alleen de datatypes enumeratie (klopt dat?) en primitief datatype zouden naar een literal gaan, de overigen naar resources.
Bij enumeratie gebruiken we owl:objectproperty want die enumeratie wordt weergegeven met een owl:Class. Als voorbeeld:
> <http://lod.onderwijsregistratie.nl/cat/cdm/sh/OrganisatieErkenning/denominatie >
> 	rdf:type sh:PropertyShape ;
> 	sh:name "denominatie"@nl ;
> 	sh:nodeKind sh:IRI ;
> 	sh:path cdm:denominatie-v03 ;
> 	sh:class cdm:Denominatie-v03.1 ;
> 	.
> <http://lod.onderwijsregistratie.nl/cat/cdm/def/Denominatie-v03>
> 	rdfs:label "denominatie" ;
> 	rdf:type owl:ObjectProperty ;
> 	rdfs:range cdm:Denominatie-v03.1 ;
> .              
> <http://lod.onderwijsregistratie.nl/cat/cdm/def/Denominatie-v03.1>
> 	rdf:type owl:Class ;
> 	rdfs:label "Denominatie"@nl ;
> 	owl:oneOf (
> 		<http://lod.onderwijsregistratie.nl/cat/cdm/def/Denominatie-v03.1/OPB>
> 		<http://lod.onderwijsregistratie.nl/cat/cdm/def/Denominatie-v03.1/RK>
> 	) ;
> . 
Verder hebben we in de database inderdaad (externe) URI’s. Die worden herkend aan het primitieve (xsd)type anyURI. 
Het rdf voorbeeld in de eerste uitwerking is eigenlijk niet compleet. Er liggen ook sh:property relaties tussen de nodeshape en de propertyshapes.
### Generalisatie
- Voorlopige oplossing is om een rdf:Statement toe te voegen. Alternatief zou zijn om een subklassen te maken van rdfs:subClassOf
Dit snap ik niet. Hieronder staat twee keer hetzelfde afgezien van de rare ? bij rdfs:subclassOf:
>   ?subtype rdfs:subClassOf ?supertype.
>   ?statement rdf:subject ?subtype.
>   ?statement rdf:predicate ?rdfs:subClassOf.
>   ?statement rdf:object ?supertype.
### Relatiesoort
- Voorlopige aanname: mim:Relatiesoort wordt gebruik
1. Dezelfde keuze als DUO. Naar analogie met objecttype:  Deze zijn bij DUO nooit globaal uniek. Ze horen bij een specifieke ontologie/namespace. 
2. Ook hier: ik zie geen sh:property relatie tussen nodeshape en propertyshape.
3. Ik verwacht ook een sh:class met verwijzing naar de de “ontvangende” klassen
### Relatieklasse
Waarom heeft dit rdf statement geen rdf:subject en rdf:object?
### Constraint
- Voorstel: alleen vertalen naar documentatie in het MiM model in RDF. Zie bv de INSPIRE RDF Guidelines waar ze dit ook zo doen. In de toekomst wellicht vertalen naar SHACL.
Dat vinden wij een gemiste kans omdat er in de XML wereld al zo is uitgekristalliseerd.  In elk geval de enkelvoudige constaints (behorende bij één attribuut) regexen, minmax lengte.  Dit is met de shacl validator goed te valideren. Deze staan trouwens verder op in het document wel genoemd. Wat mijn betreft voegen we daar ook minmaxbereik aan toe. Ook die zijn goed te vertalen naar shacl.
### Overig
Ik mis in de beschrijving de connectie tussen modelelementen en skos:begrippen

**Comment by lvdbrink** [comment]
> > Objecttype
> > Voorlopig: optie a)

> Deze voorlopige keuze gaat voor DUO niet werken en ik denk ook dat optie a) overheidsbreed niet kan werken. Wij hebben gekozen voor een “canoniek model” waarin het wel uniek moet zijn en daarnaast per systeem / per uitwisseling specifieke modellen (inderdaad namespaces). Specifieke objecttypen (en gegevensgroepen) kunnen dezelfde naam hebben, maar wel inhoudelijk afwijken.

We bedoelen hier niet dat Objecttypen een globaal unieke naam moeten hebben, maar een unieke naam binnen de set van packages die  op 1 moment getransformeerd wordt naar een instantieerbaar LD model.

**Comment by GeraldGrootRoessink** [comment]
Dank voor je reactie. In mijn woorden, wij kunnen niet een objecttype Verblijfsobject definiëren in een DUO model van het onderwijs als we tegelijkertijd het objecttype Verblijfsobject van de BAG incorporeren. Toch? Dat lijkt me goed werkbaar.

**Comment by architolk** [comment]
Er is nu gekozen dat je op package niveau de namespace kunt definiëren. Hierdoor kun je ook meerdere objecttypen met dezelfde naam in je model hebben staan. Wel gelden de algemene regels van het MIM. Dus unieke namen van objecttypen binnen 1 informatiemodel. In het voorbeeld zou je in het informatiemodel van DUO dus wel een verblijfsobject van de BAG kunnen meenemen, mits deze in een package zit met het stereotype "view" of "extern".

**Comment by architolk** [comment]
Gedeeltelijk is het reviewcommentaar verwerkt. Nog een laatste slag nodig om te kijken of de gewijzigde versie in lijn is met de opmerkingen.

**Comment by architolk** [comment]
De relatie tussen de nodeshape en de propertyshape wordt gerealiseerd via de transformatieregel van mim:attribuut, en niet in de transformatieregel van mim:Attribuutsoort, vandaar dat dit in het voorbeeld niet is uitgewerkt.

**Comment by architolk** [comment]
Reviewcommentaar verwerkt. Enige opmerkingen die over is gebleven is de optie om min/max als aspecten op te nemen. Hiervoor een nieuw issue aangemaakt.
