### ISSUE TITLE
Generalisatie heeft twee definities

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#74]
Generalisatie is gedefinieerd op zowel datatypen als objecttypen. Dit lijken verschillende aspecten te zijn.

Een oplossing zou kunnen zijn om twee subklassen te specificeren, zodat het onderscheid duidelijk is en elk een eigen definitie krijgt.

**Comment by dkrijtenburg-GNM** [comment]
we  kiezen er voor om de definities gelijk te maken.

**Comment by lennartvanbergen-kadaster** [comment]
Twee aparte stereotypes wordt wel erg verbose ... de definities zijn niet goed in elkaar te schuiven. 

Er staan nu twee definities, die met dezelfde modellering gemodelleerd worden. De definities zijn op zich helder. Waarom is dit niet toereikend? 

Ad. definities. 
De intentie is grotendeels hetzelfde, het overerven van eigenschappen van het bovenliggende modelelement, waarbij het type modelelement hetzelfde is. Echter, bij objecttypen zit er ook een ontologische insteek achter, zie ook Afspraken en regels voor conceptuele informatiemodellen (het niet introduceren van "spook" objecttypes, waar niemand het over heeft en de naam eigenlijk niet eens van weet), wat bij datatypen niet het geval is, of soepeler mee wordt omgegaan, omdat datatypen geen kenmerken zijn, maar enkel de structuur van de informatie aangeven. 

Het lijkt dus niet terecht om dezelfde definitie te hanteren. 

Nou vind ik het persoonlijk niet erg om twee definities te hebben, met dezelfde modellering, waarbij uit de context blijkt om welke definitie het gaat. Immers, het is direct duidelijk of de generalisatie tussen datatypes is, of tussen objecttypes (of gegevensgroepen of waardelijsten). 

-- 

Voorstel: 1 generieke definities, in de geest van wat een generalisatie zelf ook is als modelelement. 

De typering van het hiërarchische verband tussen gelijksoortige modelelementen, tussen een meer generiek modelelement en een meer specifiek modelelement, waarbij het laatstgenoemde modelelement eigenschappen van de eerstgenoemde modelelement overerft. Dit verband is alleen gedefinieerd voor objecttypen en datatypen. 

Toelichting: afhankelijk van of de generalisatie tussen objecttypen of tussen datatypen is, kent de generalisatie een aanvullende interpretatie. 

Hierna weer de toelichtingen van die horen bij de twee definities die we tot nu toe hadden. 

@architolk @PalmJanssen @ThiesMesdag werkt dit voor jullie? Bepreken nodig?

**Comment by lennartvanbergen-kadaster** [comment]
2e assignee, de originele opvoerder, vanwege beter kunnen monitoren van dit item.

**Comment by ThiesMesdag** [comment]
> De typering van het hiërarchische verband tussen gelijksoortige modelelementen, tussen een meer generiek modelelement en een meer specifiek modelelement, waarbij het laatstgenoemde modelelement eigenschappen van de eerstgenoemde modelelement overerft. Dit verband is alleen gedefinieerd voor objecttypen en datatypen.

Zou ik willen herschrijven naar:
De typering van het hiërarchische verband tussen een meer generiek en een meer specifiek modelelement van het zelfde soort, waarbij het meer specifieke modelelement eigenschappen van het meer generieke modelelement overerft. Dit verband is alleen gedefinieerd voor objecttypen en datatypen.

**Comment by lennartvanbergen-kadaster** [comment]
Ja, ok, dat leest inderdaad fijner. Nemen we over. Dus: 

--

_Voorstel: 1 generieke definitie, in de geest van wat een generalisatie zelf ook is als modelelement._

De typering van het hiërarchische verband tussen een meer generiek en een meer specifiek modelelement van het zelfde soort, waarbij het meer specifieke modelelement eigenschappen van het meer generieke modelelement overerft. Dit verband is alleen gedefinieerd voor objecttypen en datatypen.

Toelichting: afhankelijk van of de generalisatie tussen objecttypen of tussen datatypen is, kent de generalisatie een aanvullende interpretatie. Hierna weer de toelichtingen van die horen bij de twee definities die we tot nu toe hadden.

--

**Comment by lennartvanbergen-kadaster** [comment]
Verwerkt in Algemeen. Zie Generalisatie.

**Comment by lennartvanbergen-kadaster** [comment]
In UML hoofdstuk niets aangepast. Lijkt al goed. Zijn 2 tabellen. Wel van belang dat we de metagegevens hetzelfde houden. Zou wellicht 1 tabel kunnen worden, maar wat er nu staat is niet fout en meer in overeenstemming met het gebruik. Want een generalisatie is altijd met een betrokken source en een betrokken target. Bij een datatype zijn dit UML-Datatypes en bij objecttypes zijn dit  UML-Classes dus ook in het UML profiel en in verdere implementaties zoals XSD en JSON moet dit anders behandeld worden. Eerste plek waar dit ontstaat is in UML. Dus daarom lijkt het mij goed om dit verschil als in het UML hoofdstuk te maken.

**Comment by lennartvanbergen-kadaster** [comment]
Wat mij betreft goed zo. @dkrijtenburg-GNM graag ter ok in overleg, of het naar consultatie kan.

**Comment by architolk** [comment]
Prima zo. Er is 1 definitie en dat is wat het belangrijkst is voor nu. Wel zou ik zelf de beperking dat een generalisatie alleen van toepassing is op objecttype of datatype geen onderdeel uit laten maken van de definitie, maar van de gegevensregel. We zouden dit in de toekomst immers kunnen veranderen. Het liefst zou ik bv op termijn de generalisatie ook willen gebruiken op attribuutsoorten en relatieklassen. Indien je een Linked Data model transformeert naar het MIM zal dit al gaan gebeuren, aangezien in Linked Data dit mogelijk is (zo kun je bv aangeven dat een attribuutsoort als "mobieltelefoonnummer" een specialisatie is van de attribuutsoort "telefoonnummer".
