### ISSUE TITLE
Externe koppeling kent een verwijzing naar een andere sectie in de definitie

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#75]
In de definitie van externe koppeling wordt verwezen naar sectie 3.14. Het gebruik van verwijzingen in definities is geen goede practice. Voorstel is om deze verwijzing te schrappen, eventueel op te nemen bij de toelichting.

**Comment by architolk** [comment]
Uitgewerkt in: https://github.com/Geonovum/MIM-Werkomgeving/pull/93

**Comment by architolk** [comment]
@dkrijtenburg-GNM : kun je er voor zorgen dat de pull request wordt goedgekeurd? De wijziging is verwerkt, maar via het pull-request en deze staat nog open.

**Comment by dkrijtenburg-GNM** [comment]
@PalmJanssen , @lennartvanbergen-kadaster , @ThiesMesdag 
Graag het pull request van Marco beoordelen en (hopelijk) goedkeuren
