### ISSUE TITLE
Relatierol source en relatierol target worden niet gedefinieerd

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#76]
In het diagram worden relatierol source en relatierol target als specialistisch van relatierol neergezet, maar het ontbreekt aan een feitelijke definitie. Voorstel is om deze toe te voegen aan de tekst bij relatierol

**Comment by dkrijtenburg-GNM** [comment]
in 2.6.5

**Comment by PalmJanssen** [comment]
ik doe een voorstel in tekst
