### ISSUE TITLE
Gebruik van Identificerend is niet geheel duidelijk

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#77]
Er is een klasse <Identificerend> gedefinieerd, maar niet duidelijk is hoe deze zich verhoudt tot het kenmerk <identificerend> dat ook genoemd staat in de tekst.

**Comment by GeraldGrootRoessink** [comment]
Ik vraag me af of dit een rol moet spelen in een linked data publicatie. Bijvoorbeeld: moet dit overeenkomen met de lastPart van de URI.
