### ISSUE TITLE
Definitie van Codelist is niet onderscheidend

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#78]
De definitie van codelist is: "De definitie van een codelist is gelijk aan de definitie van een referentielijst.". Dit was in MiM 1.0: "Een referentielijst die extern wordt beheerd, en geen onderdeel is van het informatiemodel". Die laatstgenoemde definitie lijkt beter. Eerstgenoemde definitie geeft feitelijk aan dat er geen verschil is, en dat je codelist dus weg zou kunnen halen uit je model.

**Comment by GeraldGrootRoessink** [comment]
Het onderscheid dat ik er uit peur is dat een referentielijst dynamisch is en een codelist niet. Zo bekeken is een referentielijst een "vreemd" objecttype en de codelist een "vreemd" enumerationclass. Maar heel duidelijk is het niet omschreven.

**Comment by lennartvanbergen-kadaster** [comment]
Referentielijst
Definitie Referentielijst
De representatie van een lijst met een opsomming van de mogelijke domeinwaarden van een attribuutsoort, die buiten het model in een externe waardenlijst worden beheerd. De domeinwaarden in de lijst kunnen in de loop van de tijd aangepast, uitgebreid, of verwijderd worden, zonder dat het informatiemodel aangepast wordt (in tegenstelling tot bij een enumeratie). De representatie bevat een aantal kenmerken, die overgenomen zijn van de specificatie van de externe waardelijst.

Stereotype Codelijst
Definitie Codelijst
De representatie van een lijst met een opsomming van de mogelijke domeinwaarden van een attribuutsoort, die buiten het model in een externe waardenlijst worden beheerd. De domeinwaarden in de lijst kunnen in de loop van de tijd aangepast, uitgebreid, of verwijderd worden, zonder dat het informatiemodel aangepast wordt (in tegenstelling tot bij een enumeratie). De representatie bevat geen kenmerken, voor alle kenmerken wordt verwezen naar de specificatie van de externe waardelijst.
