### ISSUE TITLE
Onduidelijkheid over schrijfwijze codelist

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#79]
In de tekst staat vrijwel overal nu: "codelist". In het plaatje en op een enkele plaats wordt echter gesproken over "CodeList" of "codeList". Voorstel is om het overal "codelist" te maken. (of anders "code list" in de tekst, en "codeList" en "CodeList" overal waar de technische naam bedoeld wordt.

**Comment by dkrijtenburg-GNM** [comment]
is dubbel
