### ISSUE TITLE
In Bijlage 1 staat nog "Complex datatype".

### ISSUE THREAD

**Issue by LentjesP** [Geonovum/MIM-Werkomgeving#8]
In Bijlage in van de MIM beschrijving is onder "Complex datatype" i.p.v. "Gestructureerd datatype" opgenomen. Dit moet nog aangepast worden.

**Comment by PalmJanssen** [comment]
Het uml diagram is aangepast in de werkversie: complex datatype -> gestructureerd datatype.

Verwijzing naar Bijlage 1 -> Bijlage I is nog niet gedaan

**Comment by PalmJanssen** [comment]
Is verwerkt
