### ISSUE TITLE
De definitie van "Gestructureerd datatype" is recursief

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#81]
De definitie van "Gestructureerd datatype" verwijst naar "Gestructureerd datatype". Dit leidt tot een recursieve definitie. Voorstel is de verwijzing te wijzigen naar "Datatype".

**Comment by lennartvanbergen-kadaster** [comment]
**Definitie Gestructureerd datatype**

>   Specifiek benoemd datatype dat de structuur van een gegeven beschrijft,
>   samengesteld uit minimaal twee elementen die in samenhang betekenisvol zijn.

*Toelichting:*

De waarde van het attribuutsoort verkoopprijs met gestructureerd datatype bedrag is uitgedrukt
in een combinatie van een som en valuta zoals 35 euro. De introductie van één
datatype Bedrag, uitgedrukt in som en valuta, legt dus vast dat som en valuta
onlosmakelijk met elkaar zijn verbonden.

De eigenschappen in het Gestructureerd datatype tezamen zijn identificerend (een
Gestructureerd datatype “identificeert zichzelf”, zoals er maar per definitie
één “1 liter” bestaat, één 35 euro en één datum 6 april 2017, met per definitie
altijd dezelfde betekenis:

-   Een blik olie heeft een inhoud van **7 liter**, kost **35 euro**, en is
    verkocht op **6 april 2017**.

-   Piet heeft **1 liter** bloed gedoneerd, daarvoor **35 euro** vergoeding
    gekregen, op **6 april 2017**.

Het identificerend zijn geldt bijvoorbeeld niet voor Jan Jansen. Er zijn
meerdere personen met deze naam en dat zijn verschillende personen (Jan Jansen
is dan ook een gegevensgroeptype Naam met voornaam Jan en achternaam Jansen en
geen Gestructureerd datatype).

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Gestructureerd datatype Bedrag bestaat uit de data-elementen som en valuta.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by lennartvanbergen-kadaster** [comment]
Specifiek benoemd datatype dat de structuur van een gegeven beschrijft,
samengesteld uit minimaal twee elementen die in samenhang betekenisvol zijn.

@Paul deze definitie lijkt mij beter, wat vind jij?
