### ISSUE TITLE
Opmaak van definities inconsistent

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#83]
In sectie 2.2 wordt de definitie in 2 losse blokken getoond: eerst de titel en dan de definitie. In sectie 2.3 wordt alleen de titel in een blok getoond, en de definitie zelf in gewone tekst. Voorstel is om er in beide secties 1 blok van te maken met zowel titel als definitie.

**Comment by dkrijtenburg-GNM** [comment]
gechectk: is al opgelost in 1.1
