### ISSUE TITLE
UnionElement, Extern, View, Enumeratie en Constraint kennen geen alias in hun specificatietabel

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#84]
Dit lijkt een inconsistentie? Of geldt voor deze klassen dat er geen alias mogelijk is?

**Comment by lennartvanbergen-kadaster** [comment]
Klopt, alias is alleen voor wezenlijke kenmerken bedoeld c.q. objecttypen, attribuutsoorten, relatiesoorten (mogelijk som ik nu niet limitatief op).
