### ISSUE TITLE
Ontbreken van de waarde "Niet authentiek"

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#85]
Het aspect "authentiek" is een verplicht veld. Echter, de waardelijst voor dit veld kent alleen de mogelijkheid om waarden in te vullen in elk een bepaalde mate van authenticiteit hebben. De waarde "Niet authentiek" lijkt te ontbreken.

**Comment by dkrijtenburg-GNM** [comment]
de betekenis van basisgegeven is dat het niet authentiek is.

**Comment by GeraldGrootRoessink** [comment]
De term basisgegeven is misschien niet genoeg. Het hebben zogenaamde wettelijke basisregistraties met daarin authentieke gegevens (dus verplicht gebruik) maar ook niet verplichte gegevens. Daarnaast kent de overheid nog veel meer wettelijke registraties (bij DUO minstens 5). Dat zijn dus geen "basisregistraties" maar we maken ons wel op om die in hetzelfde stramien te gieten.

**Comment by lennartvanbergen-kadaster** [comment]
Er zijn een aantal waardes, voor een aardig scala aan mogelijkheden. 

Authentiek, Basisgegeven, Landelijk kerngegeven, Gemeentelijk kerngegeven, Overig

Dit is vooralsnog voor alle modellen tot nu toe genoeg gebleken. 

Als eentje ontbreekt, of als een definitie niet helder is, of verruimd moet worden om iets in onder te kunnen brengen ... graag. 

Bv. als blijkt dat je alles onder Overig plaatst en daar een belangrijke onderscheid in zit.

**Comment by lennartvanbergen-kadaster** [comment]
@GeraldGrootRoessink @architolk Zien jullie op basis van de toelichting reden om een waarde toe te voegen?

**Comment by GeraldGrootRoessink** [comment]
Er zijn meer wettelijke registraties zijn dan basisregistraties. Gebaseerd op een wet maar geen officieel onderdeel van het stelsel van basisregistraties. Er zitten geen authentieke (verplicht gebruikte) gegevens in. De term basisgegeven lijkt gereserveerd voor gegevens in basisregistraties die niet authentiek zijn.  Dat voelt voor mij als niet dekkend. Ik zou graag de term basisgegeven omdopen tot "wettelijk gegeven". Dat is bruikbaar voor gegevens in wettelijke registraties.

**Comment by lennartvanbergen-kadaster** [comment]
De term basisgegeven lijkt gereserveerd voor gegevens in basisregistraties die niet authentiek zijn.

Ja, dat is zo. 

"wettelijk gegeven". Dat is bruikbaar voor gegevens in wettelijke registraties.

Ja, dat is een betere term. 
Al heeft omdopen impact op bestaande modellen. En beide termen naast elkaar lijkt overlap, dus omdopen is de betere suggestie. 

Moeten dit eigenlijk afstemmen met de stelselcatalogus en andere basisregistratie partijen ... 

Goed, volgens mij zijn we in ieder geval het met elkaar eens dus we gaan hier uit komen. Dank.

**Comment by lennartvanbergen-kadaster** [comment]
Voorstel om de consultatie mee in te gaan (wat op zeer korte termijn in): 

basisgegeven : wettelijk gegeven uit een basisregistratie 
wettelijk gegeven : wettelijk gegeven uit een wettelijke registratie

**Comment by dkrijtenburg-GNM** [comment]
tabel in 5.11 en tekst in 2.13.1 aangepast
