### ISSUE TITLE
MIM document web-friendly maken 

### ISSUE THREAD

**Issue by dkrijtenburg-GNM** [Geonovum/MIM-Werkomgeving#87]

**Comment by lvdbrink** [comment]
Bijvoorbeeld: 

- Voetnoten eruit, hier ReSpec Notes van maken of hyperlinks. 
- Verwijzingen naar hoofdstukken/paragrafen zijn nu vaak plain tekst, hier interne links van maken.
- Verwijzingen naar externe standaarden en andere publicaties met een ReSpec bibliografie oplossen.
- Voorbeelden in een ReSpec Voorbeeld blokje.
- Opmaak meer webvriendelijk maken.

**Comment by JvGldr** [comment]
Gedaan, zie ook issue 88

**Comment by lvdbrink** [comment]
Ik zou de manier waarop Noten nu erin zitten toch nog wat anders doen. Het zijn nu nog steeds een soort ‘voetnoten’ die aan het eind van een hoofdstuk bij elkaar staan. Vanuit de tekst waar de noot op slaat wordt er naartoe gelinkt, dat is ok, maar er zijn dan nog 2 problemen mee: 
- je kan vanuit de noot niet terug springen naar de tekst waar je vandaan kwam
- als je het hoofdstuk van begin tot eind leest of door het document heen scrollt en je komt die noten tegen, heb je geen idee waar ze op slaan en wat ermee bedoeld wordt, omdat ze uit context gehaald zijn. 

Ik zou voorstellen om de noten nog eens kritisch te bekijken. In sommige gevallen zijn het heel korte toelichtingen die je prima als extra zin, eventueel tussen haakjes, zou kunnen toevoegen aan de tekst waar ze bij horen. In sommige gevallen kun je er hyperlinks of bibliografische verwijzingen in de tekst van maken. In andere gevallen is een ReSpec noot wel op z’n plek, maar dan zou ik die altijd ofwel net voor ofwel net na de plek waar de verwijzing nu staat opnemen, niet aan het einde van het hoofdstuk. 

Als je bv wilt toelichten wat de kolommen in een tabel betekenen, zou ik dat in een Noot net boven die tabel doen. Bijvoorbeeld bij de tabel in [3.2.1 Modellering metagegevens voor objecten en attributen in UML](https://geonovum.github.io/MIM-Werkomgeving/#modellering-metagegevens-voor-objecten-en-attributen-in-uml).
