### ISSUE TITLE
Inconsistentie tussen UML model en specificatietabel bij generalisatie

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#89]
In de specificatietabel wordt gesproken over "objecttype" en "gerelateerdObjecttype", terwijl in het UML model gesproken wordt over "subtype" en "supertype"

**Comment by lvdbrink** [comment]
De juiste termen zijn "subtype" en "supertype". Dit is conform het General Feature Model (zie ISO19103 p 47).

**Comment by architolk** [comment]
Uitgewerkt in https://github.com/Geonovum/MIM-Werkomgeving/pull/94

**Comment by lennartvanbergen-kadaster** [comment]
Dubbele #94. Deze closed.
