### ISSUE TITLE
Eigen primitief datatype gebaseerd op een standaard primitief datatype (anders dan CharacterString) 

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#9]
Een primitief datatype is vaak een CharacterString, dit is de default en is de enige die wordt toegepast. Maar het kan op zich ook met bv. een Integer. Hoe geef je het 'gebaseerd op standaard primitief type' aan?

**Comment by PalmJanssen** [comment]
Uitwerking is voldoende gedetailleerd in : 20180614 MIM-KKG - 29 - zelf gedefinieerd datatype gebaseerd op een ander datatype.pdf.

Conclusie hiervan is:

Generalisatie van datatype naar datatype. 
Voor «Primitief datatype», «Gestructureerd datatype», «Referentielijst» . 
Niet voor «Codelist», «Enumeratie », «Union». 
Opmerking: Jawel ook voor <<Codelist>> en <<Enumeratie>>. Zeker voor het conceptuele model.

Dit voorstel is verwerkt in MIM werkversie.
Generalisatie van datatype naar datatype. 
Voor «Primitief datatype», «Gestructureerd datatype», «Referentielijst» . 
Niet voor «Codelist», «Enumeratie », «Union». 
Opmerking: Jawel ook voor <<Codelist>> en <<Enumeratie>>. Zeker voor het conceptuele model.

**Comment by dkrijtenburg-GNM** [comment]
gepland voor 1.1 beta maar al in 1.0.1 opgepakt

**Comment by PalmJanssen** [comment]
Is verwerkt in de werkversie conform de voorgesteld tekst aanpassingen.

Het UML is ook aangepast. Aanpassingen in rood. UML in de bijlage is nog niet aangepast.
Mogelijk nog aanpassingen van UML profiel??

**Comment by PalmJanssen** [comment]
alles  verwerkt:
UML aangepast
UML EA profiel hoeft niet aangepast
