### ISSUE TITLE
Meerdere definities voor aspecten "unidirectioneel", "objecttype", "gerelateerdObjecttype" en "typeAggregatie"

### ISSUE THREAD

**Issue by architolk** [Geonovum/MIM-Werkomgeving#90]
Reden is dat deze aspecten zowel bij Relatiesoort en Externe koppeling voorkomen. Hierdoor zijn er meerdere definities.

**Comment by lennartvanbergen-kadaster** [comment]
Is een documentatie fout vanwege verbeteren op 1 plek en niet op de andere. Trekken we recht. Door er 1 definitie van te maken en die te hergebruiken.

**Comment by lennartvanbergen-kadaster** [comment]
Ik heb vanwege https://github.com/Geonovum/MIM-Werkomgeving/issues/90 de volgende algemene metagegeven definities toegevoegd aan het algemene deel. Hier wil ik even in het bijzonder aandacht op vestigen, omdat het relevant is voor de delen die jullie schrijven. In het UML hoofdstuk heb ik het al verwerkt. Er is geen impact op informatiemodellen in EA. 

Waarom relevant: een aantal metagegevens hadden een onhandige naam. Daarom heb ik de naam aangepast. Kunnen jullie dit ook consistent verwerken, in bv. het LD hoofdstuk en diagrammen. Ik zet dit ook nog als TODO bij het issue. 

Objecttype 		 Relatie eigenaar. 
Gerelateerd objecttype  Relatie doel. 
Type aggregatie 	 Aggregatie type 
(zo wordt het in UML ook genoemd, in de tekst, formeel heet het Aggregation kind maar de tekst en uitleg praat gewoon over Aggregatie type, EA ook, onze ‘oude’ document ook, en het is netjesvind ik om Type achteraan te zetten, dus ik heb maar gekozen voor Aggregatie type.

**Comment by lennartvanbergen-kadaster** [comment]
@architolk geeft aan: 

In het Engels zijn de termen “source” en “target”. Dit zou er voor pleiten om te praten over relatie bron en relatie doel (als letterlijke vertalingen, en dan dus ook attribuut bron). Een alternatief is “onderwerp”, in de zin van “onderwerp van het attribuuttype” en “onderwerp van de relatie”. Dit sluit wellicht wat beter aan bij de betekenis (een attribuuttype gaat over een objecttype/gegevensgroeptype, net als de betreffende relatie).

“Eigenaar” vind ik zelf niet heel handig, omdat dit op “bezit” duidt en daarmee meer een beheer-betekenis heeft, en niet een beschrijvende logische of conceptuele betekenis in de zin van een informatiemodel.

**Comment by lennartvanbergen-kadaster** [comment]
Voorstel: 

Naamgeving van de source van de relatie en de target van de relatie, in MIM termen. 

Objecttype --> bron 
Gerelateerd objecttype --> doel 

Eerst in algemeen.

**Comment by architolk** [comment]
Verwerkt in de LD onderdelen.

**Comment by PalmJanssen** [comment]
verwerkt in UML
