### ISSUE TITLE
Identificerend een modelelement of een metagegeven?

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#92]
Is dit een modelelement of een metagegeven?

Je houd er geen waarde voor bij, zoals bij metagegeven. Maar je kan het ook niet als modelelement een informatiemodel in "slepen". Wat is het ... waar beschrijven?

Staat nu bij modelelementen.

**22. Identificerend** 

>   **Definitie Identificerend**

>   Een kenmerk van een objecttype die aangeeft of deze eigenschap uniek
>   identificerend is voor alle objecten in de populatie van objecten van dit
>   objecttype.

*Toelichting:* objecten hebben, of krijgen, in een administatie of
gegevensvoorziening vaak één identificerend kenmerk. Het kan ook zijn dat een aantal kenmerken in combinatie
identificerend zijn, zoals twee attibuutsoorten of een attribuutsoort en een
relatiesoort. De combinatie met een relatiesoort wordt alleen gedaan voor
objecttypes die zelf geen unieke aanduiding hebben en daarom deze moeten
samenstellen met de unieke aanduiding van een gerelateerde objecttype.

*Voorbeeld: ‘burger service nummer’ van een PERSOON, of ‘identificatie’ van
PAND. Een combinatie van ‘postcode’, ‘huisnummer’, ‘huisnummertoevoeging’ en
‘huisletter’ van een NUMMERAANDUIDING. Een BUURT, deze heeft zelf geen unieke
identificatie. Een BUURT ligt in een WIJK en binnen die WIJK is de BUURT wel
uniek. De WIJK zelf heeft een unieke identificatie. De unieke identificatie van
BUURT is daarom samengesteld uit het attribuut Buurtcode van BUURT en de
verwijzing naar de WIJK (de identificatie van WIJK).*

**Comment by GeraldGrootRoessink** [comment]
In UML kun je stereotypes als <<pk>> en <<fk> opnemen om de sleutels te duiden. Dat is gebruikelijk bij het modelleren van een fysieke tabel. Maar niet zozeer bij een logisch model.

**Comment by lennartvanbergen-kadaster** [comment]
Ja, je mag ter visualisatie < < identificatie > > opnemen, als je in je extensie aangeeft dat dit voor visuele verheldering is en geen modelelement. Voor andere mensen leiden dubbele stereotypes weer af. 

In een UML model is het op zich al helder, want er staat { id }  achter het attribuut als je MIM volgt.

**Comment by lennartvanbergen-kadaster** [comment]
Ik ben tot de conclusie gekomen dat identificerend metadata is. Het zegt wat over een eigenschap. Het staat dus al goed in MIM H2. 

Bij het exporteren naar een MIM-export format is het relevant om aan te geven dat het om een boolean gaat. 
Zie: https://github.com/Geonovum/MIM-Werkomgeving/issues/197

Dit zit zo te zien ook al in het waardebereik van metadata dat niet een gewone string is. 
https://github.com/Geonovum/MIM-Werkomgeving/issues/162

**Comment by lennartvanbergen-kadaster** [comment]
Deze kunnen we sluiten, heb deze wens overgenomen naar 162.
