### ISSUE TITLE
herschrijven voorwoord

### ISSUE THREAD

**Issue by dkrijtenburg-GNM** [Geonovum/MIM-Werkomgeving#97]
Hierbij de nieuwe versie van het voorwoord  van MIM 1.1:

Voorwoord

Informatie is een belangrijke motor voor het functioneren van de overheid in Nederland. Steeds meer wordt er samengewerkt en uitgewisseld tussen verschillende overheidslagen en instanties. Daarom is het van groot belang dat we hetzelfde verstaan onder de gegevens die we gebruiken en gemeenschappelijke afspraken maken over de wijze van beschrijven van gegevens en de manier waarop we deze uitwisselen.
Bij huidige ontwikkelingen als het Digitaal Stelsel Omgevingswet (DSO) en de Basisregistratie Ondergrond (BRO) komt duidelijk naar voren dat veel gegevensverzamelingen uit verschillende domeinen bij elkaar komen in informatievraagstukken. Daarbij komen ook de wereld van de geografische gegevens en de wereld van de meer administratieve registraties bij elkaar. Dit geeft niet alleen extra mogelijkheden om informatie slim te combineren maar maakt ook een aantal verschillende uitgangspunten zichtbaar in de werkwijze binnen de overheid als het gaat om het modelleren van informatie.
Met het voorliggende MIM-metamodel hebben we een gemeenschappelijk vertrekpunt voor het opstellen van informatiemodellen. Het voorziet enerzijds in duidelijke afspraken die over meerdere bestuurslagen heen gaan over het vastleggen van gegevensspecificaties en biedt anderzijds ruimte aan de verschillende niveaus van modellering. 
Versie 1.1 van MIM biedt naast het al bestaande uitdrukken van het metamodel in UML ook de mogelijkheid om het metamodel uit te drukken in Linked Data. Hierbij wordt voorzien in en breed geuite behoefte. 
We hebben de afgelopen tijd gezien dat MIM breed wordt omarmd binnen de overheid en een plek heeft veroverd binnen de NORA. Met de uitbreidingen en aanpassingen in deze versie  wordt het toepassingsbereik van MIM aanzienlijk verbreed. 

Dick Krijtenburg (Geonovum)
Oktober 2019

**Comment by lennartvanbergen-kadaster** [comment]
.
